# U.S. History 6-8 — the course arc. Our own wording. Topics are guides for the writers.
UNITS = [
 dict(n=1, title="Early Encounters", years="Beginnings–1650", chapters=[
  dict(n=1, title="Three Worlds Before 1500", years="Beginnings–1500",
       topics="First peoples reach the Americas; farming and civilizations of Mesoamerica and the Andes (Olmec, Maya, Aztec, Inca); North American peoples and their environments (Ancestral Puebloans, Mississippians and Cahokia, Eastern Woodlands incl. Haudenosaunee, Plains, Northwest Coast); Europe from the Middle Ages to the Renaissance, new navigation technology, the Reformation; West African kingdoms Ghana, Mali, Songhai, gold-salt trade, Timbuktu.",
       story="Cahokia, the city of mounds (in what is now Illinois)"),
  dict(n=2, title="European Exploration of the Americas", years="1400–1680",
       topics="Portugal and the sea route to Asia; Columbus's voyages and the Taino; Spanish conquest of the Aztec and Inca; disease; the Columbian Exchange; the encomienda system and Spanish colonial society; Spanish missions and the Pueblo Revolt of 1680; France, the Netherlands and England compete (Cartier, Champlain, Hudson, the Northwest Passage, defeat of the Spanish Armada); the beginning of the Atlantic slave trade and the Middle Passage.",
       story="The Pueblo Revolt of 1680"),
 ]),
 dict(n=2, title="English Settlement", years="1585–1763", chapters=[
  dict(n=3, title="The Thirteen Colonies", years="1585–1732",
       topics="Roanoke; Jamestown, John Smith, the Powhatan Confederacy and Pocahontas, tobacco, the House of Burgesses, 1619 and the first enslaved Africans in Virginia, Bacon's Rebellion; the Pilgrims, the Mayflower Compact, the Wampanoag; the Puritans and Massachusetts Bay; dissent (Roger Williams, Anne Hutchinson); Pequot War and King Philip's (Metacom's) War; New Netherland becomes New York; William Penn and Pennsylvania; Maryland, the Carolinas, Georgia.",
       story="The lost colony of Roanoke"),
  dict(n=4, title="Colonial Development", years="1651–1763",
       topics="New England economy (fishing, shipbuilding, trade, town meetings); the Middle Colonies' farms, ports and diversity; Southern plantations, rice and indigo, the spread of slavery, life under slavery and resistance (Stono Rebellion 1739); the Triangular trade and mercantilism, Navigation Acts; colonial society, education and literacy; the Enlightenment and the Great Awakening; English rights: Magna Carta, the English Bill of Rights, colonial assemblies, the Zenger trial; the French and Indian War (causes, Washington, Albany Plan, Treaty of Paris 1763).",
       story="Colliding cultures: the fur trade between Native nations and Europeans"),
 ]),
 dict(n=3, title="A New Nation", years="1763–1791", chapters=[
  dict(n=5, title="The Road to Revolution", years="1763–1776",
       topics="Proclamation of 1763; debt and new taxes: Sugar Act, Stamp Act, 'no taxation without representation', boycotts, Sons and Daughters of Liberty, Townshend Acts; Boston Massacre; Committees of Correspondence; Tea Act and Boston Tea Party; Intolerable Acts; First Continental Congress; Lexington and Concord; Second Continental Congress, Olive Branch Petition; Common Sense; the Declaration of Independence (Jefferson, its ideas, who it left out).",
       story="The night of April 18, 1775: riders warn the countryside"),
  dict(n=6, title="The American Revolution", years="1775–1783",
       topics="Bunker Hill; Loyalists and Patriots; the loss of New York; Washington crosses the Delaware, Trenton and Princeton; Saratoga as turning point; the French alliance and other helpers (Lafayette, von Steuben, Spain, Bernardo de Gálvez); Valley Forge; women in the war (Abigail Adams, Mary Ludwig Hays, Deborah Sampson); African Americans in the war (James Armistead, Lord Dunmore's offer); war at sea (John Paul Jones); the war in the South; Yorktown; Treaty of Paris 1783; why the Americans won; legacy.",
       story="The winter at Valley Forge"),
  dict(n=7, title="From Confederation to Constitution", years="1776–1791",
       topics="State constitutions; the Articles of Confederation and their weaknesses; Land Ordinance 1785 and Northwest Ordinance 1787 (including what became Illinois, and its ban on slavery); Shays's Rebellion; the Constitutional Convention (Madison, Virginia and New Jersey Plans, Great Compromise, Three-Fifths Compromise, slave trade clause, Electoral College); separation of powers, checks and balances, federalism; Federalists vs. Antifederalists, The Federalist Papers; ratification; the Bill of Rights.",
       story="Philadelphia, the summer of 1787"),
 ]),
 dict(n=4, title="The Early Republic", years="1789–1844", chapters=[
  dict(n=8, title="Growing Pains in the New Republic", years="1789–1800",
       topics="Washington takes office, the first cabinet, the Judiciary Act; Hamilton's financial plan, national debt, the national bank, the capital on the Potomac; the Whiskey Rebellion; the first political parties (Federalists vs. Democratic-Republicans); the French Revolution and neutrality; Jay's and Pinckney's Treaties; the Battle of Fallen Timbers and the Treaty of Greenville; Washington's Farewell Address; John Adams, the XYZ Affair, the Alien and Sedition Acts, the Virginia and Kentucky Resolutions.",
       story="Mount Vernon: Washington's home, and the people enslaved there"),
  dict(n=9, title="The Jefferson Years", years="1800–1816",
       topics="The election of 1800 and the peaceful transfer of power; Jefferson's vision; Marbury v. Madison and judicial review; the Louisiana Purchase; Lewis and Clark, the Corps of Discovery, Sacagawea, York; Zebulon Pike; the Barbary pirates; impressment and the Embargo Act; Tecumseh and the Prophet, Tippecanoe; the War Hawks and the War of 1812 (burning of Washington, Fort McHenry and the Star-Spangled Banner, Battle of New Orleans, Treaty of Ghent); results of the war.",
       story="The Corps of Discovery"),
  dict(n=10, title="Expansion and Growth", years="1800–1844",
       topics="The Industrial Revolution reaches America (Samuel Slater, Lowell mills and the mill girls, interchangeable parts, Eli Whitney); roads, the National Road, steamboats, the Erie Canal, early railroads; the cotton gin and the spread of cotton and slavery; the domestic slave trade; enslaved people's lives, families, faith and resistance (Nat Turner's rebellion); Era of Good Feelings; Illinois becomes a state (1818); the Missouri Compromise; the Monroe Doctrine; nationalism vs. sectionalism.",
       story="The mighty Mississippi and the steamboat age"),
 ]),
 dict(n=5, title="Pushing National Boundaries", years="1821–1860", chapters=[
  dict(n=11, title="The Age of Jackson", years="1824–1840",
       topics="The election of 1824 and the 'corrupt bargain'; 1828 and the common man; expanded voting for white men; the spoils system; the tariff and the nullification crisis (Calhoun); the Indian Removal Act; the Cherokee, Sequoyah, Worcester v. Georgia; the Trail of Tears; the Seminole resistance; the Black Hawk War in Illinois; the war on the Bank; the Panic of 1837; the Whig Party; Martin Van Buren.",
       story="Sequoyah and the written Cherokee language"),
  dict(n=12, title="Manifest Destiny", years="1821–1853",
       topics="Manifest Destiny as an idea; mountain men; the Oregon Trail and trail life; the Mormon migration to Utah; the Santa Fe Trail; Tejanos and Mexican Texas, Stephen F. Austin; the Texas Revolution (the Alamo, San Jacinto), the Lone Star Republic and annexation; Polk, Oregon compromise; the U.S.-Mexican War and the Treaty of Guadalupe Hidalgo; the Gadsden Purchase; Californios; the California Gold Rush, forty-niners, Chinese miners, impact on Native Californians.",
       story="San Francisco: from village to gold-rush city"),
  dict(n=13, title="The Changing American Identity", years="1830–1860",
       topics="Immigration from Ireland (famine) and Germany; nativism and the Know-Nothings; growing cities; the Second Great Awakening; reform movements: temperance, public schools (Horace Mann), prisons and asylums (Dorothea Dix); American writers and artists (Emerson, Thoreau, Hudson River School); abolition (Garrison, Frederick Douglass, the Grimké sisters, Sojourner Truth, David Walker); the Underground Railroad and Harriet Tubman (and Illinois routes); the women's rights movement, Seneca Falls 1848, Elizabeth Cady Stanton, Lucretia Mott.",
       story="The Underground Railroad"),
 ]),
 dict(n=6, title="Civil War and Reconstruction", years="1846–1877", chapters=[
  dict(n=14, title="A Broken Nation", years="1846–1861",
       topics="The Wilmot Proviso; the Free-Soil Party; the Compromise of 1850 and the Fugitive Slave Act; Uncle Tom's Cabin; the Kansas-Nebraska Act (Stephen Douglas of Illinois); Bleeding Kansas and the caning of Charles Sumner; the Republican Party forms; Dred Scott v. Sandford; the Lincoln-Douglas debates across Illinois (1858); John Brown's raid at Harpers Ferry; the election of 1860; secession and the Confederacy; failed compromise; Fort Sumter.",
       story="Seven debates across Illinois, 1858"),
  dict(n=15, title="Beginnings of War", years="1861–1862",
       topics="Choosing sides, the border states; strengths and weaknesses of North and South; leaders (Lincoln, Davis, Lee, Grant); the Anaconda Plan; First Bull Run; soldiers' lives, camp, weapons, disease and medicine; women's roles (Clara Barton, nurses, Dorothea Dix); photography of the war (Mathew Brady); war in the West (Forts Henry and Donelson, Shiloh, New Orleans); ironclads; war in the East (Peninsula Campaign); Antietam (1862).",
       story="Letters home: soldiers write from the war"),
  dict(n=16, title="Turning Points of the War", years="1863–1865",
       topics="The Emancipation Proclamation; African American soldiers and the 54th Massachusetts; Frederick Douglass on the war; the draft and the New York draft riots; paying for the war; prison camps (Andersonville); Gettysburg and the Gettysburg Address (quote the Address only verbatim from its standard Bliss text); Vicksburg; Grant takes command; Sherman's March; the election of 1864; Appomattox; Lincoln's assassination; the 13th Amendment; the cost of the war.",
       story="The 54th Massachusetts at Fort Wagner"),
  dict(n=17, title="Reconstruction and the New South", years="1865–1877",
       topics="Lincoln's plan and Andrew Johnson's plan; Black Codes; the Freedmen's Bureau; the Radical Republicans, Reconstruction Acts, military districts; Johnson's impeachment; 14th and 15th Amendments; freedpeople reunite families, build churches and schools, HBCUs; Black officeholders (Hiram Revels); sharecropping and tenant farming; the Ku Klux Klan and terror, the Enforcement Acts; Grant's presidency; the election of 1876 and the Compromise of 1877; the end of Reconstruction and the start of Jim Crow; the 'New South' idea.",
       story="Freedom readers: the schools freedpeople built"),
 ]),
 dict(n=7, title="America on the Move", years="1860–1920", chapters=[
  dict(n=18, title="The Westward Movement", years="1860–1900",
       topics="Mining booms and boomtowns (Comstock Lode); cattle drives and cowboys, including Black and Mexican vaqueros; the Homestead Act; the transcontinental railroad (Chinese and Irish workers, 1869 Promontory Summit); farming the Plains, sod houses, women and children, Exodusters; farmers' troubles, the Grange, the Populist Party; Plains nations and the buffalo; Sand Creek; Little Bighorn; Chief Joseph and the Nez Perce; boarding schools; the Dawes Act; Wounded Knee (1890); the 'closing' of the frontier.",
       story="The fall and return of the American bison"),
  dict(n=19, title="Industrialization and Immigration", years="1860–1914",
       topics="Steel (Bessemer process), oil, electricity; inventors (Edison, Bell, Lewis Latimer); big business: corporations, monopolies, trusts (Carnegie, Rockefeller), philanthropy vs. 'robber barons'; the Gilded Age; new immigrants from southern and eastern Europe, Asia and Mexico; Ellis Island and Angel Island; the Chinese Exclusion Act; cities grow: tenements, skyscrapers, Chicago after the fire of 1871, Jane Addams and Hull House in Chicago; segregation, Plessy v. Ferguson, Ida B. Wells, Booker T. Washington and W.E.B. Du Bois, the NAACP; workers' lives, child labor, unions (Knights of Labor, AFL, Samuel Gompers), Haymarket (Chicago, 1886), the Pullman Strike (Illinois, 1894).",
       story="Hull House: Jane Addams's neighborhood in Chicago"),
  dict(n=20, title="The Progressive Era", years="1890–1920",
       topics="Progressives and muckrakers (Jacob Riis, Upton Sinclair's The Jungle about Chicago's stockyards, Ida Tarbell); city and state reform (initiative, referendum, recall, the 17th Amendment); Theodore Roosevelt's Square Deal, trust-busting, Pure Food and Drug Act, conservation; Taft; Wilson, the Federal Reserve, the 16th Amendment; the fight for women's suffrage (Susan B. Anthony, Alice Paul, Carrie Chapman Catt) and the 19th Amendment; America on the world stage: Hawaii, the Spanish-American War, the Philippines, the Panama Canal, the Roosevelt Corollary.",
       story="America's national parks begin"),
 ]),
 dict(n=8, title="Twentieth-Century Crises", years="1914–1945", chapters=[
  dict(n=21, title="The Great War", years="1914–1920",
       topics="Causes of World War I (militarism, alliances, imperialism, nationalism; the assassination at Sarajevo); trench warfare and new weapons; U.S. neutrality, the Lusitania, the Zimmermann Telegram; the U.S. enters (1917); the draft and the American Expeditionary Force; the home front: Liberty Bonds, propaganda, limits on speech (Espionage and Sedition Acts), women's work, the Great Migration begins; the 1918 influenza; Wilson's Fourteen Points; the Treaty of Versailles and the Senate's rejection of the League of Nations.",
       story="New weapons, old tactics: the war in the trenches"),
  dict(n=22, title="The Roaring Twenties", years="1919–1929",
       topics="Return to 'normalcy' (Harding, Coolidge); the Red Scare; immigration quotas; the revived Klan; Prohibition, bootlegging and Chicago's gangsters; the Scopes trial; the consumer economy, the Model T and the assembly line, buying on credit, radio and movies, flappers; the Jazz Age (Louis Armstrong in Chicago); the Great Migration to Chicago and the North; the Harlem Renaissance (Langston Hughes, Zora Neale Hurston); Marcus Garvey.",
       story="The Jazz Age comes to Chicago's South Side"),
  dict(n=23, title="The Great Depression", years="1929–1940",
       topics="Weaknesses in the 1920s economy; the stock market crash of 1929; bank failures and unemployment; Hoover's response; Hoovervilles; the Bonus Army; Franklin D. Roosevelt and the first hundred days; fireside chats; New Deal programs (CCC, WPA, TVA, FDIC); the Dust Bowl and migrants; the Second New Deal, Social Security, labor rights; Eleanor Roosevelt; the New Deal and women, African Americans, Mexican Americans (repatriation) and Native Americans; critics; the New Deal's legacy.",
       story="Surviving hard times: a family's Depression"),
  dict(n=24, title="World War II", years="1931–1945",
       topics="Rise of dictators (Mussolini, Hitler, Stalin, Japan's militarists); aggression in Asia and Europe; appeasement; the war begins 1939; U.S. neutrality and Lend-Lease; Pearl Harbor; the home front: mobilization, rationing, women in war work (Rosie the Riveter), the Tuskegee Airmen, Navajo Code Talkers, Mexican American service; Executive Order 9066 and Japanese American incarceration; North Africa and Italy; D-Day; the Holocaust; victory in Europe; the war in the Pacific, island hopping, Midway; the atomic bombs and Japan's surrender; the war's legacy and the United Nations.",
       story="Executive Order 9066: Japanese American incarceration"),
 ]),
 dict(n=9, title="Postwar America", years="1945–1973", chapters=[
  dict(n=25, title="The Cold War and the American Dream", years="1945–1959",
       topics="The GI Bill and the postwar boom; the baby boom; Truman and the Fair Deal; the Cold War begins: the Iron Curtain, containment, the Truman Doctrine, the Marshall Plan, the Berlin Airlift, NATO; communism in China; the Korean War; fear of communism: the Red Scare, McCarthyism, the arms race and duck-and-cover; the Eisenhower years, the interstate highways; suburbs (Levittown), cars, television, rock and roll; Sputnik; who was left out of the boom.",
       story="Television arrives in the living room"),
  dict(n=26, title="The Civil Rights Movement", years="1945–1963",
       topics="Roots: Jim Crow laws, the Great Migration, WWII service; Jackie Robinson; Truman desegregates the armed forces; the NAACP's legal strategy, Thurgood Marshall, Brown v. Board of Education (1954); Mendez v. Westminster; the Little Rock Nine; Emmett Till (a Chicago boy; handle with care, age-appropriate); Rosa Parks and the Montgomery Bus Boycott; Martin Luther King Jr. and nonviolence; the sit-ins and SNCC; the Freedom Rides; Birmingham 1963; the March on Washington; Ruby Bridges; women of the movement (Ella Baker, Fannie Lou Hamer).",
       story="Ruby Bridges walks to school"),
  dict(n=27, title="Conflict and Expanding Rights", years="1960–1973",
       topics="Kennedy and the New Frontier; the space race; the Bay of Pigs, the Berlin Wall, the Cuban Missile Crisis; Kennedy's assassination; Lyndon Johnson, the Civil Rights Act of 1964, Freedom Summer, Selma and the Voting Rights Act of 1965, the Great Society; Malcolm X and Black Power; King's assassination; César Chávez, Dolores Huerta and the farmworkers; the American Indian Movement; the women's movement (Betty Friedan, Title IX); disability rights beginnings; Vietnam: why the U.S. went in, the Gulf of Tonkin, escalation, the Tet Offensive, the antiwar movement, 1968, Nixon and withdrawal, the 26th Amendment.",
       story="1968: a year that shook the nation"),
 ]),
 dict(n=10, title="America in a Changing World", years="1969–Present", chapters=[
  dict(n=28, title="New American Politics", years="1969–1990",
       topics="Nixon: the Moon landing (1969), détente, the visit to China, the end of the draft; Earth Day, the EPA, clean air and water laws; Watergate and the resignation; Ford and Carter; the energy crisis, inflation; the Camp David Accords; the Iran hostage crisis; the 1980 election and Ronald Reagan; tax cuts and deregulation; the Americans with Disabilities Act (1990); a changing population; Reagan and Gorbachev; the fall of the Berlin Wall (1989) and the end of the Soviet Union (1991); the Persian Gulf War (1991).",
       story="The night the Berlin Wall opened"),
  dict(n=29, title="Bridge to the 21st Century", years="1990–Present",
       topics="George H.W. Bush; Bill Clinton, NAFTA, the budget surplus; the personal computer, the internet, and the digital economy; the contested election of 2000 and Bush v. Gore; September 11, 2001, and its aftermath: the Department of Homeland Security, war in Afghanistan, the Iraq War; Hurricane Katrina; the Great Recession of 2008; the election of Barack Obama, the first African American president; the Affordable Care Act; smartphones and social media; globalization; climate change and energy choices; recent elections and the COVID-19 pandemic (strictly factual and neutral); immigration and a diverse nation; how citizens take part.",
       story="Welcome to America: refugees and new citizens today"),
 ]),
]

# The site's existing 6-8 activities, mapped to where they belong in the course.
LINKS = {
 1: [("/s13", "The World Before 1500 — cards, quiz and lab"), ("/s14", "The World's Regions — geography warm-up")],
 3: [("/b9?mod=founding", "The Founding · 1776–1791 — test prep"), ("/h12", "The blueprint"), ("/h13", "Rights in writing"), ("/h5", "Words of a new nation"), ("/h9", "The courts"), ("/h10", "Congress"), ("/h11", "The presidency"), ("/h14", "How a bill becomes a law"), ("/h16", "Put it all together")],
 4: [("/b9?mod=branches", "Civics · The Three Branches — test prep"), ("/b9?mod=growth", "Growth & Economy — test prep"), ("/h1", "Order the story"), ("/h2", "Because of that"), ("/h15", "The Illinois constitution")],
 5: [("/h6", "Map of a growing nation"), ("/h3", "Whose voice?"), ("/h7", "Back it up")],
 6: [("/b9?mod=war", "The Road to War & Freedom — test prep"), ("/h4", "The main idea"), ("/h8", "One person, big ripple"), ("/s15", "Reconstruction to the Present — cards, quiz and lab")],
 7: [("/s15", "Reconstruction to the Present — cards, quiz and lab")],
 8: [("/s15", "Reconstruction to the Present — cards, quiz and lab")],
 9: [("/s15", "Reconstruction to the Present — cards, quiz and lab")],
 10: [("/s15", "Reconstruction to the Present — cards, quiz and lab")],
}
