# -*- coding: utf-8 -*-
"""The Band's lessons (music-band.html). Built by make_lab_lessons.py. Every text is (English, Spanish).
The page marks each step as it happens (AOG-LESSONS-V1 hooks in _work/music/band_script.js)."""

LAB = {
  "lab": "band",
  "key": "aog.band.lessons.v1",
  "page": "/band",
  "sheet": "band-lessons.html",
  "name": ("The Band", "La banda"),
  "steps": {
    # meet the band
    "tap1": ("Play any key on the keys", "Toca cualquier tecla"),
    "pad1": ("Hold a chord pad", "Mantén un pad de acordes"),
    "snd1": ("Pick another instrument in the Instrument menu", "Elige otro instrumento en el menú Instrumento"),
    # the four families
    "sTrumpet": ("Play the trumpet", "Toca la trompeta"),
    "sTrombone": ("Play the trombone", "Toca el trombón"),
    "sHorn": ("Play the French horn", "Toca el corno francés"),
    "sBrassSec": ("Play the brass section, all four", "Toca la sección de metales, los cuatro"),
    "sFlute": ("Play the flute", "Toca la flauta"),
    "sClarinet": ("Play the clarinet", "Toca el clarinete"),
    "sOboe": ("Play the oboe", "Toca el oboe"),
    "sWindsSec": ("Play the woodwinds, all four", "Toca las maderas, las cuatro"),
    "sViolins": ("Play the violins", "Toca los violines"),
    "sCellos": ("Play the cellos", "Toca los violonchelos"),
    "sDbass": ("Play the double bass", "Toca el contrabajo"),
    "sStringsSec": ("Play the string section, all four", "Toca la sección de cuerdas, las cuatro"),
    "sTimpani": ("Play the timpani", "Toca los timbales"),
    "sMallet": ("Play the marimba, the xylophone or the glockenspiel", "Toca la marimba, el xilófono o el glockenspiel"),
    "percPlay": ("Pick a chord pattern and press ▶ Play the chords with the percussion section",
                 "Elige un patrón y pulsa ▶ Tocar los acordes con la sección de percusión"),
    # high and low
    "loTuba": ("Play the tuba's lowest notes, at the left end of the keys", "Toca las notas más graves de la tuba, a la izquierda de las teclas"),
    "hiPicc": ("Play the piccolo's highest notes, at the right end of the keys", "Toca las notas más agudas del flautín, a la derecha de las teclas"),
    "lower1": ("Press ◀ Lower", "Pulsa ◀ Más grave"),
    "higher1": ("Press Higher ▶", "Pulsa Más agudo ▶"),
    # plucked and bowed
    "sBowed": ("Play violins, violas, cellos or double bass with the bow", "Toca violines, violas, violonchelos o contrabajo con el arco"),
    "sPizz": ("Play a plucked string sound (it says “plucked”)", "Toca un sonido de cuerda pulsada (dice “pulsado”)"),
    "sHarp": ("Play the harp", "Toca el arpa"),
    # vibrato and mutes
    "vibPlain": ("Play the trumpet, trombone, flute, oboe or bassoon", "Toca la trompeta, el trombón, la flauta, el oboe o el fagot"),
    "vibHold": ("Pick one “with vibrato” and hold a key for two seconds", "Elige uno “con vibrato” y mantén una tecla dos segundos"),
    "muteOn": ("Play a muted sound (it says “mute”)", "Toca un sonido con sordina (dice “sordina”)"),
    # how the band plays
    "pat1": ("Pick a chord pattern", "Elige un patrón de acordes"),
    "play1": ("Press ▶ Play the chords", "Pulsa ▶ Tocar los acordes"),
    "stop1": ("Press ■ Stop", "Pulsa ■ Parar"),
    "tempo1": ("Move the Tempo slider", "Mueve el control de Tempo"),
    "rh_long": ("Play it with Long notes", "Tócalo con Notas largas"),
    "rh_stabs": ("Play it with Stabs · short and punchy", "Tócalo con Golpes · cortos y con fuerza"),
    "rh_swell": ("Play it with Swell · soft to loud", "Tócalo con Crecer · de suave a fuerte"),
    "rh_march": ("Play it with March · oom-pah", "Tócalo con Marcha · um-pa"),
    "rh_waltz": ("Play it with Waltz · three beats", "Tócalo con Vals · tres tiempos"),
    "rh_offbeat": ("Play it with Off-beat · ska and reggae", "Tócalo con Contratiempo · ska y reggae"),
    "rh_broken": ("Play it with Broken · one note at a time", "Tócalo con Arpegio · una nota a la vez"),
    "kSoft": ("Tap a key near its top: a soft note", "Toca una tecla cerca de arriba: una nota suave"),
    "kLoud": ("Tap a key near its bottom: a loud note", "Toca una tecla cerca de abajo: una nota fuerte"),
    # chords and keys
    "pads6": ("Play all six chord pads", "Toca los seis pads de acordes"),
    "minor1": ("Press Minor · moody", "Pulsa Menor · melancólico"),
    "key1": ("Change the Key", "Cambia el Tono"),
    "keys5": ("Play five different keys", "Toca cinco teclas distintas"),
    "scale1": ("Pick a scale in the Scale menu", "Elige una escala en el menú Escala"),
    "scale3": ("Play three notes that have the scale's dot", "Toca tres notas que tienen el punto de la escala"),
    "own1": ("Press Make my own", "Pulsa Hacer el mío"),
    "own4": ("Tap four chords to build your pattern", "Toca cuatro acordes para armar tu patrón"),
    "wheel1": ("Tap a chord on the chord wheel", "Toca un acorde en la rueda de acordes"),
    "ownPlay": ("Play your own pattern", "Toca tu propio patrón"),
    # jazz
    "sJazzSolo": ("Play a jazz player: a trumpet or a sax with a style name", "Toca un músico de jazz: una trompeta o un saxo con nombre de estilo"),
    "bebopPlay": ("Play a pattern with the Bebop quintet", "Toca un patrón con el Quinteto de bebop"),
    "coolPlay": ("Play a pattern with the Cool jazz group", "Toca un patrón con el Grupo de cool jazz"),
    "bigPlay": ("Play a pattern with the Big band · swing", "Toca un patrón con la Big band · swing"),
    # drum beat
    "drumOn": ("Press Play with my drum beat", "Pulsa Tocar con mi ritmo de batería"),
    "drumPlay": ("Press ▶ Play the chords with your drum beat on", "Pulsa ▶ Tocar los acordes con tu ritmo de batería puesto"),
    # takes
    "rec1": ("Press ● Record", "Pulsa ● Grabar"),
    "rec2": ("Play, then press ■ Stop recording", "Toca y luego pulsa ■ Parar grabación"),
    "takeHear": ("Listen to your take", "Escucha tu toma"),
    "studio1": ("Press Send to the Mixing Desk on your take", "Pulsa Enviar a la mesa de mezclas en tu toma"),
    # songs
    "fanPat": ("Pick the pattern Three chords · 1 4 5 1", "Elige el patrón Tres acordes · 1 4 5 1"),
    "fanPlay": ("Play the brass section with Fanfare", "Toca la sección de metales con Fanfarria"),
    "fanTake": ("Record a take of your fanfare", "Graba una toma de tu fanfarria"),
    "marPlay": ("Play the Marching band with March · oom-pah", "Toca la Banda de marcha con Marcha · um-pa"),
    "marFast": ("March at a tempo of 110 or more", "Marcha con un tempo de 110 o más"),
    "marTake": ("Record a take of your march", "Graba una toma de tu marcha"),
    "lulPlay": ("Play the string section with Waltz", "Toca la sección de cuerdas con Vals"),
    "lulSlow": ("Slow it down: a tempo of 72 or less", "Hazlo lento: un tempo de 72 o menos"),
    "lulHarp": ("Play a tune of eight notes on the harp", "Toca una melodía de ocho notas en el arpa"),
    "balPat": ("Pick a jazz pattern: Jazz · 2 5 1, Jazz turnaround or Circle", "Elige un patrón de jazz: Jazz · 2 5 1, Vuelta de jazz o Círculo"),
    "balPlay": ("Play the tenor sax ballad with Long notes or Swell", "Toca el saxo tenor balada con Notas largas o Crecer"),
    "balKeys": ("Play a tune of eight notes on the tenor sax ballad", "Toca una melodía de ocho notas con el saxo tenor balada"),
    "balTake": ("Record a take with the tenor sax ballad", "Graba una toma con el saxo tenor balada"),
    "mariPat": ("Pick the pattern Fiesta · 1 4 5 4", "Elige el patrón Fiesta · 1 4 5 4"),
    "mariPlay": ("Play Fiesta with the Mariachi", "Toca Fiesta con el Mariachi"),
    "mariWaltz": ("Play the Mariachi with Waltz", "Toca el Mariachi con Vals"),
    "mariDecks": ("With the Mariachi, press Send to the turntables", "Con el Mariachi, pulsa Enviar a los platos"),
    "orchKey": ("Play the Orchestra on the keys or a pad", "Toca la Orquesta en las teclas o un pad"),
    "orchPat": ("Pick the pattern Epic", "Elige el patrón Épico"),
    "orchSwell": ("Play the Orchestra with Swell", "Toca la Orquesta con Crecer"),
    "orchTake": ("Record a take with the Orchestra", "Graba una toma con la Orquesta"),
  },
  "lessons": [
    {"id": "d1", "t": ("Meet the band", "Conoce la banda"),
     "b": ("Every note here is a real player, recorded. Tap a key for one note, or a pad for a whole chord.",
           "Cada nota aquí es un músico de verdad, grabado. Toca una tecla para una nota, o un pad para un acorde entero."),
     "steps": ["tap1", "pad1", "snd1"],
     "try": ("Hold a pad and listen until the sound fades away.", "Mantén un pad y escucha hasta que el sonido se apague."),
     "q": ("Which instrument did you pick? What does it sound like to you?", "¿Qué instrumento elegiste? ¿A qué te suena?"),
     "own": ("Name three instruments you would like to hear in your band.", "Nombra tres instrumentos que te gustaría oír en tu banda.")},
    {"id": "d2", "t": ("The brass family", "La familia de los metales"),
     "b": ("Brass players buzz their lips into a metal mouthpiece. The sound is bright and bold.",
           "Los músicos de metales hacen vibrar los labios en una boquilla de metal. El sonido es brillante y fuerte."),
     "steps": ["sTrumpet", "sTrombone", "sHorn", "sBrassSec"],
     "try": ("Play the same chord pad on each one. Which sounds warmest?", "Toca el mismo pad con cada uno. ¿Cuál suena más cálido?"),
     "q": ("The brass section has four players. Which one plays the lowest note?", "La sección de metales tiene cuatro músicos. ¿Cuál toca la nota más grave?"),
     "own": ("Draw a trumpet. Mark where the air goes in and where the sound comes out.", "Dibuja una trompeta. Marca por dónde entra el aire y por dónde sale el sonido.")},
    {"id": "d3", "t": ("The woodwind family", "La familia de las maderas"),
     "b": ("Woodwinds blow across a hole or through a reed. Their sound is soft and airy, or sweet and reedy.",
           "Las maderas soplan sobre un agujero o por una caña. Su sonido es suave y aireado, o dulce y de caña."),
     "steps": ["sFlute", "sClarinet", "sOboe", "sWindsSec"],
     "try": ("Play a slow tune on the flute, then the same tune on the oboe.", "Toca una melodía lenta en la flauta y luego la misma en el oboe."),
     "q": ("The flute has no reed. Can you hear a difference from the clarinet?", "La flauta no tiene caña. ¿Oyes una diferencia con el clarinete?"),
     "own": ("Pick a woodwind for a bird in a story. Write why.", "Elige una madera para un pájaro de un cuento. Escribe por qué.")},
    {"id": "d4", "t": ("The string family", "La familia de las cuerdas"),
     "b": ("Strings sing when a bow moves across them. Small ones sing high; big ones sing low.",
           "Las cuerdas cantan cuando un arco pasa sobre ellas. Las pequeñas cantan agudo; las grandes, grave."),
     "steps": ["sViolins", "sCellos", "sDbass", "sStringsSec"],
     "try": ("Hold one pad with the string section. Listen for the low bass under the violins.", "Mantén un pad con la sección de cuerdas. Escucha el bajo grave debajo de los violines."),
     "q": ("Which is bigger, a violin or a cello? Which sounds lower?", "¿Qué es más grande, un violín o un violonchelo? ¿Cuál suena más grave?"),
     "own": ("Put the four strings in order from smallest to biggest.", "Ordena las cuatro cuerdas de la más pequeña a la más grande.")},
    {"id": "d5", "t": ("The percussion family", "La familia de la percusión"),
     "b": ("Percussion is struck: drums, bars and bells. Some play notes; some keep the beat.",
           "La percusión se golpea: tambores, láminas y campanas. Unos tocan notas; otros llevan el ritmo."),
     "steps": ["sTimpani", "sMallet", "percPlay"],
     "try": ("Play the glockenspiel up high. It sounds like tiny bells.", "Toca el glockenspiel bien agudo. Suena como campanitas."),
     "q": ("Which percussion sounds play notes? Which only keep the beat?", "¿Qué percusiones tocan notas? ¿Cuáles solo llevan el ritmo?"),
     "own": ("Find three things at home you can tap to make a beat.", "Busca tres cosas en casa que puedas golpear para hacer un ritmo.")},
    {"id": "d6", "t": ("High and low: tuba and piccolo", "Agudo y grave: tuba y flautín"),
     "b": ("The tuba is the lowest voice in the band. The piccolo is the highest.",
           "La tuba es la voz más grave de la banda. El flautín es la más aguda."),
     "steps": ["loTuba", "hiPicc", "lower1", "higher1"],
     "try": ("Play the same key on both. Then move the keys to find each one's lowest note.", "Toca la misma tecla en los dos. Luego mueve las teclas para hallar la nota más grave de cada uno."),
     "q": ("Why does a big instrument sound lower than a small one?", "¿Por qué un instrumento grande suena más grave que uno pequeño?"),
     "own": ("Name an animal for the tuba and one for the piccolo.", "Nombra un animal para la tuba y otro para el flautín.")},
    {"id": "d7", "t": ("Plucked and bowed", "Pulsado y con arco"),
     "b": ("A bow makes a string sing long. A finger plucks it short: that is pizzicato.",
           "Un arco hace cantar la cuerda largo. Un dedo la pulsa corto: eso es pizzicato."),
     "steps": ["sBowed", "sPizz", "sHarp"],
     "try": ("Play the same chord with the violins, then with the plucked violins.", "Toca el mismo acorde con los violines y luego con los violines pulsados."),
     "q": ("Does a plucked note keep going, or fade away?", "¿Una nota pulsada sigue sonando o se apaga?"),
     "own": ("Pluck a rubber band. Is it long or short? High or low?", "Pulsa una liga. ¿Suena larga o corta? ¿Aguda o grave?")},
    {"id": "d8", "t": ("Vibrato and mutes", "Vibrato y sordinas"),
     "b": ("Vibrato is a gentle wobble in a long note. A mute is a cap in the bell that makes the sound softer.",
           "El vibrato es un temblor suave en una nota larga. La sordina es una tapa en la campana que suaviza el sonido."),
     "steps": ["vibPlain", "vibHold", "muteOn"],
     "try": ("Hold one note on the flute, then on the flute with vibrato. Hear the wobble?", "Mantén una nota en la flauta y luego en la flauta con vibrato. ¿Oyes el temblor?"),
     "q": ("Singers use vibrato too. Can you think of a song where you hear it?", "Los cantantes también usan vibrato. ¿Piensas en una canción donde lo oigas?"),
     "own": ("Hum one long note. Now hum it with a small wobble.", "Tararea una nota larga. Ahora tararéala con un pequeño temblor.")},
    {"id": "d9", "t": ("Short and long notes", "Notas cortas y largas"),
     "b": ("Pick a pattern and the band plays it. Long notes are smooth. Stabs are short and punchy.",
           "Elige un patrón y la banda lo toca. Las notas largas son suaves. Los golpes son cortos y con fuerza."),
     "steps": ["pat1", "play1", "rh_long", "rh_stabs", "stop1"],
     "try": ("Keep it playing and change How the band plays. It changes right away.", "Déjalo sonar y cambia Cómo toca la banda. Cambia en el acto."),
     "q": ("Which feels calm, long or short notes? Which feels like dancing?", "¿Qué se siente tranquilo, notas largas o cortas? ¿Cuál se siente como bailar?"),
     "own": ("Clap a long sound, then four short ones. Write them as lines and dots.", "Haz un sonido largo con las palmas y luego cuatro cortos. Escríbelos como rayas y puntos.")},
    {"id": "d10", "t": ("Soft, loud and the swell", "Suave, fuerte y el crecer"),
     "b": ("Where you tap a key sets how loud it is. A swell grows from soft to loud.",
           "Dónde tocas una tecla decide qué tan fuerte suena. Crecer va de suave a fuerte."),
     "steps": ["kSoft", "kLoud", "rh_swell"],
     "try": ("Play the swell with the strings, then with the brass. Which feels bigger?", "Toca Crecer con las cuerdas y luego con los metales. ¿Cuál se siente más grande?"),
     "q": ("Where in a film might you hear a big swell?", "¿En qué parte de una película oirías un gran crecer?"),
     "own": ("Say a word softly, then louder and louder. That is a swell.", "Di una palabra suave, luego cada vez más fuerte. Eso es crecer.")},
    {"id": "d11", "t": ("Chord pads and keys", "Pads de acordes y tonos"),
     "b": ("Six pads, six chords that fit together. Major sounds bright. Minor sounds moody.",
           "Seis pads, seis acordes que van juntos. Mayor suena brillante. Menor suena melancólico."),
     "steps": ["pads6", "minor1", "key1"],
     "try": ("On a computer, keys 1 to 6 play the pads. Make up an order and play it again.", "En la computadora, las teclas del 1 al 6 tocan los pads. Inventa un orden y tócalo otra vez."),
     "q": ("Play pad 1 in Major, then in Minor. How does each one feel?", "Toca el pad 1 en Mayor y luego en Menor. ¿Cómo se siente cada uno?"),
     "own": ("Write the four pads you like best, in order.", "Escribe los cuatro pads que más te gustan, en orden.")},
    {"id": "d12", "t": ("A tune on the keys", "Una melodía en las teclas"),
     "b": ("One key, one note. Pick a scale and the keys show which notes fit.",
           "Una tecla, una nota. Elige una escala y las teclas muestran qué notas encajan."),
     "steps": ["keys5", "scale1", "scale3"],
     "try": ("Play only the dotted keys, going up, then coming down.", "Toca solo las teclas con punto, subiendo y luego bajando."),
     "q": ("Is your tune happy, calm or sad? What makes it sound that way?", "¿Tu melodía es alegre, tranquila o triste? ¿Qué la hace sonar así?"),
     "own": ("Write your tune as note names, like C D E C.", "Escribe tu melodía con los nombres de las notas, como Do Re Mi Do.")},
    {"id": "d13", "t": ("Your own chord pattern", "Tu propio patrón de acordes"),
     "b": ("Make my own lets you choose the chords. Tap pads or the wheel in the order you want.",
           "Hacer el mío te deja elegir los acordes. Toca pads o la rueda en el orden que quieras."),
     "steps": ["own1", "own4", "wheel1", "ownPlay"],
     "try": ("Start and end your pattern on pad 1. It feels like coming home.", "Empieza y termina tu patrón en el pad 1. Se siente como volver a casa."),
     "q": ("Which chord in your pattern surprised you?", "¿Qué acorde de tu patrón te sorprendió?"),
     "own": ("Write your pattern as pad numbers, like 1 4 5 1.", "Escribe tu patrón con números de pad, como 1 4 5 1.")},
    {"id": "d14", "t": ("Tempo and the band's rhythms", "El tempo y los ritmos de la banda"),
     "b": ("Tempo is how fast. How the band plays sets the rhythm: a march, a waltz and more.",
           "El tempo es qué tan rápido. Cómo toca la banda decide el ritmo: una marcha, un vals y más."),
     "steps": ["tempo1", "rh_march", "rh_waltz", "rh_offbeat", "rh_broken"],
     "try": ("A waltz counts 1 2 3. Count along out loud.", "Un vals cuenta 1 2 3. Cuenta en voz alta."),
     "q": ("Which rhythm would you walk to? Which would you sway to?", "¿Con qué ritmo caminarías? ¿Con cuál te mecerías?"),
     "own": ("Pick a rhythm and a tempo for a rainy day. Write them down.", "Elige un ritmo y un tempo para un día de lluvia. Escríbelos.")},
    {"id": "d15", "t": ("Jazz groups and the big band", "Grupos de jazz y la big band"),
     "b": ("Jazz players each have a style. Small groups play close together; a big band is loud and swings.",
           "Cada músico de jazz tiene un estilo. Los grupos pequeños tocan juntos y cerca; una big band suena fuerte y con swing."),
     "steps": ["sJazzSolo", "bebopPlay", "coolPlay", "bigPlay"],
     "try": ("Pick Blues · 12 bars and play it with the big band and Stabs.", "Elige Blues · 12 compases y tócalo con la big band y Golpes."),
     "q": ("Bebop or cool jazz: which one feels relaxed? Which feels busy?", "Bebop o cool jazz: ¿cuál se siente relajado? ¿Cuál se siente movido?"),
     "own": ("Name a jazz player you would like to hear. Ask someone at home for one.", "Nombra un músico de jazz que te gustaría oír. Pregunta a alguien en casa.")},
    {"id": "d16", "t": ("Play along with your drum beat", "Toca con tu ritmo de batería"),
     "b": ("Make a beat on the drum machine and press Send to the turntables. Then the band can play along with it.",
           "Haz un ritmo en la caja de ritmos y pulsa Enviar a los platos. Así la banda puede tocar con él."),
     "steps": ["drumOn", "drumPlay"],
     "try": ("Try a march beat with the marching band, or a swing beat with the big band.", "Prueba un ritmo de marcha con la banda de marcha, o uno de swing con la big band."),
     "q": ("The tempo comes from your drum beat. Why does the band follow the drums?", "El tempo viene de tu ritmo de batería. ¿Por qué la banda sigue a la batería?"),
     "own": ("Write which beat and which instrument sound best together.", "Escribe qué ritmo y qué instrumento suenan mejor juntos.")},
    {"id": "d17", "t": ("Record a take and send it", "Graba una toma y envíala"),
     "b": ("● Record keeps what the band plays. Your take can go to the Mixing Desk to become part of a song.",
           "● Grabar guarda lo que toca la banda. Tu toma puede ir a la mesa de mezclas para ser parte de una canción."),
     "steps": ["rec1", "rec2", "takeHear", "studio1"],
     "try": ("Record the chords first. Then record a tune on the keys as a second take.", "Graba primero los acordes. Luego graba una melodía en las teclas como segunda toma."),
     "q": ("What did you like about your take? What would you change?", "¿Qué te gustó de tu toma? ¿Qué cambiarías?"),
     "own": ("Give your take a name and write it here.", "Ponle un nombre a tu toma y escríbelo aquí.")},
    # songs
    {"id": "d18", "t": ("Song: A fanfare", "Canción: Una fanfarria"),
     "b": ("A fanfare is brass saying “Hooray, here they come!”", "Una fanfarria son los metales diciendo “¡Hurra, aquí vienen!”"),
     "steps": ["fanPat", "fanPlay", "fanTake"],
     "try": ("Add the timpani: play it once more with the percussion section.", "Añade los timbales: tócala otra vez con la sección de percusión."),
     "q": ("Who would you play a fanfare for?", "¿Para quién tocarías una fanfarria?"),
     "own": ("Write the moment your fanfare is for, in one line.", "Escribe en una línea para qué momento es tu fanfarria."),
     "song": True},
    {"id": "d19", "t": ("Song: A march", "Canción: Una marcha"),
     "b": ("A marching band plays oom-pah so everyone steps together.", "Una banda de marcha toca um-pa para que todos caminen juntos."),
     "steps": ["marPlay", "marFast", "marTake"],
     "try": ("March on the spot while it plays: left on oom, right on pah.", "Marcha en tu lugar mientras suena: izquierda en um, derecha en pa."),
     "q": ("Where have you seen a marching band?", "¿Dónde has visto una banda de marcha?"),
     "own": ("Write the tempo that felt best for marching.", "Escribe el tempo que se sintió mejor para marchar."),
     "song": True},
    {"id": "d20", "t": ("Song: A lullaby on strings", "Canción: Una canción de cuna con cuerdas"),
     "b": ("Soft strings, a slow waltz and a harp tune: music for resting.", "Cuerdas suaves, un vals lento y una melodía de arpa: música para descansar."),
     "steps": ["lulPlay", "lulSlow", "lulHarp"],
     "try": ("Turn the Volume down a little. Calm music can be quiet.", "Baja un poco el Volumen. La música tranquila puede ser suave."),
     "q": ("What makes music feel calm to you?", "¿Qué hace que una música te parezca tranquila?"),
     "own": ("Write who or what your lullaby is for.", "Escribe para quién o para qué es tu canción de cuna."),
     "song": True},
    {"id": "d21", "t": ("Song: A jazz ballad on sax", "Canción: Una balada de jazz con saxo"),
     "b": ("A ballad is slow and warm. The tenor sax sings the tune over jazz chords.",
           "Una balada es lenta y cálida. El saxo tenor canta la melodía sobre acordes de jazz."),
     "steps": ["balPat", "balPlay", "balKeys", "balTake"],
     "try": ("Pick the Tenor sax · ballad. Play the chords, then play your tune over them.", "Elige Saxo tenor · balada. Toca los acordes y luego tu melodía encima."),
     "q": ("Jazz players make up tunes as they play. How did it feel to try?", "Los músicos de jazz inventan melodías mientras tocan. ¿Cómo se sintió probarlo?"),
     "own": ("Give your ballad a title.", "Ponle un título a tu balada."),
     "song": True},
    {"id": "d22", "t": ("Song: A mariachi celebration", "Canción: Una fiesta de mariachi"),
     "b": ("Mariachi is music from Mexico: trumpets, violins, harp and a plucked bass, for a party.",
           "El mariachi es música de México: trompetas, violines, arpa y un bajo pulsado, para una fiesta."),
     "steps": ["mariPat", "mariPlay", "mariWaltz", "mariDecks"],
     "try": ("Make it faster and shout ¡Ajúa! at the end.", "Hazlo más rápido y grita ¡Ajúa! al final."),
     "q": ("What celebration would you play this at?", "¿En qué celebración tocarías esto?"),
     "own": ("Write the names of the instruments in a mariachi.", "Escribe los nombres de los instrumentos de un mariachi."),
     "song": True},
    {"id": "d23", "t": ("Song: The whole orchestra", "Canción: Toda la orquesta"),
     "b": ("In the orchestra everyone plays together: strings, woodwinds, brass and percussion.",
           "En la orquesta todos tocan juntos: cuerdas, maderas, metales y percusión."),
     "steps": ["orchKey", "orchPat", "orchSwell", "orchTake"],
     "try": ("Send your take to the Mixing Desk. Add a drum part there.", "Envía tu toma a la mesa de mezclas. Añade allí una parte de batería."),
     "q": ("Which family could you hear best in the orchestra?", "¿Qué familia oíste mejor en la orquesta?"),
     "own": ("Draw the orchestra: who sits at the front, who sits at the back?", "Dibuja la orquesta: ¿quién se sienta delante y quién detrás?"),
     "song": True},
  ],
}
