# -*- coding: utf-8 -*-
"""The Drum Kit's lessons (music-kit.html). Built by make_lab_lessons.py. Every text is (English, Spanish).
The page marks each step as it happens (AOG-LESSONS-V1 hooks in music-kit.html)."""

LAB = {
  "lab": "kit",
  "key": "aog.kit.lessons.v1",
  "page": "/drum-kit",
  "sheet": "drum-kit-lessons.html",
  "name": ("The Drum Kit", "La batería"),
  "steps": {
    # meet the kit
    "tap1": ("Tap any drum", "Toca cualquier tambor"),
    "kick": ("Tap the kick, the big drum at the bottom", "Toca el bombo, el tambor grande de abajo"),
    "snare": ("Tap the snare", "Toca la caja"),
    "hat": ("Tap the closed hi-hat", "Toca el charles cerrado"),
    # loud and soft
    "loud": ("Tap right in the middle of a drum: a loud hit", "Toca justo en el centro de un tambor: un golpe fuerte"),
    "soft": ("Tap near the edge of a drum: a soft hit", "Toca cerca del borde de un tambor: un golpe suave"),
    "ghost": ("Tap the snare softly, near its edge: a ghost note", "Toca la caja suave, cerca del borde: una nota fantasma"),
    # kits
    "kit1": ("Pick another kit in Drum kit", "Elige otra batería en Batería"),
    "kits3": ("Try three different kits", "Prueba tres baterías distintas"),
    # cymbals
    "crash": ("Tap the crash cymbal", "Toca el platillo crash"),
    "ride": ("Tap the ride cymbal", "Toca el platillo ride"),
    "ride8": ("Tap the ride 8 times in a row, steady", "Toca el ride 8 veces seguidas, parejo"),
    # hi-hat
    "open": ("Tap the open hi-hat and let it ring", "Toca el charles abierto y déjalo sonar"),
    "choke": ("Tap the open hat, then the closed hat to stop it", "Toca el charles abierto y luego el cerrado para pararlo"),
    "kitped": ("Pick a kit with a hi-hat pedal: Kit R, U or X", "Elige una batería con pedal de charles: Kit R, U o X"),
    "pedal": ("Tap the hi-hat pedal", "Toca el pedal del charles"),
    "pchoke": ("Tap the open hat, then stop it with the pedal", "Toca el charles abierto y luego páralo con el pedal"),
    # toms
    "tom": ("Tap a tom", "Toca un tom"),
    "kitS": ("Pick Kit S · prog rock, many toms", "Elige Kit S · rock progresivo, muchos toms"),
    "tom3": ("On Kit S, tap the high tom, the middle tom, then the floor tom", "En el Kit S, toca el tom agudo, el tom medio y luego el tom de piso"),
    # rock beat by hand
    "hatkick": ("Tap the hi-hat and the kick at the same time, with two fingers", "Toca el charles y el bombo a la vez, con dos dedos"),
    "rockhand": ("Play kick, snare, kick, snare, with hi-hat taps in between", "Toca bombo, caja, bombo, caja, con toques de charles en medio"),
    # beat player
    "beat1": ("Pick a beat in Beat", "Elige un ritmo en Ritmo"),
    "play1": ("Press ▶ Play the beat", "Pulsa ▶ Tocar el ritmo"),
    "stop1": ("Press ■ Stop the beat", "Pulsa ■ Parar el ritmo"),
    "tempo1": ("Change the Speed", "Cambia la Velocidad"),
    "tfast": ("Make it fast: 140 or more", "Hazlo rápido: 140 o más"),
    "tslow": ("Make it slow: 70 or less", "Hazlo lento: 70 o menos"),
    "reset1": ("Press ↺ to get the beat's own speed back", "Pulsa ↺ para volver a la velocidad del ritmo"),
    "sw60": ("Set Swing to 60 % or more", "Pon el Swing en 60 % o más"),
    "playsw": ("Play a beat with swing on", "Toca un ritmo con el swing puesto"),
    "sw50": ("Bring Swing back to 50 %: straight", "Vuelve a poner el Swing en 50 %: recto"),
    # play along
    "vol1": ("Change the Beat volume", "Cambia el Volumen del ritmo"),
    "along8": ("Tap 8 hits while the beat plays", "Toca 8 golpes mientras suena el ritmo"),
    "backbeat": ("Tap the snare on 2 and 4 with the beat, four times", "Toca la caja en el 2 y el 4 con el ritmo, cuatro veces"),
    # fills
    "fill4": ("Play four tom hits in a row, quickly", "Toca cuatro golpes de tom seguidos, rápido"),
    "fillcrash": ("Play a tom fill, then a crash right after", "Toca un redoble en los toms y justo después un crash"),
    "crash1": ("Tap the crash on 1, while the beat plays", "Toca el crash en el 1 mientras suena el ritmo"),
    # record a take
    "take1": ("Press ● Record a take", "Pulsa ● Grabar una toma"),
    "take2": ("Play, then stop recording", "Toca y luego para la grabación"),
    # whole screen
    "big1": ("Open the whole-screen kit: turn your phone sideways, or press ⤢", "Abre la batería en toda la pantalla: gira el teléfono de lado o pulsa ⤢"),
    "sidetap": ("Play a drum on the whole-screen kit", "Toca un tambor en la batería de pantalla completa"),
    "sideclose": ("Press ✕ Close in ☰ Menu", "Pulsa ✕ Cerrar en ☰ Menú"),
    # songs
    "srock": ("Play a beat from Rock on Kit J, Q, S or T", "Toca un ritmo de Rock en el Kit J, Q, S o T"),
    "srock16": ("Play along: 16 hits with the rock beat", "Toca encima: 16 golpes con el ritmo de rock"),
    "scrash": ("Tap the crash on 1 with the rock beat", "Toca el crash en el 1 con el ritmo de rock"),
    "sfunk": ("Play a beat from Funk and soul on Kit W · studio funk", "Toca un ritmo de Funk y soul en el Kit W · funk de estudio"),
    "sghost": ("Tap 4 ghost notes on the snare with the funk beat", "Toca 4 notas fantasma en la caja con el ritmo de funk"),
    "sfunk16": ("Play along: 16 hits with the funk beat", "Toca encima: 16 golpes con el ritmo de funk"),
    "sjazz": ("Play a beat from Jazz and swing on Kit K or Kit V, the brush kits", "Toca un ritmo de Jazz y swing en el Kit K o el Kit V, las de escobillas"),
    "sride": ("Tap the ride 8 times with the jazz beat", "Toca el ride 8 veces con el ritmo de jazz"),
    "schick": ("Tap the hi-hat on 2 and 4 with the jazz beat, four times", "Toca el charles en el 2 y el 4 con el ritmo de jazz, cuatro veces"),
    "slatin": ("Play a beat from Latin on Kit H · Latin percussion", "Toca un ritmo de Latino en el Kit H · percusión latina"),
    "sconga": ("Tap the conga or the bongo 8 times with the beat", "Toca la conga o el bongó 8 veces con el ritmo"),
    "sclave": ("Tap the clave 8 times with the beat", "Toca la clave 8 veces con el ritmo"),
    "smarch": ("Play Military march, March or Parade on Kit O · marching band", "Toca Marcha militar, Marcha o Desfile en el Kit O · banda de marcha"),
    "sroll": ("Tap the snare roll with the march", "Toca el redoble con la marcha"),
    "ssnare8": ("Tap the snare 8 times with the march", "Toca la caja 8 veces con la marcha"),
    "stake": ("Start ● Record a take while a beat plays", "Empieza ● Grabar una toma mientras suena un ritmo"),
    "staketap": ("Play 16 hits while it records", "Toca 16 golpes mientras graba"),
  },
  "lessons": [
    {"id": "k1", "t": ("Meet the kit", "Conoce la batería"),
     "b": ("A drum kit is many drums and cymbals played by one person. Start with the three you hear most.",
           "Una batería son muchos tambores y platillos que toca una sola persona. Empieza con los tres que más se oyen."),
     "steps": ["tap1", "kick", "snare", "hat"],
     "try": ("Say each name out loud as you tap it: kick, snare, hi-hat.", "Di cada nombre en voz alta al tocarlo: bombo, caja, charles."),
     "q": ("Which drum sounds the deepest? Which sounds the brightest?", "¿Qué tambor suena más grave? ¿Cuál suena más brillante?"),
     "own": ("Draw the kit and label the kick, the snare and the hi-hat.", "Dibuja la batería y escribe dónde están el bombo, la caja y el charles.")},
    {"id": "k2", "t": ("Loud and soft", "Fuerte y suave"),
     "b": ("Where you tap changes the sound. The middle plays loud. The edge plays soft.",
           "Donde tocas cambia el sonido. El centro suena fuerte. El borde suena suave."),
     "steps": ["loud", "soft", "ghost"],
     "try": ("Play the snare loud, soft, loud, soft. Can you hear the difference?", "Toca la caja fuerte, suave, fuerte, suave. ¿Oyes la diferencia?"),
     "q": ("Why would a drummer want to play softly sometimes?", "¿Por qué un baterista querría tocar suave a veces?"),
     "own": ("Write a pattern of four hits. Mark each one L for loud or S for soft.", "Escribe un patrón de cuatro golpes. Marca cada uno con F de fuerte o S de suave.")},
    {"id": "k3", "t": ("Every kit has a style", "Cada batería tiene su estilo"),
     "b": ("Each kit is a real recording of a different drum set. Some are for rock, some for jazz, some for Latin music.",
           "Cada batería es una grabación de verdad de un set distinto. Unas son para rock, otras para jazz, otras para música latina."),
     "steps": ["kit1", "kits3"],
     "try": ("Play the same three taps on each kit. Which one do you like best?", "Toca los mismos tres golpes en cada batería. ¿Cuál te gusta más?"),
     "q": ("How does the kit change the feeling of the music?", "¿Cómo cambia la batería lo que se siente en la música?"),
     "own": ("Name your favorite kit. Write three words for how it sounds.", "Escribe tu batería favorita y tres palabras de cómo suena.")},
    {"id": "k4", "t": ("Crash and ride", "Crash y ride"),
     "b": ("Two big cymbals. The crash is for big moments. The ride keeps a steady beat.",
           "Dos platillos grandes. El crash es para los momentos grandes. El ride lleva un pulso parejo."),
     "steps": ["crash", "ride", "ride8"],
     "try": ("Tap the ride like a clock: tick, tick, tick, tick. Keep it even.", "Toca el ride como un reloj: tic, tic, tic, tic. Mantenlo parejo."),
     "q": ("When in a song would you hit the crash?", "¿En qué momento de una canción tocarías el crash?"),
     "own": ("Write a place in a song you know where a crash would sound great.", "Escribe un momento de una canción que conozcas donde un crash sonaría genial.")},
    {"id": "k5", "t": ("The hi-hat: open and closed", "El charles: abierto y cerrado"),
     "b": ("The hi-hat is two cymbals. Closed, it ticks. Open, it rings. A closed tap stops the ring, like on a real kit.",
           "El charles son dos platillos. Cerrado, hace tic. Abierto, suena largo. Un toque cerrado para el sonido, como en una batería de verdad."),
     "steps": ["hat", "open", "choke"],
     "try": ("Play tick, tick, tick, open, then close it. Do it again.", "Toca tic, tic, tic, abierto, y luego ciérralo. Hazlo otra vez."),
     "q": ("Why does a closed hat stop an open one?", "¿Por qué el charles cerrado para al abierto?"),
     "own": ("Write a hi-hat pattern with x for closed and o for open.", "Escribe un patrón de charles con x para cerrado y o para abierto.")},
    {"id": "k6", "t": ("The hi-hat pedal", "El pedal del charles"),
     "b": ("A drummer closes the hi-hat with a foot pedal. It makes a soft chick and stops an open hat.",
           "El baterista cierra el charles con un pedal. Hace un chic suave y para el charles abierto."),
     "steps": ["kitped", "pedal", "pchoke"],
     "try": ("Tap the pedal on every other beat while your other hand plays the ride.", "Toca el pedal cada dos pulsos mientras la otra mano toca el ride."),
     "q": ("A drummer uses both hands and both feet. Which part does each foot play?", "Un baterista usa las dos manos y los dos pies. ¿Qué toca cada pie?"),
     "own": ("Write which fingers you use for the pedal and for the ride.", "Escribe qué dedos usas para el pedal y para el ride.")},
    {"id": "k7", "t": ("The toms", "Los toms"),
     "b": ("Toms are the round drums that sing a note. Small toms sound high. The floor tom sounds low.",
           "Los toms son los tambores redondos que cantan una nota. Los pequeños suenan agudo. El tom de piso suena grave."),
     "steps": ["tom", "kitS", "tom3"],
     "try": ("Go high, middle, low, then low, middle, high.", "Ve de agudo a medio a grave, y luego de grave a medio a agudo."),
     "q": ("Why is a bigger drum lower?", "¿Por qué un tambor más grande suena más grave?"),
     "own": ("Draw the three toms from smallest to biggest.", "Dibuja los tres toms del más pequeño al más grande.")},
    {"id": "k8", "t": ("A rock beat with your fingers", "Un ritmo de rock con los dedos"),
     "b": ("The rock beat: kick, snare, kick, snare, with the hi-hat ticking in between. Use both hands.",
           "El ritmo de rock: bombo, caja, bombo, caja, con el charles marcando en medio. Usa las dos manos."),
     "steps": ["hatkick", "rockhand"],
     "try": ("Go slowly. Count 1, 2, 3, 4: kick on 1 and 3, snare on 2 and 4.", "Ve despacio. Cuenta 1, 2, 3, 4: bombo en el 1 y el 3, caja en el 2 y el 4."),
     "q": ("Why do so many songs use this beat?", "¿Por qué tantas canciones usan este ritmo?"),
     "own": ("Write the beat: K for kick, S for snare, H for hi-hat.", "Escribe el ritmo: B para bombo, C para caja, H para charles.")},
    {"id": "k9", "t": ("The beat player", "El reproductor de ritmos"),
     "b": ("Under the kit is a beat that plays by itself on the kit you picked. It starts only when you press Play.",
           "Debajo de la batería hay un ritmo que suena solo en la batería que elegiste. Empieza solo cuando pulsas Tocar."),
     "steps": ["beat1", "play1", "stop1"],
     "try": ("Watch the drums light up as the beat plays. Which ones does it use?", "Mira cómo se encienden los tambores con el ritmo. ¿Cuáles usa?"),
     "q": ("Pick a beat from a style you have never heard. What did you notice?", "Elige un ritmo de un estilo que nunca oíste. ¿Qué notaste?"),
     "own": ("Write the names of three beats you liked.", "Escribe los nombres de tres ritmos que te gustaron.")},
    {"id": "k10", "t": ("Fast and slow", "Rápido y lento"),
     "b": ("Speed is how many beats play in one minute. The same beat feels new when it is faster or slower.",
           "La velocidad es cuántos pulsos suenan en un minuto. El mismo ritmo se siente nuevo más rápido o más lento."),
     "steps": ["tempo1", "tfast", "tslow", "reset1"],
     "try": ("Tap your foot to the beat at 70, then at 140.", "Marca el pulso con el pie a 70 y luego a 140."),
     "q": ("Which speed feels calm? Which feels exciting?", "¿Qué velocidad se siente tranquila? ¿Cuál emociona?"),
     "own": ("Find the speed you like best for one beat. Write it down.", "Busca la velocidad que más te gusta para un ritmo. Escríbela.")},
    {"id": "k11", "t": ("Swing", "El swing"),
     "b": ("Swing makes every second note a little late. Straight sounds even. Swing sounds bouncy.",
           "El swing hace que cada segunda nota llegue un poco tarde. Recto suena parejo. Con swing suena saltarín."),
     "steps": ["sw60", "playsw", "sw50"],
     "try": ("Play the same beat straight, then with swing. Say \"ta-ta\" and then \"taa-ta\".", "Toca el mismo ritmo recto y luego con swing. Di \"ta-ta\" y luego \"taa-ta\"."),
     "q": ("What kinds of music swing?", "¿Qué tipos de música tienen swing?"),
     "own": ("Write the swing number that sounds best to you, and why.", "Escribe el número de swing que mejor te suena y por qué.")},
    {"id": "k12", "t": ("Play along: the backbeat", "Toca encima: el contratiempo"),
     "b": ("Now you join the band. Turn the beat down, then add your own hits on top.",
           "Ahora entras a la banda. Baja el ritmo y luego toca tus golpes encima."),
     "steps": ["vol1", "along8", "backbeat"],
     "try": ("Count 1, 2, 3, 4 out loud. Tap the snare on 2 and 4.", "Cuenta 1, 2, 3, 4 en voz alta. Toca la caja en el 2 y el 4."),
     "q": ("How do you know where 1 is in the beat?", "¿Cómo sabes dónde está el 1 en el ritmo?"),
     "own": ("Write which beat was easiest to play along with.", "Escribe con qué ritmo fue más fácil tocar encima.")},
    {"id": "k13", "t": ("Fills and the crash on 1", "Redobles y el crash en el 1"),
     "b": ("A fill is a short run on the toms at the end of a part. It often lands on a crash, right on 1.",
           "Un redoble es una corrida corta en los toms al final de una parte. Muchas veces cae en un crash, justo en el 1."),
     "steps": ["fill4", "fillcrash", "crash1"],
     "try": ("Count 1, 2, 3, 4. Play the fill on 4. Crash on the next 1.", "Cuenta 1, 2, 3, 4. Toca el redoble en el 4. Crash en el siguiente 1."),
     "q": ("Why does a crash on 1 feel like a new start?", "¿Por qué un crash en el 1 se siente como un nuevo comienzo?"),
     "own": ("Make up a fill. Write the toms you use, in order.", "Inventa un redoble. Escribe los toms que usas, en orden.")},
    {"id": "k14", "t": ("Record a take", "Graba una toma"),
     "b": ("A take is a recording of you playing. You can listen back, keep it or delete it.",
           "Una toma es una grabación de lo que tocas. Puedes escucharla, guardarla o borrarla."),
     "steps": ["take1", "take2"],
     "try": ("Listen to your take. What would you play the same next time? What would you change?", "Escucha tu toma. ¿Qué tocarías igual la próxima vez? ¿Qué cambiarías?"),
     "q": ("Why do musicians record themselves?", "¿Por qué los músicos se graban?"),
     "own": ("Write one thing you liked in your take.", "Escribe algo que te gustó de tu toma.")},
    {"id": "k15", "t": ("The whole screen", "Toda la pantalla"),
     "b": ("The kit can fill the whole screen, so every drum is bigger under your fingers.",
           "La batería puede llenar toda la pantalla, así cada tambor queda más grande bajo tus dedos."),
     "steps": ["big1", "sidetap", "sideclose"],
     "try": ("Hold the phone or tablet with both hands. Play with your thumbs.", "Sostén el teléfono o la tableta con las dos manos. Toca con los pulgares."),
     "q": ("Is it easier to play big or small? Why?", "¿Es más fácil tocar en grande o en pequeño? ¿Por qué?"),
     "own": ("Write which fingers play which drums.", "Escribe qué dedos tocan qué tambores.")},
    {"id": "k16", "t": ("Song: Rock out", "Canción: A rockear"),
     "b": ("A big rock groove on a big kit, with a crash to start each part.",
           "Un groove de rock grande en una batería grande, con un crash al empezar cada parte."),
     "steps": ["srock", "srock16", "scrash"],
     "try": ("Play along for four bars, then a tom fill, then crash on 1.", "Toca encima cuatro compases, luego un redoble en los toms y un crash en el 1."),
     "q": ("What makes rock drums sound big?", "¿Qué hace que la batería de rock suene grande?"),
     "own": ("Name your rock song. Write which beat and kit you used.", "Ponle nombre a tu canción de rock. Escribe qué ritmo y qué batería usaste."),
     "song": True},
    {"id": "k17", "t": ("Song: Funk groove", "Canción: Groove de funk"),
     "b": ("Funk is tight and bouncy. Soft ghost notes on the snare fill the gaps.",
           "El funk es ajustado y saltarín. Las notas fantasma suaves en la caja llenan los huecos."),
     "steps": ["sfunk", "sghost", "sfunk16"],
     "try": ("Keep the loud snare on 2 and 4. Put soft ghost notes between them.", "Deja la caja fuerte en el 2 y el 4. Pon notas fantasma suaves entre ellas."),
     "q": ("How do soft notes make a groove feel better?", "¿Cómo hacen las notas suaves que un groove se sienta mejor?"),
     "own": ("Write where your ghost notes go in the bar.", "Escribe dónde van tus notas fantasma en el compás."),
     "song": True},
    {"id": "k18", "t": ("Song: Jazz with brushes", "Canción: Jazz con escobillas"),
     "b": ("Jazz drummers swing on the ride and close the hi-hat on 2 and 4. Brushes make it soft and warm.",
           "Los bateristas de jazz llevan el swing en el ride y cierran el charles en el 2 y el 4. Las escobillas lo hacen suave y cálido."),
     "steps": ["sjazz", "sride", "schick"],
     "try": ("Ride pattern: ding, ding-a, ding, ding-a. Say it while you tap.", "Patrón de ride: din, din-ga, din, din-ga. Dilo mientras tocas."),
     "q": ("How are brushes different from sticks?", "¿En qué se diferencian las escobillas de las baquetas?"),
     "own": ("Write the ride pattern with words or marks.", "Escribe el patrón del ride con palabras o marcas."),
     "song": True},
    {"id": "k19", "t": ("Song: Latin groove", "Canción: Groove latino"),
     "b": ("Latin music has many drums talking together: congas, bongos, clave and more.",
           "La música latina tiene muchos tambores conversando: congas, bongós, clave y más."),
     "steps": ["slatin", "sconga", "sclave"],
     "try": ("The clave pattern: 1, 2, 3 ... 1, 2. Tap it over the beat.", "El patrón de clave: 1, 2, 3 ... 1, 2. Tócalo sobre el ritmo."),
     "q": ("Why do Latin bands have so many drummers?", "¿Por qué las bandas latinas tienen tantos percusionistas?"),
     "own": ("Write the names of the Latin drums you played.", "Escribe los nombres de los tambores latinos que tocaste."),
     "song": True},
    {"id": "k20", "t": ("Song: March", "Canción: Marcha"),
     "b": ("A marching band walks to the drums. The snare keeps everyone in step.",
           "Una banda de marcha camina al ritmo de los tambores. La caja mantiene a todos al paso."),
     "steps": ["smarch", "sroll", "ssnare8"],
     "try": ("March in place while you tap: left, right, left, right.", "Marcha en tu lugar mientras tocas: izquierda, derecha, izquierda, derecha."),
     "q": ("Where have you heard a marching band?", "¿Dónde has oído una banda de marcha?"),
     "own": ("Write a short snare part for your own march.", "Escribe una parte corta de caja para tu propia marcha."),
     "song": True},
    {"id": "k21", "t": ("Song: Your own groove", "Canción: Tu propio groove"),
     "b": ("Pick any kit and any beat. Play your own part on top and record it.",
           "Elige cualquier batería y cualquier ritmo. Toca tu parte encima y grábala."),
     "steps": ["stake", "staketap", "take2"],
     "try": ("Plan it first: a groove, a fill, a crash, then the groove again.", "Planéalo primero: un groove, un redoble, un crash y otra vez el groove."),
     "q": ("What would you change if you played it again?", "¿Qué cambiarías si lo tocaras otra vez?"),
     "own": ("Write your groove's name, its kit, its beat and its speed.", "Escribe el nombre de tu groove, su batería, su ritmo y su velocidad."),
     "song": True},
  ],
}
