# -*- coding: utf-8 -*-
"""The Bass's lessons (music-bass.html, built from _work/music/strings_page.html). Built by make_lab_lessons.py.
Every text is (English, Spanish). The page marks each step as it happens (AOG-LESSONS-V1 hooks in strings_page.html)."""

LAB = {
  "lab": "bass",
  "key": "aog.bass.lessons.v1",
  "page": "/bass",
  "sheet": "bass-lessons.html",
  "name": ("The Bass", "El bajo"),
  "steps": {
    "open0": ("Play the low E string: the thickest one", "Toca la cuerda Mi: la más gruesa"),
    "open1": ("Play the A string", "Toca la cuerda La"),
    "open2": ("Play the D string", "Toca la cuerda Re"),
    "open3": ("Play the G string: the thinnest one", "Toca la cuerda Sol: la más fina"),
    "fret1": ("Tap a string on any fret", "Toca una cuerda en cualquier traste"),
    "higher": ("Press Higher ▶", "Pulsa Más agudo ▶"),
    "fret5": ("Play a note on fret 5 or higher", "Toca una nota en el traste 5 o más arriba"),
    "lower": ("Press ◀ Lower", "Pulsa ◀ Más grave"),
    "pad1": ("Tap a chord pad: you hear its root, the chord's home note", "Toca un pad de acorde: oyes su raíz, la nota casa del acorde"),
    "padall": ("Play all six chord pads", "Toca los seis pads de acordes"),
    "seven": ("In the row of chords by the neck, play one of the last four", "En la fila de acordes junto al mástil, toca uno de los cuatro últimos"),
    "mute": ("Press ✋ Mute the strings", "Pulsa ✋ Apagar las cuerdas"),
    "octave": ("Play a note, then the same note an octave higher", "Toca una nota y luego la misma nota una octava más aguda"),
    "fret12": ("Play a note on fret 12", "Toca una nota en el traste 12"),
    "fifth": ("Play a note, then its fifth: one string up, two frets up", "Toca una nota y luego su quinta: una cuerda más arriba, dos trastes más"),
    "fifthlow": ("Play a note, then the fifth below it: same fret, one string lower", "Toca una nota y luego la quinta de abajo: el mismo traste, una cuerda más grave"),
    "pat1": ("Pick a pattern in Start from a chord pattern", "Elige un patrón en Empieza con un patrón de acordes"),
    "play": ("Press ▶ Play the chords", "Pulsa ▶ Tocar los acordes"),
    "tempo": ("Move the Tempo slider", "Mueve el control de Tempo"),
    "stop": ("Press ■ Stop", "Pulsa ■ Parar"),
    "p_root": ("Play the chords with Root", "Toca los acordes con Raíz"),
    "p_steady": ("Play the chords with Steady", "Toca los acordes con Constante"),
    "p_eighths": ("Play the chords with Driving", "Toca los acordes con Con empuje"),
    "p_fifth": ("Play the chords with Root and fifth", "Toca los acordes con Raíz y quinta"),
    "p_waltz": ("Play the chords with Waltz", "Toca los acordes con Vals"),
    "p_walk": ("Play the chords with Walking", "Toca los acordes con Caminando"),
    "p_arpeggio": ("Play the chords with Arpeggio", "Toca los acordes con Arpegio"),
    "p_octave": ("Play the chords with Octaves", "Toca los acordes con Octavas"),
    "p_approach": ("Play the chords with Lead-in", "Toca los acordes con Entrada"),
    "key1": ("Change the Key", "Cambia el Tono"),
    "minor": ("Press Minor · moody", "Pulsa Menor · melancólico"),
    "wheel1": ("Tap a chord on the chord wheel", "Toca un acorde en la rueda de acordes"),
    "turn": ("Turn the wheel with one of its buttons", "Gira la rueda con uno de sus botones"),
    "slide": ("Slide a finger along a string to another fret", "Desliza un dedo por una cuerda hasta otro traste"),
    "sfretless": ("Pick Fretless or Upright bass in Instrument", "Elige un bajo sin trastes o el contrabajo en Instrumento"),
    "flnote": ("Play a note with that sound", "Toca una nota con ese sonido"),
    "snd1": ("Pick another bass in Instrument", "Elige otro bajo en Instrumento"),
    "amp1": ("Change a knob or a setting on the amp", "Cambia una perilla o un ajuste del amplificador"),
    "pedal": ("Turn a pedal on or off", "Enciende o apaga un pedal"),
    "era": ("Move the Sound dial between 1987 and 2026", "Mueve el control de Sonido entre 1987 y 2026"),
    "drums": ("Turn on Play with my drum beat", "Activa Tocar con mi ritmo de batería"),
    "drumplay": ("Press ▶ Play the chords with your drum beat on", "Pulsa ▶ Tocar los acordes con tu ritmo de batería puesto"),
    "pvbig": ("Turn your phone sideways, or press ⤢ Play on the whole screen", "Gira tu teléfono de lado, o pulsa ⤢ Tocar en toda la pantalla"),
    "pvhold": ("In ☰ Menu, pick ✋ Hold + strum", "En ☰ Menú, elige ✋ Pisar + rasguear"),
    "holdstrum": ("Hold a fret with one hand. Pluck the strip with the other", "Pisa un traste con una mano. Pulsa la franja con la otra"),
    "handstyle": ("While the chords play, hold a fret: the line follows it", "Mientras suenan los acordes, pisa un traste: la línea lo sigue"),
    "solo1": ("Press Solo, above the neck", "Pulsa Solo, encima del mástil"),
    "solo8": ("Tap eight lit notes: each tap is a slap", "Toca ocho notas iluminadas: cada toque es un slap"),
    "scale1": ("Pick another Scale", "Elige otra Escala"),
    "band": ("Press ▶ Play the band", "Pulsa ▶ Tocar la banda"),
    "pop": ("In Solo mode, flick a string up fast to pop it", "En el modo Solo, sube rápido el dedo en una cuerda para hacer pop"),
    "bend": ("In Solo mode, push a note across its string to bend it", "En el modo Solo, empuja una nota a lo ancho de su cuerda para estirarla"),
    "chordsback": ("Press Chords to go back", "Pulsa Acordes para volver"),
    "take1": ("Press ● Record", "Pulsa ● Grabar"),
    "take2": ("Play, then press ■ Stop to keep the take", "Toca y luego pulsa ■ Parar para guardar la toma"),
    "studio": ("On your take, press Send to the Mixing Desk", "En tu toma, pulsa Enviar a la mesa de mezclas"),
    "decks": ("Press Send to the turntables", "Pulsa Enviar a los platos"),
    "pat_blues": ("Pick the pattern Blues · 12 bars", "Elige el patrón Blues · 12 compases"),
    "sg_walk": ("Play it with Walking", "Tócalo con Caminando"),
    "tk_walk": ("Record a take while it plays", "Graba una toma mientras suena"),
    "pat_disco": ("Pick the pattern Disco · 2 5 with sevenths", "Elige el patrón Disco · 2 5 con séptimas"),
    "sg_disco": ("Play it with Octaves", "Tócalo con Octavas"),
    "tk_disco": ("Record a take while it plays", "Graba una toma mientras suena"),
    "pat_minor": ("Pick the pattern Minor groove", "Elige el patrón Ritmo menor"),
    "sdub": ("Pick Dub · deep and dark", "Elige Dub · profundo y oscuro"),
    "sg_reggae": ("Play it with Reggae", "Tócalo con Reggae"),
    "tk_reggae": ("Record a take while it plays", "Graba una toma mientras suena"),
    "pat_funk": ("Pick the pattern Funk · 1 4 with sevenths", "Elige el patrón Funk · 1 4 con séptimas"),
    "sslap": ("Pick a slap sound in Instrument", "Elige un sonido de slap en Instrumento"),
    "sg_funk": ("Play it with Funk", "Tócalo con Funk"),
    "tk_funk": ("Record a take while it plays", "Graba una toma mientras suena"),
    "own1": ("Press Make my own", "Pulsa Hacer el mío"),
    "own4": ("Tap four chords, one after another", "Toca cuatro acordes, uno tras otro"),
    "sg_own": ("Play your own pattern in a style you like", "Toca tu propio patrón en un estilo que te guste"),
    "tk_own": ("Record a take while it plays", "Graba una toma mientras suena"),
    "studio2": ("Send a second take to the Mixing Desk", "Envía una segunda toma a la mesa de mezclas"),
  },
  "lessons": [
    {"id": "s1", "t": ("The four strings", "Las cuatro cuerdas"),
     "b": ("Tap a string at the far left, before the frets. It rings open. From thick to thin: E A D G.",
           "Toca una cuerda a la izquierda del todo, antes de los trastes. Suena al aire. De gruesa a fina: Mi La Re Sol."),
     "steps": ["open0", "open1", "open2", "open3"],
     "try": ("Play E, A, D, G slowly, then G, D, A, E. Feel the low notes in your chest.", "Toca Mi, La, Re, Sol despacio y luego Sol, Re, La, Mi. Siente las notas graves en el pecho."),
     "q": ("The bass's four strings have the same names as the guitar's lowest four. Why might that help a band?", "Las cuatro cuerdas del bajo se llaman como las cuatro más graves de la guitarra. ¿Por qué ayudará eso a una banda?"),
     "own": ("Make up a way to remember E A D G.", "Inventa una forma de recordar Mi La Re Sol.")},
    {"id": "s2", "t": ("Frets make notes", "Los trastes hacen notas"),
     "b": ("Press a string on a fret and the note goes up. Each fret is one small step.", "Pisa una cuerda en un traste y la nota sube. Cada traste es un pasito."),
     "steps": ["fret1", "higher", "fret5", "lower"],
     "try": ("Play the E string on frets 1 to 5. Hear it climb.", "Toca la cuerda Mi en los trastes 1 al 5. Oye cómo sube."),
     "q": ("The E string on fret 5 sounds just like another open string. Which one?", "La cuerda Mi en el traste 5 suena igual que otra cuerda al aire. ¿Cuál?"),
     "own": ("Play a short tune on one string. Write the fret numbers.", "Toca una melodía corta en una cuerda. Escribe los números de traste.")},
    {"id": "s3", "t": ("Root notes", "Notas raíz"),
     "b": ("Every chord has a root: its home note. The bass plays it, and the whole band stands on it.", "Cada acorde tiene una raíz: su nota casa. El bajo la toca y toda la banda se apoya en ella."),
     "steps": ["pad1", "padall", "seven", "mute"],
     "try": ("Tap pads 1, 4, 5, 1. Watch where the ringed dot moves on the neck.", "Toca los pads 1, 4, 5, 1. Mira adónde se mueve el punto con anillo en el mástil."),
     "q": ("Why does a song feel empty when the bass stops?", "¿Por qué una canción se siente vacía cuando para el bajo?"),
     "own": ("Write the root note of each pad you played.", "Escribe la nota raíz de cada pad que tocaste.")},
    {"id": "s4", "t": ("Octaves", "Octavas"),
     "b": ("An octave is the same note, higher. On the bass it is two strings up and two frets up.", "Una octava es la misma nota, más aguda. En el bajo está dos cuerdas más arriba y dos trastes más."),
     "steps": ["octave", "fret12", "p_octave"],
     "try": ("Bounce between a note and its octave: low, high, low, high. That is disco.", "Salta entre una nota y su octava: grave, aguda, grave, aguda. Eso es disco."),
     "q": ("Fret 12 sounds like the open string, only higher. Why do you think that is?", "El traste 12 suena como la cuerda al aire, pero más aguda. ¿Por qué será?"),
     "own": ("Draw where a note and its octave sit on the four strings.", "Dibuja dónde están una nota y su octava en las cuatro cuerdas.")},
    {"id": "s5", "t": ("Fifths", "Quintas"),
     "b": ("The fifth is the root's best friend. Root and fifth make a strong, simple bass line.", "La quinta es la mejor amiga de la raíz. Raíz y quinta hacen una línea de bajo fuerte y sencilla."),
     "steps": ["fifth", "fifthlow", "p_fifth"],
     "try": ("Play root, fifth, root, fifth with a steady count. That is country bass.", "Toca raíz, quinta, raíz, quinta contando parejo. Eso es bajo de country."),
     "q": ("The fifth above and the fifth below share a name. How do they sound different?", "La quinta de arriba y la de abajo se llaman igual. ¿En qué suenan distinto?"),
     "own": ("Write a root and fifth line for two chords.", "Escribe una línea de raíz y quinta para dos acordes.")},
    {"id": "s6", "t": ("Follow the chords", "Sigue los acordes"),
     "b": ("Pick a chord pattern and press Play. The bass follows each chord, one bar at a time.", "Elige un patrón de acordes y pulsa Tocar. El bajo sigue cada acorde, un compás cada vez."),
     "steps": ["pat1", "play", "tempo", "stop"],
     "try": ("Watch the neck while it plays. The orange dot is the note ringing now.", "Mira el mástil mientras suena. El punto naranja es la nota que suena ahora."),
     "q": ("What does the small number under each chord tell you?", "¿Qué te dice el número pequeño bajo cada acorde?"),
     "own": ("Name a pattern you liked and the tempo that felt best.", "Nombra un patrón que te gustó y el tempo que mejor se sintió.")},
    {"id": "s7", "t": ("Steady lines", "Líneas firmes"),
     "b": ("A steady bass keeps the whole band together. Pick a style in How the bass plays.", "Un bajo firme mantiene unida a toda la banda. Elige un estilo en Cómo suena el bajo."),
     "steps": ["p_root", "p_steady", "p_eighths", "p_waltz"],
     "try": ("Keep one pattern and change only the style. Tap your foot to each one.", "Deja un patrón y cambia solo el estilo. Marca el pie con cada uno."),
     "q": ("The waltz counts in threes. How does that feel different?", "El vals cuenta de tres en tres. ¿En qué se siente distinto?"),
     "own": ("Pick a steady style for a calm song and one for a fast song.", "Elige un estilo firme para una canción tranquila y otro para una rápida.")},
    {"id": "s8", "t": ("Moving lines", "Líneas que se mueven"),
     "b": ("Some bass lines walk from chord to chord, with little steps in between.", "Algunas líneas de bajo caminan de acorde en acorde, con pasitos entre medias."),
     "steps": ["p_walk", "p_arpeggio", "p_approach"],
     "try": ("Listen to the last note of each bar. It leads into the next chord.", "Escucha la última nota de cada compás. Lleva al siguiente acorde."),
     "q": ("Why does a walking line feel like it is going somewhere?", "¿Por qué una línea que camina se siente como si fuera a algún sitio?"),
     "own": ("Write four notes that walk from one chord's root to the next.", "Escribe cuatro notas que caminen de la raíz de un acorde a la del siguiente.")},
    {"id": "s9", "t": ("Keys, moods and the chord wheel", "Tonos, ánimos y la rueda de acordes"),
     "b": ("The key sets which chords fit. Major sounds bright. Minor sounds moody. The wheel shows every chord.", "El tono decide qué acordes encajan. Mayor suena brillante. Menor suena melancólico. La rueda muestra todos los acordes."),
     "steps": ["key1", "minor", "wheel1", "turn"],
     "try": ("Neighbours on the wheel sound good together. Play three roots side by side.", "Los vecinos en la rueda suenan bien juntos. Toca tres raíces que estén lado a lado."),
     "q": ("When you turned the wheel, what happened to the six light chords?", "Al girar la rueda, ¿qué pasó con los seis acordes claros?"),
     "own": ("Choose a key and a mood for a song about a storm.", "Elige un tono y un ánimo para una canción sobre una tormenta.")},
    {"id": "s10", "t": ("Slides and the fretless bass", "Deslizar y el bajo sin trastes"),
     "b": ("Slide a finger along a string and the note glides. A fretless bass glides with no steps at all.", "Desliza un dedo por una cuerda y la nota se desliza. Un bajo sin trastes se desliza sin escalones."),
     "steps": ["slide", "sfretless", "flnote"],
     "try": ("On the whole screen, a fretless note is right under your finger. Slide slowly.", "En toda la pantalla, una nota sin trastes está justo bajo tu dedo. Desliza despacio."),
     "q": ("A slide sounds like a voice. What feeling can it show?", "Un deslizamiento suena como una voz. ¿Qué sentimiento puede mostrar?"),
     "own": ("Make up a line with one slide in it. Write where it starts and ends.", "Inventa una línea con un deslizamiento. Escribe dónde empieza y dónde acaba.")},
    {"id": "s11", "t": ("Bass sounds, amp and pedals", "Sonidos de bajo, amplificador y pedales"),
     "b": ("Each bass has its own amp and pedals. Change any of it, and it stays with that sound.", "Cada bajo tiene su propio amplificador y pedales. Cambia lo que quieras y se queda con ese sonido."),
     "steps": ["snd1", "amp1", "pedal", "era"],
     "try": ("Turn on one pedal, play a note, then turn it off. Name what it added.", "Enciende un pedal, toca una nota y apágalo. Di qué añadió."),
     "q": ("Which bass sound would you pick for a calm song? Which for a loud one?", "¿Qué sonido de bajo elegirías para una canción tranquila? ¿Y para una fuerte?"),
     "own": ("Make a sound you love. Write the bass, the amp and the pedals.", "Haz un sonido que te encante. Escribe el bajo, el amplificador y los pedales.")},
    {"id": "s12", "t": ("Lock in with the drums", "Encaja con la batería"),
     "b": ("The bass and the kick drum are a team. Make a beat on the drum machine and play with it here.", "El bajo y el bombo son un equipo. Haz un ritmo en la caja de ritmos y toca con él aquí."),
     "steps": ["drums", "drumplay"],
     "try": ("Listen for the kick. Try Steady, then Driving. Which one sits with it best?", "Escucha el bombo. Prueba Constante y luego Con empuje. ¿Cuál encaja mejor?"),
     "q": ("Why do bass players listen to the kick drum so closely?", "¿Por qué los bajistas escuchan tan de cerca el bombo?"),
     "own": ("Name your drum beat and the bass style that fits it best.", "Nombra tu ritmo de batería y el estilo de bajo que mejor le va.")},
    {"id": "s13", "t": ("Hold and pluck, like a real bass", "Pisar y pulsar, como un bajo de verdad"),
     "b": ("On the whole screen, one hand holds a fret and the other plucks. A style can follow the fret you hold, too.", "En toda la pantalla, una mano pisa un traste y la otra pulsa. Un estilo también puede seguir el traste que pisas."),
     "steps": ["pvbig", "pvhold", "holdstrum", "handstyle"],
     "try": ("Pluck with two fingers in turn, like a real bass player.", "Pulsa con dos dedos, uno y otro, como un bajista de verdad."),
     "q": ("What happens when you lift your fretting finger?", "¿Qué pasa cuando levantas el dedo que pisa?"),
     "own": ("Find a note that sounds good under every chord. Write its fret.", "Encuentra una nota que suene bien bajo todos los acordes. Escribe su traste.")},
    {"id": "s14", "t": ("Solo mode", "Modo Solo"),
     "b": ("Solo mode lights a scale on the neck. Every lit note fits. A band can play along.", "El modo Solo ilumina una escala en el mástil. Todas las notas iluminadas encajan. Una banda puede acompañarte."),
     "steps": ["solo1", "solo8", "scale1", "band"],
     "try": ("Start and end on a ringed note. That is the home note.", "Empieza y termina en una nota con anillo. Es la nota casa."),
     "q": ("How did the new scale change the mood?", "¿Cómo cambió el ánimo la nueva escala?"),
     "own": ("Write the frets of a five-note idea you liked.", "Escribe los trastes de una idea de cinco notas que te gustó.")},
    {"id": "s15", "t": ("Slap, pop and bend", "Slap, pop y estirar"),
     "b": ("Funk bass players slap the low strings with the thumb and pop the high ones.", "Los bajistas de funk golpean las cuerdas graves con el pulgar y tiran de las agudas."),
     "steps": ["pop", "bend", "chordsback"],
     "try": ("Slap a low note, then pop an octave up: thump, snap.", "Haz slap en una nota grave y luego pop una octava más arriba: pum, chas."),
     "q": ("Which sounds more like a drum: the slap or the pop?", "¿Qué suena más como un tambor: el slap o el pop?"),
     "own": ("Write a slap and pop pattern, like T T P T.", "Escribe un patrón de slap y pop, como T T P T.")},
    {"id": "s16", "t": ("Record a take and share it", "Graba una toma y compártela"),
     "b": ("A take keeps everything you play. Send it to the Mixing Desk or the turntables.", "Una toma guarda todo lo que tocas. Envíala a la mesa de mezclas o a los platos."),
     "steps": ["take1", "take2", "studio", "decks"],
     "try": ("Record two takes of the same line. Keep the one you like best.", "Graba dos tomas de la misma línea. Quédate con la que más te guste."),
     "q": ("What changed between your first take and your second?", "¿Qué cambió entre tu primera toma y la segunda?"),
     "own": ("Plan a 30-second take: what do you play first, and what comes next?", "Planea una toma de 30 segundos: ¿qué tocas primero y qué viene después?")},
    {"id": "s17", "t": ("Song: Walking blues", "Canción: Blues que camina"),
     "b": ("Twelve bars of blues, with a bass line that walks on every beat.", "Doce compases de blues, con una línea de bajo que camina en cada tiempo."),
     "steps": ["pat_blues", "sg_walk", "tk_walk"],
     "try": ("Try the Upright bass for a jazz club sound.", "Prueba el contrabajo para un sonido de club de jazz."),
     "q": ("Count the bars. Where does the line go to chord 4? Where to chord 5?", "Cuenta los compases. ¿Dónde va la línea al acorde 4? ¿Y al 5?"),
     "own": ("Write the twelve bars as numbers: 1 1 1 1, then the rest.", "Escribe los doce compases con números: 1 1 1 1 y el resto."),
     "song": True},
    {"id": "s18", "t": ("Song: Disco octaves", "Canción: Octavas de disco"),
     "b": ("Low, high, low, high: a bouncing octave line for the dance floor.", "Grave, aguda, grave, aguda: una línea de octavas que rebota para la pista de baile."),
     "steps": ["pat_disco", "sg_disco", "tk_disco"],
     "try": ("Set the tempo near 120. Play it with a four-on-the-floor drum beat.", "Pon el tempo cerca de 120. Tócalo con un ritmo de batería de cuatro en el piso."),
     "q": ("Why does the octave jump make people want to dance?", "¿Por qué el salto de octava da ganas de bailar?"),
     "own": ("Give your disco line a name and a tempo.", "Ponle nombre y tempo a tu línea de disco."),
     "song": True},
    {"id": "s19", "t": ("Song: Reggae one drop", "Canción: Reggae one drop"),
     "b": ("A deep, round bass with room to breathe. In reggae, the bass is the star.", "Un bajo grave y redondo con espacio para respirar. En el reggae, el bajo es la estrella."),
     "steps": ["pat_minor", "sdub", "sg_reggae", "tk_reggae"],
     "try": ("Turn the tempo down near 75. Let each note sit.", "Baja el tempo cerca de 75. Deja que cada nota repose."),
     "q": ("What do the gaps between the notes do for the song?", "¿Qué le aportan a la canción los huecos entre las notas?"),
     "own": ("Describe your reggae line in five words.", "Describe tu línea de reggae en cinco palabras."),
     "song": True},
    {"id": "s20", "t": ("Song: Funk line", "Canción: Línea de funk"),
     "b": ("Short, jumpy notes and a slap sound. Funk is all about the groove.", "Notas cortas y saltarinas y un sonido de slap. El funk se trata del groove."),
     "steps": ["pat_funk", "sslap", "sg_funk", "tk_funk"],
     "try": ("Play it with a drum beat from the drum machine. Lock in with the kick.", "Tócalo con un ritmo de la caja de ritmos. Encaja con el bombo."),
     "q": ("Funk leaves out lots of notes. Why might that make it groove more?", "El funk deja fuera muchas notas. ¿Por qué eso le dará más groove?"),
     "own": ("Write where your funk notes land in one bar.", "Escribe dónde caen tus notas de funk en un compás."),
     "song": True},
    {"id": "s21", "t": ("Song: Your own, start to finish", "Canción: La tuya, de principio a fin"),
     "b": ("Your chords, your bass style, your take, sent to the Mixing Desk.", "Tus acordes, tu estilo de bajo, tu toma, enviada a la mesa de mezclas."),
     "steps": ["own1", "own4", "sg_own", "tk_own", "studio2"],
     "try": ("Send your bass take and a guitar take. Put them together on the Mixing Desk.", "Envía tu toma de bajo y una de guitarra. Júntalas en la mesa de mezclas."),
     "q": ("What would you change if you made it again?", "¿Qué cambiarías si la hicieras otra vez?"),
     "own": ("Write your song's name, its chords and its bass style.", "Escribe el nombre de tu canción, sus acordes y su estilo de bajo."),
     "song": True},
  ],
}
