# -*- coding: utf-8 -*-
"""The Drum Machine's lessons (music-pads.html). Built by make_lab_lessons.py. Every text is (English, Spanish).
The page marks each step as it happens (AOG-LESSONS-V1 hooks in music-pads.html)."""

LAB = {
  "lab": "pads",
  "key": "aog.pads.lessons.v1",
  "page": "/drum-machine",
  "sheet": "beat-lab-lessons.html",
  "name": ("The Drum Machine", "La caja de ritmos"),
  "steps": {
    "tap1": ("Tap any pad", "Toca cualquier pad"),
    "vloud": ("Tap a pad right in the middle: a loud hit", "Toca un pad justo en el centro: un golpe fuerte"),
    "vsoft": ("Tap a pad near its edge: a soft hit", "Toca un pad cerca del borde: un golpe suave"),
    "drum8": ("On bank A, play pads 1 to 8", "En el banco A, toca los pads 1 al 8"),
    "beat1": ("Pick a beat in Start from a beat", "Elige un ritmo en Empieza con un ritmo"),
    "play1": ("Press ▶ Play", "Pulsa ▶ Tocar"),
    "stop1": ("Press ■ Stop", "Pulsa ■ Parar"),
    "tempo1": ("Change the tempo", "Cambia el tempo"),
    "tfast": ("Make it fast: 120 or more", "Hazlo rápido: 120 o más"),
    "tslow": ("Make it slow: 80 or less", "Hazlo lento: 80 o menos"),
    "stepadd": ("Tap an empty step to add a hit", "Toca un paso vacío para poner un golpe"),
    "stepdel": ("Tap a lit step to take a hit away", "Toca un paso encendido para quitar un golpe"),
    "rec1": ("Turn on ● Record the loop", "Activa ● Grabar el bucle"),
    "rechit": ("Tap four hits while it records", "Toca cuatro golpes mientras graba"),
    "undo1": ("Press ↶ Undo", "Pulsa ↶ Deshacer"),
    "clear1": ("Press Clear the loop", "Pulsa Borrar el bucle"),
    "q16": ("Set Line up taps to: 16th notes", "Pon Alinear los toques a: semicorcheas"),
    "qoff": ("Set Line up taps to: Exactly as played", "Pon Alinear los toques a: Tal como se tocó"),
    "sw54": ("Set Swing to 54 % or more", "Pon el Swing en 54 % o más"),
    "playsw": ("Press Play with swing on", "Pulsa Tocar con el swing puesto"),
    "rpt1": ("Turn on Repeat", "Activa Repetir"),
    "rptroll": ("Hold a pad: it rolls by itself", "Mantén un pad: redobla solo"),
    "rate1": ("Change the Repeat speed", "Cambia la Velocidad de repetición"),
    "rptrec": ("Record a roll while the loop plays", "Graba un redoble mientras suena el bucle"),
    "kitA": ("Change the kit for pads 1 to 8", "Cambia la batería de los pads 1 a 8"),
    "kitB": ("Change the kit for pads 9 to 16", "Cambia la batería de los pads 9 a 16"),
    "pad916": ("Play a pad from 9 to 16", "Toca un pad del 9 al 16"),
    "full1": ("Turn on Every hit full", "Activa Todo a tope"),
    "click1": ("Turn on Click", "Activa Clic"),
    "bars4": ("Set Loop length to 4 bars", "Pon el Largo del bucle en 4 compases"),
    "bankB": ("Pick bank B · Chords", "Elige el banco B · Acordes"),
    "c1564": ("Tap pads 1, 5, 6, 4, in that order", "Toca los pads 1, 5, 6, 4, en ese orden"),
    "ckey": ("Change the key on bank B", "Cambia el tono en el banco B"),
    "cminor": ("Set bank B's scale to Minor", "Pon la escala del banco B en Menor"),
    "cinst": ("Change bank B's instrument", "Cambia el instrumento del banco B"),
    "c7": ("Play a seventh chord: pads 9 to 15", "Toca un acorde de séptima: pads 9 al 15"),
    "bankC": ("Pick bank C · Notes", "Elige el banco C · Notas"),
    "nup": ("Play pads 1 to 8 going up, one by one", "Toca los pads 1 al 8 subiendo, uno por uno"),
    "nscale": ("Change bank C's scale", "Cambia la escala del banco C"),
    "ninst": ("Change bank C's instrument", "Cambia el instrumento del banco C"),
    "nrange": ("Change bank C's range", "Cambia el registro del banco C"),
    "bankD": ("Pick bank D · Chops", "Elige el banco D · Cortes"),
    "chop4": ("Play four different chops", "Toca cuatro cortes distintos"),
    "crec": ("Pick another record to chop", "Elige otro disco para cortar"),
    "cbar": ("Start the chops at another bar", "Empieza los cortes en otro compás"),
    "cmatch": ("Press Use its tempo", "Pulsa Usar su tempo"),
    "pvol": ("Change a pad's Volume", "Cambia el Volumen de un pad"),
    "ptune": ("Change a pad's Pitch", "Cambia el Tono de un pad"),
    "ppan": ("Move a pad left or right", "Mueve un pad a la izquierda o a la derecha"),
    "preset": ("Press Reset this pad", "Pulsa Restablecer este pad"),
    "bounce": ("Press Make the loop into a file", "Pulsa Convertir el bucle en un archivo"),
    "bsave": ("Press Save as .wav", "Pulsa Guardar como .wav"),
    "bstudio": ("Press Send to the Mixing Desk", "Pulsa Enviar a la mesa de mezclas"),
    "bdecks": ("Press Send to the turntables", "Pulsa Enviar a los tocadiscos"),
    "take1": ("Press ● Record a take to keep", "Pulsa ● Grabar una toma para guardar"),
    "take2": ("Play, then stop recording", "Toca y luego para la grabación"),
    "sbb": ("Pick Boom bap (90s hip-hop)", "Elige Boom bap (hip-hop de los 90)"),
    "slofi": ("Pick Lo-fi study beat", "Elige Lo-fi para estudiar"),
    "shouse": ("Pick House", "Elige House"),
    "strap": ("Pick Trap", "Elige Trap"),
    "schords": ("Record four chords on bank B", "Graba cuatro acordes en el banco B"),
    "sbass": ("Record four bass notes on bank C", "Graba cuatro notas de bajo en el banco C"),
    "schop": ("Record a chop on bank D", "Graba un corte en el banco D"),
    "sminor": ("Bank B in Minor, with chords recorded", "El banco B en Menor, con acordes grabados"),
    "sparts3": ("Send three parts to the Mixing Desk", "Envía tres partes a la mesa de mezclas"),
    "guide1": ("Open the guide: How to make a killer song", "Abre la guía: Cómo hacer una canción increíble"),
  },
  "lessons": [
    {"id": "b1", "t": ("Meet the pads", "Conoce los pads"),
     "b": ("Sixteen pads. How you tap them changes the sound.", "Dieciséis pads. Cómo los tocas cambia el sonido."),
     "steps": ["tap1", "vloud", "vsoft", "drum8"],
     "try": ("Play a beat with your two pointer fingers: kick on pad 1, snare on pad 2.", "Toca un ritmo con los dos dedos índice: bombo en el pad 1, caja en el pad 2."),
     "q": ("Which pad sounds lowest? Which sounds highest?", "¿Qué pad suena más grave? ¿Cuál suena más agudo?"),
     "own": ("Make up a pattern with three pads. Write their numbers in order.", "Inventa un patrón con tres pads. Escribe sus números en orden.")},
    {"id": "b2", "t": ("Start a beat", "Empieza un ritmo"),
     "b": ("There are 105 beats ready. Pick one and press Play.", "Hay 105 ritmos listos. Elige uno y pulsa Tocar."),
     "steps": ["beat1", "play1", "stop1"],
     "try": ("Pick a beat from a country you have never been to.", "Elige un ritmo de un país donde nunca has estado."),
     "q": ("What did the line under the bank say about your beat?", "¿Qué dijo la línea bajo el banco sobre tu ritmo?"),
     "own": ("Name your three favourite beats.", "Nombra tus tres ritmos favoritos.")},
    {"id": "b3", "t": ("Fast and slow", "Rápido y lento"),
     "b": ("Tempo is how many beats a minute. It sets the mood.", "El tempo es cuántos pulsos por minuto. Marca el ánimo."),
     "steps": ["tempo1", "tfast", "tslow"],
     "try": ("Play the same beat at 70, then at 130. Does it feel like a different song?", "Toca el mismo ritmo a 70 y luego a 130. ¿Se siente como otra canción?"),
     "q": ("What tempo feels like walking? Like running?", "¿Qué tempo se siente como caminar? ¿Como correr?"),
     "own": ("Tap your foot to a song you like. Guess its tempo.", "Marca con el pie una canción que te guste. Adivina su tempo.")},
    {"id": "b4", "t": ("The steps", "Los pasos"),
     "b": ("Each pad has steps under the pads. A lit step is a hit.", "Cada pad tiene pasos debajo. Un paso encendido es un golpe."),
     "steps": ["stepadd", "stepdel", "play1"],
     "try": ("Pick the kick. Add a hit on step 11. Hear the bounce.", "Elige el bombo. Pon un golpe en el paso 11. Oye el rebote."),
     "q": ("How many steps are in one bar?", "¿Cuántos pasos hay en un compás?"),
     "own": ("Draw 16 boxes. Fill the ones where your kick plays.", "Dibuja 16 casillas. Rellena donde suena tu bombo.")},
    {"id": "b5", "t": ("Record a beat", "Graba un ritmo"),
     "b": ("Record the loop keeps what you tap. You hear it the next time round.", "Grabar el bucle guarda lo que tocas. Lo oyes en la siguiente vuelta."),
     "steps": ["rec1", "rechit", "undo1", "clear1"],
     "try": ("Record the hi-hat on every beat, then the snare on 2 and 4.", "Graba el charles en cada tiempo y luego la caja en el 2 y el 4."),
     "q": ("Undo took back your last change. When would that help?", "Deshacer quitó tu último cambio. ¿Cuándo ayuda eso?"),
     "own": ("Record a beat with only two pads. Make it groove.", "Graba un ritmo con solo dos pads. Haz que tenga groove.")},
    {"id": "b6", "t": ("Line up and swing", "Alinear y swing"),
     "b": ("Line up moves your taps onto the beat. Swing makes them bounce.", "Alinear pone tus toques en el pulso. El swing los hace rebotar."),
     "steps": ["q16", "qoff", "sw54", "playsw"],
     "try": ("Record hi-hats with Swing at 50, then at 62. Which one makes you nod?", "Graba charles con Swing en 50 y luego en 62. ¿Con cuál mueves la cabeza?"),
     "q": ("Why might a drummer play a little late on purpose?", "¿Por qué un baterista tocaría un poco tarde a propósito?"),
     "own": ("Write a tempo and a swing that feel good together.", "Escribe un tempo y un swing que se sientan bien juntos.")},
    {"id": "b7", "t": ("Rolls with Repeat", "Redobles con Repetir"),
     "b": ("Repeat plays a held pad again and again, in time.", "Repetir toca un pad sostenido una y otra vez, a tiempo."),
     "steps": ["rpt1", "rptroll", "rate1", "rptrec"],
     "try": ("Hold the hi-hat at 1/16, then 1/32 for one beat. That is a trap roll.", "Mantén el charles en 1/16 y luego 1/32 por un tiempo. Es un redoble de trap."),
     "q": ("Where in a song would a roll fit best?", "¿En qué parte de una canción va mejor un redoble?"),
     "own": ("Record a roll that leads into beat 1.", "Graba un redoble que lleve al tiempo 1.")},
    {"id": "b8", "t": ("Pick your drums", "Elige tu batería"),
     "b": ("Bank A has two kits: one on pads 1 to 8, one on 9 to 16.", "El banco A tiene dos baterías: una en los pads 1 a 8 y otra en 9 a 16."),
     "steps": ["kitA", "kitB", "pad916", "full1"],
     "try": ("Put a rock kit on 1 to 8 and Latin percussion on 9 to 16. Mix them.", "Pon una batería de rock en 1 a 8 y percusión latina en 9 a 16. Mézclalas."),
     "q": ("Which kit would you pick for a calm song? Why?", "¿Qué batería elegirías para una canción tranquila? ¿Por qué?"),
     "own": ("Name the two kits you like best together.", "Nombra las dos baterías que mejor suenan juntas.")},
    {"id": "b9", "t": ("Chords", "Acordes"),
     "b": ("Bank B plays chords. Pads 1 to 8 are the key's chords.", "El banco B toca acordes. Los pads 1 a 8 son los acordes del tono."),
     "steps": ["bankB", "c1564", "ckey", "c7"],
     "try": ("Tap 1, 5, 6, 4 slowly, then fast. Same chords, two feelings.", "Toca 1, 5, 6, 4 despacio y luego rápido. Mismos acordes, dos sensaciones."),
     "q": ("Which chord sounds like home?", "¿Qué acorde suena a casa?"),
     "own": ("Write a four-chord pattern with the pad numbers.", "Escribe un patrón de cuatro acordes con los números de los pads.")},
    {"id": "b10", "t": ("Happy and sad chords", "Acordes alegres y tristes"),
     "b": ("Major sounds bright. Minor sounds moody.", "Mayor suena brillante. Menor suena melancólico."),
     "steps": ["bankB", "cminor", "cinst", "c1564"],
     "try": ("Play 1, 5, 6, 4 in Major, then in Minor. Tell someone which one is sad.", "Toca 1, 5, 6, 4 en Mayor y luego en Menor. Dile a alguien cuál es triste."),
     "q": ("Name a song that sounds Minor to you.", "Nombra una canción que te suene en Menor."),
     "own": ("Pick an instrument and a mood for a song you could make.", "Elige un instrumento y un ánimo para una canción que podrías hacer.")},
    {"id": "b11", "t": ("Notes and melodies", "Notas y melodías"),
     "b": ("Bank C plays one note per pad, low to high, in a scale.", "El banco C toca una nota por pad, de grave a agudo, en una escala."),
     "steps": ["bankC", "nup", "nscale", "ninst", "nrange"],
     "try": ("In Minor pentatonic, every pad sounds good with every other. Play freely.", "En Pentatónica menor, todos los pads suenan bien juntos. Toca libremente."),
     "q": ("Why do a bass and a flute sound so different on the same pad?", "¿Por qué un bajo y una flauta suenan tan distintos en el mismo pad?"),
     "own": ("Write a five-note melody with pad numbers.", "Escribe una melodía de cinco notas con números de pad.")},
    {"id": "b12", "t": ("Chop a record", "Corta un disco"),
     "b": ("Bank D cuts a record into sixteen beats. Each pad plays one.", "El banco D corta un disco en dieciséis tiempos. Cada pad toca uno."),
     "steps": ["bankD", "chop4", "crec", "cbar", "cmatch"],
     "try": ("Find the chop with a drum hit. Play it on beat 1 of every bar.", "Encuentra el corte con un golpe de batería. Tócalo en el tiempo 1 de cada compás."),
     "q": ("How is chopping a record like making a collage?", "¿En qué se parece cortar un disco a hacer un collage?"),
     "own": ("Write the numbers of the three chops you like best.", "Escribe los números de los tres cortes que más te gustan.")},
    {"id": "b13", "t": ("Mix the pads", "Mezcla los pads"),
     "b": ("Each pad has its own volume, pitch, and place left or right.", "Cada pad tiene su volumen, tono y lugar a la izquierda o derecha."),
     "steps": ["pvol", "ptune", "ppan", "preset"],
     "try": ("Turn the hi-hat down to 70 %. Hear the kick and snare come forward.", "Baja el charles a 70 %. Oye cómo el bombo y la caja pasan al frente."),
     "q": ("Why not make every pad as loud as it can be?", "¿Por qué no poner cada pad lo más fuerte posible?"),
     "own": ("Which pad would you move left, and which right?", "¿Qué pad moverías a la izquierda y cuál a la derecha?")},
    {"id": "b14", "t": ("Keep your loop", "Guarda tu bucle"),
     "b": ("Make the loop into one file, with no gap. Save it or send it on.", "Convierte el bucle en un archivo, sin pausa. Guárdalo o envíalo."),
     "steps": ["bounce", "bsave", "bstudio", "bdecks"],
     "try": ("On the turntables, play your loop and scratch over it.", "En los tocadiscos, toca tu bucle y raya encima."),
     "q": ("What is the difference between the loop and a take?", "¿Qué diferencia hay entre el bucle y una toma?"),
     "own": ("Give your loop a name.", "Ponle nombre a tu bucle.")},
    {"id": "b15", "t": ("Play live, and record it", "Toca en vivo y grábalo"),
     "b": ("A take keeps everything you play, like a recording of a show.", "Una toma guarda todo lo que tocas, como la grabación de un concierto."),
     "steps": ["click1", "take1", "take2"],
     "try": ("Let the loop play and add drums live on top for 30 seconds.", "Deja sonar el bucle y agrega batería en vivo encima por 30 segundos."),
     "q": ("What changed between your first take and your second?", "¿Qué cambió entre tu primera toma y la segunda?"),
     "own": ("Plan a 30-second show: what plays first, what comes in later?", "Planea un show de 30 segundos: ¿qué suena primero y qué entra después?")},
    {"id": "b16", "t": ("Song: Boom bap", "Canción: Boom bap"),
     "b": ("A 90s hip-hop track: drums, chords and bass.", "Una pista de hip-hop de los 90: batería, acordes y bajo."),
     "steps": ["sbb", "bars4", "schords", "sbass", "bounce"],
     "try": ("Bass on the same beats as the kick makes it hit hard.", "El bajo en los mismos tiempos que el bombo lo hace golpear fuerte."),
     "q": ("Which part did you make first? Why?", "¿Qué parte hiciste primero? ¿Por qué?"),
     "own": ("Write the four chords and four bass notes you used.", "Escribe los cuatro acordes y las cuatro notas de bajo que usaste."),
     "song": True},
    {"id": "b17", "t": ("Song: Lo-fi study", "Canción: Lo-fi para estudiar"),
     "b": ("A calm, swinging loop to study to: soft drums, minor chords, a chop.", "Un bucle tranquilo con swing para estudiar: batería suave, acordes menores, un corte."),
     "steps": ["slofi", "sw54", "sminor", "schop", "bstudio"],
     "try": ("Turn the drums down and pitch the chop down 3 steps for a warm, dusty sound.", "Baja la batería y el corte 3 semitonos para un sonido cálido y polvoriento."),
     "q": ("What makes music good to study to?", "¿Qué hace que una música sea buena para estudiar?"),
     "own": ("Name your lo-fi track and describe it in five words.", "Ponle nombre a tu pista lo-fi y descríbela en cinco palabras."),
     "song": True},
    {"id": "b18", "t": ("Song: Dance floor", "Canción: Pista de baile"),
     "b": ("Four on the floor at 120 or faster, with a bass line and a roll.", "Cuatro en el piso a 120 o más rápido, con bajo y un redoble."),
     "steps": ["shouse", "tfast", "sbass", "rptrec", "bounce"],
     "try": ("Drop the kick for one bar, then bring it back. The crowd jumps.", "Quita el bombo un compás y luego vuélvelo a poner. La gente salta."),
     "q": ("Why do dance songs keep the kick on every beat?", "¿Por qué las canciones de baile tienen el bombo en cada tiempo?"),
     "own": ("Plan a drop: what goes away, and when does it come back?", "Planea una caída: ¿qué se quita y cuándo vuelve?"),
     "song": True},
    {"id": "b19", "t": ("Song: Trap", "Canción: Trap"),
     "b": ("Slow, heavy and full of rolls.", "Lento, pesado y lleno de redobles."),
     "steps": ["strap", "rptrec", "sbass", "cminor", "bounce"],
     "try": ("Use a deep bass on bank C, range Low, in Minor.", "Usa un bajo grave en el banco C, registro Grave, en Menor."),
     "q": ("Trap sounds slow and fast at the same time. How?", "El trap suena lento y rápido a la vez. ¿Cómo?"),
     "own": ("Write where your rolls happen in the loop.", "Escribe dónde suenan tus redobles en el bucle."),
     "song": True},
    {"id": "b20", "t": ("Song: Your own, start to finish", "Canción: La tuya, de principio a fin"),
     "b": ("A whole song: intro, verse and chorus, built on the Mixing Desk.", "Una canción entera: intro, estrofa y coro, armada en la mesa de mezclas."),
     "steps": ["guide1", "schords", "sbass", "schop", "sparts3"],
     "try": ("Follow the guide's eight steps. Then play your song to someone.", "Sigue los ocho pasos de la guía. Luego toca tu canción para alguien."),
     "q": ("What would you change if you made it again?", "¿Qué cambiarías si la hicieras otra vez?"),
     "own": ("Write your song's name and its parts in order.", "Escribe el nombre de tu canción y sus partes en orden."),
     "song": True},
  ],
}
