# -*- coding: utf-8 -*-
"""The Mixing Desk's lessons (music-studio.html). Built by make_lab_lessons.py. Every text is (English, Spanish).
The page marks each step as it happens (AOG-LESSONS-V1 hooks in music-studio.html)."""

LAB = {
  "lab": "studio",
  "key": "aog.studio.lessons.v1",
  "page": "/mixing-desk",
  "sheet": "mixing-desk-lessons.html",
  "name": ("The Mixing Desk", "La mesa de mezclas"),
  "steps": {
    # getting recordings, tracks, play
    "inbox1": ("Record on any instrument, then press Send to the Mixing Desk. Your take shows up here.",
               "Graba en cualquier instrumento y pulsa Enviar a la mesa de mezclas. Tu toma aparece aquí."),
    "put1": ("Press Put it on track", "Pulsa Ponla en la pista"),
    "play1": ("Press ▶ Play", "Pulsa ▶ Tocar"),
    "stop1": ("Press ■ Stop", "Pulsa ■ Parar"),
    "end1": ("Press Play again and let it play to the end", "Pulsa Tocar otra vez y deja que suene hasta el final"),
    "track2": ("Pick another track in the Track menu", "Elige otra pista en el menú Pista"),
    "put2": ("Put a recording on a second track", "Pon una grabación en una segunda pista"),
    "play2": ("Press Play to hear both tracks together", "Pulsa Tocar para oír las dos pistas juntas"),
    # the mixer
    "vol1": ("Move a track's Volume", "Mueve el Volumen de una pista"),
    "volLow": ("Turn one track down to 50 or less", "Baja una pista a 50 o menos"),
    "panL": ("Move a track's Side to the left", "Mueve el Lado de una pista a la izquierda"),
    "panR": ("Move a track's Side to the right", "Mueve el Lado de una pista a la derecha"),
    "mute1": ("Press Mute on a track", "Pulsa Silenciar en una pista"),
    "unmute1": ("Press Mute again to bring it back", "Pulsa Silenciar otra vez para que vuelva"),
    "solo1": ("Press Solo on a track", "Pulsa Solo en una pista"),
    "unsolo1": ("Press Solo again to hear everything", "Pulsa Solo otra vez para oír todo"),
    "eqLow": ("Move a track's Low", "Mueve los Graves de una pista"),
    "eqMid": ("Move a track's Middle", "Mueve los Medios de una pista"),
    "eqHigh": ("Move a track's High", "Mueve los Agudos de una pista"),
    "fx1": ("Try Punch, Room or Echo on a track", "Prueba Pegada, Sala o Eco en una pista"),
    # editing a track
    "later1": ("Under Starts at bar, press Later +", "En Empieza en el compás, pulsa Después +"),
    "earlier1": ("Press − Earlier to bring it back", "Pulsa − Antes para traerla de vuelta"),
    "more1": ("Under Plays, press More +", "En Suena, pulsa Más +"),
    "fewer1": ("Press − Fewer", "Pulsa − Menos"),
    "copy1": ("Press Copy this piece", "Pulsa Copiar esta parte"),
    "cut1": ("Pick a place in Cut at, then press ✂ Cut here", "Elige un lugar en Cortar en y pulsa ✂ Cortar aquí"),
    "piece1": ("Pick a piece in the Piece menu", "Elige una parte en el menú Parte"),
    "drop1": ("Press Remove this piece", "Pulsa Quitar esta parte"),
    "undo1": ("Press ↶ Undo to bring it back", "Pulsa ↶ Deshacer para traerla de vuelta"),
    "trimIn": ("Under Cut from the start, press +1 beat or +1 bar", "En Recortar el principio, pulsa +1 pulso o +1 compás"),
    "trimOut": ("Under Cut from the end, press +1 beat or +1 bar", "En Recortar el final, pulsa +1 pulso o +1 compás"),
    "fadeIn1": ("Pick a Fade in", "Elige una Entrada suave"),
    "fadeOut1": ("Pick a Fade out", "Elige una Salida suave"),
    "slow1": ("Slide Speed below 100 %", "Desliza la Velocidad por debajo de 100 %"),
    "fast1": ("Slide Speed above 100 %", "Desliza la Velocidad por encima de 100 %"),
    "keep1": ("Press Keep the pitch to hear the difference", "Pulsa Mantener el tono para oír la diferencia"),
    # the whole song
    "loopOn": ("Press Loop under Loop bars", "Pulsa Repetir en Repetir compases"),
    "loopSet": ("Pick the bars to loop in the two menus", "Elige los compases que se repiten en los dos menús"),
    "loopPlay": ("Press Play with Loop on", "Pulsa Tocar con Repetir puesto"),
    "startAt": ("Pick a bar in Start at bar", "Elige un compás en Empezar en el compás"),
    "mEq": ("In The whole song, move Low, Middle or High", "En Toda la canción, mueve Graves, Medios o Agudos"),
    "mGlue": ("Move Glue", "Mueve Unión"),
    "mVol": ("Move Song volume", "Mueve Volumen de la canción"),
    "mix1": ("Press Make the mix", "Pulsa Hacer la mezcla"),
    "listen1": ("Play your mix in the player", "Toca tu mezcla en el reproductor"),
    "save1": ("Press Save as .wav", "Pulsa Guardar como .wav"),
    "send1": ("Press Send to the turntables", "Pulsa Enviar a los platos"),
    # songs
    "mixInst2": ("Make a mix with two instruments in it", "Haz una mezcla con dos instrumentos"),
    "mixBal": ("In that mix, one track is quieter than the other", "En esa mezcla, una pista suena más bajo que la otra"),
    "tracks4": ("Put recordings on four tracks", "Pon grabaciones en cuatro pistas"),
    "enter": ("Make one track start at bar 3 or later", "Haz que una pista empiece en el compás 3 o después"),
    "bars8": ("Make the song 8 bars long or longer", "Haz que la canción dure 8 compases o más"),
    "mixBand": ("Make the mix with four tracks playing", "Haz la mezcla con cuatro pistas sonando"),
    "swap": ("Cut a recording and move a later piece in front of an earlier one",
             "Corta una grabación y pon una parte de después delante de una de antes"),
    "mixRemix": ("Make the mix of your remix", "Haz la mezcla de tu remezcla"),
    "sendRemix": ("Send your remix to the turntables", "Envía tu remezcla a los platos"),
    "bedFade": ("Turn a music track down to 40 or less and give it a fade in and a fade out",
                "Baja una pista de música a 40 o menos y ponle entrada y salida suaves"),
    "mixBed": ("Make the mix with that quiet track in it", "Haz la mezcla con esa pista suave"),
    "own3": ("Use recordings from three or more instruments", "Usa grabaciones de tres instrumentos o más"),
    "ownLong": ("Make the song 16 bars long or longer", "Haz que la canción dure 16 compases o más"),
    "mixOwn": ("Make the mix of your song", "Haz la mezcla de tu canción"),
  },
  "lessons": [
    {"id": "m1", "t": ("Where recordings come from", "De dónde vienen las grabaciones"),
     "b": ("A mixing desk puts recordings together into one song. You make the recordings on the site's instruments: the piano, the guitar, the bass, the drum kit, the drum machine or the band.",
           "Una mesa de mezclas junta grabaciones en una sola canción. Las grabaciones las haces en los instrumentos del sitio: el piano, la guitarra, el bajo, la batería, la caja de ritmos o la banda."),
     "steps": ["inbox1", "put1"],
     "try": ("Open the Music tools menu at the top to find an instrument. Come back here when you have sent a take.",
             "Abre el menú Instrumentos de arriba para encontrar un instrumento. Vuelve aquí cuando hayas enviado una toma."),
     "q": ("Which instrument did you record first? Why that one?", "¿Qué instrumento grabaste primero? ¿Por qué ese?"),
     "own": ("Write the names of two instruments you want in your song.", "Escribe los nombres de dos instrumentos que quieres en tu canción.")},
    {"id": "m2", "t": ("Play and stop", "Tocar y parar"),
     "b": ("Play starts your song from the start. Stop ends it at once. Space does the same on a keyboard.",
           "Tocar empieza tu canción desde el principio. Parar la detiene enseguida. La barra espaciadora hace lo mismo en un teclado."),
     "steps": ["play1", "stop1", "end1"],
     "try": ("Watch the bar number move while it plays.", "Mira cómo cambia el número de compás mientras suena."),
     "q": ("How long is your song right now, in bars?", "¿Cuántos compases dura tu canción ahora?"),
     "own": ("Draw a line for your song. Mark where each bar starts.", "Dibuja una línea para tu canción. Marca dónde empieza cada compás.")},
    {"id": "m3", "t": ("A song in layers", "Una canción en capas"),
     "b": ("There are eight tracks. Each track holds one recording. They all play at the same time.",
           "Hay ocho pistas. Cada pista guarda una grabación. Todas suenan al mismo tiempo."),
     "steps": ["track2", "put2", "play2"],
     "try": ("Put the same take on two tracks. It sounds bigger.", "Pon la misma toma en dos pistas. Suena más grande."),
     "q": ("What changes when two recordings play together?", "¿Qué cambia cuando dos grabaciones suenan juntas?"),
     "own": ("Plan four tracks: write what goes on each one.", "Planea cuatro pistas: escribe qué va en cada una.")},
    {"id": "m4", "t": ("Volume and balance", "Volumen y equilibrio"),
     "b": ("Volume makes a track louder or quieter. A good mix lets you hear every part.",
           "El Volumen hace una pista más fuerte o más suave. Una buena mezcla deja oír cada parte."),
     "steps": ["vol1", "volLow"],
     "try": ("Play the song. Move one Volume until the two tracks feel even.", "Toca la canción. Mueve un Volumen hasta que las dos pistas se sientan parejas."),
     "q": ("Which part should be the loudest in your song?", "¿Qué parte debe sonar más fuerte en tu canción?"),
     "own": ("Write each track and the volume you picked for it.", "Escribe cada pista y el volumen que elegiste.")},
    {"id": "m5", "t": ("Left and right", "Izquierda y derecha"),
     "b": ("Side moves a track to your left ear or your right ear. Headphones make it easy to hear.",
           "Lado mueve una pista a tu oído izquierdo o derecho. Con audífonos se oye fácil."),
     "steps": ["panL", "panR"],
     "try": ("Put one track a little left and one a little right. Keep drums and bass in the middle.",
             "Pon una pista un poco a la izquierda y otra un poco a la derecha. Deja la batería y el bajo en el centro."),
     "q": ("Why might a band put the guitar on one side?", "¿Por qué una banda pondría la guitarra a un lado?"),
     "own": ("Draw a stage. Put each of your tracks where it stands.", "Dibuja un escenario. Pon cada pista donde está."),},
    {"id": "m6", "t": ("Mute and solo", "Silenciar y solo"),
     "b": ("Mute turns one track off. Solo lets you hear only that track. Both help you listen closely.",
           "Silenciar apaga una pista. Solo te deja oír solo esa pista. Las dos te ayudan a escuchar con atención."),
     "steps": ["mute1", "unmute1", "solo1", "unsolo1"],
     "try": ("Play the song and Solo each track, one at a time.", "Toca la canción y pon Solo en cada pista, una por una."),
     "q": ("What did you hear in Solo that you missed before?", "¿Qué oíste con Solo que antes no notabas?"),
     "own": ("Write one thing you like about each track.", "Escribe algo que te guste de cada pista.")},
    {"id": "m7", "t": ("Shape the sound: low, middle, high", "Da forma al sonido: graves, medios, agudos"),
     "b": ("Low is the deep part of a sound. High is the bright part. Middle is in between. Punch, Room and Echo add more color.",
           "Graves es la parte profunda de un sonido. Agudos es la parte brillante. Medios está en el centro. Pegada, Sala y Eco le dan más color."),
     "steps": ["eqLow", "eqMid", "eqHigh", "fx1"],
     "try": ("Take a little Low off the piano so the bass has room.", "Quita un poco de Graves al piano para que el bajo tenga espacio."),
     "q": ("Which instrument sounds best with more High? Why?", "¿Qué instrumento suena mejor con más Agudos? ¿Por qué?"),
     "own": ("Pick words for your mix: warm, bright, deep, big. Which fit?", "Elige palabras para tu mezcla: cálida, brillante, profunda, grande. ¿Cuáles encajan?")},
    {"id": "m8", "t": ("Move a recording in time", "Mueve una grabación en el tiempo"),
     "b": ("Starts at bar says when a track begins. A part that comes in later makes the song grow.",
           "Empieza en el compás dice cuándo empieza una pista. Una parte que entra después hace crecer la canción."),
     "steps": ["later1", "earlier1"],
     "try": ("Let the drums start alone. Bring the piano in at bar 3.", "Deja que la batería empiece sola. Haz entrar el piano en el compás 3."),
     "q": ("Why do many songs start with just one instrument?", "¿Por qué muchas canciones empiezan con un solo instrumento?"),
     "own": ("Write the bar where each of your tracks comes in.", "Escribe el compás en que entra cada pista.")},
    {"id": "m9", "t": ("Repeat a loop", "Repite un bucle"),
     "b": ("Plays says how many times a recording plays in a row. A short loop can fill a whole song.",
           "Suena dice cuántas veces seguidas suena una grabación. Un bucle corto puede llenar toda una canción."),
     "steps": ["more1", "fewer1", "copy1"],
     "try": ("Make a drum loop play 4 times under everything else.", "Haz que un bucle de batería suene 4 veces debajo de todo."),
     "q": ("How many times can a loop repeat before you want a change?", "¿Cuántas veces puede repetirse un bucle antes de que quieras un cambio?"),
     "own": ("Count the bars: loop length × times = song length.", "Cuenta los compases: largo del bucle × veces = largo de la canción.")},
    {"id": "m10", "t": ("Cut into pieces", "Corta en partes"),
     "b": ("Cut splits a recording in two. Each piece can move, repeat or go away on its own. Undo always brings it back.",
           "Cortar divide una grabación en dos. Cada parte puede moverse, repetirse o quitarse sola. Deshacer siempre la trae de vuelta."),
     "steps": ["cut1", "piece1", "drop1", "undo1"],
     "try": ("Cut out your favorite bar and copy it three times.", "Corta tu compás favorito y cópialo tres veces."),
     "q": ("Which part of your take is the best part?", "¿Cuál es la mejor parte de tu toma?"),
     "own": ("Write your pieces in the order you want them.", "Escribe tus partes en el orden que quieres.")},
    {"id": "m11", "t": ("Trim and fade", "Recorta y suaviza"),
     "b": ("Trim cuts quiet bits or mistakes off the start and end. A fade lets a track come in or go out gently.",
           "Recortar quita silencios o errores del principio y del final. Una entrada o salida suave deja que una pista entre o se vaya despacio."),
     "steps": ["trimIn", "trimOut", "fadeIn1", "fadeOut1"],
     "try": ("Give the last track in your song a long fade out.", "Ponle una salida suave larga a la última pista de tu canción."),
     "q": ("When is a fade better than a sudden stop?", "¿Cuándo es mejor una salida suave que un final de golpe?"),
     "own": ("Mark on your song line where each fade goes.", "Marca en la línea de tu canción dónde va cada salida suave.")},
    {"id": "m12", "t": ("Speed", "Velocidad"),
     "b": ("Speed makes a recording slower or faster. Keep the pitch keeps the notes in tune. Off, it works like a tape.",
           "Velocidad hace una grabación más lenta o más rápida. Mantener el tono deja las notas afinadas. Sin él, funciona como una cinta."),
     "steps": ["slow1", "fast1", "keep1"],
     "try": ("Slow a take to 75 % with Keep the pitch off. It sounds deep and dreamy.", "Pon una toma al 75 % sin Mantener el tono. Suena grave y como un sueño."),
     "q": ("Why do the notes go lower when a tape plays slower?", "¿Por qué las notas bajan cuando una cinta suena más lenta?"),
     "own": ("Write the speed you liked best, and why.", "Escribe la velocidad que más te gustó y por qué.")},
    {"id": "m13", "t": ("Loop bars while you work", "Repite compases mientras trabajas"),
     "b": ("Loop plays the same few bars again and again. You can fix one spot while you listen.",
           "Repetir toca los mismos compases una y otra vez. Puedes arreglar una parte mientras escuchas."),
     "steps": ["loopOn", "loopSet", "loopPlay", "startAt"],
     "try": ("Loop bars 1 to 2 and move a Volume while it plays.", "Repite los compases 1 a 2 y mueve un Volumen mientras suena."),
     "q": ("Which part of your song needs the most care?", "¿Qué parte de tu canción necesita más cuidado?"),
     "own": ("Write the bars you looped and what you changed.", "Escribe los compases que repetiste y qué cambiaste.")},
    {"id": "m14", "t": ("The whole song: Glue and Song volume", "Toda la canción: Unión y Volumen de la canción"),
     "b": ("The whole song has its own controls. Glue holds the parts together. Song volume sets how loud it all is.",
           "Toda la canción tiene sus propios controles. Unión mantiene las partes juntas. Volumen de la canción decide qué tan fuerte suena todo."),
     "steps": ["mEq", "mGlue", "mVol"],
     "try": ("Turn Glue up and down while it plays. Listen to the drums.", "Sube y baja Unión mientras suena. Escucha la batería."),
     "q": ("What does it mean for a song to sound together?", "¿Qué significa que una canción suene unida?"),
     "own": ("Write your Glue and Song volume numbers.", "Escribe tus números de Unión y Volumen de la canción.")},
    {"id": "m15", "t": ("Make your song into a file", "Haz de tu canción un archivo"),
     "b": ("Make the mix turns every track into one recording. Save as .wav keeps it on your device.",
           "Hacer la mezcla convierte todas las pistas en una sola grabación. Guardar como .wav la guarda en tu aparato."),
     "steps": ["mix1", "listen1", "save1"],
     "try": ("Change one thing, make the mix again and compare.", "Cambia una cosa, haz la mezcla otra vez y compara."),
     "q": ("Who would you like to play your song for?", "¿Para quién te gustaría tocar tu canción?"),
     "own": ("Give your song a name.", "Ponle un nombre a tu canción.")},
    {"id": "m16", "t": ("Send to the turntables", "Envía a los platos"),
     "b": ("Your mix can go to the turntables. There you can scratch it, mix it with a record or loop it.",
           "Tu mezcla puede ir a los platos. Allí puedes rayarla, mezclarla con un disco o repetirla."),
     "steps": ["send1"],
     "try": ("Open the turntables from the Music tools menu and play your song there.", "Abre los platos desde el menú Instrumentos y toca tu canción allí."),
     "q": ("What would a DJ do with your song?", "¿Qué haría un DJ con tu canción?"),
     "own": ("Write one idea for your song on the turntables.", "Escribe una idea para tu canción en los platos.")},
    {"id": "m17", "t": ("Song: Drums and piano", "Canción: Batería y piano"),
     "b": ("Two instruments, two tracks, one song. Record a drum beat and a piano part, then mix them.",
           "Dos instrumentos, dos pistas, una canción. Graba un ritmo de batería y una parte de piano, luego mézclalos."),
     "steps": ["mixInst2", "mixBal", "save1"],
     "try": ("Keep the drums a little quieter than the piano, so the tune comes through.", "Deja la batería un poco más baja que el piano, para que se oiga la melodía."),
     "q": ("Which track did you make louder, and why?", "¿Qué pista subiste más y por qué?"),
     "own": ("Write the two volumes you picked.", "Escribe los dos volúmenes que elegiste."),
     "song": True},
    {"id": "m18", "t": ("Song: The band arrangement", "Canción: El arreglo de banda"),
     "b": ("Build an intro, a verse and a chorus from drum machine loops and other takes. Parts come in one by one.",
           "Arma una intro, una estrofa y un coro con bucles de la caja de ritmos y otras tomas. Las partes entran una por una."),
     "steps": ["tracks4", "enter", "bars8", "mixBand"],
     "try": ("Intro: drums alone. Verse: add bass. Chorus: add chords and a tune.", "Intro: batería sola. Estrofa: suma el bajo. Coro: suma acordes y una melodía."),
     "q": ("How does a listener know the chorus has started?", "¿Cómo sabe quien escucha que empezó el coro?"),
     "own": ("Write your song's parts and the bar where each starts.", "Escribe las partes de tu canción y el compás en que empieza cada una."),
     "song": True},
    {"id": "m19", "t": ("Song: Remix", "Canción: Remezcla"),
     "b": ("Same takes, new order. Cut a recording into pieces and play them in a new way.",
           "Las mismas tomas, en otro orden. Corta una grabación en partes y tócalas de otra manera."),
     "steps": ["swap", "mixRemix", "sendRemix"],
     "try": ("Change the speed of one track too. Remixes often do.", "Cambia también la velocidad de una pista. Las remezclas lo hacen a menudo."),
     "q": ("What stays the same in your remix? What is new?", "¿Qué sigue igual en tu remezcla? ¿Qué es nuevo?"),
     "own": ("Write the order of your pieces, before and after.", "Escribe el orden de tus partes, antes y después."),
     "song": True},
    {"id": "m20", "t": ("Song: Music under a story", "Canción: Música debajo de una historia"),
     "b": ("Podcasts and videos use soft music under a voice. Make a quiet bed of music you could talk over.",
           "Los pódcasts y los videos usan música suave debajo de una voz. Haz una base de música tranquila sobre la que puedas hablar."),
     "steps": ["bedFade", "mixBed"],
     "try": ("Play your mix and tell a short story out loud over it. Is the music quiet enough?",
             "Toca tu mezcla y cuenta una historia corta en voz alta encima. ¿La música está lo bastante suave?"),
     "q": ("Why should music under a voice be quiet and simple?", "¿Por qué la música debajo de una voz debe ser suave y sencilla?"),
     "own": ("Write the first two lines of the story you would tell.", "Escribe las dos primeras frases de la historia que contarías."),
     "song": True},
    {"id": "m21", "t": ("Song: Your own, start to finish", "Canción: La tuya, de principio a fin"),
     "b": ("A whole song, your way: three or more instruments, 16 bars or more, mixed and finished.",
           "Una canción entera, a tu manera: tres instrumentos o más, 16 compases o más, mezclada y terminada."),
     "steps": ["own3", "ownLong", "mixOwn"],
     "try": ("Use everything you learned: balance, sides, a part that comes in later, a fade out.",
             "Usa todo lo que aprendiste: equilibrio, lados, una parte que entra después, una salida suave."),
     "q": ("What would you change if you made it again?", "¿Qué cambiarías si la hicieras otra vez?"),
     "own": ("Write your song's name, its instruments and its parts in order.", "Escribe el nombre de tu canción, sus instrumentos y sus partes en orden."),
     "song": True},
  ],
}
