# -*- coding: utf-8 -*-
"""The Guitar's lessons (music-guitar.html, built from _work/music/strings_page.html). Built by make_lab_lessons.py.
Every text is (English, Spanish). The page marks each step as it happens (AOG-LESSONS-V1 hooks in strings_page.html)."""

LAB = {
  "lab": "guitar",
  "key": "aog.guitar.lessons.v1",
  "page": "/guitar",
  "sheet": "guitar-lessons.html",
  "name": ("The Guitar", "La guitarra"),
  "steps": {
    "open0": ("Play the low E string: the thickest one", "Toca la cuerda Mi grave: la más gruesa"),
    "open1": ("Play the A string", "Toca la cuerda La"),
    "open2": ("Play the D string", "Toca la cuerda Re"),
    "open3": ("Play the G string", "Toca la cuerda Sol"),
    "open4": ("Play the B string", "Toca la cuerda Si"),
    "open5": ("Play the high E string: the thinnest one", "Toca la cuerda Mi aguda: la más fina"),
    "fret1": ("Tap a string on any fret", "Toca una cuerda en cualquier traste"),
    "higher": ("Press Higher ▶", "Pulsa Más agudo ▶"),
    "fret5": ("Play a note on fret 5 or higher", "Toca una nota en el traste 5 o más arriba"),
    "lower": ("Press ◀ Lower", "Pulsa ◀ Más grave"),
    "pad1": ("Tap a chord pad", "Toca un pad de acorde"),
    "padall": ("Play all six chord pads", "Toca los seis pads de acordes"),
    "seven": ("In the row of chords by the neck, play one of the last four", "En la fila de acordes junto al mástil, toca uno de los cuatro últimos"),
    "mute": ("Press ✋ Mute the strings", "Pulsa ✋ Apagar las cuerdas"),
    "keyG": ("Set the Key to G", "Pon el Tono en Sol"),
    "chG": ("Play a G chord", "Toca un acorde de Sol"),
    "chC": ("Play a C chord", "Toca un acorde de Do"),
    "chD": ("Play a D chord", "Toca un acorde de Re"),
    "chE": ("Play an E chord", "Toca un acorde de Mi"),
    "chA": ("Play an A chord", "Toca un acorde de La"),
    "chEm": ("Play an E minor chord (Em)", "Toca un acorde de Mi menor (Mi m)"),
    "chAm": ("Play an A minor chord (Am)", "Toca un acorde de La menor (La m)"),
    "strumdn": ("Swipe down across the strings on the right", "Desliza hacia abajo por las cuerdas de la derecha"),
    "strumup": ("Swipe back up across them", "Desliza de vuelta hacia arriba por ellas"),
    "strum6": ("Strum all six strings in one swipe", "Rasguea las seis cuerdas de un solo deslizamiento"),
    "pat1": ("Pick a pattern in Start from a chord pattern", "Elige un patrón en Empieza con un patrón de acordes"),
    "play": ("Press ▶ Play the chords", "Pulsa ▶ Tocar los acordes"),
    "tempo": ("Move the Tempo slider", "Mueve el control de Tempo"),
    "stop": ("Press ■ Stop", "Pulsa ■ Parar"),
    "p_down": ("Play the chords with Down strums", "Toca los acordes con Rasgueos hacia abajo"),
    "p_folk": ("Play the chords with Folk", "Toca los acordes con Folk"),
    "p_pick": ("Play the chords with Fingerpicking", "Toca los acordes con Punteo"),
    "p_travis": ("Play the chords with Travis picking", "Toca los acordes con Punteo Travis"),
    "p_chug": ("Play the chords with Chug", "Toca los acordes con Chug"),
    "key1": ("Change the Key", "Cambia el Tono"),
    "minor": ("Press Minor · moody", "Pulsa Menor · melancólico"),
    "wheel1": ("Tap a chord on the chord wheel", "Toca un acorde en la rueda de acordes"),
    "turn": ("Turn the wheel with one of its buttons", "Gira la rueda con uno de sus botones"),
    "anyplay": ("Under Any chord, pick a kind and press ▶ Play this chord", "En Cualquier acorde, elige un tipo y pulsa ▶ Tocar este acorde"),
    "selec": ("Pick an electric guitar in Instrument", "Elige una guitarra eléctrica en Instrumento"),
    "amp1": ("Change a knob or a setting on the amp", "Cambia una perilla o un ajuste del amplificador"),
    "pedal": ("Turn a pedal on or off", "Enciende o apaga un pedal"),
    "era": ("Move the Sound dial between 1987 and 2026", "Mueve el control de Sonido entre 1987 y 2026"),
    "smetal": ("Pick a Metal sound in Instrument", "Elige un sonido de Metal en Instrumento"),
    "power": ("With that sound, tap a chord: you hear a power chord", "Con ese sonido, toca un acorde: oyes un acorde de poder"),
    "pvbig": ("Turn your phone sideways, or press ⤢ Play on the whole screen", "Gira tu teléfono de lado, o pulsa ⤢ Tocar en toda la pantalla"),
    "pvhold": ("In ☰ Menu, pick ✋ Hold + strum", "En ☰ Menú, elige ✋ Pisar + rasguear"),
    "holdstrum": ("Hold a fret with one hand. Strum the strip with the other", "Pisa un traste con una mano. Rasguea la franja con la otra"),
    "handstyle": ("While the chords play, hold frets: the style plays them", "Mientras suenan los acordes, pisa trastes: el estilo los toca"),
    "solo1": ("Press Solo, above the neck", "Pulsa Solo, encima del mástil"),
    "solo8": ("Play eight lit notes", "Toca ocho notas iluminadas"),
    "scale1": ("Pick another Scale", "Elige otra Escala"),
    "chordsback": ("Press Chords to go back", "Pulsa Acordes para volver"),
    "bend": ("In Solo mode, push a note across its string to bend it", "En el modo Solo, empuja una nota a lo ancho de su cuerda para estirarla"),
    "slide": ("Slide a finger along a string to another fret", "Desliza un dedo por una cuerda hasta otro traste"),
    "lick": ("Pick a lick and press ▶ Play this lick", "Elige una frase y pulsa ▶ Tocar esta frase"),
    "band": ("Press ▶ Play the band", "Pulsa ▶ Tocar la banda"),
    "drums": ("Turn on Play with my drum beat", "Activa Tocar con mi ritmo de batería"),
    "drumplay": ("Press ▶ Play the chords with your drum beat on", "Pulsa ▶ Tocar los acordes con tu ritmo de batería puesto"),
    "take1": ("Press ● Record", "Pulsa ● Grabar"),
    "take2": ("Play, then press ■ Stop to keep the take", "Toca y luego pulsa ■ Parar para guardar la toma"),
    "studio": ("On your take, press Send to the Mixing Desk", "En tu toma, pulsa Enviar a la mesa de mezclas"),
    "decks": ("Press Send to the turntables", "Pulsa Enviar a los platos"),
    "pat_pop": ("Pick the pattern Pop · 1 5 6 4", "Elige el patrón Pop · 1 5 6 4"),
    "sg_camp": ("In the key of G, play it with Folk", "En el tono de Sol, tócalo con Folk"),
    "tk_camp": ("Record a take while it plays", "Graba una toma mientras suena"),
    "pat_blues": ("Pick the pattern Blues · 12 bars", "Elige el patrón Blues · 12 compases"),
    "sg_blues": ("Play it with Shuffle", "Tócalo con Shuffle"),
    "tk_blues": ("Record a take while it plays", "Graba una toma mientras suena"),
    "pat_minor": ("Pick the pattern Minor groove", "Elige el patrón Ritmo menor"),
    "sg_reggae": ("Play it with Off-beat · reggae and ska", "Tócalo con Contratiempo · reggae y ska"),
    "tk_reggae": ("Record a take while it plays", "Graba una toma mientras suena"),
    "pat_power": ("Pick the pattern Power chords · 1 ♭3 4 1", "Elige el patrón Acordes de poder · 1 ♭3 4 1"),
    "sg_rock": ("With a Metal sound, play it with Rock, Punk or Chug", "Con un sonido de Metal, tócalo con Rock, Punk o Chug"),
    "tk_rock": ("Record a take while it plays", "Graba una toma mientras suena"),
    "pat_bossa": ("Pick the pattern Bossa nova · 1 2 5 1", "Elige el patrón Bossa nova · 1 2 5 1"),
    "snylon": ("Pick Classical guitar · nylon strings", "Elige Guitarra clásica · cuerdas de nailon"),
    "sg_bossa": ("With the classical guitar, play it with Bossa nova", "Con la guitarra clásica, tócalo con Bossa nova"),
    "tk_bossa": ("Record a take while it plays", "Graba una toma mientras suena"),
    "own1": ("Press Make my own", "Pulsa Hacer el mío"),
    "own4": ("Tap four chords, one after another", "Toca cuatro acordes, uno tras otro"),
    "sg_own": ("Play your own pattern in a style you like", "Toca tu propio patrón en un estilo que te guste"),
    "tk_own": ("Record a take while it plays", "Graba una toma mientras suena"),
    "studio2": ("Send a second take to the Mixing Desk", "Envía una segunda toma a la mesa de mezclas"),
  },
  "lessons": [
    {"id": "g1", "t": ("The six strings", "Las seis cuerdas"),
     "b": ("Tap a string at the far left, before the frets. It rings open. From thick to thin: E A D G B E.",
           "Toca una cuerda a la izquierda del todo, antes de los trastes. Suena al aire. De gruesa a fina: Mi La Re Sol Si Mi."),
     "steps": ["open0", "open1", "open2", "open3", "open4", "open5"],
     "try": ("Say each name out loud as you play it: E, A, D, G, B, E.", "Di cada nombre en voz alta al tocarla: Mi, La, Re, Sol, Si, Mi."),
     "q": ("Which string sounds lowest? Which sounds highest? Why might that be?", "¿Qué cuerda suena más grave? ¿Cuál más aguda? ¿Por qué será?"),
     "own": ("Make up a way to remember E A D G B E. For example: Eddie Ate Dynamite, Good Bye Eddie.", "Inventa una forma de recordar Mi La Re Sol Si Mi. Por ejemplo, una frase con esas sílabas.")},
    {"id": "g2", "t": ("Frets make notes", "Los trastes hacen notas"),
     "b": ("Press a string on a fret and the note goes up. Each fret is one small step.", "Pisa una cuerda en un traste y la nota sube. Cada traste es un pasito."),
     "steps": ["fret1", "higher", "fret5", "lower"],
     "try": ("Play the low E string on frets 1, 2, 3, 4 and 5. Hear it climb.", "Toca la cuerda Mi grave en los trastes 1, 2, 3, 4 y 5. Oye cómo sube."),
     "q": ("The low E on fret 5 sounds just like another open string. Which one?", "El Mi grave en el traste 5 suena igual que otra cuerda al aire. ¿Cuál?"),
     "own": ("Play a short tune on one string. Write the fret numbers in order.", "Toca una melodía corta en una sola cuerda. Escribe los números de traste en orden.")},
    {"id": "g3", "t": ("Chord pads", "Los pads de acordes"),
     "b": ("A chord is a few notes together. Each pad strums one. Every pad fits the key.", "Un acorde son varias notas juntas. Cada pad rasguea uno. Todos los pads van con el tono."),
     "steps": ["pad1", "padall", "seven", "mute"],
     "try": ("Tap pads 1, 4, 5, 1. That is how many songs go.", "Toca los pads 1, 4, 5, 1. Así van muchas canciones."),
     "q": ("Look at the neck when you tap a pad. What do the pale dots show?", "Mira el mástil al tocar un pad. ¿Qué muestran los puntos claros?"),
     "own": ("Pick the pad that sounds most like home to you. Write its name.", "Elige el pad que más te suene a casa. Escribe su nombre.")},
    {"id": "g4", "t": ("First chords: G, C and D", "Primeros acordes: Sol, Do y Re"),
     "b": ("Three chords. Thousands of songs use just these.", "Tres acordes. Miles de canciones usan solo estos."),
     "steps": ["keyG", "chG", "chC", "chD"],
     "try": ("Play G, C, G, D. Then try it slower, with a steady count of four.", "Toca Sol, Do, Sol, Re. Luego más despacio, contando cuatro."),
     "q": ("Look at where the fingers go for G and for C. What is the same? What changes?", "Mira dónde van los dedos para Sol y para Do. ¿Qué se repite? ¿Qué cambia?"),
     "own": ("Draw the G chord on six lines. Put a dot where each finger goes.", "Dibuja el acorde de Sol en seis líneas. Pon un punto donde va cada dedo.")},
    {"id": "g5", "t": ("E, A, and two minor chords", "Mi, La y dos acordes menores"),
     "b": ("A minor chord sounds softer and more thoughtful. Em and Am are easy ones to start with.", "Un acorde menor suena más suave y pensativo. Mi m y La m son fáciles para empezar."),
     "steps": ["chE", "chA", "chEm", "chAm"],
     "try": ("Play E, then Em. Only one note changes. Can you hear which?", "Toca Mi y luego Mi m. Solo cambia una nota. ¿Oyes cuál?"),
     "q": ("Tip: the key of G has Em and Am. The key of A has A and E. How did you find them?", "Pista: el tono de Sol tiene Mi m y La m. El tono de La tiene La y Mi. ¿Cómo los encontraste?"),
     "own": ("Write a four-chord pattern using only E, A, Em and Am.", "Escribe un patrón de cuatro acordes con solo Mi, La, Mi m y La m.")},
    {"id": "g6", "t": ("Strum", "Rasguea"),
     "b": ("Tap a chord, then swipe across the strip on the right. Every string you cross rings.", "Toca un acorde y desliza el dedo por la franja de la derecha. Suena cada cuerda que cruzas."),
     "steps": ["strumdn", "strumup", "strum6"],
     "try": ("Strum down, down, up, down. Keep your hand moving like a pendulum.", "Rasguea abajo, abajo, arriba, abajo. Mueve la mano como un péndulo."),
     "q": ("A fast swipe and a slow swipe sound different. How?", "Un deslizamiento rápido y uno lento suenan distinto. ¿Cómo?"),
     "own": ("Write a strum pattern with arrows, like ↓ ↓ ↑ ↓.", "Escribe un patrón de rasgueo con flechas, como ↓ ↓ ↑ ↓.")},
    {"id": "g7", "t": ("Chord patterns", "Patrones de acordes"),
     "b": ("A pattern is a row of chords, one for each bar. The page plays it for you.", "Un patrón es una fila de acordes, uno por compás. La página lo toca por ti."),
     "steps": ["pat1", "play", "tempo", "stop"],
     "try": ("Watch the neck while it plays. The orange dots are the notes ringing now.", "Mira el mástil mientras suena. Los puntos naranjas son las notas que suenan ahora."),
     "q": ("What does the small number under each chord tell you?", "¿Qué te dice el número pequeño bajo cada acorde?"),
     "own": ("Name a pattern you liked and the tempo that felt best.", "Nombra un patrón que te gustó y el tempo que mejor se sintió.")},
    {"id": "g8", "t": ("Ways to strum and pick", "Formas de rasguear y puntear"),
     "b": ("The same chords can be strummed or picked one string at a time. Pick a style in How the chords play.", "Los mismos acordes se pueden rasguear o puntear cuerda a cuerda. Elige un estilo en Cómo suenan los acordes."),
     "steps": ["p_down", "p_folk", "p_pick", "p_travis"],
     "try": ("Keep one pattern and change only the style. Which one feels calm? Which one feels busy?", "Deja un patrón y cambia solo el estilo. ¿Cuál se siente tranquilo? ¿Cuál se siente movido?"),
     "q": ("In Travis picking, the thumb keeps the beat. Can you hear the low notes go back and forth?", "En el punteo Travis, el pulgar lleva el pulso. ¿Oyes las notas graves ir y venir?"),
     "own": ("Pick a style for a sleepy song and one for a dancing song.", "Elige un estilo para una canción de dormir y otro para una de bailar.")},
    {"id": "g9", "t": ("Keys, moods and the chord wheel", "Tonos, ánimos y la rueda de acordes"),
     "b": ("The key sets which chords fit. Major sounds bright. Minor sounds moody. The wheel shows every chord.", "El tono decide qué acordes encajan. Mayor suena brillante. Menor suena melancólico. La rueda muestra todos los acordes."),
     "steps": ["key1", "minor", "wheel1", "turn", "anyplay"],
     "try": ("Neighbours on the wheel sound good together. Play three chords side by side.", "Los vecinos en la rueda suenan bien juntos. Toca tres acordes que estén lado a lado."),
     "q": ("When you turned the wheel, what happened to the six light chords?", "Al girar la rueda, ¿qué pasó con los seis acordes claros?"),
     "own": ("Choose a key and a mood for a song about the sea.", "Elige un tono y un ánimo para una canción sobre el mar.")},
    {"id": "g10", "t": ("Amp and pedals", "Amplificador y pedales"),
     "b": ("An electric guitar plays through an amp. Pedals change its sound: echo, crunch, wobble and more.", "Una guitarra eléctrica suena por un amplificador. Los pedales cambian su sonido: eco, crujido, ondas y más."),
     "steps": ["selec", "amp1", "pedal", "era"],
     "try": ("Turn on one pedal, play a chord, then turn it off. Name what it added.", "Enciende un pedal, toca un acorde y apágalo. Di qué añadió."),
     "q": ("Which pedal would you use for a dreamy song? Which for a loud one?", "¿Qué pedal usarías para una canción de ensueño? ¿Y para una fuerte?"),
     "own": ("Make a sound you love. Write the amp and the pedals you used.", "Haz un sonido que te encante. Escribe el amplificador y los pedales que usaste.")},
    {"id": "g11", "t": ("Power chords", "Acordes de poder"),
     "b": ("A power chord is just the root and its fifth. It stays clear through a loud, heavy amp.", "Un acorde de poder es solo la raíz y su quinta. Suena claro con un amplificador fuerte y pesado."),
     "steps": ["smetal", "power", "p_chug"],
     "try": ("Look at the neck: a power chord uses only two or three strings.", "Mira el mástil: un acorde de poder usa solo dos o tres cuerdas."),
     "q": ("Why might heavy music leave out the third of the chord?", "¿Por qué la música pesada dejará fuera la tercera del acorde?"),
     "own": ("Write the three strings and frets of one power chord you played.", "Escribe las tres cuerdas y trastes de un acorde de poder que tocaste.")},
    {"id": "g12", "t": ("Hold + strum, like a real guitar", "Pisar + rasguear, como una guitarra de verdad"),
     "b": ("On the whole screen, one hand holds the frets and the other strums. A style can play the frets you hold, too.", "En toda la pantalla, una mano pisa los trastes y la otra rasguea. Un estilo también puede tocar los trastes que pisas."),
     "steps": ["pvbig", "pvhold", "holdstrum", "handstyle"],
     "try": ("Hold the shape the pale dots show, then strum. Change one finger and strum again.", "Pisa la forma que muestran los puntos claros y rasguea. Cambia un dedo y rasguea otra vez."),
     "q": ("What happens when you lift your fretting finger?", "¿Qué pasa cuando levantas el dedo que pisa?"),
     "own": ("Find a shape of your own that sounds good. Draw it.", "Encuentra una forma propia que suene bien. Dibújala.")},
    {"id": "g13", "t": ("Solo mode and scales", "Modo Solo y escalas"),
     "b": ("Solo mode lights a scale on the neck. Every lit note fits, so you can play freely.", "El modo Solo ilumina una escala en el mástil. Todas las notas iluminadas encajan, así que puedes tocar libremente."),
     "steps": ["solo1", "solo8", "scale1", "chordsback"],
     "try": ("Start and end your solo on a ringed note. That is the home note.", "Empieza y termina tu solo en una nota con anillo. Es la nota casa."),
     "q": ("How did the new scale change the mood?", "¿Cómo cambió el ánimo la nueva escala?"),
     "own": ("Write the frets of a five-note idea you liked.", "Escribe los trastes de una idea de cinco notas que te gustó.")},
    {"id": "g14", "t": ("Bends, slides and licks", "Estirar, deslizar y frases"),
     "b": ("Lead players make notes sing: they bend them and slide between them. Licks are short ideas to copy.", "Los solistas hacen cantar las notas: las estiran y se deslizan entre ellas. Las frases son ideas cortas para copiar."),
     "steps": ["bend", "slide", "lick", "band"],
     "try": ("Copy a lick slowly with the speed slider, then play it over the band.", "Copia una frase despacio con el control de velocidad y luego tócala con la banda."),
     "q": ("A bend sounds like a voice. What feeling can it show?", "Estirar una nota suena como una voz. ¿Qué sentimiento puede mostrar?"),
     "own": ("Make up a lick with one bend and one slide. Write its frets.", "Inventa una frase con un estirón y un deslizamiento. Escribe sus trastes.")},
    {"id": "g15", "t": ("Play with your drum beat", "Toca con tu ritmo de batería"),
     "b": ("Make a beat on the drum machine and send it here. The guitar plays in time with it.", "Haz un ritmo en la caja de ritmos y envíalo aquí. La guitarra toca a tiempo con él."),
     "steps": ["drums", "drumplay"],
     "try": ("Try a funky drum beat with the Funk style.", "Prueba un ritmo funky de batería con el estilo Funk."),
     "q": ("Why does the tempo now come from the drum beat?", "¿Por qué ahora el tempo viene del ritmo de batería?"),
     "own": ("Name your drum beat and the guitar style that fits it best.", "Nombra tu ritmo de batería y el estilo de guitarra que mejor le va.")},
    {"id": "g16", "t": ("Record a take and share it", "Graba una toma y compártela"),
     "b": ("A take keeps everything you play. Send it to the Mixing Desk or the turntables.", "Una toma guarda todo lo que tocas. Envíala a la mesa de mezclas o a los platos."),
     "steps": ["take1", "take2", "studio", "decks"],
     "try": ("Record two takes of the same chords. Keep the one you like best.", "Graba dos tomas de los mismos acordes. Quédate con la que más te guste."),
     "q": ("What changed between your first take and your second?", "¿Qué cambió entre tu primera toma y la segunda?"),
     "own": ("Plan a 30-second take: what do you play first, and what comes next?", "Planea una toma de 30 segundos: ¿qué tocas primero y qué viene después?")},
    {"id": "g17", "t": ("Song: Campfire song", "Canción: Junto a la fogata"),
     "b": ("Four chords, a folk strum, the key of G. A song for singing along.", "Cuatro acordes, un rasgueo folk, el tono de Sol. Una canción para cantar juntos."),
     "steps": ["pat_pop", "sg_camp", "tk_camp"],
     "try": ("Hum a tune over it. Then make up one line of words.", "Tararea una melodía encima. Luego inventa una línea de letra."),
     "q": ("Why do so many songs use these same four chords?", "¿Por qué tantas canciones usan estos mismos cuatro acordes?"),
     "own": ("Write the four chords and one line of words for your campfire song.", "Escribe los cuatro acordes y una línea de letra para tu canción de fogata."),
     "song": True},
    {"id": "g18", "t": ("Song: Blues shuffle", "Canción: Blues shuffle"),
     "b": ("Twelve bars of blues, with a swinging shuffle on the low strings.", "Doce compases de blues, con un shuffle con swing en las cuerdas graves."),
     "steps": ["pat_blues", "sg_blues", "tk_blues"],
     "try": ("Try it in the key of A or E. Then solo over it with the Blues scale.", "Pruébalo en La o en Mi. Luego toca un solo encima con la escala de Blues."),
     "q": ("Count the bars. Where does the music go to chord 4? Where to chord 5?", "Cuenta los compases. ¿Dónde va la música al acorde 4? ¿Y al 5?"),
     "own": ("Write the twelve bars as numbers: 1 1 1 1, then the rest.", "Escribe los doce compases con números: 1 1 1 1 y el resto."),
     "song": True},
    {"id": "g19", "t": ("Song: Reggae skank", "Canción: Reggae skank"),
     "b": ("Short chords on the off-beat, with lots of space. Relaxed and steady.", "Acordes cortos a contratiempo, con mucho espacio. Relajado y constante."),
     "steps": ["pat_minor", "sg_reggae", "tk_reggae"],
     "try": ("Count 1 and 2 and 3 and 4 and. The guitar plays on every and.", "Cuenta 1 y 2 y 3 y 4 y. La guitarra toca en cada y."),
     "q": ("What does the space between the chords do for the song?", "¿Qué le aporta a la canción el espacio entre los acordes?"),
     "own": ("Write where the chords land, using the word and.", "Escribe dónde caen los acordes, con la palabra y."),
     "song": True},
    {"id": "g20", "t": ("Song: Rock riff with power chords", "Canción: Riff de rock con acordes de poder"),
     "b": ("A heavy sound, power chords and a driving strum.", "Un sonido pesado, acordes de poder y un rasgueo con empuje."),
     "steps": ["pat_power", "smetal", "sg_rock", "tk_rock"],
     "try": ("Turn the tempo up for punk. Turn it down for a slow, huge doom riff.", "Sube el tempo para punk. Bájalo para un riff de doom lento y enorme."),
     "q": ("Which part makes it sound heavy: the sound, the chords, or the strum?", "¿Qué lo hace sonar pesado: el sonido, los acordes o el rasgueo?"),
     "own": ("Give your riff a name and write its four chords.", "Ponle nombre a tu riff y escribe sus cuatro acordes."),
     "song": True},
    {"id": "g21", "t": ("Song: Bossa nova", "Canción: Bossa nova"),
     "b": ("A gentle groove from Brazil, on nylon strings, with soft seventh chords.", "Un ritmo suave de Brasil, con cuerdas de nailon y acordes de séptima suaves."),
     "steps": ["pat_bossa", "snylon", "sg_bossa", "tk_bossa"],
     "try": ("Set the tempo near 120 and keep it soft. Let it float.", "Pon el tempo cerca de 120 y tócalo suave. Deja que flote."),
     "q": ("How do the seventh chords change the feeling?", "¿Cómo cambian el sentimiento los acordes de séptima?"),
     "own": ("Describe your bossa nova in five words.", "Describe tu bossa nova en cinco palabras."),
     "song": True},
    {"id": "g22", "t": ("Song: Your own, start to finish", "Canción: La tuya, de principio a fin"),
     "b": ("Your chords, your style, your take, sent to the Mixing Desk.", "Tus acordes, tu estilo, tu toma, enviada a la mesa de mezclas."),
     "steps": ["own1", "own4", "sg_own", "tk_own", "studio2"],
     "try": ("Record one take with chords and one with a solo. Put both on the Mixing Desk.", "Graba una toma con acordes y otra con un solo. Pon las dos en la mesa de mezclas."),
     "q": ("What would you change if you made it again?", "¿Qué cambiarías si la hicieras otra vez?"),
     "own": ("Write your song's name, its chords and its style.", "Escribe el nombre de tu canción, sus acordes y su estilo."),
     "song": True},
  ],
}
