# -*- coding: utf-8 -*-
"""AOG-PIANO-LESSONS-V1 (2026-10-03) — the piano's lessons, one source for two pages.

Jimmy: "May I also have the same type of lessons and worksheets and pages within where it lives?"
The same shape as the drum machine: twenty-one skill lessons, then seventeen songs we make
together. make_piano_lessons.py turns this file into
  · the lesson data inside music-piano.html (the steps tick themselves from the piano's state)
  · piano-lessons.html, one worksheet per lesson.

Every text is (English, Spanish). Plain words: short sentences, what to do, warm and direct.
Notes in Spanish use Do Re Mi Fa Sol La Si, as the piano does.
"""

# ── the step lines on the bench: id → (English, Spanish) ─────────────────────────────────────
LSTEP = {
  # 1 · turn it on
  "key1": ("Tap any key and hear it", "Toca cualquier tecla y escúchala"),
  "pad1": ("Tap any chord pad", "Toca cualquier pad de acorde"),
  "pat1": ("Pick a chord pattern", "Elige un patrón de acordes"),
  "play1": ("Press Play the chords", "Pulsa Tocar los acordes"),
  "stop1": ("Press Stop", "Pulsa Parar"),
  # 2 · find C
  "fc": ("Play a C", "Toca un Do"),
  "fc2": ("Play two different C's, one higher than the other", "Toca dos Do distintos, uno más agudo que el otro"),
  "fb2": ("Play both keys of a group of two black keys", "Toca las dos teclas de un grupo de dos teclas negras"),
  "fb3": ("Play all three keys of a group of three black keys", "Toca las tres teclas de un grupo de tres teclas negras"),
  # 3 · seven names
  "up8": ("Play C D E F G A B C, going up", "Toca Do Re Mi Fa Sol La Si Do, subiendo"),
  "down8": ("Play it back down: C B A G F E D C", "Tócala de bajada: Do Si La Sol Fa Mi Re Do"),
  "up8hi": ("Play the scale going up again, one octave higher", "Toca la escala subiendo otra vez, una octava más arriba"),
  # 4 · octaves
  "opair": ("Play a note, then the same note one octave higher", "Toca una nota y luego la misma nota una octava más arriba"),
  "ohigher": ("Press Higher ▶ to move the keyboard up", "Pulsa Más agudo ▶ para subir el teclado"),
  "olower": ("Press ◀ Lower to move it down", "Pulsa ◀ Más grave para bajarlo"),
  "ofar": ("Play a very low note (C2 or lower) and a very high one (C6 or higher)", "Toca una nota muy grave (Do2 o más abajo) y una muy aguda (Do6 o más arriba)"),
  # 5 · soft and loud
  "vsoft": ("Play a soft note: press near the top of a key", "Toca una nota suave: presiona cerca de la parte de arriba de una tecla"),
  "vloud": ("Play a loud note: press near the bottom of a key", "Toca una nota fuerte: presiona cerca de la parte de abajo de una tecla"),
  "vgrow": ("Play one key four times, from soft to loud", "Toca una tecla cuatro veces, de suave a fuerte"),
  # 6 · a chord by hand
  "hceg": ("Hold C, E and G down together", "Mantén Do, Mi y Sol presionadas a la vez"),
  "hfac": ("Hold F, A and C together", "Mantén Fa, La y Do a la vez"),
  "hgbd": ("Hold G, B and D together", "Mantén Sol, Si y Re a la vez"),
  "hpad": ("Key C, Major: tap pad 1 and hear the same chord", "Tono Do, Mayor: toca el pad 1 y oye el mismo acorde"),
  # 7 · major and minor
  "mjr": ("Hold C, E and G: C major", "Mantén Do, Mi y Sol: Do mayor"),
  "mnr": ("Hold C, E♭ and G: C minor", "Mantén Do, Mi♭ y Sol: Do menor"),
  "mmood": ("Press Minor · moody, then tap pad 1", "Pulsa Menor · melancólico y toca el pad 1"),
  "mback": ("Press Major · bright and tap pad 1 again", "Pulsa Mayor · brillante y toca otra vez el pad 1"),
  # 8 · the pads
  "p6": ("Tap all six pads", "Toca los seis pads"),
  "p51": ("Tap pad 5, then pad 1. Hear it come home", "Toca el pad 5 y luego el pad 1. Oye cómo vuelve a casa"),
  "pmin": ("In Major, tap a minor pad: 2, 3 or 6", "En Mayor, toca un pad menor: 2, 3 o 6"),
  "p4key": ("Change the Key and tap all six pads again", "Cambia el Tono y toca otra vez los seis pads"),
  # 9 · a pattern
  "cpop": ("Pick Pop · 1 5 6 4", "Elige Pop · 1 5 6 4"),
  "cplay": ("Press Play the chords", "Pulsa Tocar los acordes"),
  "cround": ("Let it go round twice: 8 bars", "Déjalo dar dos vueltas: 8 compases"),
  "cswap": ("Pick another pattern while it plays", "Elige otro patrón mientras suena"),
  # 10 · four ways
  "rhold": ("Play with Hold · one long chord", "Toca con Mantener · un acorde largo"),
  "rpulse": ("Play with Pulse · four beats", "Toca con Pulso · cuatro tiempos"),
  "rbroken": ("Play with Broken · one note at a time", "Toca con Arpegio · una nota a la vez"),
  "roff": ("Play with Off-beat · reggae and ska", "Toca con Contratiempo · reggae y ska"),
  # 11 · tempo
  "t60": ("Set the tempo to 60", "Pon el tempo en 60"),
  "t60p": ("Play a pattern at 60", "Toca un patrón a 60"),
  "t120": ("Set the tempo to 120: twice as fast", "Pon el tempo en 120: el doble de rápido"),
  "t120p": ("Play it at 120", "Tócalo a 120"),
  # 12 · the key
  "kpat": ("Play a chord pattern in the key of C", "Toca un patrón de acordes en el tono de Do"),
  "kg": ("Change Key to G and play it again", "Cambia el Tono a Sol y tócalo otra vez"),
  "k3": ("Play it in three different keys", "Tócalo en tres tonos distintos"),
  "klive": ("Change the Key while it plays", "Cambia el Tono mientras suena"),
  # 13 · your own
  "own1": ("Press Make my own", "Pulsa Hacer el mío"),
  "own4": ("Tap four pads: a pattern of four chords", "Toca cuatro pads: un patrón de cuatro acordes"),
  "ownhome": ("End your pattern on pad 1, the home chord", "Termina tu patrón en el pad 1, el acorde casa"),
  "ownplay": ("Play your pattern", "Toca tu patrón"),
  # 14 · the pedal
  "son": ("Turn on Hold notes (pedal)", "Activa Mantener notas (pedal)"),
  "sring": ("With the pedal on, play five keys one after another", "Con el pedal activo, toca cinco teclas una tras otra"),
  "soff": ("Turn the pedal off and hear the notes stop", "Desactiva el pedal y oye cómo paran las notas"),
  # 15 · eight sounds
  "tgrand": ("Play on the Grand piano", "Toca con el Piano de cola"),
  "tep": ("Play on an electric piano", "Toca con un piano eléctrico"),
  "torg": ("Play on an organ", "Toca con un órgano"),
  "tall": ("Try all eight sounds", "Prueba los ocho sonidos"),
  # 16 · the lit keys
  "lplay": ("Play a pattern with Hold · one long chord", "Toca un patrón con Mantener · un acorde largo"),
  "llit": ("While it plays, play a lit key", "Mientras suena, toca una tecla iluminada"),
  "llit8": ("Play eight lit notes in a row", "Toca ocho notas iluminadas seguidas"),
  "lchange": ("Keep going when the chord changes: play lit notes on two different chords", "Sigue cuando cambia el acorde: toca notas iluminadas en dos acordes distintos"),
  # 17 · the drum machine
  "dsend": ("On the drum machine, make a beat and press Send to the turntables", "En la caja de ritmos, haz un ritmo y pulsa Enviar a los platos"),
  "don": ("Back here, press Play with my drum beat", "De vuelta aquí, pulsa Tocar con mi ritmo de batería"),
  "dplay": ("Play your chords with the beat", "Toca tus acordes con el ritmo"),
  "dpulse": ("With the drums, try Pulse or Off-beat", "Con la batería, prueba Pulso o Contratiempo"),
  # 18 · the blues
  "bpick": ("Pick Blues · 12 bars", "Elige Blues · 12 compases"),
  "borg": ("Pick the Rock and jazz organ", "Elige el Órgano de rock y jazz"),
  "bpulse": ("Set How the chords play to Pulse", "Pon Cómo suenan los acordes en Pulso"),
  "b12": ("Play all twelve bars", "Toca los doce compases"),
  # 19 · sevenths
  "jpick": ("Pick Jazz · 2 5 1", "Elige Jazz · 2 5 1"),
  "jep": ("Pick Electric piano · warm", "Elige Piano eléctrico · cálido"),
  "jplay": ("Play it with Broken · one note at a time", "Tócalo con Arpegio · una nota a la vez"),
  "jhand": ("On the keys, hold D, F, A and C together: D minor 7", "En las teclas, mantén Re, Fa, La y Do a la vez: Re menor 7"),
  # 20 · 1987 or 2026
  "e87": ("Turn the Sound dial all the way to 1987 and play", "Gira el dial de Sonido del todo a 1987 y toca"),
  "ehigh": ("On 1987, play the highest keys and hear the fizz", "En 1987, toca las teclas más agudas y oye el chisporroteo"),
  "e26": ("Turn it to 2026 and play those high keys again", "Gíralo a 2026 y toca otra vez esas teclas agudas"),
  "emid": ("Find your spot in the middle and play there", "Busca tu punto en el medio y toca ahí"),
  # 21 · a track
  "fown": ("Make your own pattern of four or more chords", "Haz tu propio patrón de cuatro acordes o más"),
  "fname": ("Type a name for your piece", "Escribe un nombre para tu pieza"),
  "fsend": ("Press Send to the turntables", "Pulsa Enviar a los platos"),
  "fsheet": ("Open the worksheet for this lesson", "Abre la hoja de esta lección"),
}

W = "https://en.wikipedia.org/wiki/"
CML = "https://musiclab.chromeexperiments.com/"

# ── the twenty-one skill lessons ───────────────────────────────────────────────────────────────
# try kinds: notes (a row of note boxes) · keys (one octave, C to C, a row per chord) · table
SKILLS = [
 dict(id="p1", t=("Turn it on and play", "Enciéndelo y toca"),
  blurb=("Tap a key. Tap a chord pad. Pick a pattern and press Play. That is the whole piano.",
         "Toca una tecla. Toca un pad de acorde. Elige un patrón y pulsa Tocar. Ese es todo el piano."),
  steps=["key1", "pad1", "pat1", "play1", "stop1"],
  do=[("Open the piano.", "Abre el piano."),
      ("Tap three keys: one on the left, one in the middle, one on the right. Listen to each one.", "Toca tres teclas: una a la izquierda, una en el medio y una a la derecha. Escucha cada una."),
      ("Tap a chord pad. Three notes play at once.", "Toca un pad de acorde. Suenan tres notas a la vez."),
      ("Under Start from a chord pattern, pick Pop. Press Play the chords.", "En Empieza con un patrón de acordes, elige Pop. Pulsa Tocar los acordes."),
      ("Let it play for a few seconds. Then press Stop.", "Déjalo sonar unos segundos. Luego pulsa Parar.")],
  kw=[("key", "tecla"), ("chord", "acorde"), ("pattern", "patrón")],
  q1=("Which sounded higher: a key on the left or a key on the right?", "¿Cuál sonó más agudo: una tecla de la izquierda o una de la derecha?"),
  q2=("How is tapping one key different from tapping a chord pad?", "¿En qué se diferencia tocar una tecla de tocar un pad de acorde?"),
  tryit=dict(kind="notes", n=3, hint=("Write the names of three keys you played. Each key shows its name.", "Escribe los nombres de tres teclas que tocaste. Cada tecla muestra su nombre.")),
  refl=("One thing I noticed the first time I pressed Play:", "Algo que noté la primera vez que pulsé Tocar:"),
  links=[("Piano — Wikipedia", W + "Piano"), ("Song Maker — Chrome Music Lab", CML + "Song-Maker/")]),

 dict(id="p2", t=("Find C: the black keys show the way", "Encuentra el Do: las teclas negras te guían"),
  blurb=("The black keys come in groups of two and three. Every C sits just to the left of a group of two.",
         "Las teclas negras vienen en grupos de dos y de tres. Cada Do está justo a la izquierda de un grupo de dos."),
  steps=["fc", "fc2", "fb2", "fb3"],
  do=[("Look at the black keys. Find a group of two, then a group of three.", "Mira las teclas negras. Busca un grupo de dos y luego un grupo de tres."),
      ("The white key just left of the group of two is C. Play it.", "La tecla blanca justo a la izquierda del grupo de dos es Do. Tócala."),
      ("Find another C. On a phone, use the C at the right end, or press Higher ▶.", "Busca otro Do. En un teléfono, usa el Do del extremo derecho o pulsa Más agudo ▶."),
      ("Play the two black keys of a pair. Then play the three of a trio.", "Toca las dos teclas negras de un par. Luego toca las tres de un trío.")],
  kw=[("C", "Do"), ("black key", "tecla negra"), ("pattern", "patrón")],
  q1=("How did you find C without reading the names?", "¿Cómo encontraste el Do sin leer los nombres?"),
  q2=("How many black keys are there from one C up to the next C?", "¿Cuántas teclas negras hay de un Do al siguiente Do?"),
  tryit=dict(kind="keys", rows=[("C", "Do"), ("Black keys", "Teclas negras")],
             hint=("Row 1: put an X under each C. Row 2: write 2 under the black keys of the pair and 3 under the black keys of the trio.",
                   "Fila 1: pon una X debajo de cada Do. Fila 2: escribe 2 debajo de las teclas negras del par y 3 debajo de las del trío.")),
  refl=("A trick I can use to find any note quickly:", "Un truco que puedo usar para encontrar cualquier nota rápido:"),
  links=[("C (musical note) — Wikipedia", W + "C_(musical_note)"), ("Musical keyboard — Wikipedia", W + "Musical_keyboard")]),

 dict(id="p3", t=("Seven letters, then they repeat", "Siete notas, y se repiten"),
  blurb=("The white keys are named A B C D E F G, and then the names start over. From C up to the next C is the C major scale.",
         "Las teclas blancas se llaman Do Re Mi Fa Sol La Si, y luego los nombres empiezan otra vez. De un Do al siguiente Do tienes la escala de Do mayor."),
  steps=["up8", "down8", "up8hi"],
  do=[("Find C. Play every white key going up, one at a time, until the next C.", "Busca Do. Toca cada tecla blanca subiendo, una por una, hasta el siguiente Do."),
      ("Say each name out loud as you play it.", "Di cada nombre en voz alta mientras lo tocas."),
      ("Now play the same eight keys going down.", "Ahora toca las mismas ocho teclas bajando."),
      ("Move one octave higher and play the scale going up again. On a computer, the keys A S D F G H J K play it.", "Sube una octava y toca la escala subiendo otra vez. En la computadora, las teclas A S D F G H J K la tocan.")],
  kw=[("scale", "escala"), ("note name", "nombre de la nota"), ("C major", "Do mayor")],
  q1=("Which two pairs of white keys have no black key between them?", "¿Qué dos pares de teclas blancas no tienen una tecla negra entre ellas?"),
  q2=("Does the scale sound finished if you stop on B? Why?", "¿Suena terminada la escala si te detienes en Si? ¿Por qué?"),
  tryit=dict(kind="notes", n=8, hint=("Write the eight notes of the C major scale, from C up to C.", "Escribe las ocho notas de la escala de Do mayor, de Do a Do.")),
  refl=("The note that feels most like home, and why:", "La nota que más se siente como casa, y por qué:"),
  links=[("Major scale — Wikipedia", W + "Major_scale"), ("Piano Roll — Chrome Music Lab", CML + "Piano-Roll/")]),

 dict(id="p4", t=("Octaves: same name, twice as fast", "Octavas: el mismo nombre, el doble de rápido"),
  blurb=("Play a C, then the next C up. It sounds like the same note, only higher. The higher string shakes twice as fast. That jump is an octave.",
         "Toca un Do y luego el siguiente Do hacia arriba. Suena como la misma nota, pero más aguda. La cuerda de arriba vibra el doble de rápido. Ese salto es una octava."),
  steps=["opair", "ohigher", "olower", "ofar"],
  do=[("Play a C. Count the white keys up to the next C: that is one octave.", "Toca un Do. Cuenta las teclas blancas hasta el siguiente Do: eso es una octava."),
      ("Play both C's, one after the other. Listen: same name, higher sound.", "Toca los dos Do, uno tras otro. Escucha: el mismo nombre, un sonido más agudo."),
      ("Press Higher ▶ and ◀ Lower. The small number on each C tells you which octave you are in.", "Pulsa Más agudo ▶ y ◀ Más grave. El número pequeño en cada Do te dice en qué octava estás."),
      ("Go all the way down and play a low note. Then go all the way up and play a high one.", "Baja del todo y toca una nota grave. Luego sube del todo y toca una aguda.")],
  kw=[("octave", "octava"), ("pitch", "altura"), ("frequency", "frecuencia")],
  q1=("A4 shakes 440 times a second. How many times does A5 shake? And A3?", "La4 vibra 440 veces por segundo. ¿Cuántas veces vibra La5? ¿Y La3?"),
  q2=("Why do you think notes an octave apart get the same name?", "¿Por qué crees que las notas separadas por una octava tienen el mismo nombre?"),
  tryit=dict(kind="table", hint=("Each octave up, the number of shakes a second doubles. Fill in the missing numbers.",
                                 "Con cada octava hacia arriba, el número de vibraciones por segundo se duplica. Completa los números que faltan."),
             cols=[("A2", "La2"), ("A3", "La3"), ("A4", "La4"), ("A5", "La5"), ("A6", "La6")],
             rows=[dict(label=("Shakes a second", "Vibraciones por segundo"), cells=[("in", 5), ("tx", ("220", "220")), ("tx", ("440", "440")), ("in", 5), ("in", 5)])]),
  refl=("Where I have heard very low or very high sounds outside music class:", "Dónde he oído sonidos muy graves o muy agudos fuera de la clase de música:"),
  links=[("Octave — Wikipedia", W + "Octave"), ("Pitch (music) — Wikipedia", W + "Pitch_(music)"), ("Strings — Chrome Music Lab", CML + "Strings/")]),

 dict(id="p5", t=("Soft and loud: piano and forte", "Suave y fuerte: piano y forte"),
  blurb=("The piano's full name is pianoforte, Italian for soft-loud. Press near the top of a key for a soft note and near the bottom for a loud one.",
         "El nombre completo del piano es pianoforte, que en italiano quiere decir suave-fuerte. Presiona cerca de la parte de arriba de una tecla para una nota suave, y cerca de la de abajo para una fuerte."),
  steps=["vsoft", "vloud", "vgrow"],
  do=[("Pick the Grand piano.", "Elige el Piano de cola."),
      ("Press a key near its top edge. Then press it near its bottom edge. Listen to the difference.", "Presiona una tecla cerca de su borde de arriba. Luego presiónala cerca del borde de abajo. Escucha la diferencia."),
      ("Play the same key four times, each one a little louder.", "Toca la misma tecla cuatro veces, cada una un poco más fuerte."),
      ("On a computer, click high or low on a key with the mouse. The letter keys always play medium.", "En la computadora, haz clic arriba o abajo en una tecla con el ratón. Las teclas de letras siempre tocan a medio volumen.")],
  kw=[("dynamics", "dinámica"), ("piano (soft)", "piano (suave)"), ("forte (loud)", "forte (fuerte)")],
  q1=("Besides getting louder, how did the grand piano change when you played hard?", "Además de sonar más fuerte, ¿cómo cambió el piano de cola cuando tocaste fuerte?"),
  q2=("When would a song want soft notes? When would it want loud ones?", "¿Cuándo querría una canción notas suaves? ¿Cuándo las querría fuertes?"),
  tryit=dict(kind="table", hint=("Musicians write p for soft, mf for medium and f for loud. Write one for each of your four taps.",
                                 "Los músicos escriben p para suave, mf para medio y f para fuerte. Escribe una para cada uno de tus cuatro toques."),
             cols=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
             rows=[dict(label=("Tap", "Toque"), cells=[("in", 2), ("in", 2), ("in", 2), ("in", 2)])]),
  refl=("A sound in my day that starts soft and gets loud:", "Un sonido de mi día que empieza suave y se hace fuerte:"),
  links=[("Dynamics (music) — Wikipedia", W + "Dynamics_(music)"), ("Dynamics — Britannica", "https://www.britannica.com/art/dynamics-music")]),

 dict(id="p6", t=("Make a chord with your hand", "Haz un acorde con tu mano"),
  blurb=("A chord is three or more notes played together. Play one key, skip one, play one, skip one, play one.",
         "Un acorde son tres o más notas tocadas juntas. Toca una tecla, salta una, toca una, salta una, toca una."),
  steps=["hceg", "hfac", "hgbd", "hpad"],
  do=[("Put your thumb on C, your middle finger on E and your little finger on G. Press all three together.", "Pon el pulgar en Do, el dedo medio en Mi y el meñique en Sol. Presiona las tres a la vez."),
      ("Move your whole hand so your thumb is on F: F, A, C. Then on G: G, B, D.", "Mueve toda la mano para que el pulgar quede en Fa: Fa, La, Do. Luego en Sol: Sol, Si, Re."),
      ("On a computer, hold A, D and G for C, E and G.", "En la computadora, mantén A, D y G para Do, Mi y Sol."),
      ("Set Key to C and Mood to Major. Tap pad 1. It is the same chord; the pad plays it for you.", "Pon el Tono en Do y el Ánimo en Mayor. Toca el pad 1. Es el mismo acorde; el pad lo toca por ti.")],
  kw=[("chord", "acorde"), ("triad", "tríada"), ("root", "fundamental")],
  q1=("Which note of C E G gives the chord its name?", "¿Qué nota de Do Mi Sol le da el nombre al acorde?"),
  q2=("Why do you think we skip a key between the notes?", "¿Por qué crees que saltamos una tecla entre las notas?"),
  tryit=dict(kind="keys", rows=[("C chord", "Acorde de Do"), ("F chord", "Acorde de Fa"), ("G chord", "Acorde de Sol")],
             hint=("Put an X under the three keys of each chord. A note can be in any octave.", "Pon una X debajo de las tres teclas de cada acorde. Una nota puede estar en cualquier octava.")),
  refl=("How my hand felt holding three keys at once:", "Cómo se sintió mi mano al sostener tres teclas a la vez:"),
  links=[("Chord (music) — Wikipedia", W + "Chord_(music)"), ("Chords — Chrome Music Lab", CML + "Chords/")]),

 dict(id="p7", t=("Major and minor: bright and moody", "Mayor y menor: brillante y melancólico"),
  blurb=("Move the middle note of a chord down one key, and bright turns moody. C E G is C major. C E♭ G is C minor.",
         "Baja una tecla la nota del medio de un acorde, y lo brillante se vuelve melancólico. Do Mi Sol es Do mayor. Do Mi♭ Sol es Do menor."),
  steps=["mjr", "mnr", "mmood", "mback"],
  do=[("Hold C, E and G. Listen.", "Mantén Do, Mi y Sol. Escucha."),
      ("Slide your middle finger to the black key just left of E. That is E♭. Hold C, E♭ and G.", "Desliza el dedo medio a la tecla negra justo a la izquierda de Mi. Esa es Mi♭. Mantén Do, Mi♭ y Sol."),
      ("Go back and forth between the two. Find one word for each sound.", "Ve y vuelve entre los dos. Busca una palabra para cada sonido."),
      ("Press Minor · moody and tap pad 1. Then press Major · bright and tap it again.", "Pulsa Menor · melancólico y toca el pad 1. Luego pulsa Mayor · brillante y tócalo otra vez.")],
  kw=[("major", "mayor"), ("minor", "menor"), ("mood", "ánimo")],
  q1=("Which one note changed between C major and C minor?", "¿Qué nota cambió entre Do mayor y Do menor?"),
  q2=("Name a moment in a movie or a game that needs a minor chord. Why?", "Nombra un momento de una película o un juego que necesite un acorde menor. ¿Por qué?"),
  tryit=dict(kind="keys", rows=[("C major", "Do mayor"), ("C minor", "Do menor")],
             hint=("Put an X under the three keys of each chord. E♭ is the same key as D♯. Circle the key that moved.",
                   "Pon una X debajo de las tres teclas de cada acorde. Mi♭ es la misma tecla que Re♯. Encierra en un círculo la tecla que se movió.")),
  refl=("A song or a sound I know that feels minor:", "Una canción o un sonido que conozco que se siente menor:"),
  links=[("Major and minor — Wikipedia", W + "Major_and_minor"), ("Chords — Chrome Music Lab", CML + "Chords/")]),

 dict(id="p8", t=("Six chords that fit: the pads", "Seis acordes que encajan: los pads"),
  blurb=("In every key, a handful of chords belong together. The pads show six of them, numbered by the step of the scale they start on. Pad 1 is home.",
         "En cada tono, unos cuantos acordes van juntos. Los pads muestran seis, numerados por el paso de la escala donde empiezan. El pad 1 es la casa."),
  steps=["p6", "p51", "pmin", "p4key"],
  do=[("Set Key to C and Mood to Major. Tap the pads from 1 to 6.", "Pon el Tono en Do y el Ánimo en Mayor. Toca los pads del 1 al 6."),
      ("Pads 1, 4 and 5 are major. Pads 2, 3 and 6 are minor. Listen for bright and moody.", "Los pads 1, 4 y 5 son mayores. Los pads 2, 3 y 6 son menores. Escucha lo brillante y lo melancólico."),
      ("Tap 5, then 1. Feel the pull back home. On a computer, the number keys 1 to 6 play the pads.", "Toca el 5 y luego el 1. Siente cómo jala de vuelta a casa. En la computadora, las teclas de números del 1 al 6 tocan los pads."),
      ("Pick a new Key. The names change, but the pads still fit together.", "Elige un Tono nuevo. Los nombres cambian, pero los pads siguen encajando.")],
  kw=[("home chord", "acorde casa"), ("scale step", "paso de la escala"), ("key", "tono")],
  q1=("In the key of C, which three pads are major?", "En el tono de Do, ¿qué tres pads son mayores?"),
  q2=("What does home feel like when you tap 5 and then 1?", "¿Cómo se siente la casa cuando tocas el 5 y luego el 1?"),
  tryit=dict(kind="table", hint=("Write the chord on each pad in the key of C. Pad 1 is done for you.", "Escribe el acorde de cada pad en el tono de Do. El pad 1 ya está."),
             cols=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"), ("6", "6")],
             rows=[dict(label=("Chord", "Acorde"), cells=[("tx", ("C", "Do")), ("in", 6), ("in", 6), ("in", 6), ("in", 6), ("in", 6)])]),
  refl=("The pad I liked best, and how it made me feel:", "El pad que más me gustó, y cómo me hizo sentir:"),
  links=[("Tonic (music) — Wikipedia", W + "Tonic_(music)"), ("Roman numeral analysis — Wikipedia", W + "Roman_numeral_analysis")]),

 dict(id="p9", t=("A chord pattern: one chord each bar", "Un patrón de acordes: un acorde por compás"),
  blurb=("Most songs repeat a short pattern of chords. Each chord lasts one bar: count 1 2 3 4, and the next chord comes in.",
         "Casi todas las canciones repiten un patrón corto de acordes. Cada acorde dura un compás: cuenta 1 2 3 4 y entra el siguiente acorde."),
  steps=["cpop", "cplay", "cround", "cswap"],
  do=[("Under Start from a chord pattern, pick Pop · 1 5 6 4.", "En Empieza con un patrón de acordes, elige Pop · 1 5 6 4."),
      ("Press Play the chords. Count 1 2 3 4 out loud. A new chord starts on every 1.", "Pulsa Tocar los acordes. Cuenta 1 2 3 4 en voz alta. Un acorde nuevo empieza en cada 1."),
      ("Watch your pattern: the chord playing now lights up, and so do its keys.", "Mira tu patrón: el acorde que suena ahora se ilumina, y también sus teclas."),
      ("While it plays, pick a different pattern and listen to the change.", "Mientras suena, elige otro patrón y escucha el cambio.")],
  kw=[("bar", "compás"), ("chord progression", "progresión de acordes"), ("loop", "bucle")],
  q1=("How many beats does each chord last?", "¿Cuántos pulsos dura cada acorde?"),
  q2=("Which chord in Pop · 1 5 6 4 sounds the saddest?", "¿Qué acorde de Pop · 1 5 6 4 suena más triste?"),
  tryit=dict(kind="table", hint=("Write the four chords of Pop · 1 5 6 4 in the key of C.", "Escribe los cuatro acordes de Pop · 1 5 6 4 en el tono de Do."),
             cols=[("Bar 1", "Compás 1"), ("Bar 2", "Compás 2"), ("Bar 3", "Compás 3"), ("Bar 4", "Compás 4")],
             rows=[dict(label=("Pad", "Pad"), cells=[("tx", ("1", "1")), ("tx", ("5", "5")), ("tx", ("6", "6")), ("tx", ("4", "4"))]),
                   dict(label=("Chord", "Acorde"), cells=[("in", 6), ("in", 6), ("in", 6), ("in", 6)])]),
  refl=("Songs repeat a lot. Why do you think that is?", "Las canciones se repiten mucho. ¿Por qué crees que es así?"),
  links=[("Chord progression — Wikipedia", W + "Chord_progression"), ("I–V–vi–IV progression — Wikipedia", W + "I%E2%80%93V%E2%80%93vi%E2%80%93IV_progression")]),

 dict(id="p10", t=("Four ways to play a chord", "Cuatro maneras de tocar un acorde"),
  blurb=("The same chords can feel calm, steady, flowing or bouncy. Change How the chords play and listen.",
         "Los mismos acordes pueden sentirse tranquilos, firmes, fluidos o saltarines. Cambia Cómo suenan los acordes y escucha."),
  steps=["rhold", "rpulse", "rbroken", "roff"],
  do=[("Pick any chord pattern and press Play the chords.", "Elige cualquier patrón de acordes y pulsa Tocar los acordes."),
      ("While it plays, change How the chords play. Try all four.", "Mientras suena, cambia Cómo suenan los acordes. Prueba las cuatro."),
      ("Broken plays the notes of each chord one at a time. Musicians call that an arpeggio.", "Arpegio toca las notas de cada acorde una por una. Así se llama: un arpegio."),
      ("Off-beat plays between the counts: 1 AND 2 AND. Clap on each AND.", "Contratiempo toca entre los conteos: 1 Y 2 Y. Aplaude en cada Y.")],
  kw=[("rhythm", "ritmo"), ("arpeggio", "arpegio"), ("off-beat", "contratiempo")],
  q1=("Which way of playing would you pick for a lullaby? Why?", "¿Qué manera de tocar elegirías para una canción de cuna? ¿Por qué?"),
  q2=("Which one makes you want to move? Why?", "¿Cuál te da ganas de moverte? ¿Por qué?"),
  tryit=dict(kind="table", hint=("Write one word for how each one feels.", "Escribe una palabra para cómo se siente cada una."),
             cols=[("One word", "Una palabra")],
             rows=[dict(label=("Hold", "Mantener"), cells=[("in", 18)]), dict(label=("Pulse", "Pulso"), cells=[("in", 18)]),
                   dict(label=("Broken", "Arpegio"), cells=[("in", 18)]), dict(label=("Off-beat", "Contratiempo"), cells=[("in", 18)])]),
  refl=("The way of playing that fits my mood today:", "La manera de tocar que va con mi ánimo hoy:"),
  links=[("Arpeggio — Wikipedia", W + "Arpeggio"), ("Syncopation — Wikipedia", W + "Syncopation"), ("Arpeggios — Chrome Music Lab", CML + "Arpeggios/")]),

 dict(id="p11", t=("Tempo: beats in a minute", "Tempo: pulsos en un minuto"),
  blurb=("Tempo is how many beats fit in one minute. At 60, one beat lasts exactly one second, like the second hand of a clock.",
         "El tempo es cuántos pulsos caben en un minuto. A 60, cada pulso dura exactamente un segundo, como la aguja de los segundos de un reloj."),
  steps=["t60", "t60p", "t120", "t120p"],
  do=[("Slide Tempo until it says 60 beats a minute.", "Desliza el Tempo hasta que diga 60 pulsos por minuto."),
      ("Pick a pattern, choose Pulse, and press Play. Watch a clock: one beat, one second.", "Elige un patrón, escoge Pulso y pulsa Tocar. Mira un reloj: un pulso, un segundo."),
      ("Slide Tempo to 120 and listen. Two beats for every second.", "Desliza el Tempo a 120 y escucha. Dos pulsos por cada segundo."),
      ("If Play with my drum beat is on, the drums set the tempo. Turn it off for this lesson.", "Si Tocar con mi ritmo de batería está activo, la batería pone el tempo. Desactívalo para esta lección.")],
  kw=[("tempo", "tempo"), ("beats a minute", "pulsos por minuto"), ("beat", "pulso")],
  q1=("At 120, how long does one beat last?", "A 120, ¿cuánto dura un pulso?"),
  q2=("A resting heart beats about 70 times a minute. Which tempo feels most like your heartbeat?", "Un corazón en reposo late unas 70 veces por minuto. ¿Qué tempo se parece más a tu latido?"),
  tryit=dict(kind="table", hint=("At 60, one beat lasts one second. Fill in the others.", "A 60, un pulso dura un segundo. Completa los demás."),
             cols=[("One beat lasts", "Un pulso dura")],
             rows=[dict(label=("Tempo 60", "Tempo 60"), cells=[("tx", ("1 second", "1 segundo"))]),
                   dict(label=("Tempo 120", "Tempo 120"), cells=[("in", 14)]),
                   dict(label=("Tempo 30", "Tempo 30"), cells=[("in", 14)])]),
  refl=("Music I like that is fast, and music I like that is slow:", "Música que me gusta que es rápida, y música que me gusta que es lenta:"),
  links=[("Tempo — Wikipedia", W + "Tempo"), ("Beat and tempo — Ableton Learning Music", "https://learningmusic.ableton.com/make-beats/beat-and-tempo.html")]),

 dict(id="p12", t=("Change the key", "Cambia el tono"),
  blurb=("A key is the home note a song is built on. Change the key, and every chord moves together. It is the same song, just higher or lower.",
         "El tono es la nota casa sobre la que se construye una canción. Cambia el tono, y todos los acordes se mueven juntos. Es la misma canción, solo más aguda o más grave."),
  steps=["kpat", "kg", "k3", "klive"],
  do=[("Set Key to C. Pick Pop · 1 5 6 4 and press Play.", "Pon el Tono en Do. Elige Pop · 1 5 6 4 y pulsa Tocar."),
      ("Change Key to G. Look at the chord names: every one moved.", "Cambia el Tono a Sol. Mira los nombres de los acordes: todos se movieron."),
      ("Try a third key. Which key fits your voice best?", "Prueba un tercer tono. ¿Qué tono le queda mejor a tu voz?"),
      ("Change the key while the music plays and hear it jump.", "Cambia el tono mientras suena la música y oye cómo salta.")],
  kw=[("key", "tono"), ("transpose", "transportar"), ("home note", "nota casa")],
  q1=("The numbers stayed 1 5 6 4, but the names changed. Why?", "Los números siguieron siendo 1 5 6 4, pero los nombres cambiaron. ¿Por qué?"),
  q2=("Why might a singer ask for a different key?", "¿Por qué un cantante pediría otro tono?"),
  tryit=dict(kind="table", hint=("Pop · 1 5 6 4 in C is done. Write it in G.", "Pop · 1 5 6 4 en Do ya está. Escríbelo en Sol."),
             cols=[("1", "1"), ("5", "5"), ("6", "6"), ("4", "4")],
             rows=[dict(label=("In C", "En Do"), cells=[("tx", ("C", "Do")), ("tx", ("G", "Sol")), ("tx", ("Am", "La m")), ("tx", ("F", "Fa"))]),
                   dict(label=("In G", "En Sol"), cells=[("in", 6), ("in", 6), ("in", 6), ("in", 6)])]),
  refl=("The key I liked best, and why:", "El tono que más me gustó, y por qué:"),
  links=[("Key (music) — Wikipedia", W + "Key_(music)"), ("Transposition (music) — Wikipedia", W + "Transposition_(music)")]),

 dict(id="p13", t=("Make your own pattern", "Haz tu propio patrón"),
  blurb=("Press Make my own and tap the pads in any order. You are writing the chords of a song.",
         "Pulsa Hacer el mío y toca los pads en el orden que quieras. Estás escribiendo los acordes de una canción."),
  steps=["own1", "own4", "ownhome", "ownplay"],
  do=[("Press Clear, then Make my own.", "Pulsa Borrar y luego Hacer el mío."),
      ("Tap four pads in the order you like. They appear under Your chord pattern.", "Toca cuatro pads en el orden que quieras. Aparecen en Tu patrón de acordes."),
      ("Try ending on pad 1. Then try ending on pad 5. Which one sounds finished?", "Prueba terminar en el pad 1. Luego prueba terminar en el pad 5. ¿Cuál suena terminado?"),
      ("Press Play and listen to your pattern go round.", "Pulsa Tocar y escucha tu patrón dar vueltas.")],
  kw=[("compose", "componer"), ("ending", "final"), ("home chord", "acorde casa")],
  q1=("Why does ending on pad 1 sound finished?", "¿Por qué terminar en el pad 1 suena terminado?"),
  q2=("What changed when you moved one chord to a new place?", "¿Qué cambió cuando moviste un acorde a otro lugar?"),
  tryit=dict(kind="table", hint=("Write your pattern: the pad number and the chord name for each bar.", "Escribe tu patrón: el número de pad y el nombre del acorde de cada compás."),
             cols=[(str(i), str(i)) for i in range(1, 9)],
             rows=[dict(label=("Pad", "Pad"), cells=[("in", 1)] * 8), dict(label=("Chord", "Acorde"), cells=[("in", 6)] * 8)]),
  refl=("A name for my pattern, and why:", "Un nombre para mi patrón, y por qué:"),
  links=[("Song Maker — Chrome Music Lab", CML + "Song-Maker/"), ("Cadence — Wikipedia", W + "Cadence")]),

 dict(id="p14", t=("The pedal: let it ring", "El pedal: déjalo sonar"),
  blurb=("On a real piano, the right pedal lifts felt dampers off the strings, so notes keep ringing after you let go. Here it is the Hold notes button, or Shift on a computer.",
         "En un piano real, el pedal derecho levanta los apagadores de fieltro de las cuerdas, y las notas siguen sonando cuando sueltas. Aquí es el botón Mantener notas, o Shift en la computadora."),
  steps=["son", "sring", "soff"],
  do=[("Play a few keys without the pedal. Each note stops when you let go.", "Toca unas teclas sin el pedal. Cada nota para cuando sueltas."),
      ("Press Hold notes (pedal). Play C, E, G, C, E going up. They all keep ringing.", "Pulsa Mantener notas (pedal). Toca Do, Mi, Sol, Do, Mi subiendo. Todas siguen sonando."),
      ("Press Hold notes again to lift the pedal. The sound stops.", "Pulsa otra vez Mantener notas para soltar el pedal. El sonido para."),
      ("On a computer, hold Shift for the pedal.", "En la computadora, mantén Shift para el pedal.")],
  kw=[("sustain pedal", "pedal de resonancia"), ("damper", "apagador"), ("ring", "resonar")],
  q1=("What happens if you keep the pedal down while you change chords?", "¿Qué pasa si dejas el pedal abajo mientras cambias de acorde?"),
  q2=("Why do you think real pianos have dampers at all?", "¿Por qué crees que los pianos reales tienen apagadores?"),
  tryit=dict(kind="table", hint=("Describe the sound each way.", "Describe el sonido de cada manera."),
             cols=[("What I heard", "Lo que oí")],
             rows=[dict(label=("Pedal off", "Sin pedal"), cells=[("in", 40)]), dict(label=("Pedal on", "Con pedal"), cells=[("in", 40)])]),
  refl=("A place where sound keeps ringing, like the pedal (a gym, a stairwell, a church):", "Un lugar donde el sonido sigue resonando, como con el pedal (un gimnasio, una escalera, una iglesia):"),
  links=[("Sustain pedal — Wikipedia", W + "Sustain_pedal"), ("Piano — Wikipedia", W + "Piano")]),

 dict(id="p15", t=("Eight sounds: hammers, tines, reeds and pipes", "Ocho sonidos: martillos, varillas, lengüetas y tubos"),
  blurb=("A grand piano hits strings with felt hammers. An electric piano hits metal tines or reeds. An organ blows air through pipes or spins wheels. Same notes, different color. That color is called timbre.",
         "Un piano de cola golpea cuerdas con martillos de fieltro. Un piano eléctrico golpea varillas o lengüetas de metal. Un órgano sopla aire por tubos o hace girar ruedas. Las mismas notas, otro color. Ese color se llama timbre."),
  steps=["tgrand", "tep", "torg", "tall"],
  do=[("Pick a chord pad you like. Keep tapping it as you change the Instrument.", "Elige un pad de acorde que te guste. Sigue tocándolo mientras cambias el Instrumento."),
      ("Listen to how each sound starts and how it fades.", "Escucha cómo empieza cada sonido y cómo se apaga."),
      ("Hold a key on the Grand piano, then on an organ. Which one fades? Which one keeps going?", "Mantén una tecla con el Piano de cola y luego con un órgano. ¿Cuál se apaga? ¿Cuál sigue?"),
      ("Open Meet the sounds in the Go to menu to read how each one works.", "Abre Conoce los sonidos en el menú Ir a para leer cómo funciona cada uno.")],
  kw=[("timbre", "timbre"), ("hammer", "martillo"), ("decay", "caída")],
  q1=("Why does a piano note fade, but an organ note does not?", "¿Por qué una nota de piano se apaga y una de órgano no?"),
  q2=("Which sound would you pick for a scary scene? Which for a party?", "¿Qué sonido elegirías para una escena de miedo? ¿Y para una fiesta?"),
  tryit=dict(kind="table", hint=("How each sound is made is filled in. Write one word for its color.", "Ya está cómo se hace cada sonido. Escribe una palabra para su color."),
             cols=[("How it is made", "Cómo se hace"), ("One word for its color", "Una palabra para su color")],
             rows=[dict(label=("Grand piano", "Piano de cola"), cells=[("tx", ("Felt hammers hit long strings", "Martillos de fieltro golpean cuerdas largas")), ("in", 18)]),
                   dict(label=("Upright piano", "Piano vertical"), cells=[("tx", ("Hammers hit strings that stand up tall", "Martillos golpean cuerdas que están de pie")), ("in", 18)]),
                   dict(label=("Honky-tonk piano", "Piano honky-tonk"), cells=[("tx", ("An upright, a little out of tune with itself", "Un vertical, un poco desafinado consigo mismo")), ("in", 18)]),
                   dict(label=("Electric piano · warm", "Piano eléctrico · cálido"), cells=[("tx", ("Hammers hit thin metal tines", "Martillos golpean varillas delgadas de metal")), ("in", 18)]),
                   dict(label=("Electric piano · bright", "Piano eléctrico · brillante"), cells=[("tx", ("Hammers hit flat metal reeds", "Martillos golpean lengüetas planas de metal")), ("in", 18)]),
                   dict(label=("'80s electric piano", "Piano eléctrico de los 80"), cells=[("tx", ("A computer chip does the math (FM)", "Un chip de computadora hace las cuentas (FM)")), ("in", 18)]),
                   dict(label=("Rock and jazz organ", "Órgano de rock y jazz"), cells=[("tx", ("Spinning wheels near magnets", "Ruedas que giran cerca de imanes")), ("in", 18)]),
                   dict(label=("Church organ", "Órgano de iglesia"), cells=[("tx", ("Air blown through pipes", "Aire que sopla por tubos")), ("in", 18)])]),
  refl=("The sound I liked best, and what I would play with it:", "El sonido que más me gustó, y qué tocaría con él:"),
  links=[("Timbre — Wikipedia", W + "Timbre"), ("Electric piano — Wikipedia", W + "Electric_piano"), ("Hammond organ — Wikipedia", W + "Hammond_organ")]),

 dict(id="p16", t=("Play along: follow the lit keys", "Toca encima: sigue las teclas iluminadas"),
  blurb=("While the chords play, the keys of each chord light up. Any lit key fits. Play them in your own order and you are making up a melody.",
         "Mientras suenan los acordes, se iluminan las teclas de cada acorde. Cualquier tecla iluminada encaja. Tócalas en tu propio orden y estás inventando una melodía."),
  steps=["lplay", "llit", "llit8", "lchange"],
  do=[("Pick a pattern, choose Hold · one long chord, and press Play. Slow the tempo down if you like.", "Elige un patrón, escoge Mantener · un acorde largo y pulsa Tocar. Baja el tempo si quieres."),
      ("Watch the keyboard. The keys of the chord playing now light up.", "Mira el teclado. Se iluminan las teclas del acorde que suena ahora."),
      ("Play the lit keys one at a time, in any order. Borrow the rhythm of a song you know.", "Toca las teclas iluminadas una a la vez, en cualquier orden. Toma prestado el ritmo de una canción que conozcas."),
      ("When the chord changes, the lights move. Follow them.", "Cuando cambia el acorde, las luces se mueven. Síguelas.")],
  kw=[("melody", "melodía"), ("improvise", "improvisar"), ("chord tone", "nota del acorde")],
  q1=("What happened when you played a key that was not lit?", "¿Qué pasó cuando tocaste una tecla que no estaba iluminada?"),
  q2=("How did you decide which lit key to play next?", "¿Cómo decidiste qué tecla iluminada tocar después?"),
  tryit=dict(kind="notes", n=8, hint=("Write the eight notes of your melody, in order.", "Escribe las ocho notas de tu melodía, en orden.")),
  refl=("How it felt to make up music on the spot:", "Cómo se sintió inventar música en el momento:"),
  links=[("Musical improvisation — Wikipedia", W + "Musical_improvisation"), ("Melody — Wikipedia", W + "Melody"), ("Melody Maker — Chrome Music Lab", CML + "Melody-Maker/")]),

 dict(id="p17", t=("Play with the drum machine", "Toca con la caja de ritmos"),
  blurb=("Make a beat on the drum machine and press Send to the turntables. The piano finds it too, and plays your chords in time with it.",
         "Haz un ritmo en la caja de ritmos y pulsa Enviar a los platos. El piano también lo encuentra y toca tus acordes a tiempo con él."),
  steps=["dsend", "don", "dplay", "dpulse"],
  do=[("Open the drum machine. Pick a beat in Start from a beat, or make your own.", "Abre la caja de ritmos. Elige un ritmo en Empieza con un ritmo, o haz el tuyo."),
      ("Press Send to the turntables. Then come back to the piano.", "Pulsa Enviar a los platos. Luego vuelve al piano."),
      ("Under Tempo, press Play with my drum beat. Now the drums set the tempo.", "Debajo del Tempo, pulsa Tocar con mi ritmo de batería. Ahora la batería pone el tempo."),
      ("Pick a pattern and press Play. Try each way the chords can play.", "Elige un patrón y pulsa Tocar. Prueba cada manera en que pueden sonar los acordes.")],
  kw=[("tempo", "tempo"), ("in time", "a tiempo"), ("swing", "swing")],
  q1=("Which way of playing the chords fit your beat best?", "¿Qué manera de tocar los acordes le quedó mejor a tu ritmo?"),
  q2=("Why does the Tempo slider stop moving when the drums are on?", "¿Por qué el deslizador del Tempo deja de moverse cuando la batería está activa?"),
  tryit=dict(kind="table", hint=("Write down what you put together.", "Anota lo que armaste."),
             cols=[("Mine", "El mío")],
             rows=[dict(label=("My drum beat", "Mi ritmo de batería"), cells=[("in", 40)]), dict(label=("Its tempo", "Su tempo"), cells=[("in", 8)]),
                   dict(label=("My chord pattern", "Mi patrón de acordes"), cells=[("in", 40)]), dict(label=("How the chords play", "Cómo suenan los acordes"), cells=[("in", 30)])]),
  refl=("What changed when the piano and the drums played together:", "Qué cambió cuando el piano y la batería tocaron juntos:"),
  links=[("Drum machine — Wikipedia", W + "Drum_machine"), ("Beat (music) — Wikipedia", W + "Beat_(music)")]),

 dict(id="p18", t=("Twelve-bar blues", "Blues de doce compases"),
  blurb=("The blues grew in the American South around 1900, from African American work songs and spirituals. Twelve bars, three chords, and a seventh in every one.",
         "El blues nació en el sur de Estados Unidos hacia 1900, de los cantos de trabajo y los espirituales afroamericanos. Doce compases, tres acordes y una séptima en cada uno."),
  steps=["bpick", "borg", "bpulse", "b12"],
  do=[("Pick Blues · 12 bars and the Rock and jazz organ.", "Elige Blues · 12 compases y el Órgano de rock y jazz."),
      ("Set How the chords play to Pulse and press Play.", "Pon Cómo suenan los acordes en Pulso y pulsa Tocar."),
      ("Count the bars on your fingers, 1 to 12. Notice where the chord changes.", "Cuenta los compases con los dedos, del 1 al 12. Fíjate dónde cambia el acorde."),
      ("Bars 1 to 4 stay home. Bar 5 moves to the 4 chord. Bar 9 climbs to the 5.", "Los compases 1 al 4 se quedan en casa. El compás 5 va al acorde 4. El compás 9 sube al 5.")],
  kw=[("blues", "blues"), ("twelve-bar", "doce compases"), ("seventh chord", "acorde de séptima")],
  q1=("Which bars use the home chord?", "¿Qué compases usan el acorde casa?"),
  q2=("The blues often tells a story of trouble and hope. How do the chords help tell it?", "El blues muchas veces cuenta una historia de problemas y esperanza. ¿Cómo ayudan los acordes a contarla?"),
  tryit=dict(kind="table", hint=("Write the chord for each bar of the blues in C. Use C7, F7 and G7.", "Escribe el acorde de cada compás del blues en Do. Usa Do7, Fa7 y Sol7."),
             cols=[(str(i), str(i)) for i in range(1, 13)],
             rows=[dict(label=("Chord", "Acorde"), cells=[("in", 5)] * 12)]),
  refl=("A feeling I would sing about in a blues:", "Un sentimiento sobre el que cantaría en un blues:"),
  links=[("Twelve-bar blues — Wikipedia", W + "Twelve-bar_blues"), ("Blues — Wikipedia", W + "Blues")]),

 dict(id="p19", t=("Seventh chords: jazz 2-5-1", "Acordes de séptima: el 2-5-1 del jazz"),
  blurb=("Stack one more note on a chord, skipping a key again, and you get a seventh chord. Jazz is built on them, and 2-5-1 is its favorite way home.",
         "Pon una nota más encima de un acorde, saltando otra tecla, y tienes un acorde de séptima. El jazz se construye con ellos, y el 2-5-1 es su camino favorito a casa."),
  steps=["jpick", "jep", "jplay", "jhand"],
  do=[("Pick Jazz · 2 5 1 and Electric piano · warm.", "Elige Jazz · 2 5 1 y Piano eléctrico · cálido."),
      ("Set How the chords play to Broken and press Play. Listen for four different notes in each chord.", "Pon Cómo suenan los acordes en Arpegio y pulsa Tocar. Escucha cuatro notas distintas en cada acorde."),
      ("Stop. Hold D, F, A and C with four fingers. That is the 2 chord, D minor 7.", "Para. Mantén Re, Fa, La y Do con cuatro dedos. Ese es el acorde 2, Re menor 7."),
      ("On a computer, hold S, F, H and K.", "En la computadora, mantén S, F, H y K.")],
  kw=[("seventh chord", "acorde de séptima"), ("jazz", "jazz"), ("2-5-1", "2-5-1")],
  q1=("How does a seventh chord sound different from a three-note chord?", "¿En qué se diferencia el sonido de un acorde de séptima del de un acorde de tres notas?"),
  q2=("In 2-5-1, which chord feels like arriving home?", "En el 2-5-1, ¿qué acorde se siente como llegar a casa?"),
  tryit=dict(kind="keys", rows=[("D minor 7", "Re menor 7"), ("G7", "Sol7"), ("C major 7", "Do maj7")],
             hint=("Put an X under the four keys of each chord. A note can be in any octave.", "Pon una X debajo de las cuatro teclas de cada acorde. Una nota puede estar en cualquier octava.")),
  refl=("Where I have heard jazz chords (a movie, a café, a game):", "Dónde he oído acordes de jazz (una película, un café, un juego):"),
  links=[("Seventh chord — Wikipedia", W + "Seventh_chord"), ("ii–V–I progression — Wikipedia", W + "Ii%E2%80%93V%E2%80%93I_progression")]),

 dict(id="p20", t=("1987 or 2026? Sound becomes numbers", "¿1987 o 2026? El sonido se vuelve números"),
  blurb=("A computer keeps sound as a long list of numbers. The 1987 samplers kept fewer, rougher numbers, and that is the crunch. Turn the Sound dial and hear it.",
         "Una computadora guarda el sonido como una lista larga de números. Los samplers de 1987 guardaban menos números, más ásperos, y ese es el crujido. Gira el dial de Sonido y escúchalo."),
  steps=["e87", "ehigh", "e26", "emid"],
  do=[("Pick the Grand piano. Turn the Sound dial all the way left, to 1987.", "Elige el Piano de cola. Gira el dial de Sonido del todo a la izquierda, a 1987."),
      ("Press Higher ▶ until you reach the top. Play the high keys and listen for a fizz.", "Pulsa Más agudo ▶ hasta llegar arriba. Toca las teclas agudas y escucha el chisporroteo."),
      ("Turn the dial to 2026 and play the same keys.", "Gira el dial a 2026 y toca las mismas teclas."),
      ("Find the spot you like best. Many producers like a little crunch.", "Busca el punto que más te guste. A muchos productores les gusta un poco de crujido.")],
  kw=[("sample", "muestra"), ("sampling rate", "frecuencia de muestreo"), ("bit depth", "profundidad de bits")],
  q1=("Why is the crunch easiest to hear on the highest notes?", "¿Por qué el crujido se oye más en las notas más agudas?"),
  q2=("Where did you set the dial for your music? Why?", "¿Dónde pusiste el dial para tu música? ¿Por qué?"),
  tryit=dict(kind="table", hint=("The numbers are filled in. Write what you heard on each side of the dial.", "Los números ya están. Escribe lo que oíste en cada lado del dial."),
             cols=[("Numbers a second", "Números por segundo"), ("Steps of loudness", "Escalones de volumen"), ("What I heard", "Lo que oí")],
             rows=[dict(label=("1987", "1987"), cells=[("tx", ("26,040", "26 040")), ("tx", ("4,096", "4096")), ("in", 30)]),
                   dict(label=("2026 (CD)", "2026 (CD)"), cells=[("tx", ("44,100", "44 100")), ("tx", ("65,536", "65 536")), ("in", 30)])]),
  refl=("An old sound I like because it is a little rough:", "Un sonido viejo que me gusta porque es un poco áspero:"),
  links=[("Sampling (signal processing) — Wikipedia", W + "Sampling_(signal_processing)"), ("Audio bit depth — Wikipedia", W + "Audio_bit_depth"), ("E-mu SP-1200 — Wikipedia", W + "E-mu_SP-1200")]),

 dict(id="p21", t=("Make a track, then hand it in", "Haz una pista y entrégala"),
  blurb=("Choose a sound, a key and a pattern that feel like you. Send it to the turntables, give it a name, and hand in the worksheet.",
         "Elige un sonido, un tono y un patrón que se sientan tuyos. Mándalo a los platos, ponle nombre y entrega la hoja."),
  steps=["fown", "fname", "fsend", "fsheet"],
  do=[("Choose an Instrument, a Key and a Mood.", "Elige un Instrumento, un Tono y un Ánimo."),
      ("Press Make my own and build a pattern of four to eight chords. End on pad 1 if you want it to feel finished.", "Pulsa Hacer el mío y arma un patrón de cuatro a ocho acordes. Termina en el pad 1 si quieres que se sienta terminado."),
      ("Pick how the chords play and a tempo. Add your drum beat if you made one.", "Elige cómo suenan los acordes y un tempo. Agrega tu ritmo de batería si hiciste uno."),
      ("Type a name in the lesson card. Press Send to the turntables, then open the turntables and play it.", "Escribe un nombre en la tarjeta de la lección. Pulsa Enviar a los platos, luego abre los platos y tócalo.")],
  kw=[("track", "pista"), ("composer", "compositor"), ("arrangement", "arreglo")],
  q1=("Why did you pick that sound and that key?", "¿Por qué elegiste ese sonido y ese tono?"),
  q2=("What would you change if you made it again?", "¿Qué cambiarías si lo hicieras otra vez?"),
  tryit=dict(kind="table", hint=("Write down your track so you can play it again.", "Anota tu pista para poder tocarla otra vez."),
             cols=[("Mine", "La mía")],
             rows=[dict(label=("Name", "Nombre"), cells=[("in", 40)]), dict(label=("Instrument", "Instrumento"), cells=[("in", 40)]),
                   dict(label=("Key and mood", "Tono y ánimo"), cells=[("in", 30)]), dict(label=("Tempo", "Tempo"), cells=[("in", 8)]),
                   dict(label=("How the chords play", "Cómo suenan los acordes"), cells=[("in", 30)]), dict(label=("Chords, bar by bar", "Acordes, compás por compás"), cells=[("in", 60)])]),
  refl=("What makes me proud of this track:", "Lo que más me enorgullece de esta pista:"),
  links=[("Song structure — Wikipedia", W + "Song_structure"), ("Musical composition — Wikipedia", W + "Musical_composition")]),
]

# ── the seventeen songs we make together (lessons 22–38) ───────────────────────────────────────
# key: 0 = C … 11 = B. pads: pad numbers in the song's mood (Make my own). preset: a pattern in the menu.
# mel: lines played on the keys, as note numbers 0–11 (C = 0), checked in order. era: Sound dial toward 1987.
SONGS = [
 dict(n=22, t=("Frère Jacques · a round", "Frère Jacques (Martinillo) · un canon"), key=0, minor=False, bpm=100, sound="grand", rhythm="pulse", pads=[1],
  mel=[(("Line 1: C D E C, two times", "Línea 1: Do Re Mi Do, dos veces"), [0, 2, 4, 0, 0, 2, 4, 0]),
       (("Line 2: E F G, two times", "Línea 2: Mi Fa Sol, dos veces"), [4, 5, 7, 4, 5, 7]),
       (("Line 3: G A G F E C, two times", "Línea 3: Sol La Sol Fa Mi Do, dos veces"), [7, 9, 7, 5, 4, 0, 7, 9, 7, 5, 4, 0]),
       (("Line 4: C G C, two times (that G is the low one)", "Línea 4: Do Sol Do, dos veces (ese Sol es el grave)"), [0, 7, 0, 0, 7, 0])],
  blurb=("A French song from the 1700s, sung all over the world. In Spanish it is Martinillo. It is a round: groups start the same tune at different times, and it still fits together.",
         "Una canción francesa del siglo XVIII que se canta en todo el mundo. En español es Martinillo. Es un canon: los grupos empiezan la misma melodía en momentos distintos, y aun así encaja."),
  tog=("Make three groups. Group 1 starts singing. Group 2 starts when group 1 reaches line 2, then group 3. The piano keeps everyone together.",
       "Hagan tres grupos. El grupo 1 empieza a cantar. El grupo 2 empieza cuando el grupo 1 llega a la línea 2, y luego el grupo 3. El piano mantiene a todos juntos."),
  kw=[("round", "canon"), ("melody", "melodía"), ("harmony", "armonía")],
  q1=("Most notes in the tune are C, E or G. Why does that let the whole song fit over one chord?", "Casi todas las notas de la melodía son Do, Mi o Sol. ¿Por qué eso deja que toda la canción quepa sobre un solo acorde?"),
  q2=("What did it sound like when all three groups sang at once?", "¿Cómo sonó cuando los tres grupos cantaron a la vez?"),
  links=[("Frère Jacques — Wikipedia", W + "Fr%C3%A8re_Jacques"), ("Round (music) — Wikipedia", W + "Round_(music)")]),

 dict(n=23, t=("Ode to Joy", "Himno de la alegría"), key=0, minor=False, bpm=100, sound="grand", rhythm="pulse", pads=[1, 5, 1, 5, 1, 5, 1, 1],
  mel=[(("Line 1: E E F G G F E D", "Línea 1: Mi Mi Fa Sol Sol Fa Mi Re"), [4, 4, 5, 7, 7, 5, 4, 2]),
       (("Line 2: C C D E E D D", "Línea 2: Do Do Re Mi Mi Re Re"), [0, 0, 2, 4, 4, 2, 2]),
       (("Line 3: line 1 again, then the ending: C C D E D C C", "Línea 3: otra vez la línea 1, y el final: Do Do Re Mi Re Do Do"), [0, 0, 2, 4, 2, 0, 0])],
  blurb=("Ludwig van Beethoven wrote this tune for his Ninth Symphony in 1824, when he could hardly hear at all. Today it is the anthem of Europe.",
         "Ludwig van Beethoven escribió esta melodía para su Novena Sinfonía en 1824, cuando ya casi no podía oír. Hoy es el himno de Europa."),
  tog=("One group plays the chords on the piano. Everyone else hums or sings the tune, one note for each beat.",
       "Un grupo toca los acordes en el piano. Todos los demás tararean o cantan la melodía, una nota por cada pulso."),
  kw=[("melody", "melodía"), ("symphony", "sinfonía"), ("anthem", "himno")],
  q1=("Which notes of the tune are also in the C chord: C, E and G?", "¿Qué notas de la melodía también están en el acorde de Do: Do, Mi y Sol?"),
  q2=("Beethoven could hardly hear when he wrote this. How do you think he heard the music in his head?", "Beethoven casi no podía oír cuando escribió esto. ¿Cómo crees que oía la música en su cabeza?"),
  links=[("Ode to Joy — Wikipedia", W + "Ode_to_Joy"), ("Symphony No. 9 (Beethoven) — Wikipedia", W + "Symphony_No._9_(Beethoven)")]),

 dict(n=24, t=("When the Saints Go Marching In", "When the Saints Go Marching In (Cuando los santos marchan)"), key=0, minor=False, bpm=112, sound="honky", rhythm="pulse", pads=[1, 1, 1, 5, 1, 4, 5, 1],
  mel=[(("Line 1: C E F G, two times", "Línea 1: Do Mi Fa Sol, dos veces"), [0, 4, 5, 7, 0, 4, 5, 7]),
       (("Line 2: C E F G E C E D", "Línea 2: Do Mi Fa Sol Mi Do Mi Re"), [0, 4, 5, 7, 4, 0, 4, 2]),
       (("Line 3: E E D C C E G G F", "Línea 3: Mi Mi Re Do Do Mi Sol Sol Fa"), [4, 4, 2, 0, 0, 4, 7, 7, 5]),
       (("Line 4: E F G E C D C", "Línea 4: Mi Fa Sol Mi Do Re Do"), [4, 5, 7, 4, 0, 2, 0])],
  blurb=("A Black American spiritual that became the marching song of New Orleans jazz. Brass bands still play it in the city's street parades.",
         "Un espiritual afroamericano que se volvió la canción de marcha del jazz de Nueva Orleans. Las bandas de metales todavía la tocan en los desfiles de la ciudad."),
  tog=("Everyone marches in place and sings. Wave a hand each time the chord changes.",
       "Todos marchan en su lugar y cantan. Saluden con la mano cada vez que cambia el acorde."),
  kw=[("spiritual", "espiritual"), ("march", "marcha"), ("brass band", "banda de metales")],
  q1=("Why does a marching song need a steady pulse?", "¿Por qué una canción de marcha necesita un pulso firme?"),
  q2=("The honky-tonk piano is a little out of tune. How does that change the feel?", "El piano honky-tonk está un poco desafinado. ¿Cómo cambia eso la sensación?"),
  links=[("When the Saints Go Marching In — Wikipedia", W + "When_the_Saints_Go_Marching_In"), ("Second line (parades) — Wikipedia", W + "Second_line_(parades)")]),

 dict(n=25, t=("Canon", "Canon"), key=2, minor=False, bpm=66, sound="church", rhythm="broken", preset="canon",
  blurb=("Johann Pachelbel, a church organist in Germany, wrote this canon around 1700. Its eight chords go round and round under new tunes, and pop songs still borrow them.",
         "Johann Pachelbel, organista de iglesia en Alemania, escribió este canon hacia 1700. Sus ocho acordes dan vueltas y vueltas debajo de melodías nuevas, y las canciones pop todavía los toman prestados."),
  tog=("Sit still and listen to the eight chords go round three times. Then two volunteers hum lit notes on top.",
       "Siéntense quietos y escuchen los ocho acordes dar tres vueltas. Luego dos voluntarios tararean notas iluminadas encima."),
  kw=[("canon", "canon"), ("organ", "órgano"), ("arpeggio", "arpegio")],
  q1=("How many chords go by before the pattern starts again?", "¿Cuántos acordes pasan antes de que el patrón empiece otra vez?"),
  q2=("Why do you think songwriters still borrow these chords more than 300 years later?", "¿Por qué crees que los compositores todavía toman estos acordes más de 300 años después?"),
  links=[("Pachelbel's Canon — Wikipedia", W + "Pachelbel%27s_Canon"), ("Pipe organ — Wikipedia", W + "Pipe_organ")]),

 dict(n=26, t=("Blues on the organ", "Blues con órgano"), key=5, minor=False, bpm=96, sound="organ", rhythm="offbeat", preset="blues",
  blurb=("In the 1950s and 60s, jazz and soul players brought the blues to the Hammond organ, a heavy keyboard with spinning wheels inside that make its tone.",
         "En los años 50 y 60, músicos de jazz y soul llevaron el blues al órgano Hammond, un teclado pesado con ruedas que giran por dentro y hacen su sonido."),
  tog=("Everyone snaps on 2 and 4. Count the twelve bars out loud, 1 to 12, then start again.",
       "Todos chasquean los dedos en 2 y 4. Cuenten los doce compases en voz alta, del 1 al 12, y vuelvan a empezar."),
  kw=[("blues", "blues"), ("Hammond organ", "órgano Hammond"), ("off-beat", "contratiempo")],
  q1=("In which bar does the second chord first come in?", "¿En qué compás entra por primera vez el segundo acorde?"),
  q2=("Which bar feels like a question, and which feels like the answer?", "¿Qué compás se siente como una pregunta, y cuál como la respuesta?"),
  links=[("Hammond organ — Wikipedia", W + "Hammond_organ"), ("Twelve-bar blues — Wikipedia", W + "Twelve-bar_blues")]),

 dict(n=27, t=("Doo-wop ballad", "Balada doo-wop"), key=3, minor=False, bpm=76, sound="upright", rhythm="broken", preset="fifties",
  blurb=("In the 1950s, teenagers in US cities sang in groups on street corners, with their voices in place of instruments. Their favorite chords went 1 6 4 5.",
         "En los años 50, adolescentes de las ciudades de Estados Unidos cantaban en grupo en las esquinas, con sus voces en lugar de instrumentos. Sus acordes favoritos iban 1 6 4 5."),
  tog=("Make four groups, one for each chord. Each group sings a soft 'ooh' while its chord plays.",
       "Hagan cuatro grupos, uno por acorde. Cada grupo canta un 'uh' suave mientras suena su acorde."),
  kw=[("doo-wop", "doo-wop"), ("harmony", "armonía"), ("ballad", "balada")],
  q1=("Which of the four chords sounds most like home?", "¿Cuál de los cuatro acordes suena más como casa?"),
  q2=("How does singing a chord together feel different from playing it?", "¿En qué se siente distinto cantar un acorde juntos y tocarlo?"),
  links=[("Doo-wop — Wikipedia", W + "Doo-wop"), ("Chord progression — Wikipedia", W + "Chord_progression")]),

 dict(n=28, t=("Highlife", "Highlife"), key=9, minor=False, bpm=120, sound="epreed", rhythm="broken", pads=[1, 4, 1, 5],
  blurb=("Highlife began in Ghana in the early 1900s, when dance bands mixed local rhythms with brass and guitars. Its bright, rolling chords spread across West Africa.",
         "El highlife nació en Ghana a principios del siglo XX, cuando las bandas de baile mezclaron ritmos locales con metales y guitarras. Sus acordes brillantes y ondulantes se extendieron por África occidental."),
  tog=("Everyone steps side to side, one step for each beat. A few learners clap between the steps.",
       "Todos dan un paso al lado en cada pulso. Algunos aplauden entre los pasos."),
  kw=[("highlife", "highlife"), ("West Africa", "África occidental"), ("dance band", "banda de baile")],
  q1=("The pattern goes 1 4 1 5. Which chord does it keep coming back to?", "El patrón va 1 4 1 5. ¿A qué acorde vuelve una y otra vez?"),
  q2=("Why might a bright electric piano stand in for the guitars here?", "¿Por qué un piano eléctrico brillante podría tomar el lugar de las guitarras aquí?"),
  links=[("Highlife — Wikipedia", W + "Highlife")]),

 dict(n=29, t=("Ska", "Ska"), key=7, minor=False, bpm=150, sound="upright", rhythm="offbeat", pads=[1, 4, 5, 4],
  blurb=("Ska was born in Jamaica in the early 1960s, mixing local mento with American rhythm and blues. The piano and guitar play on the off-beats, between the counts.",
         "El ska nació en Jamaica a principios de los años 60, mezclando el mento local con el rhythm and blues de Estados Unidos. El piano y la guitarra tocan en los contratiempos, entre los conteos."),
  tog=("Everyone counts 1 2 3 4 out loud and claps only on the AND between the numbers.",
       "Todos cuentan 1 2 3 4 en voz alta y aplauden solo en el Y entre los números."),
  kw=[("ska", "ska"), ("off-beat", "contratiempo"), ("tempo", "tempo")],
  q1=("Do the chords land on the numbers or between them?", "¿Los acordes caen en los números o entre ellos?"),
  q2=("Play it at 100, then at 150. Which one feels like ska? Why?", "Tócalo a 100 y luego a 150. ¿Cuál se siente como ska? ¿Por qué?"),
  links=[("Ska — Wikipedia", W + "Ska"), ("Mento — Wikipedia", W + "Mento")]),

 dict(n=30, t=("Reggae organ", "Órgano de reggae"), key=9, minor=True, bpm=76, sound="organ", rhythm="offbeat", preset="minor",
  blurb=("Reggae grew out of ska in Jamaica in the late 1960s. It slowed down, and the organ began to bubble on the off-beats while the bass sang underneath.",
         "El reggae salió del ska en Jamaica a finales de los años 60. Se volvió más lento, y el órgano empezó a burbujear en los contratiempos mientras el bajo cantaba por debajo."),
  tog=("Sway gently and say 'chk' on each off-beat. If your class made the Reggae one drop on the drum machine, send it here and press Play with my drum beat.",
       "Mézanse suave y digan 'chk' en cada contratiempo. Si su clase hizo el Reggae one drop en la caja de ritmos, mándenlo aquí y pulsen Tocar con mi ritmo de batería."),
  kw=[("reggae", "reggae"), ("minor key", "tono menor"), ("organ bubble", "burbujeo del órgano")],
  q1=("This one is in a minor key. How does it feel next to the ska song?", "Esta está en un tono menor. ¿Cómo se siente junto a la canción de ska?"),
  q2=("Why might reggae sound better slower than ska?", "¿Por qué el reggae podría sonar mejor más lento que el ska?"),
  links=[("Reggae — Wikipedia", W + "Reggae")]),

 dict(n=31, t=("Cumbia", "Cumbia"), key=4, minor=True, bpm=94, sound="ep80", rhythm="offbeat", pads=[1, 3, 4, 1],
  blurb=("Cumbia began on the Caribbean coast of Colombia, from African, Indigenous and Spanish music. Today it is played from Mexico to Argentina, often on electronic keyboards.",
         "La cumbia nació en la costa caribe de Colombia, de música africana, indígena y española. Hoy se toca de México a Argentina, muchas veces con teclados electrónicos."),
  tog=("Step side to side on each beat, like a cumbia dancer. If your class made the Cumbia-style groove on the drum machine, send it here and play along.",
       "Den un paso al lado en cada pulso, como en el baile de cumbia. Si su clase hizo el Ritmo estilo cumbia en la caja de ritmos, mándenlo aquí y toquen encima."),
  kw=[("cumbia", "cumbia"), ("Caribbean coast", "costa caribe"), ("keyboard", "teclado")],
  q1=("Cumbia mixes African, Indigenous and Spanish music. What other music do you know that mixes cultures?", "La cumbia mezcla música africana, indígena y española. ¿Qué otra música conoces que mezcle culturas?"),
  q2=("The chords play between the beats. What does that do to your feet?", "Los acordes suenan entre los pulsos. ¿Qué les hace eso a tus pies?"),
  links=[("Cumbia — Wikipedia", W + "Cumbia")]),

 dict(n=32, t=("Flamenco · the Andalusian cadence", "Flamenco · la cadencia andaluza"), key=9, minor=True, bpm=100, sound="grand", rhythm="broken", preset="flamenco",
  blurb=("Flamenco comes from Andalusia, in southern Spain, with roots in Romani, Arab, Jewish and Spanish music. Four chords step down, and the last one sounds like a door left open.",
         "El flamenco viene de Andalucía, en el sur de España, con raíces en la música gitana, árabe, judía y española. Cuatro acordes bajan paso a paso, y el último suena como una puerta que se queda abierta."),
  tog=("Half the class claps on every beat (palmas). The other half claps softly on 2 and 4.",
       "La mitad de la clase aplaude en cada pulso (palmas). La otra mitad aplaude suave en 2 y 4."),
  kw=[("flamenco", "flamenco"), ("cadence", "cadencia"), ("palmas", "palmas")],
  q1=("Each chord steps down. Which one sounds the least finished?", "Cada acorde baja un paso. ¿Cuál suena menos terminado?"),
  q2=("What pictures or places does this music bring to mind?", "¿Qué imágenes o lugares te trae a la mente esta música?"),
  links=[("Flamenco — Wikipedia", W + "Flamenco"), ("Andalusian cadence — Wikipedia", W + "Andalusian_cadence")]),

 dict(n=33, t=("Black keys only", "Solo teclas negras"), key=6, minor=False, bpm=90, sound="epwarm", rhythm="broken", pads=[1, 4, 5, 1], black=True,
  blurb=("The five black keys make a pentatonic scale, one of the oldest scales in the world. Folk music from China, Scotland, West Africa and the Andes uses it. Over these chords, every black key fits.",
         "Las cinco teclas negras forman una escala pentatónica, una de las escalas más antiguas del mundo. La música tradicional de China, Escocia, África occidental y los Andes la usa. Sobre estos acordes, cada tecla negra encaja."),
  tog=("Take turns. Each learner plays one short black-key tune over the chords. Everyone else listens, then claps.",
       "Túrnense. Cada quien toca una melodía corta con teclas negras sobre los acordes. Los demás escuchan y luego aplauden."),
  kw=[("pentatonic", "pentatónica"), ("scale", "escala"), ("improvise", "improvisar")],
  q1=("Why does every black key fit over these chords?", "¿Por qué cada tecla negra encaja sobre estos acordes?"),
  q2=("Did your tune sound like music from a place you know? Which one?", "¿Tu melodía sonó como música de algún lugar que conoces? ¿De cuál?"),
  links=[("Pentatonic scale — Wikipedia", W + "Pentatonic_scale")]),

 dict(n=34, t=("City pop", "City pop"), key=4, minor=False, bpm=112, sound="ep80", rhythm="pulse", preset="anime",
  blurb=("City pop was the sound of Tokyo in the 1980s: bright, smooth and full of the new digital electric piano. Its favorite chords, 4 5 3 6, still fill anime songs.",
         "El city pop fue el sonido de Tokio en los años 80: brillante, suave y lleno del nuevo piano eléctrico digital. Sus acordes favoritos, 4 5 3 6, siguen llenando las canciones de anime."),
  tog=("Everyone nods on beat 1. Two volunteers make up a 'la la' tune on the lit keys.",
       "Todos asienten en el pulso 1. Dos voluntarios inventan una melodía de 'la la' con las teclas iluminadas."),
  kw=[("city pop", "city pop"), ("FM synthesis", "síntesis FM"), ("anime", "anime")],
  q1=("The pattern starts on chord 4, not on 1. How does that change the feel?", "El patrón empieza en el acorde 4, no en el 1. ¿Cómo cambia eso la sensación?"),
  q2=("How does the '80s electric piano sound different from the grand piano?", "¿En qué suena distinto el piano eléctrico de los 80 del piano de cola?"),
  links=[("City pop — Wikipedia", W + "City_pop"), ("Yamaha DX7 — Wikipedia", W + "Yamaha_DX7")]),

 dict(n=35, t=("Pop anthem · 1 5 6 4", "Himno pop · 1 5 6 4"), key=7, minor=False, bpm=100, sound="grand", rhythm="pulse", preset="pop",
  blurb=("Four chords, 1 5 6 4, sit under hundreds of hit songs from many countries. Learn them once and you can play along with the radio.",
         "Cuatro acordes, 1 5 6 4, están debajo de cientos de éxitos de muchos países. Apréndelos una vez y podrás acompañar a la radio."),
  tog=("Everyone sings one long 'oh' on the same note while the chords change under it. Notice how the same note feels different on each chord.",
       "Todos cantan un 'oh' largo en la misma nota mientras los acordes cambian debajo. Fíjense cómo la misma nota se siente distinta en cada acorde."),
  kw=[("chord progression", "progresión de acordes"), ("pop", "pop"), ("anthem", "himno")],
  q1=("Which chord in 1 5 6 4 is minor? How can you hear it?", "¿Qué acorde de 1 5 6 4 es menor? ¿Cómo lo oyes?"),
  q2=("Why do you think so many songs use the same four chords?", "¿Por qué crees que tantas canciones usan los mismos cuatro acordes?"),
  links=[("I–V–vi–IV progression — Wikipedia", W + "I%E2%80%93V%E2%80%93vi%E2%80%93IV_progression")]),

 dict(n=36, t=("Sad pop · 6 4 1 5", "Pop triste · 6 4 1 5"), key=0, minor=False, bpm=72, sound="upright", rhythm="broken", preset="sadpop",
  blurb=("These are the same four chords as the pop anthem, started on the minor one. Starting on 6 makes the whole song feel more serious.",
         "Son los mismos cuatro acordes del himno pop, empezando por el menor. Empezar en el 6 hace que toda la canción se sienta más seria."),
  tog=("Close your eyes for one time round. Then everyone writes one word for how it made them feel.",
       "Cierren los ojos durante una vuelta. Luego cada quien escribe una palabra sobre cómo le hizo sentir."),
  kw=[("mood", "ánimo"), ("minor chord", "acorde menor"), ("ballad", "balada")],
  q1=("The pop anthem and sad pop use the same chords. Why do they feel different?", "El himno pop y el pop triste usan los mismos acordes. ¿Por qué se sienten distintos?"),
  q2=("Which instrument would you pick for a sad song? Why?", "¿Qué instrumento elegirías para una canción triste? ¿Por qué?"),
  links=[("Chord progression — Wikipedia", W + "Chord_progression")]),

 dict(n=37, t=("Lo-fi study beat", "Ritmo lo-fi para estudiar"), key=5, minor=False, bpm=76, sound="epwarm", rhythm="hold", preset="jazz", era=True,
  blurb=("Lo-fi beats grew online in the 2010s: slow hip-hop drums, soft jazz chords and a dusty sound, on purpose. Turn the Sound dial toward 1987 for the dust.",
         "Los ritmos lo-fi crecieron en internet en los años 2010: batería lenta de hip-hop, acordes suaves de jazz y un sonido polvoso, a propósito. Gira el dial de Sonido hacia 1987 para el polvo."),
  tog=("If your class made the Lo-fi study beat on the drum machine, send it here and press Play with my drum beat. Then everyone reads or writes quietly for one minute while it plays.",
       "Si su clase hizo el ritmo Lo-fi para estudiar en la caja de ritmos, mándenlo aquí y pulsen Tocar con mi ritmo de batería. Luego todos leen o escriben en silencio un minuto mientras suena."),
  kw=[("lo-fi", "lo-fi"), ("seventh chord", "acorde de séptima"), ("texture", "textura")],
  q1=("What does the 1987 side of the dial add to this song?", "¿Qué le agrega a esta canción el lado de 1987 del dial?"),
  q2=("Why do people like this kind of music for studying?", "¿Por qué a la gente le gusta esta música para estudiar?"),
  links=[("Lo-fi music — Wikipedia", W + "Lo-fi_music")]),

 dict(n=38, t=("Our class song", "La canción de nuestra clase"), free=True,
  blurb=("Everyone adds something. Each group picks the chords for its part of the pattern, and the piano plays them all as one song.",
         "Todos aportan algo. Cada grupo elige los acordes de su parte del patrón, y el piano los toca todos como una sola canción."),
  tog=("Make four groups. Each group chooses two chords, in order. When your two bars play, your group stands up.",
       "Hagan cuatro grupos. Cada grupo elige dos acordes, en orden. Cuando suenan sus dos compases, su grupo se pone de pie."),
  kw=[("arrangement", "arreglo"), ("collaboration", "colaboración"), ("composer", "compositor")],
  q1=("Which two chords did your group add? Why those?", "¿Qué dos acordes aportó tu grupo? ¿Por qué esos?"),
  q2=("What helped everyone's chords fit together?", "¿Qué ayudó a que los acordes de todos encajaran?"),
  links=[("Song structure — Wikipedia", W + "Song_structure"), ("Musical composition — Wikipedia", W + "Musical_composition")]),
]

# ── the piano's own words, copied from music-piano.html so the steps say exactly what the page says ──
SOUND_NAMES = {
  "grand": ("Grand piano", "Piano de cola"), "upright": ("Upright piano", "Piano vertical"), "honky": ("Honky-tonk piano", "Piano honky-tonk"),
  "epwarm": ("Electric piano · warm", "Piano eléctrico · cálido"), "epreed": ("Electric piano · bright", "Piano eléctrico · brillante"),
  "ep80": ("'80s electric piano", "Piano eléctrico de los 80"), "organ": ("Rock and jazz organ", "Órgano de rock y jazz"), "church": ("Church organ", "Órgano de iglesia"),
}
RHYTHM_NAMES = {"hold": ("Hold · one long chord", "Mantener · un acorde largo"), "pulse": ("Pulse · four beats", "Pulso · cuatro tiempos"),
                "broken": ("Broken · one note at a time", "Arpegio · una nota a la vez"), "offbeat": ("Off-beat · reggae and ska", "Contratiempo · reggae y ska")}
PRESETS = {
  "pop": (("Pop · 1 5 6 4", "Pop · 1 5 6 4"), False, [(0, "maj"), (7, "maj"), (9, "min"), (5, "maj")]),
  "fifties": (("Fifties · 1 6 4 5", "Años 50 · 1 6 4 5"), False, [(0, "maj"), (9, "min"), (5, "maj"), (7, "maj")]),
  "sadpop": (("Sad pop · 6 4 1 5", "Pop triste · 6 4 1 5"), False, [(9, "min"), (5, "maj"), (0, "maj"), (7, "maj")]),
  "anime": (("Anime and J-pop · 4 5 3 6", "Anime y J-pop · 4 5 3 6"), False, [(5, "maj"), (7, "maj"), (4, "min"), (9, "min")]),
  "canon": (("Canon · 8 chords", "Canon · 8 acordes"), False, [(0, "maj"), (7, "maj"), (9, "min"), (4, "min"), (5, "maj"), (0, "maj"), (5, "maj"), (7, "maj")]),
  "blues": (("Blues · 12 bars", "Blues · 12 compases"), False, [(0, "dom7")] * 4 + [(5, "dom7")] * 2 + [(0, "dom7")] * 2 + [(7, "dom7"), (5, "dom7"), (0, "dom7"), (7, "dom7")]),
  "jazz": (("Jazz · 2 5 1", "Jazz · 2 5 1"), False, [(2, "m7"), (7, "dom7"), (0, "maj7"), (0, "maj7")]),
  "minor": (("Minor groove", "Ritmo menor"), True, [(0, "min"), (8, "maj"), (3, "maj"), (10, "maj")]),
  "flamenco": (("Flamenco", "Flamenco"), True, [(0, "min"), (10, "maj"), (8, "maj"), (7, "maj")]),
}
PADS_MAJOR = {1: (0, "maj"), 2: (2, "min"), 3: (4, "min"), 4: (5, "maj"), 5: (7, "maj"), 6: (9, "min")}
PADS_MINOR = {1: (0, "min"), 2: (3, "maj"), 3: (5, "min"), 4: (7, "min"), 5: (8, "maj"), 6: (10, "maj")}   # AOG-PADS-1TO6-V1
KEY_NAMES = {"en": ["C", "D♭", "D", "E♭", "E", "F", "F♯", "G", "A♭", "A", "B♭", "B"],
             "es": ["Do", "Re♭", "Re", "Mi♭", "Mi", "Fa", "Fa♯", "Sol", "La♭", "La", "Si♭", "Si"]}
NAMES = {"sharp": ["C", "C♯", "D", "D♯", "E", "F", "F♯", "G", "G♯", "A", "A♯", "B"], "flat": ["C", "D♭", "D", "E♭", "E", "F", "G♭", "G", "A♭", "A", "B♭", "B"]}
SOLFA = {"sharp": ["Do", "Do♯", "Re", "Re♯", "Mi", "Fa", "Fa♯", "Sol", "Sol♯", "La", "La♯", "Si"], "flat": ["Do", "Re♭", "Re", "Mi♭", "Mi", "Fa", "Sol♭", "Sol", "La♭", "La", "Si♭", "Si"]}
SUF = {"maj": "", "min": "m", "dom7": "7", "maj7": "maj7", "m7": "m7"}
SUF_ES = {"maj": "", "min": " m", "dom7": "7", "maj7": " maj7", "m7": " m7"}
