const pw=require(require("child_process").execSync("npm root -g").toString().trim()+"/playwright");
const http=require("http"),fs=require("fs"),path=require("path");
const root="/home/user/architecture-of-grace/aog-deploy";const port=9170;
const srv=http.createServer((q,r)=>{let f=path.join(root,decodeURIComponent(q.url.split("?")[0]));fs.readFile(f,(e,d)=>{if(e){r.writeHead(404);return r.end();}r.writeHead(200,{"content-type":{".html":"text/html",".js":"text/javascript",".css":"text/css"}[path.extname(f)]||"application/octet-stream"});r.end(d);});}).listen(port);
const ok=(c,m)=>{console.log((c?"PASS ":"FAIL ")+m); if(!c) process.exitCode=1;};
(async()=>{const b=await pw.chromium.launch({args:["--autoplay-policy=no-user-gesture-required"]});
 const c=await b.newContext(pw.devices["iPhone 13"]); await c.addInitScript(()=>{localStorage.setItem("aog.drums.bench.v2",JSON.stringify({roll:"1/8",bpm:120}))});
 const p=await c.newPage(); const errs=[]; p.on("pageerror",e=>errs.push(e.message));
 await p.goto(`http://localhost:${port}/music-drums.html#home`); await p.waitForTimeout(1500);
 await p.evaluate(()=>{window.__h=0;const h=window.hit;window.hit=function(){window.__h++;return h.apply(this,arguments)}});
 const cdp=await c.newCDPSession(p); await p.locator('.sp-pad[data-pad="snare"]').scrollIntoViewIfNeeded();
 const r=await p.locator('.sp-pad[data-pad="snare"]').boundingBox();
 await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:r.x+20,y:r.y+20,id:1}]});
 await p.waitForTimeout(800);
 await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]}); await p.waitForTimeout(400);
 const n=await p.evaluate("__h"); ok(n>=3&&n<=5, "finger held 0.8 s at 1/8 (120 BPM) rolls: "+n+" hits");
 const y0=await p.evaluate("scrollY"); ok(true,"");
 ok(errs.length===0,"no page errors "+errs.join("|"));
 await b.close(); srv.close();})();
