# World Cultures and Societies — Daily Drafts banks. Cultures, social classes and political
# ideas from left to right (including the extremes), across Europe, Asia, the Americas,
# Africa and the Middle East. Neutral and balanced: we describe what each idea holds and what
# supporters and critics say; we never tell learners which side to take.
def mc(q, a, w): return ["mc", q, a, w]
def tf(q, v): return ["tf", q, v]
def voc(w, d): return ["voc", w, d]
def op(q, m): return ["open", q, m]

BANDS = {}

BANDS['k2'] = [
("Families Everywhere", "Familias en todas partes", [
 mc("Every family is…", "special in its own way", ["exactly the same", "always big", "always small"]),
 mc("Some children live with their…", "grandparents", ["teachers", "mail carrier", "bus driver"]),
 mc("Many relatives living together is…", "an extended family", ["a class", "a team", "a town"]),
 mc("In many homes, grandparents help…", "care for the children", ["drive buses", "run schools", "fly planes"]),
 mc("Families show love by…", "helping each other", ["yelling", "hiding", "ignoring"]),
 mc("A family can have…", "one or many people", ["only four people", "only two people", "no people"]),
 tf("Families around the world love their children.", True),
 tf("All families look the same.", False),
 voc("family", "People who love and care for each other."),
 op("Who is in your family?", "Any people the child names who care for them."),
]),
("Homes Around the World", "Casas del mundo", [
 mc("In the Arctic, some people once built…", "igloos from snow", ["huts of leaves", "tents of silk", "homes of glass"]),
 mc("In big cities, many families live in…", "apartments", ["caves", "igloos", "tree houses"]),
 mc("Some Mongolian herders live in tents called…", "gers or yurts", ["igloos", "castles", "tepees"]),
 mc("Some homes in hot places are made of…", "mud bricks", ["ice", "snow", "paper"]),
 mc("Some homes near water stand on…", "stilts", ["wheels", "clouds", "boats of ice"]),
 mc("A home keeps us…", "safe and warm", ["hungry", "wet", "cold"]),
 tf("Homes are different in different places.", True),
 tf("Everyone in the world lives in igloos.", False),
 voc("home", "A place where people live and feel safe."),
 op("What is your favorite place in your home?", "A place, and why they like it."),
]),
("Foods We Eat", "Comidas que comemos", [
 mc("Many people in Japan eat…", "rice and fish", ["only pizza", "only tacos", "only bread"]),
 mc("Tortillas are a food from…", "Mexico", ["Japan", "Norway", "India"]),
 mc("Pasta is a famous food from…", "Italy", ["China", "Peru", "Kenya"]),
 mc("In China, many people eat with…", "chopsticks", ["only hands", "straws", "spoons only"]),
 mc("Naan is a bread from…", "India", ["Canada", "Brazil", "France"]),
 mc("Potatoes first grew in…", "South America", ["Europe", "Australia", "Africa"]),
 tf("People in different places eat different foods.", True),
 tf("Everyone eats with chopsticks.", False),
 voc("food", "What we eat to grow and stay strong."),
 op("What food does your family love?", "A food and when they eat it."),
]),
("Clothes People Wear", "Ropa que usamos", [
 mc("A kimono is clothing from…", "Japan", ["Mexico", "Ghana", "Peru"]),
 mc("A sari is worn by many women in…", "India", ["Russia", "Canada", "Chile"]),
 mc("Kente cloth comes from…", "Ghana", ["China", "France", "Brazil"]),
 mc("In cold places, people wear…", "warm coats", ["swimsuits", "sandals only", "no clothes"]),
 mc("A poncho is worn in the…", "Andes mountains", ["Sahara desert", "Arctic ice", "moon"]),
 mc("People wear special clothes for…", "holidays", ["sleeping only", "baths", "nothing"]),
 tf("Clothes can show a family's culture.", True),
 tf("Everyone in the world wears a kimono.", False),
 voc("culture", "The way a group lives, eats, dresses and celebrates."),
 op("What clothes do you wear on a special day?", "Clothes and the special day."),
]),
("Holidays and Festivals", "Días festivos y fiestas", [
 mc("Diwali is a festival of…", "lights", ["snow", "rain", "silence"]),
 mc("Lunar New Year is big in…", "China", ["Peru", "Mexico", "Kenya"]),
 mc("Day of the Dead is from…", "Mexico", ["Japan", "India", "Spain only"]),
 mc("At Lunar New Year, many children get…", "red envelopes", ["homework", "shovels", "blue hats"]),
 mc("Eid al-Fitr comes after a month of…", "fasting", ["snow", "school", "sports"]),
 mc("Holidays often bring families…", "together", ["apart", "to sleep", "to work"]),
 tf("Many cultures have festivals with lights.", True),
 tf("Every family has the same holidays.", False),
 voc("festival", "A happy time when people celebrate together."),
 op("What is your favorite holiday? Why?", "A holiday and one reason."),
]),
("Languages and Greetings", "Idiomas y saludos", [
 mc("\"Hola\" means hello in…", "Spanish", ["Japanese", "French", "Hindi"]),
 mc("\"Bonjour\" means hello in…", "French", ["Spanish", "Chinese", "Swahili"]),
 mc("In Japan, people often greet with a…", "bow", ["hug only", "jump", "clap"]),
 mc("\"Jambo\" means hello in…", "Swahili", ["German", "Korean", "Spanish"]),
 mc("In India, people may say…", "\"Namaste\"", ["\"Ciao\"", "\"Aloha\"", "\"Hola\""]),
 mc("The world has about…", "7,000 languages", ["7 languages", "70 languages", "7 million languages"]),
 tf("People speak many languages around the world.", True),
 tf("Everyone in the world speaks only English.", False),
 voc("language", "The words people use to talk and write."),
 op("How do you say hello in another language?", "Any greeting in another language."),
]),
("Jobs People Do", "Trabajos de la gente", [
 mc("A farmer…", "grows food", ["flies planes", "fixes teeth", "teaches math"]),
 mc("A doctor helps people who are…", "sick", ["hungry for toys", "sleepy", "bored"]),
 mc("A fisher works…", "on the water", ["in a mine", "in a bank", "in space"]),
 mc("A teacher helps children…", "learn", ["cook", "drive", "shop"]),
 mc("A builder makes…", "houses", ["clouds", "rain", "rivers"]),
 mc("Every job helps the…", "community", ["moon", "weather", "ocean floor"]),
 tf("People do many kinds of jobs.", True),
 tf("Only grown-ups in one country have jobs.", False),
 voc("job", "Work a person does, often to earn money."),
 op("What job would you like someday?", "A job and why it helps people."),
]),
("Rules and Fairness", "Reglas y justicia", [
 mc("Rules help us stay…", "safe", ["lost", "sad", "hungry"]),
 mc("Taking turns is…", "fair", ["mean", "rude", "silly"]),
 mc("A rule at school is to…", "listen to others", ["push in line", "grab toys", "shout"]),
 mc("Fair means everyone…", "gets what they need", ["gets nothing", "is the same size", "wins"]),
 mc("If you break a rule, you can…", "fix it and try again", ["never play again", "hide forever", "leave town"]),
 mc("Rules for a whole country are called…", "laws", ["games", "songs", "stories"]),
 tf("Every country has rules called laws.", True),
 tf("Rules are only for grown-ups.", False),
 voc("fair", "When everyone is treated in a right way."),
 op("What is one rule that helps your class?", "A rule and how it helps."),
]),
("Leaders and Voting", "Líderes y votar", [
 mc("A leader helps a group…", "make choices", ["sleep", "hide", "get lost"]),
 mc("When we vote, we…", "choose together", ["fight", "run away", "stay silent"]),
 mc("A school leader is the…", "principal", ["school bus", "bus", "lunch tray"]),
 mc("A town leader is often a…", "mayor", ["pilot", "chef", "clown"]),
 mc("When most people pick one thing, it…", "wins the vote", ["loses", "breaks", "disappears"]),
 mc("A good leader…", "listens to people", ["yells at people", "takes toys", "never helps"]),
 tf("People can vote to choose leaders.", True),
 tf("Voting means one person picks for all.", False),
 voc("vote", "To choose by raising a hand or marking paper."),
 op("If your class voted, what would you pick?", "A choice and one reason."),
]),
("Kind to Everyone", "Amables con todos", [
 mc("When a new friend talks differently, we…", "listen kindly", ["laugh", "walk away", "copy rudely"]),
 mc("Being kind means…", "helping and sharing", ["pushing", "teasing", "grabbing"]),
 mc("People from other places can teach us…", "new things", ["nothing", "only games", "bad words"]),
 mc("If a friend is sad, you can…", "ask if they are okay", ["laugh", "ignore them", "leave"]),
 mc("Our differences make the world…", "interesting", ["boring", "smaller", "quiet"]),
 mc("Inviting someone new to play is…", "kind", ["rude", "silly", "wrong"]),
 tf("We can be friends with people who are different.", True),
 tf("Kids from other countries cannot be our friends.", False),
 voc("kind", "Being friendly, gentle and helpful."),
 op("How can you help a new student feel welcome?", "One kind action, like saying hi or sharing."),
]),
]

BANDS['35'] = [
("Continents and Cultures", "Continentes y culturas", [
 mc("Most maps in the US show how many continents?", "seven", ["five", "nine", "twelve"]),
 mc("Which continent has the most people?", "Asia", ["Europe", "Australia", "Antarctica"]),
 mc("Brazil, Peru and Argentina are in…", "South America", ["Europe", "Africa", "Asia"]),
 mc("France, Germany and Italy are in…", "Europe", ["Asia", "South America", "Africa"]),
 mc("Nigeria, Kenya and Egypt are in…", "Africa", ["Asia", "Europe", "North America"]),
 mc("The main language of Brazil is…", "Portuguese", ["Spanish", "English", "French"]),
 tf("A single continent can hold many different cultures.", True),
 tf("Africa is a single country.", False),
 voc("continent", "One of the seven very large areas of land on Earth."),
 op("Pick a continent. What would you like to learn about the people there?", "Names a continent and a question about its people, food, language or customs."),
]),
("Customs and Festivals", "Costumbres y fiestas", [
 mc("Carnival in Rio de Janeiro is famous for…", "parades and samba dancing", ["ice sculptures", "silent prayer", "snowball fights"]),
 mc("Holi, the festival of colors, comes from…", "India", ["Norway", "Mexico", "Japan"]),
 mc("During the Mid-Autumn Festival in China, people eat…", "mooncakes", ["tacos", "pancakes", "pizza"]),
 mc("Oktoberfest is a festival from…", "Germany", ["Peru", "China", "Egypt"]),
 mc("Inti Raymi, the Festival of the Sun, is held in…", "Peru", ["Sweden", "Korea", "Italy"]),
 mc("A custom is…", "a way of doing things a group keeps over time", ["a new law", "a type of weather", "a kind of money"]),
 tf("Many festivals mark seasons, harvests or important stories.", True),
 tf("Customs never change over time.", False),
 voc("tradition", "A belief or custom passed down from older people to younger people."),
 op("Describe a custom your family keeps. Where did it come from?", "Describes a custom and names who taught it or where it began."),
]),
("Rich, Poor and Work", "Ricos, pobres y el trabajo", [
 mc("Some jobs pay more often because they…", "need long training or rare skills", ["are always easier", "are done outside", "start early"]),
 mc("A doctor studies for many years. This is an example of…", "training that raises pay", ["luck only", "a holiday", "a tax"]),
 mc("Money people earn from work is called…", "income", ["a custom", "a vote", "a border"]),
 mc("When many people want to do a job, pay for it often…", "stays lower", ["goes up fast", "disappears", "doubles"]),
 mc("Being poor means…", "not having enough money for basic needs", ["living in a big city", "having a big family", "living in the country"]),
 mc("Which is a basic need?", "food", ["video games", "jewelry", "a sports car"]),
 tf("Where a person is born can affect how much money they have.", True),
 tf("People are poor only because they do not work hard.", False),
 voc("wealth", "Money and things of value that a person or family owns."),
 op("Why do you think some jobs pay more than others?", "Gives reasons such as training, skill, danger or how many people can do the job."),
]),
("Kings, Nobles and Peasants", "Reyes, nobles y campesinos", [
 mc("In Europe long ago, the most powerful person was often the…", "king or queen", ["peasant", "blacksmith", "priest's helper"]),
 mc("Nobles were…", "rich landowners who served the king", ["farm workers with no land", "sailors", "merchants only"]),
 mc("Most people in medieval Europe were…", "peasants who farmed", ["knights", "kings", "bankers"]),
 mc("Knights promised to…", "fight for their lord", ["build roads", "teach school", "sell cloth"]),
 mc("Peasants usually gave the lord…", "part of their crops", ["all their children", "their houses", "nothing"]),
 mc("A castle was the home of a…", "lord or king", ["peasant family", "fisher", "shepherd"]),
 tf("Long ago, most people were born into their place in society.", True),
 tf("In medieval Europe, most people were nobles.", False),
 voc("peasant", "A poor farmer long ago who worked land owned by someone else."),
 op("Would you want to live as a peasant or a noble long ago? Why?", "Picks one and gives reasons about work, food, safety or freedom."),
]),
("What a Government Does", "Qué hace un gobierno", [
 mc("A government…", "makes and carries out laws", ["grows all food", "picks your friends", "writes your homework"]),
 mc("Money people pay to the government is called…", "taxes", ["wages", "gifts", "prizes"]),
 mc("Taxes can pay for…", "roads and schools", ["your toys", "private parties", "your pets"]),
 mc("The leader of a city is often called a…", "mayor", ["king", "judge", "general"]),
 mc("A judge's job is to…", "decide if laws were broken", ["make all laws", "collect trash", "fly planes"]),
 mc("Which is a service a government gives?", "fire fighters", ["movie tickets", "candy", "video games"]),
 tf("Governments help keep people safe.", True),
 tf("Every country has exactly the same government.", False),
 voc("government", "The group of people who lead a country, state or town."),
 op("If you led your town, what is one thing you would fix?", "Names a need, such as parks or roads, and how they would help."),
]),
("Democracy or One Ruler", "Democracia o un solo gobernante", [
 mc("In a democracy, leaders are chosen by…", "the people voting", ["one family", "the army", "a coin toss"]),
 mc("One of the first democracies began long ago in…", "ancient Athens, Greece", ["ancient Egypt", "ancient China", "the Aztec Empire"]),
 mc("A dictator is a ruler who…", "holds power without fair elections", ["is chosen every year", "shares power equally", "has no power"]),
 mc("In a monarchy, the ruler is usually…", "a king or queen from one family", ["elected every year", "a judge", "a mayor"]),
 mc("The United Kingdom has a king but also…", "an elected Parliament", ["no laws", "no voting", "a dictator"]),
 mc("\"Demos\" is a Greek word that means…", "the people", ["the king", "the army", "the gods"]),
 tf("In a democracy, people can vote leaders out.", True),
 tf("A dictator must win fair elections to stay in power.", False),
 voc("democracy", "A government where the people choose leaders by voting."),
 op("What is good about letting people vote? What can be hard about it?", "Names a benefit, such as fairness, and a challenge, such as disagreement."),
]),
("Rights and Responsibilities", "Derechos y responsabilidades", [
 mc("A right is…", "something every person should be allowed to have or do", ["a chore", "a punishment", "a tax"]),
 mc("Which is a responsibility?", "following laws", ["going to recess", "eating dessert", "watching TV"]),
 mc("Freedom of speech means you can…", "share your ideas", ["take others' things", "skip school", "break laws"]),
 mc("The Universal Declaration of Human Rights was written in…", "1948", ["1492", "1776", "2010"]),
 mc("The Universal Declaration of Human Rights was made by the…", "United Nations", ["Roman Empire", "Aztecs", "Olympic Games"]),
 mc("A responsibility that comes with voting is to…", "learn about the choices", ["vote many times", "vote for your friend only", "stay home"]),
 tf("Rights often come with responsibilities.", True),
 tf("Children have no rights.", False),
 voc("responsibility", "A duty or job you are trusted to do."),
 op("What is one right you have at school, and one responsibility?", "Names a right, such as learning, and a matching duty, such as respecting others."),
]),
("Asia: People and Places", "Asia: gente y lugares", [
 mc("The country with the most people today is…", "India", ["Japan", "Canada", "France"]),
 mc("The Great Wall is in…", "China", ["Korea", "India", "Vietnam"]),
 mc("Hanbok is traditional clothing from…", "Korea", ["Mexico", "Egypt", "Spain"]),
 mc("Many people in Vietnam and Thailand grow…", "rice", ["wheat only", "coffee only", "potatoes only"]),
 mc("Tokyo is the capital of…", "Japan", ["China", "Thailand", "India"]),
 mc("Hindi is widely spoken in…", "India", ["Japan", "Korea", "Russia"]),
 tf("Asia is the largest continent.", True),
 tf("Everyone in Asia speaks the same language.", False),
 voc("capital", "The city where a country's government meets."),
 op("Choose one country in Asia. What would you want to see there?", "Names a country and a place, food or custom."),
]),
("The Americas: People and Places", "Las Américas: gente y lugares", [
 mc("The Maya lived in what is now…", "Mexico and Central America", ["Canada", "Brazil", "Argentina"]),
 mc("The Inca built Machu Picchu in…", "Peru", ["Chile", "Cuba", "Canada"]),
 mc("The main language of Argentina is…", "Spanish", ["Portuguese", "English", "French"]),
 mc("French is an official language of…", "Canada", ["Mexico", "Peru", "Chile"]),
 mc("The Haudenosaunee (Iroquois) lived in what is now…", "New York and Canada", ["Mexico", "Peru", "Florida only"]),
 mc("Mexico City was built on the old Aztec city of…", "Tenochtitlan", ["Cusco", "Rome", "Quito"]),
 tf("People lived in the Americas long before Europeans arrived.", True),
 tf("Brazil's main language is Spanish.", False),
 voc("Indigenous", "The first peoples who lived in a place, and their families today."),
 op("What is one thing you know about a culture in the Americas?", "Names a people or country and one fact about their life."),
]),
("Europe and Africa: People and Places", "Europa y África: gente y lugares", [
 mc("The ancient Egyptians built…", "pyramids", ["igloos", "skyscrapers", "pagodas"]),
 mc("Mali's old city of Timbuktu was famous for…", "books and learning", ["ice skating", "car factories", "volcanoes"]),
 mc("Swahili is spoken in…", "East Africa", ["Northern Europe", "South America", "Japan"]),
 mc("Many countries in Europe share one money called the…", "euro", ["peso", "yen", "rupee"]),
 mc("The Eiffel Tower is in…", "Paris, France", ["Rome, Italy", "Cairo, Egypt", "Madrid, Spain"]),
 mc("Nelson Mandela led the fight for equal rights in…", "South Africa", ["Norway", "Brazil", "China"]),
 tf("Africa has more than 50 countries.", True),
 tf("Everyone in Europe speaks the same language.", False),
 voc("custom", "Something a group of people usually does, like a greeting or meal."),
 op("What would you pack to visit a country in Europe or Africa? Why?", "Names a country and items that fit its weather or customs."),
]),
]

BANDS['68'] = [
("Feudal Europe and the Three Estates", "La Europa feudal y los tres estados", [
 mc("Feudalism was a system based on…", "land given in exchange for loyalty and service", ["factories and wages", "elections every year", "trade with Asia only"]),
 mc("A lord who received land from a king was called a…", "vassal", ["serf", "guild", "burgher"]),
 mc("Serfs were peasants who…", "were bound to work the lord's land", ["owned large estates", "were free to move anywhere", "ruled towns"]),
 mc("In France before 1789, the First Estate was the…", "clergy", ["nobility", "common people", "royal family"]),
 mc("The Second Estate in old-regime France was the…", "nobility", ["clergy", "peasants", "merchants"]),
 mc("The Third Estate included…", "peasants, workers and the middle class", ["bishops only", "nobles only", "the king's family"]),
 tf("The Third Estate made up the large majority of France's people.", True),
 tf("Serfs in feudal Europe could leave the manor whenever they wished.", False),
 voc("estate", "In old France, one of the three legal orders of society: clergy, nobles and commoners."),
 op("Why might the Third Estate have felt the old system was unfair?", "Mentions that they were most of the people, paid most taxes and had little power."),
]),
("India's Caste System in History", "El sistema de castas de la India en la historia", [
 mc("The four broad varnas described in ancient Indian texts were Brahmins, Kshatriyas, Vaishyas and…", "Shudras", ["Samurai", "Mandarins", "Patricians"]),
 mc("In the varna system, Brahmins were traditionally…", "priests and scholars", ["warriors", "traders", "laborers"]),
 mc("Kshatriyas were traditionally…", "rulers and warriors", ["priests", "merchants", "farm laborers"]),
 mc("Jati refers to…", "thousands of birth-based groups often linked to occupation", ["a type of temple", "a royal title", "a kind of tax"]),
 mc("People outside the varna system faced harsh exclusion and were once called \"untouchables\"; many today use the name…", "Dalits", ["Brahmins", "Rajas", "Vaishyas"]),
 mc("B. R. Ambedkar, born a Dalit, helped write…", "India's Constitution", ["the Magna Carta", "the Analects", "the US Bill of Rights"]),
 tf("India's Constitution, in force from 1950, abolished untouchability.", True),
 tf("Under the traditional caste system, people could easily change caste during their lives.", False),
 voc("caste", "A social group a person is born into, traditionally tied to rank, job and marriage."),
 op("How can a law against unfair treatment help, and why might old attitudes take longer to change?", "Explains that laws set rights and penalties, while customs and beliefs change more slowly."),
]),
("China's Traditional Social Order", "El orden social tradicional de China", [
 mc("Traditional Chinese thought ranked four groups: scholars, farmers, artisans and…", "merchants", ["soldiers", "priests", "nobles"]),
 mc("Scholars were ranked highest because they…", "were seen as wise and served in government", ["owned the most land", "fought wars", "made the most money"]),
 mc("Farmers ranked second because they…", "grew the food everyone needed", ["were the richest", "were royalty", "wrote laws"]),
 mc("Merchants ranked lowest because they were seen as…", "making profit without producing goods", ["too religious", "too warlike", "foreign"]),
 mc("To become a government official in imperial China, a man often had to pass the…", "civil service examinations", ["knighthood test", "Olympic Games", "caste council"]),
 mc("The civil service exams mainly tested knowledge of…", "Confucian classics", ["mathematics only", "sword fighting", "foreign languages"]),
 tf("In practice, some merchants in imperial China became very wealthy.", True),
 tf("In the traditional order, merchants were ranked above scholars.", False),
 voc("bureaucracy", "A system of government run by many appointed officials."),
 op("Is a test like the civil service exam a fair way to choose leaders? Explain.", "Weighs merit and open access against the cost of study time that poor families could not always afford."),
]),
("Japan: Samurai and the Tokugawa Order", "Japón: samuráis y el orden Tokugawa", [
 mc("The Tokugawa shogunate ruled Japan from about…", "1603 to 1868", ["1066 to 1215", "1776 to 1865", "1914 to 1945"]),
 mc("The shogun was…", "the top military ruler", ["a Buddhist monk", "a merchant", "a farmer"]),
 mc("Samurai were…", "warriors who served lords called daimyo", ["rice farmers", "fishers", "traders"]),
 mc("The samurai code of honor is often called…", "bushido", ["dharma", "chivalry", "karma"]),
 mc("Under Tokugawa rule, the class order was samurai, farmers, artisans and…", "merchants", ["priests", "scholars", "kings"]),
 mc("During the Meiji era after 1868, Japan…", "ended the samurai class and modernized quickly", ["returned to feudal rule", "closed all schools", "banned trade"]),
 tf("Japan's emperor existed during the Tokugawa period, but the shogun held real power.", True),
 tf("Samurai were the largest group in Tokugawa Japan.", False),
 voc("daimyo", "A powerful lord in feudal Japan who controlled land and samurai."),
 op("Compare the samurai with European knights. How were they alike and different?", "Notes both were warrior classes loyal to lords with honor codes; notes differences in culture, religion or weapons."),
]),
("Aztec and Inca Societies", "Las sociedades azteca e inca", [
 mc("The capital of the Aztec Empire was…", "Tenochtitlan", ["Cusco", "Tikal", "Lima"]),
 mc("The Aztec ruler was called the…", "tlatoani (Huey Tlatoani)", ["Sapa Inca", "pharaoh", "shogun"]),
 mc("Aztec commoners were called…", "macehualtin", ["pipiltin", "samurai", "Brahmins"]),
 mc("The Inca ruler was called the…", "Sapa Inca", ["tlatoani", "sultan", "emperor of Rome"]),
 mc("The Inca system of labor owed to the state was called…", "mit'a", ["tribute of cacao", "feudalism", "jizya"]),
 mc("The Inca kept records with knotted strings called…", "quipu", ["codex", "scrolls", "tablets"]),
 tf("The Inca built a large road network through the Andes.", True),
 tf("Aztec society had no social classes.", False),
 voc("tribute", "Goods or labor that conquered or lower groups had to give to rulers."),
 op("How did the Inca road system help rulers control a large empire?", "Mentions moving armies, messengers, goods and officials across long distances."),
]),
("Colonial Latin America and the Castas", "América Latina colonial y las castas", [
 mc("Peninsulares were people born in…", "Spain or Portugal", ["the Americas", "Africa", "Asia"]),
 mc("Criollos (creoles) were people of Spanish descent born in…", "the Americas", ["Spain", "Africa", "the Philippines"]),
 mc("A mestizo had…", "European and Indigenous ancestry", ["only Spanish ancestry", "only African ancestry", "Asian and African ancestry"]),
 mc("In the colonial order, the highest positions were usually held by…", "peninsulares", ["mestizos", "Indigenous people", "enslaved Africans"]),
 mc("The encomienda system gave Spanish colonists…", "the right to demand labor or tribute from Indigenous people", ["free schooling", "voting rights", "land in Spain"]),
 mc("Many independence leaders, such as Simón Bolívar, were…", "criollos", ["peninsulares", "enslaved people", "Aztec nobles"]),
 tf("The casta system ranked people largely by ancestry and birthplace.", True),
 tf("In colonial Latin America, Indigenous people held most top government posts.", False),
 voc("casta", "A colonial Spanish label that ranked people by their mixed ancestry."),
 op("Why might criollos have wanted independence from Spain?", "Mentions being blocked from top posts, trade limits, or ideas of self-rule."),
]),
("Slavery in the Americas", "La esclavitud en las Américas", [
 mc("The forced shipment of enslaved Africans across the Atlantic is called the…", "transatlantic slave trade", ["Silk Road", "Columbian Exchange only", "Great Migration"]),
 mc("About how many enslaved Africans were shipped across the Atlantic?", "about 12 million", ["about 12 thousand", "about 1 thousand", "about 120 million"]),
 mc("The brutal sea journey from Africa to the Americas was called the…", "Middle Passage", ["Oregon Trail", "Silk Road", "Long March"]),
 mc("The largest number of enslaved Africans was taken to…", "Brazil", ["Canada", "Argentina", "Chile"]),
 mc("Haiti won independence in 1804 after…", "a revolution led by formerly enslaved people", ["a vote in France", "a gift from Spain", "a treaty with Britain"]),
 mc("The last country in the Americas to abolish slavery, in 1888, was…", "Brazil", ["the United States", "Mexico", "Haiti"]),
 tf("The United States abolished slavery with the 13th Amendment in 1865.", True),
 tf("Enslaved people in the Americas never resisted slavery.", False),
 voc("abolition", "Ending a practice by law, especially the ending of slavery."),
 op("What are some ways enslaved people kept their cultures and resisted slavery?", "Mentions music, religion, stories, running away, revolts or community bonds."),
]),
("Industrial Revolution and the Working Class", "La Revolución Industrial y la clase obrera", [
 mc("The Industrial Revolution began in about the 1760s in…", "Britain", ["Japan", "Brazil", "Russia"]),
 mc("During the Industrial Revolution, many people moved from farms to…", "cities with factories", ["castles", "monasteries", "deserts"]),
 mc("The group that grew larger by owning or managing businesses was the…", "middle class", ["serfs", "samurai", "clergy"]),
 mc("Factory workers who earned wages formed the…", "working class", ["nobility", "First Estate", "gentry"]),
 mc("Workers joined together to seek better pay and safer conditions in…", "labor unions", ["guilds of kings", "castles", "monasteries"]),
 mc("One early problem in factories was…", "long hours and child labor", ["too much vacation", "high pay for children", "no machines"]),
 tf("New laws in Britain in the 1800s began to limit child labor.", True),
 tf("The Industrial Revolution began with computers.", False),
 voc("wage", "Money paid to a worker for work, often by the hour or week."),
 op("How did the Industrial Revolution change family life?", "Mentions moving to cities, factory work, children working or new goods."),
]),
("Left and Right: Where the Words Came From", "Izquierda y derecha: de dónde vienen", [
 mc("The terms \"left\" and \"right\" in politics come from…", "seating in the French National Assembly in 1789", ["the Roman Senate", "the US Congress in 1900", "Chinese emperors"]),
 mc("In 1789, members who sat on the right tended to support…", "the king and tradition", ["ending the monarchy fast", "abolishing churches", "rule by workers"]),
 mc("Members who sat on the left tended to want…", "big changes and less power for the king", ["more power for the king", "no changes", "rule by the church"]),
 mc("Today, the \"left\" often stresses…", "equality and government action to reduce inequality", ["only tradition", "ending all government", "one-person rule"]),
 mc("Today, the \"right\" often stresses…", "tradition, free markets and limited government", ["rule by workers' councils", "abolishing private property", "ending all laws"]),
 mc("The middle of the spectrum is called the…", "center", ["edge", "wing tip", "corner"]),
 tf("People can hold some views from the left and some from the right.", True),
 tf("The words left and right first came from seats in China's imperial court.", False),
 voc("political spectrum", "A line used to show political ideas from left to right."),
 op("Why might a single left-right line be too simple to describe what people believe?", "Notes that people mix views on money, freedom and tradition, and that more than one line may be needed."),
]),
("Kinds of Government", "Tipos de gobierno", [
 mc("A government ruled by a king or queen is a…", "monarchy", ["republic", "democracy", "oligarchy"]),
 mc("A constitutional monarchy is one where the monarch…", "has limited power under laws", ["has total power", "is elected every year", "runs the army alone"]),
 mc("A republic is a country where…", "leaders are chosen and there is no king or queen", ["a king rules alone", "the church rules", "no one leads"]),
 mc("A dictatorship is rule by…", "one person or group with unchecked power", ["the voters", "a parliament", "judges only"]),
 mc("Rule by a small group of powerful people is called…", "oligarchy", ["democracy", "anarchy", "monarchy"]),
 mc("Which country is a constitutional monarchy?", "Japan", ["France", "Mexico", "the United States"]),
 tf("A country can be both a republic and a democracy.", True),
 tf("In a dictatorship, courts and newspapers are always free to criticize the ruler.", False),
 voc("republic", "A country where power belongs to the people and their elected leaders, not a monarch."),
 op("Which kind of government best protects people's rights? Give reasons.", "Picks a system and supports it with reasons about voting, checks on power or rights."),
]),
]

BANDS['912'] = [
("Liberalism and Conservatism", "Liberalismo y conservadurismo", [
 mc("Classical liberalism, linked to John Locke, stresses…", "individual rights, limited government and consent of the governed", ["rule by a single party", "abolishing private property", "divine right of kings"]),
 mc("Edmund Burke, often called a founder of modern conservatism, warned against…", "sudden radical change like the French Revolution", ["any government at all", "private property", "gradual reform"]),
 mc("Conservatives often value…", "tradition, stable institutions and gradual change", ["permanent revolution", "abolishing the family", "ending all borders"]),
 mc("In the United States, \"liberal\" today usually means support for…", "a larger government role in social programs", ["an absolute monarchy", "no taxes at all", "one-party rule"]),
 mc("Critics of conservatism argue that it can…", "slow needed reforms", ["cause instant revolution", "end all traditions", "abolish markets"]),
 mc("Critics of liberalism argue that it can…", "weaken community ties or grow government too much", ["ban all elections", "restore feudalism", "end individual rights"]),
 tf("The word \"liberal\" can mean different things in different countries.", True),
 tf("Conservatism always means wanting no change at all.", False),
 voc("conservatism", "A political view that values tradition, order and careful, gradual change."),
 op("Choose a value that liberals and conservatives might share. How might they pursue it differently?", "Names a shared value such as freedom or fairness and describes two fair, different approaches."),
]),
("Socialism and Social Democracy", "Socialismo y socialdemocracia", [
 mc("Socialism holds that major industries should be…", "owned or controlled by society as a whole", ["owned by a king", "free of all rules", "run by churches"]),
 mc("Social democracy aims to…", "keep a market economy with strong welfare programs", ["abolish all markets", "end elections", "cut all taxes"]),
 mc("The Nordic model is linked with countries such as…", "Sweden, Norway and Denmark", ["Japan, Korea and Vietnam", "Chile, Peru and Bolivia", "Egypt, Libya and Sudan"]),
 mc("A key feature of the Nordic model is…", "high taxes paying for broad public services", ["no taxes", "state ownership of all shops", "no labor unions"]),
 mc("Supporters of social democracy say it…", "reduces poverty and inequality", ["ends all markets", "removes all taxes", "abolishes voting"]),
 mc("Critics of social democracy say high taxes can…", "discourage work or investment", ["end democracy", "ban unions", "abolish welfare"]),
 tf("Nordic countries hold free, multi-party elections.", True),
 tf("Social democrats seek to abolish elections and markets.", False),
 voc("welfare state", "A system where government provides services like health care, pensions and support for those in need."),
 op("What are the trade-offs of high taxes paying for many public services?", "Names benefits such as security and equal access and costs such as less take-home pay or less choice."),
]),
("Libertarianism and Nationalism", "Libertarismo y nacionalismo", [
 mc("Libertarians want…", "the smallest government possible and maximum individual freedom", ["a large planned economy", "one-party rule", "a state church"]),
 mc("A libertarian would most likely support…", "lower taxes and fewer regulations", ["state ownership of factories", "censorship of the press", "a single ruling party"]),
 mc("Nationalism is the belief that…", "a nation's people should have their own state and loyalty to it comes first", ["all borders should disappear", "workers of all nations should unite", "kings rule by divine right"]),
 mc("Nationalism helped unify which countries in the 1800s?", "Italy and Germany", ["the USSR and Cuba", "India and Pakistan", "Brazil and Chile"]),
 mc("Nationalism also inspired many colonies to seek…", "independence", ["annexation", "monarchy", "feudalism"]),
 mc("Critics warn that extreme nationalism can lead to…", "hostility toward outsiders and war", ["world government", "no borders", "abolishing the military"]),
 tf("Libertarians may agree with the left on some personal freedoms and with the right on economic freedom.", True),
 tf("Nationalism has only ever led to harmful outcomes.", False),
 voc("nationalism", "Strong loyalty to one's nation and the belief it should govern itself."),
 op("When can national pride bring people together, and when can it become harmful?", "Gives an example of unity (independence, shared effort) and a warning sign (hatred, aggression)."),
]),
("Communism and Marxism-Leninism", "Comunismo y marxismo-leninismo", [
 mc("Karl Marx and Friedrich Engels published The Communist Manifesto in…", "1848", ["1776", "1917", "1989"]),
 mc("Marx argued that history is driven by…", "class struggle", ["the will of kings", "weather patterns", "religious miracles"]),
 mc("Lenin led the Bolshevik Revolution in Russia in…", "1917", ["1789", "1848", "1945"]),
 mc("Under Stalin, millions were sent to forced-labor camps known as the…", "Gulag", ["kibbutz", "commune", "soviet"]),
 mc("Mao Zedong's Great Leap Forward (1958–1962) led to…", "a famine in which tens of millions died", ["rapid food surpluses", "free elections", "the end of communism"]),
 mc("The Khmer Rouge, who ruled Cambodia from 1975 to 1979, caused the deaths of about…", "1.5 to 2 million people", ["a few hundred people", "20 million people", "about 5,000 people"]),
 tf("Cuba and North Korea are still ruled by communist parties today.", True),
 tf("In Marxist-Leninist states, many parties competed freely for power.", False),
 voc("communism", "An ideology aiming at a classless society with shared ownership; in practice, one-party states ran the economy."),
 op("Why did communism's promise of equality attract many people, and what did critics point to in practice?", "Mentions appeal to the poor and workers, and critics' points about one-party rule, repression, famines or shortages."),
]),
("Fascism and Nazism", "Fascismo y nazismo", [
 mc("Fascism first came to power in Italy under…", "Benito Mussolini", ["Francisco Franco", "Joseph Stalin", "Winston Churchill"]),
 mc("Mussolini came to power in…", "1922", ["1848", "1945", "1968"]),
 mc("Fascism glorifies…", "the nation, a single leader and military strength", ["individual rights above all", "international workers' unity", "limited government"]),
 mc("Adolf Hitler and the Nazi Party came to power in Germany in…", "1933", ["1914", "1945", "1918"]),
 mc("The Holocaust was the Nazi murder of about…", "six million Jews, along with millions of others", ["six thousand Jews", "six hundred people", "sixty million Jews"]),
 mc("Francisco Franco ruled Spain as a dictator from 1939 until…", "his death in 1975", ["1945", "1918", "1990"]),
 tf("Fascist governments banned rival parties and controlled the press.", True),
 tf("The Nazis came to power only by armed invasion, never through elections.", False),
 voc("fascism", "A far-right ideology of extreme nationalism, one-party rule, a single leader and suppression of opponents."),
 op("What conditions in 1920s–1930s Europe helped fascist movements gain support?", "Mentions economic crisis, fear of communism, national humiliation after World War I, or weak democracies."),
]),
("Totalitarianism and Anarchism", "Totalitarismo y anarquismo", [
 mc("A totalitarian state seeks to control…", "nearly every part of public and private life", ["only foreign policy", "only taxes", "nothing"]),
 mc("Which regimes are commonly described as totalitarian?", "Stalin's USSR and Hitler's Germany", ["Denmark and Canada", "Switzerland and Iceland", "New Zealand and Ireland"]),
 mc("A common tool of totalitarian states is…", "secret police and mass surveillance", ["independent courts", "a free press", "competitive elections"]),
 mc("Anarchism holds that…", "the state should be abolished and replaced by voluntary cooperation", ["the state should control everything", "kings should rule", "one party should lead"]),
 mc("A well-known anarchist thinker was…", "Pierre-Joseph Proudhon", ["Adam Smith", "Edmund Burke", "Otto von Bismarck"]),
 mc("Critics of anarchism argue that without a state…", "people may lack protection from violence", ["taxes would rise", "kings would return peacefully", "elections would multiply"]),
 tf("Totalitarianism can appear on both the far left and the far right.", True),
 tf("Anarchists want a single, all-powerful government.", False),
 voc("totalitarianism", "A system in which the state aims to control all aspects of life and allows no opposition."),
 op("How do totalitarian and anarchist ideas sit at opposite ends of a scale about state power?", "Explains total state control versus no state, and places other systems between them."),
]),
("Models of the Spectrum", "Modelos del espectro", [
 mc("The \"horseshoe theory\" suggests that…", "the far left and far right resemble each other in some ways", ["the center is always extreme", "there is no left or right", "all views are the same"]),
 mc("A two-axis \"political compass\" measures economics and…", "personal or social freedom versus authority", ["height and weight", "age and income", "north and south"]),
 mc("On a two-axis model, someone favoring free markets and personal freedom would be…", "economically right and libertarian", ["economically left and authoritarian", "centrist on everything", "off the chart"]),
 mc("Critics of horseshoe theory argue that…", "the goals of the far left and far right are very different", ["the spectrum is a circle", "there is no far right", "extremes never use violence"]),
 mc("A person who wants state control of the economy and strict social order would be…", "economically left and authoritarian", ["economically right and libertarian", "anarchist", "centrist"]),
 mc("Why do scholars use more than one axis?", "Because views on economics and personal freedom can vary separately", ["Because there are only two parties", "Because maps need two lines", "Because voting has two steps"]),
 tf("Different models of the spectrum can place the same person in different spots.", True),
 tf("Every political view fits perfectly on a single straight line.", False),
 voc("authoritarian", "Favoring strong central power and limited personal freedom."),
 op("Where do you think a two-axis model is more useful than a single line? Give an example.", "Shows two views that share economics but differ on freedom, or the reverse."),
]),
("Class and Mobility Around the World", "Clase y movilidad en el mundo", [
 mc("Social mobility means…", "the ability to move up or down in social class", ["moving to a new city", "changing political parties", "traveling abroad"]),
 mc("The Gini coefficient measures…", "income inequality in a country", ["population growth", "average temperature", "voter turnout"]),
 mc("A Gini coefficient of 0 would mean…", "perfect equality", ["perfect inequality", "no economy", "high growth"]),
 mc("Latin America has long had some of the world's…", "highest income inequality", ["lowest populations", "coldest climates", "smallest cities"]),
 mc("In the UK, class has traditionally been linked to…", "accent, schooling and family background", ["hair color", "height", "favorite sport only"]),
 mc("In India today, reservations (quotas) set aside places in schools and jobs for…", "historically disadvantaged castes and tribes", ["foreign students", "the wealthy", "government officials' children"]),
 tf("Caste discrimination is illegal in India, though it still affects some people's lives.", True),
 tf("All countries have the same level of social mobility.", False),
 voc("social mobility", "Movement of people between social classes over a lifetime or across generations."),
 op("What factors help a person move up in society? Which are hardest to change?", "Mentions education, family wealth, health, networks, discrimination and policy."),
]),
("Asian Economies", "Economías asiáticas", [
 mc("China's economic reforms under Deng Xiaoping began in…", "1978", ["1949", "1989", "2001"]),
 mc("Deng's reforms allowed…", "private businesses and foreign investment alongside state control", ["full return to monarchy", "abolition of the Communist Party", "no trade"]),
 mc("South Korea's rapid growth after the 1960s was based largely on…", "export industries like steel, ships and electronics", ["fur trading", "gold mining", "tourism only"]),
 mc("Singapore became independent in…", "1965", ["1776", "1918", "1999"]),
 mc("Japan's fast economic growth after World War II is often called the…", "economic miracle", ["Great Leap Forward", "Meiji Restoration", "Cultural Revolution"]),
 mc("India opened its economy with major reforms in…", "1991", ["1947", "1857", "2020"]),
 tf("China's reforms lifted hundreds of millions of people out of extreme poverty.", True),
 tf("China's 1978 reforms ended Communist Party rule.", False),
 voc("market economy", "An economy where prices and production are mainly set by buying and selling, not government orders."),
 op("Why might a country mix government planning with free markets?", "Mentions growth from markets and stability, infrastructure or fairness from government, with trade-offs."),
]),
("Populism and Propaganda", "Populismo y propaganda", [
 mc("Scholars often describe populism as dividing society into…", "\"the pure people\" versus \"the corrupt elite\"", ["cities versus farms only", "old versus young only", "north versus south only"]),
 mc("Populist movements can come from…", "both the left and the right", ["only the left", "only the right", "only monarchies"]),
 mc("Propaganda is…", "information used to push a view, often by appealing to emotion", ["any neutral fact", "a type of vote", "a court ruling"]),
 mc("A common propaganda technique is…", "blaming a scapegoat group for problems", ["citing many sources", "admitting uncertainty", "showing both sides"]),
 mc("One good way to test a claim is to…", "check several independent, reliable sources", ["share it right away", "trust the loudest voice", "read only the headline"]),
 mc("Both Nazi Germany and the Soviet Union used…", "state-controlled media to spread propaganda", ["free, competing newspapers", "open fact-checking", "independent broadcasting"]),
 tf("Propaganda often uses fear, repetition and simple slogans.", True),
 tf("If a message makes you feel strongly, it must be true.", False),
 voc("propaganda", "Messages designed to shape beliefs, often one-sided or misleading."),
 op("Find a slogan or ad. What emotion does it target, and what facts would you want to check?", "Names the emotion, the claim, and specific facts or sources to check."),
]),
]

BANDS['adult'] = [
("Reading the News", "Leer las noticias", [
 mc("A news report should mainly give…", "facts about what happened", ["the writer's feelings only", "ads", "rumors"]),
 mc("An opinion piece gives…", "one writer's view", ["only facts", "the weather", "sports scores"]),
 mc("A headline is…", "the title of a news story", ["the last paragraph", "the author's name", "a photo caption"]),
 mc("A good sign a source is reliable is that it…", "names its sources and corrects mistakes", ["has no author", "uses all capital letters", "asks you to share fast"]),
 mc("\"Clickbait\" is a headline that…", "tries to get clicks more than inform", ["sums up facts fairly", "is always true", "is written by a judge"]),
 mc("Before sharing a surprising story, you should…", "check if other trusted outlets report it", ["share it at once", "add your own details", "trust it if it is funny"]),
 tf("Reading more than one news source can give a fuller picture.", True),
 tf("A photo online is always proof that a story is true.", False),
 voc("bias", "Leaning toward one side in a way that can be unfair."),
 op("Where do you get your news? How do you decide if you trust it?", "Names sources and at least one way to check trust, like comparing outlets."),
]),
("Civic Life", "La vida cívica", [
 mc("A town or city council…", "makes local rules and budgets", ["runs the army", "writes national laws", "prints money"]),
 mc("Jury duty means…", "helping decide a court case as a citizen", ["working for the police", "running for office", "paying a fine"]),
 mc("A public meeting lets residents…", "speak about local issues", ["skip taxes", "arrest people", "change federal law"]),
 mc("Volunteering means…", "giving your time to help without pay", ["working overtime", "voting twice", "paying taxes"]),
 mc("To contact your state lawmaker, you can…", "call, write or email their office", ["only visit Washington", "go to the DMV", "ask a bank"]),
 mc("A petition is…", "a signed request asking leaders for action", ["a type of tax", "a court sentence", "a ballot for president"]),
 tf("People can take part in civic life even when it is not election time.", True),
 tf("Only people with college degrees may speak at a public meeting.", False),
 voc("citizen", "A legal member of a country with rights and duties."),
 op("What is one local issue you care about? How could you take action?", "Names an issue and a step, such as attending a meeting or contacting an official."),
]),
("Voting", "Votar", [
 mc("In the United States, citizens can vote in federal elections starting at age…", "18", ["16", "21", "25"]),
 mc("Before voting, most states require you to…", "register to vote", ["pay a fee", "pass a test", "own land"]),
 mc("A ballot is…", "the form you use to mark your vote", ["a campaign ad", "a tax bill", "a court paper"]),
 mc("A secret ballot means…", "no one can see how you voted", ["you vote out loud", "your boss picks for you", "only some votes count"]),
 mc("A primary election chooses…", "each party's candidates", ["the final winner", "the Supreme Court", "the governor's cabinet"]),
 mc("A good way to learn about candidates is a…", "nonpartisan voter guide", ["single social media post", "rumor from a friend", "random ad"]),
 tf("Local elections, like school board races, can affect daily life.", True),
 tf("You must tell your employer who you voted for.", False),
 voc("nonpartisan", "Not favoring any political party."),
 op("What helps you make a choice when you vote?", "Names steps such as reading guides, comparing positions and checking records."),
]),
("Comparing Governments", "Comparar gobiernos", [
 mc("In a democracy, power comes from…", "the people through voting", ["one ruler's family", "the army", "a single party"]),
 mc("In a dictatorship, people usually…", "cannot freely vote leaders out", ["choose leaders often", "control the courts", "write the laws"]),
 mc("A constitution is…", "a country's basic set of rules and rights", ["a tax form", "a news story", "a party slogan"]),
 mc("Checks and balances mean…", "each branch of government can limit the others", ["one branch holds all power", "no one follows rules", "the army decides"]),
 mc("A free press helps democracy by…", "letting reporters question leaders", ["praising leaders only", "hiding problems", "choosing candidates"]),
 mc("Which is a sign of a one-party state?", "other parties are banned", ["many parties run", "courts are independent", "elections are open"]),
 tf("Many democracies have more than two political parties.", True),
 tf("A country is a democracy just because it holds elections, even if they are not fair.", False),
 voc("constitution", "The written plan for how a government works and what rights people have."),
 op("What do you think makes an election fair?", "Mentions secret ballots, open choices, honest counting and free press."),
]),
("Ideas Left to Right", "Ideas de izquierda a derecha", [
 mc("People on the left often want government to…", "do more to reduce inequality", ["do nothing", "restore kings", "end elections"]),
 mc("People on the right often want…", "lower taxes and respect for tradition", ["state control of all business", "no borders", "no laws"]),
 mc("Socialists believe key industries should be…", "shared or run for the public good", ["owned by a king", "left totally unregulated", "closed"]),
 mc("Libertarians want…", "as little government as possible", ["a very large government", "one ruler", "state-run media"]),
 mc("A moderate or centrist person…", "mixes views from both sides", ["always agrees with the left", "always agrees with the right", "never votes"]),
 mc("In the US, the two largest parties are the…", "Democrats and Republicans", ["Liberals and Tories", "Labour and Greens", "Socialists and Monarchists"]),
 tf("Reasonable people can disagree about the best role for government.", True),
 tf("Everyone in a political party agrees on every issue.", False),
 voc("moderate", "Holding views near the middle, not at either extreme."),
 op("Talk with someone who sees politics differently. What is one thing you agree on?", "Names a shared value or goal and shows respectful listening."),
]),
("The Extremes: Lessons from History", "Los extremos: lecciones de la historia", [
 mc("Fascism is a far-right system that…", "puts one leader and the nation above all rights", ["protects free elections", "shares power widely", "limits the army"]),
 mc("Nazi Germany carried out the Holocaust, murdering about…", "six million Jews", ["six thousand Jews", "sixty Jews", "six hundred thousand people in all"]),
 mc("Soviet leader Joseph Stalin sent millions of people to…", "forced-labor camps called the Gulag", ["free universities", "farms they owned", "vacation towns"]),
 mc("The famine during China's Great Leap Forward killed…", "tens of millions of people", ["a few hundred people", "no one", "only soldiers"]),
 mc("The Khmer Rouge carried out a genocide in…", "Cambodia", ["Chile", "Poland", "Kenya"]),
 mc("Both far-left and far-right dictatorships have…", "jailed critics and banned opposition", ["protected a free press", "held fair elections", "had independent courts"]),
 tf("Extreme regimes on both the left and the right have killed millions.", True),
 tf("Only one side of the political spectrum has ever produced dictators.", False),
 voc("genocide", "The deliberate killing of a large group of people because of who they are."),
 op("Why is it important to learn about crimes by extreme governments on both sides?", "Mentions honoring victims, spotting warning signs and protecting rights."),
]),
("Warning Signs of Extremism", "Señales de alerta del extremismo", [
 mc("A warning sign of extremism is…", "calling a whole group of people enemies", ["listening to other views", "checking facts", "voting peacefully"]),
 mc("Extremist groups often say that…", "violence is the only answer", ["compromise is good", "courts should decide", "elections matter"]),
 mc("Online, extremist recruiters often target people who feel…", "lonely or angry", ["busy and content", "well-informed", "connected to family"]),
 mc("A leader who attacks judges and the press may be trying to…", "remove checks on their power", ["protect democracy", "share power", "hold fair elections"]),
 mc("Dehumanizing language means…", "describing people as less than human", ["using simple words", "speaking two languages", "being polite"]),
 mc("If someone you know is drawn toward extremism, a helpful first step is to…", "stay in touch and listen calmly", ["cut them off at once", "mock them", "share their posts"]),
 tf("Extremist ideas can come from the far left or the far right.", True),
 tf("Disagreeing strongly with the government is itself extremism.", False),
 voc("extremism", "Holding ideas far outside the mainstream, often with support for force or violence."),
 op("What makes the difference between strong opinions and dangerous extremism?", "Mentions violence, hatred of groups, rejecting elections or rights."),
]),
("Class and Getting Ahead", "La clase social y salir adelante", [
 mc("Social class is often linked to…", "income, education and job type", ["eye color", "height", "favorite food"]),
 mc("Upward mobility means…", "moving to a better economic position", ["moving to a new state", "losing a job", "changing your name"]),
 mc("One of the strongest paths to higher pay is…", "more education or job training", ["luck alone", "lottery tickets", "moving every year"]),
 mc("Inequality means…", "big gaps in income or wealth between groups", ["everyone earns the same", "no one works", "prices never change"]),
 mc("A community college can help adults…", "earn job skills and credits at lower cost", ["skip all classes", "avoid taxes", "get free houses"]),
 mc("Long ago, in systems like feudalism or caste, a person's place was mostly set by…", "birth", ["test scores", "votes", "choice"]),
 tf("Many adults return to school and improve their job options.", True),
 tf("A person's future is fully decided by the family they were born into.", False),
 voc("mobility", "The ability to move or change position, such as moving up in income."),
 op("What is one step that could help you or someone you know get ahead?", "Names a concrete step like a class, certificate, mentor or budgeting."),
]),
("Cultures Across the World", "Culturas del mundo", [
 mc("Culture includes…", "language, food, beliefs, customs and art", ["only money", "only weather", "only laws"]),
 mc("Ramadan is a month of fasting in…", "Islam", ["Hinduism", "Buddhism", "Judaism"]),
 mc("The world's most widely spoken first language is…", "Mandarin Chinese", ["French", "German", "Italian"]),
 mc("Lunar New Year is widely celebrated in…", "China, Korea and Vietnam", ["Brazil, Chile and Peru", "Norway and Sweden", "Egypt and Morocco"]),
 mc("Quechua is an Indigenous language spoken in…", "Peru and the Andes", ["Japan", "Kenya", "Russia"]),
 mc("Learning about other cultures can help you…", "work and live well with many people", ["forget your own culture", "stop voting", "avoid neighbors"]),
 tf("Many cultures in the Middle East, Africa and Asia have very long written histories.", True),
 tf("A culture stays exactly the same forever.", False),
 voc("diversity", "Many different kinds of people, cultures and ideas together."),
 op("Share a tradition from your family or culture. What does it mean to you?", "Names a tradition and its meaning or origin."),
]),
("Rights and Responsibilities as Adults", "Derechos y responsabilidades de los adultos", [
 mc("Freedom of speech in the US is protected by the…", "First Amendment", ["Fifth Amendment", "Tenth Amendment", "Declaration of Independence"]),
 mc("Paying taxes is a…", "responsibility of residents", ["crime", "choice with no rules", "right only for the rich"]),
 mc("The right to a fair trial means…", "you can defend yourself before a judge or jury", ["you are always guilty", "police decide your case", "no lawyer is allowed"]),
 mc("The Universal Declaration of Human Rights says rights belong to…", "every person", ["only citizens of rich nations", "only adults over 30", "only voters"]),
 mc("Respecting others' rights means…", "allowing others to speak even if you disagree", ["silencing people you dislike", "taking their property", "ignoring laws"]),
 mc("If you think your rights were violated, you can seek help from…", "legal aid or a civil rights group", ["a random website", "a store clerk", "nobody"]),
 tf("Rights come with responsibilities to respect others.", True),
 tf("Only citizens have any legal rights in the United States.", False),
 voc("civil rights", "Rights that protect people from unfair treatment by government or others."),
 op("Which right matters most to you, and what duty goes with it?", "Names a right and a related responsibility."),
]),
]
