# The Measured Step (martial arts history) — Daily Drafts banks. History only: rooms, codes,
# schools and who was let in. No technique. Every item comes from the course's own reviewed
# lessons (see hist_banks.py); this file only adds the Spanish strand names and a third wrong
# choice for each K–2 question.
from hist_banks import make

ES = {
 # K–2
 "Rooms That Are Circles": "Espacios que son círculos",
 "Long Strips and Soft Mats": "Pistas largas y tapetes suaves",
 "Songs That Open the Room": "Canciones que abren el espacio",
 "Jackets for Class": "Chaquetas para la clase",
 "Different Rooms, Different Clothes": "Otros espacios, otra ropa",
 "Japan and Okinawa": "Japón y Okinawa",
 "Thailand, Europe and the Olympics": "Tailandia, Europa y los Juegos Olímpicos",
 "Salutes, Hands and Bells": "Saludos, manos y campanas",
 "Pictures From Long Ago": "Imágenes de hace mucho tiempo",
 "Stories and Places": "Historias y lugares",
 # 3–5
 "Wrestlers on Old Walls": "Luchadores en muros antiguos",
 "A State Association Steps In": "Una asociación estatal toma parte",
 "What a Date Measures": "Lo que mide una fecha",
 "From Tokyo to the World": "De Tokio al mundo",
 "Scores and Safety": "Puntos y seguridad",
 "From Island to Capital": "De la isla a la capital",
 "Korea Before Taekwondo": "Corea antes del taekwondo",
 "Before There Were Schools": "Antes de que hubiera escuelas",
 "From Backyard to Academy": "Del patio a la academia",
 "Club, College and Town Gym": "Club, universidad y gimnasio del pueblo",
 # 6–8
 "One Word, Many Arts": "Una palabra, muchas artes",
 "Two Codes, One Sport Body": "Dos códigos, un organismo deportivo",
 "Reading a School's Own Papers": "Leer los documentos de una escuela",
 "Objects of the Gym": "Objetos del gimnasio",
 "Arnis, Eskrima, Kali": "Arnis, eskrima, kali",
 "A Law for Schools": "Una ley para las escuelas",
 "Rings That Still Change": "Rings que siguen cambiando",
 "Words on the Doors": "Palabras en las puertas",
 "Campus Judo and the Boxing Gym": "Judo universitario y el gimnasio de boxeo",
 "Doors Open in 1965": "Puertas abiertas en 1965",
 # 9–12
 "Scrolls Before Belts": "Pergaminos antes de los cinturones",
 "Staying on the Program": "Seguir en el programa",
 "Mixed Contests Before a League": "Combates mixtos antes de una liga",
 "Drill Halls Before PE": "Salas de instrucción antes de la educación física",
 "Judo and Sumo in School Rooms": "Judo y sumo en las escuelas",
 "Schools Far From Home": "Escuelas lejos de casa",
 "Who Draws the Categories": "Quién traza las categorías",
 "Two Origins": "Dos orígenes",
 "Prizes Kept in Cases": "Premios guardados en vitrinas",
 "Nations That Closed the Ring": "Naciones que cerraron el ring",
 # Adult
 "Names Held by Nations": "Nombres en manos de naciones",
 "After the Founder Dies": "Cuando muere el fundador",
 "Slavery and Song": "Esclavitud y canción",
 "Hard Topics, Told Plainly": "Temas difíciles, contados con claridad",
 "Armed Sport and Flowing Practice": "Deporte con armas y práctica fluida",
 "Diaspora and Modern Mix": "Diáspora y mezcla moderna",
 "Who May Start": "Quién puede empezar",
 "Books That Survived": "Libros que sobrevivieron",
 "A Title Crosses the Color Line": "Un título cruza la barrera racial",
 "A Champion Refuses the Draft": "Un campeón rechaza el reclutamiento",
}

EXTRA = {
 "What is a roda?": "a fencing mask",
 "Where does capoeira come from?": "Korea",
 "Who made capoeira?": "fencers in Paris",
 "What is a dohyo?": "a drum",
 "What happens if a sumo wrestler steps out of the ring?": "he gets a belt",
 "Where does sumo come from?": "Thailand",
 "What is a piste?": "a drum",
 "How long is a fencing strip?": "1,000 meters",
 "When was fencing first in the modern Olympics?": "1992",
 "When did judo begin?": "2014",
 "What are tatami?": "swords",
 "What shape is marked on an Olympic wrestling mat?": "a star",
 "What language are capoeira songs sung in?": "Korean",
 "What is call and response?": "Everyone reads a book.",
 "What do many capoeira songs tell about?": "fencing masks",
 "Where does Muay Thai come from?": "Japan",
 "What is the wai khru?": "a sumo ring",
 "What plays music at many Muay Thai matches in Thailand?": "a pandeiro",
 "Who started judo?": "Funakoshi Gichin",
 "What is a judogi?": "a boxing bell",
 "What was Kanō's school called?": "the dojang",
 "Where did karate grow?": "Thailand",
 "Which clothes did karate students wear in Tokyo?": "a sumo belt",
 "Who was one karate teacher in Tokyo in the 1920s?": "the Marquess of Queensberry",
 "What is a singlet?": "a fencing mask",
 "When did Illinois girls have their first state wrestling finals?": "1882",
 "Who runs high school wrestling in Illinois?": "the FIE",
 "What color do fencers wear?": "green",
 "Where did fencing grow?": "Korea",
 "What helped judges score at the 1936 Olympics?": "drums",
 "What does do mean in judo?": "circle",
 "What does ju mean?": "loud",
 "Where did Kanō choose the name judo?": "Paris",
 "What was the old kingdom on Okinawa called?": "Brazil",
 "What does karate mean?": "big circle",
 "When did Japan take over the Ryukyu kingdom?": "1100",
 "What does muay mean?": "song",
 "What is a mongkon?": "a sumo ring",
 "What does touché mean?": "circle",
 "Where was the FIE made?": "Bangkok",
 "What language are many fencing words in?": "Portuguese",
 "When did judo join the Olympics?": "1867",
 "Which art was in the first modern Games in 1896?": "judo",
 "Where did taekwondo become an Olympic medal sport?": "Chicago",
 "Where did fencing grow from?": "drum schools in Thailand",
 "Who does a fencer salute?": "the fans only",
 "Since when has fencing been in every modern Olympics?": "2020",
 "When do wrestlers shake hands?": "only at lunch",
 "Who writes the rules for Olympic wrestling?": "the FIE",
 "What does the wrestling handshake say?": "the gym is closed",
 "What starts a round in boxing?": "a drum song",
 "How long was a round in the Queensberry Rules?": "one hour",
 "Who rings the boxing bell?": "a fan in the seats",
 "Where is Beni Hasan?": "Chicago",
 "What do the Beni Hasan tomb walls show?": "sumo rings",
 "About how old are the Beni Hasan tombs?": "four years",
 "Where were the ancient Olympics held?": "Brazil",
 "What did Greek artists paint sports on?": "fencing masks",
 "Which sport joined the ancient games first?": "judo",
 "When was the Nihon Shoki finished?": "2014",
 "What is a legend?": "a new rule",
 "What do historians do with legends?": "sell them",
 "What does a museum do?": "rings the bell",
 "Which city has a Sumo Museum?": "Paris",
 "What does the judo museum at the Kodokan tell about?": "Chicago parks",
}

BANDS = make('mar', ES, EXTRA)
