# Medicine and Health — Daily Drafts banks. The body, staying healthy, and the world's medical
# traditions (Western biomedicine, Traditional Chinese Medicine, Ayurveda, Unani, Kampo, Indigenous
# healing). Traditions are described respectfully ("Ayurveda holds…"); evidence is stated plainly.
# No dosing advice. Always point to a doctor, nurse or trusted adult.
def mc(q, a, w): return ["mc", q, a, w]
def tf(q, v): return ["tf", q, v]
def voc(w, d): return ["voc", w, d]
def op(q, m): return ["open", q, m]

BANDS = {}

BANDS['k2'] = [
("Washing Hands", "Lavarse las manos", [
 mc("We wash hands with soap and…", "water", ["mud", "juice", "sand"]),
 mc("When should you wash your hands?", "before you eat", ["while you sleep", "never", "only on Sunday"]),
 mc("Wash your hands after you use the…", "toilet", ["crayons", "swing", "window"]),
 mc("How long should you scrub your hands?", "about 20 seconds", ["one second", "one hour", "no time"]),
 mc("A song can help you scrub long…", "enough", ["too little", "never", "backward"]),
 mc("After washing, dry your hands with a…", "clean towel", ["dirty sock", "your hair", "the floor"]),
 tf("Soap helps wash germs away.", True),
 tf("You never need to wash your hands.", False),
 voc("soap", "Something that helps wash dirt and germs away."),
 op("When do you wash your hands each day?", "Any time, such as before eating or after the toilet."),
]),
("Germs", "Los microbios", [
 mc("Germs are too small to…", "see with your eyes", ["hear", "exist", "touch you"]),
 mc("Some germs can make you…", "sick", ["taller", "faster", "purple"]),
 mc("When you sneeze, cover it with your…", "elbow", ["friend", "food", "book"]),
 mc("A tissue goes in the…", "trash can", ["pocket forever", "sink", "lunch box"]),
 mc("If you feel sick, tell a…", "grown-up", ["pet", "toy", "tree"]),
 mc("Sharing a cup can share…", "germs", ["stickers", "songs", "games"]),
 tf("Some germs can make people sick.", True),
 tf("You can see germs with just your eyes.", False),
 voc("germ", "A tiny living thing that can make you sick."),
 op("How can you keep germs from spreading?", "Washing hands, covering sneezes, or staying home when sick."),
]),
("Happy Teeth", "Dientes felices", [
 mc("Brush your teeth two times each…", "day", ["year", "month", "week"]),
 mc("We brush teeth with a toothbrush and…", "toothpaste", ["glue", "paint", "jam"]),
 mc("A tooth doctor is called a…", "dentist", ["baker", "pilot", "farmer"]),
 mc("Lots of sweet candy can hurt your…", "teeth", ["shoes", "hair", "ears"]),
 mc("Floss cleans between your…", "teeth", ["toes", "fingers", "ears"]),
 mc("Baby teeth fall out to make room for…", "grown-up teeth", ["no teeth", "candy", "hair"]),
 tf("Brushing helps keep teeth healthy.", True),
 tf("You should never visit a dentist.", False),
 voc("dentist", "A doctor who cares for teeth."),
 op("How do you care for your teeth?", "Brushing, flossing, visiting the dentist, or fewer sweets."),
]),
("Sleep and Rest", "Dormir y descansar", [
 mc("Sleep helps your body…", "grow and rest", ["shrink", "get sick", "stop working"]),
 mc("Kids need lots of sleep each…", "night", ["minute", "lunch", "recess"]),
 mc("Before bed, a calm thing to do is…", "read a book", ["run fast", "eat candy", "yell"]),
 mc("A good bedroom for sleep is…", "dark and quiet", ["loud and bright", "full of TV", "very hot"]),
 mc("If you sleep well, you feel…", "ready to learn", ["grumpy all day", "sick", "sleepy at school"]),
 mc("Screens right before bed can make sleep…", "harder", ["easier", "longer", "sweeter"]),
 tf("Sleep helps your body grow.", True),
 tf("Kids do not need sleep.", False),
 voc("rest", "A quiet time to let your body relax."),
 op("What helps you fall asleep?", "Any calm habit, such as a story, a song or a hug."),
]),
("Healthy Food", "Comida saludable", [
 mc("Which food is a fruit?", "apple", ["bread", "cheese", "egg"]),
 mc("Which food is a vegetable?", "carrot", ["cookie", "milk", "chicken"]),
 mc("The best drink for thirst is…", "water", ["soda", "syrup", "ketchup"]),
 mc("Milk and cheese help build strong…", "bones", ["clouds", "shoes", "rocks"]),
 mc("A healthy plate has many…", "colors of food", ["candies", "chips only", "sodas"]),
 mc("Sweets are best as a…", "sometimes treat", ["every meal", "breakfast only", "medicine"]),
 tf("Fruits and vegetables help you grow.", True),
 tf("Candy is the best food for every meal.", False),
 voc("vegetable", "A plant food like a carrot or pea."),
 op("What is your favorite healthy food?", "Any fruit, vegetable, grain, or protein food."),
]),
("Moving Your Body", "Mover el cuerpo", [
 mc("Playing and running make your heart…", "strong", ["weak", "small", "sleepy"]),
 mc("Before you run, it helps to…", "warm up", ["eat candy", "nap", "sit still"]),
 mc("After playing hard, drink some…", "water", ["soda", "syrup", "paint"]),
 mc("Which one is exercise?", "dancing", ["sleeping", "watching TV", "sitting"]),
 mc("Exercise can make you feel…", "happy", ["sad on purpose", "sick", "sleepy all day"]),
 mc("When you ride a bike, wear a…", "helmet", ["hat made of paper", "crown", "mask"]),
 tf("Moving your body is good for you.", True),
 tf("Exercise makes your heart weak.", False),
 voc("exercise", "Moving your body to stay strong."),
 op("What is your favorite way to move?", "Any activity, such as dancing, running or swimming."),
]),
("Feelings and Calm Breathing", "Sentimientos y respiración tranquila", [
 mc("When you feel upset, you can take a…", "slow deep breath", ["fast run away", "loud yell", "bite"]),
 mc("Smell the flower, blow out the…", "candle", ["car", "door", "shoe"]),
 mc("All feelings are…", "okay to have", ["bad", "wrong", "silly"]),
 mc("If you feel sad, you can talk to a…", "trusted grown-up", ["wall", "stranger online", "nobody"]),
 mc("A calm corner is a place to…", "feel calm again", ["get in trouble", "shout", "hide toys"]),
 mc("Belly breathing means your belly moves…", "out and in", ["side to side", "not at all", "up the wall"]),
 tf("Slow breaths can help you feel calm.", True),
 tf("Some feelings are not allowed.", False),
 voc("calm", "Feeling quiet and peaceful inside."),
 op("What helps you feel calm?", "Any calm tool, such as breathing, a hug, music or a quiet spot."),
]),
("Health Helpers", "Ayudantes de la salud", [
 mc("A doctor helps you when you are…", "sick or hurt", ["hungry for pizza", "bored", "at the park"]),
 mc("A nurse works with…", "doctors", ["pilots", "bakers", "clowns"]),
 mc("A doctor for kids is a…", "pediatrician", ["plumber", "painter", "farmer"]),
 mc("A doctor listens to your heart with a…", "stethoscope", ["spoon", "phone", "drum"]),
 mc("A pharmacist gives out…", "medicine", ["pets", "books", "shoes"]),
 mc("An eye doctor checks how well you…", "see", ["jump", "sing", "eat"]),
 tf("Nurses help people feel better.", True),
 tf("Dentists take care of your feet.", False),
 voc("nurse", "A person who cares for sick or hurt people."),
 op("Which health helper would you like to be?", "Any helper, with a reason, such as a nurse who helps people."),
]),
("Staying Safe", "Mantenerse seguro", [
 mc("Medicine is only taken with help from a…", "grown-up", ["friend", "pet", "sibling"]),
 mc("In the car, always wear your…", "seat belt", ["bathrobe", "slippers", "crown"]),
 mc("Before crossing the street, look…", "both ways", ["at the sky", "down only", "nowhere"]),
 mc("If you find pills, you should…", "tell a grown-up", ["eat them", "hide them", "share them"]),
 mc("Hot stoves can…", "burn you", ["tickle you", "cool you", "sing"]),
 mc("In an emergency, grown-ups call…", "911", ["a pizza shop", "a friend", "nobody"]),
 tf("A seat belt keeps you safe.", True),
 tf("Medicine is candy.", False),
 voc("safe", "Protected from getting hurt."),
 op("What is one safety rule you know?", "Any safety rule, such as seat belts or looking both ways."),
]),
("Checkups and Old Ways", "Chequeos y costumbres antiguas", [
 mc("At a checkup, the doctor measures how…", "tall you are", ["loud you are", "fast you eat", "old your shoes are"]),
 mc("A checkup is when you visit a doctor while…", "healthy", ["asleep", "at school", "on a trip"]),
 mc("In India, people have done yoga for a…", "very long time", ["few days", "week", "minute"]),
 mc("Many people in China drink warm…", "tea", ["paint", "glue", "soap"]),
 mc("Tai chi is slow, gentle…", "moving", ["shouting", "eating", "sleeping"]),
 mc("Long ago, people used plants called…", "herbs", ["rocks", "cars", "clouds"]),
 tf("China and India have old ways to stay well.", True),
 tf("A checkup is only when you are very sick.", False),
 voc("checkup", "A visit to check that you are well."),
 op("What happens at a checkup?", "Measuring height and weight, listening to the heart, or asking questions."),
]),
]

BANDS['35'] = [
("Body Systems", "Sistemas del cuerpo", [
 mc("Which organ pumps blood around the body?", "heart", ["lungs", "stomach", "brain"]),
 mc("Which organs help you breathe?", "lungs", ["kidneys", "bones", "liver"]),
 mc("The skeleton is made of…", "bones", ["muscles", "blood", "skin"]),
 mc("Which organ is the control center of the body?", "brain", ["heart", "stomach", "lungs"]),
 mc("The digestive system breaks down…", "food", ["bones", "air", "light"]),
 mc("Muscles help your body…", "move", ["think", "see", "hear"]),
 tf("The heart is a muscle.", True),
 tf("The lungs digest food.", False),
 voc("organ", "A body part that does a special job, like the heart or lungs."),
 op("Pick one body system and explain its job.", "Names a system and describes its job correctly."),
]),
("Nutrition", "Nutrición", [
 mc("Which nutrient helps build muscles?", "protein", ["sugar", "salt", "water only"]),
 mc("Calcium is important for…", "bones and teeth", ["hair color", "eyesight only", "height of ears"]),
 mc("Whole grains like oatmeal give lasting…", "energy", ["sugar crashes", "headaches", "colds"]),
 mc("Which food is a good source of vitamin C?", "orange", ["butter", "bread", "rice"]),
 mc("Drinks with lots of added sugar are best…", "only sometimes", ["at every meal", "instead of water", "before bed"]),
 mc("A nutrition label tells you…", "what is in a food", ["who cooked it", "where to buy it", "its price"]),
 tf("Water is important for your body.", True),
 tf("A healthy diet means eating only one food.", False),
 voc("nutrient", "Something in food that the body needs to grow and work."),
 op("Plan a healthy lunch. Why is it healthy?", "Includes several food groups and explains how they help."),
]),
("Vaccines and Germs", "Vacunas y microbios", [
 mc("A vaccine helps your body…", "learn to fight a germ", ["grow taller", "digest food", "sleep"]),
 mc("Bacteria and viruses are two kinds of…", "germs", ["vitamins", "bones", "cells of plants"]),
 mc("Vaccines are usually given as a…", "shot", ["sandwich", "haircut", "song"]),
 mc("The body's system that fights germs is the…", "immune system", ["skeletal system", "digestive system", "hair system"]),
 mc("When many people are vaccinated, germs…", "spread less", ["spread more", "grow bigger", "turn into food"]),
 mc("Who decides which vaccines you get?", "doctors and families together", ["only kids", "your friends", "a TV ad"]),
 tf("Vaccines help protect people from some diseases.", True),
 tf("Vaccines are a kind of candy.", False),
 voc("vaccine", "Medicine that teaches your body to fight a germ."),
 op("Why do you think vaccines help a whole community?", "Fewer people get sick, so germs spread less and protect others."),
]),
("First Aid Basics", "Primeros auxilios", [
 mc("For a small cut, first…", "wash it gently with water", ["ignore it", "put dirt on it", "pick at it"]),
 mc("A bandage keeps a cut…", "clean", ["hot", "dirty", "open"]),
 mc("For a small burn, cool it with…", "cool running water", ["butter", "ice cream", "hot water"]),
 mc("If someone is badly hurt, you should…", "get a grown-up or call 911", ["walk away", "wait a day", "take a photo"]),
 mc("A nosebleed: sit up, lean forward, and…", "pinch the soft part of the nose", ["lie flat", "tip head far back", "blow hard"]),
 mc("A first aid kit holds things like…", "bandages", ["toys", "snacks", "pencils"]),
 tf("Calling 911 is for emergencies.", True),
 tf("Butter is the best thing for a burn.", False),
 voc("first aid", "Simple help given right away to someone hurt or sick."),
 op("What would you do if a friend fell and scraped a knee?", "Stay calm, get a grown-up, wash and cover the scrape."),
]),
("Hippocrates", "Hipócrates", [
 mc("Hippocrates was a doctor from ancient…", "Greece", ["China", "Mexico", "Japan"]),
 mc("Hippocrates is called the father of…", "Western medicine", ["music", "math", "farming"]),
 mc("Hippocrates taught doctors to…", "watch patients carefully", ["guess wildly", "blame spirits only", "never listen"]),
 mc("New doctors often take an oath named after…", "Hippocrates", ["Galen", "Pasteur", "Nightingale"]),
 mc("Hippocrates believed sickness had…", "natural causes", ["no causes", "only magic causes", "star causes only"]),
 mc("Hippocrates lived about…", "2,400 years ago", ["240 years ago", "24 years ago", "24,000 years ago"]),
 tf("Hippocrates lived in ancient Greece.", True),
 tf("Hippocrates invented vaccines.", False),
 voc("oath", "A serious promise."),
 op("Why is it good for doctors to make a promise to help?", "Patients can trust them; doctors aim to help and not harm."),
]),
("Florence Nightingale", "Florence Nightingale", [
 mc("Florence Nightingale was a famous…", "nurse", ["pilot", "painter", "queen"]),
 mc("She was known as the Lady with the…", "Lamp", ["Crown", "Horse", "Sword"]),
 mc("She cared for soldiers during the…", "Crimean War", ["Civil War", "World War II", "Moon landing"]),
 mc("Nightingale showed that clean hospitals…", "save lives", ["make germs stronger", "do not matter", "cost nothing"]),
 mc("She used charts and numbers, which is…", "statistics", ["poetry", "painting", "cooking"]),
 mc("Florence Nightingale's home country was…", "Britain", ["Brazil", "China", "Egypt"]),
 tf("Florence Nightingale helped make nursing a respected job.", True),
 tf("Florence Nightingale said hospitals should be dirty.", False),
 voc("nurse", "A trained person who cares for the sick."),
 op("How did Florence Nightingale use numbers to help people?", "She collected data and made charts to show clean care saved lives."),
]),
("Louis Pasteur", "Louis Pasteur", [
 mc("Louis Pasteur was a scientist from…", "France", ["Italy", "India", "Canada"]),
 mc("Pasteur showed that many diseases are caused by…", "germs", ["bad air only", "the moon", "cold feet"]),
 mc("Heating milk to kill germs is called…", "pasteurization", ["freezing", "fermenting", "boiling over"]),
 mc("Pasteur made a vaccine for…", "rabies", ["the flu", "a cold", "headaches"]),
 mc("Pasteur used a tool that makes tiny things look big, a…", "microscope", ["telescope", "thermometer", "megaphone"]),
 mc("Pasteur's ideas are part of…", "germ theory", ["gravity", "weather science", "music theory"]),
 tf("Pasteurization helps make milk safer.", True),
 tf("Pasteur said germs do not exist.", False),
 voc("microscope", "A tool that makes very small things look bigger."),
 op("How does Pasteur's work help you today?", "Safer milk and food, vaccines, and knowing to wash hands."),
]),
("Chinese Medicine", "Medicina china", [
 mc("Traditional Chinese Medicine began in…", "China", ["Peru", "Norway", "Kenya"]),
 mc("Acupuncture uses very thin…", "needles", ["rocks", "feathers", "strings"]),
 mc("Tai chi is a slow form of…", "exercise", ["cooking", "painting", "singing"]),
 mc("Traditional Chinese Medicine teaches about an energy it calls…", "qi", ["dosha", "atom", "vitamin"]),
 mc("Chinese medicine often uses plants called…", "herbs", ["metals", "plastics", "shells only"]),
 mc("Scientists have not found qi with…", "measuring tools", ["their own eyes only", "maps", "clocks"]),
 tf("Tai chi is gentle movement that many people enjoy.", True),
 tf("Scientists have proven qi is a measurable energy.", False),
 voc("acupuncture", "A Chinese practice using thin needles placed in the skin."),
 op("Why should a family tell a doctor about herbs they use?", "Some herbs mix badly with medicines; the doctor can keep them safe."),
]),
("Ayurveda and Yoga", "Ayurveda y yoga", [
 mc("Ayurveda is a traditional medicine from…", "India", ["Spain", "Japan", "Chile"]),
 mc("Ayurveda holds that people have three…", "doshas", ["hearts", "brains", "shadows"]),
 mc("Yoga includes poses and…", "breathing", ["shouting", "racing", "juggling"]),
 mc("The word Ayurveda means roughly…", "knowledge of life", ["fast food", "big river", "strong bones"]),
 mc("Doshas are an idea from Ayurveda, not something…", "measured by science", ["written in books", "taught in India", "talked about"]),
 mc("Yoga can help many people feel…", "calm and flexible", ["angry", "sick", "stiff"]),
 tf("Ayurveda comes from India.", True),
 tf("Doshas have been measured in a science lab.", False),
 voc("yoga", "An old practice from India with poses, breathing and rest."),
 op("How can gentle stretching or breathing help you?", "It can help you feel calm, loose and focused."),
]),
("Mental Health", "Salud mental", [
 mc("Mental health is about your…", "thoughts and feelings", ["shoe size", "hair color", "height"]),
 mc("If you feel worried a lot, it helps to…", "talk to a trusted adult", ["keep it secret forever", "stop eating", "stay up late"]),
 mc("A school counselor helps kids with…", "feelings and problems", ["fixing cars", "painting walls", "cooking lunch"]),
 mc("Which habit helps mental health?", "getting enough sleep", ["skipping meals", "never going outside", "no friends"]),
 mc("Asking for help is a sign of…", "strength", ["weakness", "trouble", "silliness"]),
 mc("Naming your feeling, like \"I feel nervous,\" can help you…", "calm down", ["get angrier", "forget it", "feel worse"]),
 tf("Everyone has hard days sometimes.", True),
 tf("You should never ask for help with feelings.", False),
 voc("counselor", "A person trained to help with feelings and problems."),
 op("Who are three people you could go to for help?", "Names trusted adults, such as a parent, teacher or counselor."),
]),
]

BANDS['68'] = [
("Ancient Egypt and Greece", "Egipto y Grecia antiguos", [
 mc("Ancient Egyptian medical writings were recorded on…", "papyrus", ["paper made of plastic", "clay only", "silk"]),
 mc("The Edwin Smith Papyrus mostly describes…", "treating injuries", ["star charts", "recipes for bread", "tax records"]),
 mc("The Ebers Papyrus lists many…", "remedies", ["battles", "songs", "kings"]),
 mc("Hippocrates taught that disease comes from…", "natural causes", ["angry gods only", "stars only", "nothing"]),
 mc("The four humors were blood, phlegm, yellow bile and…", "black bile", ["saliva", "sweat", "tears"]),
 mc("Humoral theory said illness came from humors being…", "out of balance", ["too clean", "too cold only", "missing germs"]),
 tf("Humoral theory was later replaced by modern science.", True),
 tf("The four humors are still the basis of modern medicine.", False),
 voc("papyrus", "A paper-like material made from a plant by ancient Egyptians."),
 op("What did Hippocrates get right, and what did later science change?", "Natural causes and careful observation were right; the humors were replaced."),
]),
("Galen and Ibn Sina", "Galeno e Ibn Sina", [
 mc("Galen was a doctor in the…", "Roman Empire", ["Aztec Empire", "Ming dynasty", "Mughal Empire"]),
 mc("Galen learned anatomy partly by dissecting…", "animals", ["statues", "plants only", "rocks"]),
 mc("Ibn Sina is also known in Europe as…", "Avicenna", ["Averroes", "Galen", "Vesalius"]),
 mc("Ibn Sina's famous medical book is the…", "Canon of Medicine", ["Iliad", "Odyssey", "Republic"]),
 mc("The Canon was used in European universities for about…", "several hundred years", ["a few weeks", "a few days", "ten thousand years"]),
 mc("Unani medicine grew from Greek ideas and…", "Islamic scholars", ["Viking sagas", "Inca farmers", "Roman gladiators"]),
 tf("Ibn Sina was a Persian scholar.", True),
 tf("Galen's ideas were never questioned.", False),
 voc("anatomy", "The study of the body's structure."),
 op("Why was a book like the Canon so important for so long?", "It gathered and organized medical knowledge for many generations."),
]),
("Chinese and Indian Classics", "Clásicos chinos e indios", [
 mc("The Huangdi Neijing is also called the…", "Yellow Emperor's Inner Classic", ["Book of Songs", "Art of War", "Analects"]),
 mc("Traditional Chinese Medicine describes balance between…", "yin and yang", ["north and south", "hot dogs and buns", "day and month"]),
 mc("The Charaka Samhita is a classic text of…", "Ayurveda", ["Unani", "Kampo", "Greek medicine"]),
 mc("The Sushruta Samhita is known for describing…", "surgery", ["astronomy", "farming", "music"]),
 mc("Sushruta described an early form of…", "nose reconstruction", ["heart transplant", "X-ray", "vaccination"]),
 mc("Kampo is a Japanese adaptation of…", "Chinese herbal medicine", ["Greek humors", "Egyptian papyri", "Ayurveda"]),
 tf("Ancient India had detailed writings on surgery.", True),
 tf("The Huangdi Neijing was written in ancient Greece.", False),
 voc("yin and yang", "A Chinese idea of two opposite forces kept in balance."),
 op("Why is it useful to study medical traditions from many cultures?", "Different cultures made discoveries and shared ideas; it builds respect and understanding."),
]),
("Anatomy Revolution", "Revolución anatómica", [
 mc("Andreas Vesalius wrote a famous anatomy book in…", "1543", ["1066", "1776", "1928"]),
 mc("Vesalius corrected Galen by dissecting…", "human bodies", ["only animals", "plants", "clay models"]),
 mc("William Harvey showed that blood…", "circulates around the body", ["is made in the liver and used up", "stays still", "is air"]),
 mc("Harvey showed the heart works as a…", "pump", ["filter", "furnace", "sponge"]),
 mc("Vesalius's book is called…", "On the Fabric of the Human Body", ["The Canon", "The Origin of Species", "Principia"]),
 mc("Better anatomy came from careful…", "observation", ["guessing", "legends", "voting"]),
 tf("Harvey described the circulation of blood.", True),
 tf("Vesalius agreed with every idea of Galen.", False),
 voc("circulation", "The movement of blood around the body."),
 op("Why does checking old ideas matter in science?", "Testing can find mistakes and improve knowledge."),
]),
("Jenner and Vaccines", "Jenner y las vacunas", [
 mc("Edward Jenner developed a vaccine against…", "smallpox", ["polio", "measles", "flu"]),
 mc("Jenner used material from…", "cowpox", ["chickenpox", "rabies", "a cold"]),
 mc("Jenner's work was in…", "1796", ["1492", "1900", "1965"]),
 mc("Smallpox was declared eradicated by the WHO in…", "1980", ["1800", "1920", "2020"]),
 mc("The word vaccine comes from the Latin for…", "cow", ["needle", "cure", "germ"]),
 mc("Earlier, people in China, India and Africa practiced…", "variolation", ["pasteurization", "anesthesia", "surgery"]),
 tf("Smallpox has been wiped out worldwide.", True),
 tf("Jenner discovered penicillin.", False),
 voc("eradicate", "To get rid of something completely."),
 op("How did a whole world work together to end smallpox?", "Vaccination campaigns, tracking cases, and sharing across countries."),
]),
("Germ Theory and Surgery", "Teoría de los gérmenes y cirugía", [
 mc("Germ theory says many diseases are caused by…", "microorganisms", ["bad smells", "the moon", "humors"]),
 mc("Robert Koch identified the germ that causes…", "tuberculosis", ["smallpox", "diabetes", "scurvy"]),
 mc("Joseph Lister used carbolic acid to make surgery…", "antiseptic", ["faster only", "painful", "cheaper"]),
 mc("Ignaz Semmelweis urged doctors to…", "wash their hands", ["stop surgery", "wear hats", "work at night"]),
 mc("Before germ theory, many blamed disease on…", "miasma, or bad air", ["germs", "genes", "vitamins"]),
 mc("Antiseptic methods lowered deaths from…", "infection after surgery", ["broken bones", "old age", "sunburn"]),
 tf("Handwashing lowered deaths in hospitals.", True),
 tf("Lister thought surgery did not need to be clean.", False),
 voc("antiseptic", "Something that kills germs to prevent infection."),
 op("Why was it hard for some doctors to accept germ theory?", "Germs were invisible and it challenged old beliefs and habits."),
]),
("Anesthesia and Antibiotics", "Anestesia y antibióticos", [
 mc("Anesthesia helps patients…", "not feel pain during surgery", ["heal instantly", "grow taller", "stay awake and feel pain"]),
 mc("An early public demonstration of ether anesthesia was in…", "1846", ["1546", "1946", "1746"]),
 mc("Alexander Fleming discovered penicillin in…", "1928", ["1828", "1968", "1898"]),
 mc("Penicillin was found growing from a…", "mold", ["rock", "flower", "fish"]),
 mc("Antibiotics work against…", "bacteria", ["viruses", "broken bones", "allergies"]),
 mc("When bacteria stop responding to antibiotics, it is called…", "antibiotic resistance", ["immunity", "vaccination", "anesthesia"]),
 tf("Antibiotics do not work on viruses like colds.", True),
 tf("Penicillin was discovered in 1628.", False),
 voc("antibiotic", "A medicine that kills or stops bacteria."),
 op("Why should antibiotics be used only when a doctor says so?", "Overuse helps resistance grow; they don't help viruses."),
]),
("Public Health", "Salud pública", [
 mc("John Snow traced a cholera outbreak in London in…", "1854", ["1654", "1954", "1754"]),
 mc("Snow linked the outbreak to a…", "water pump", ["bakery", "church bell", "cat"]),
 mc("Snow made a map showing where…", "cases happened", ["roads went", "kings lived", "rain fell"]),
 mc("Cholera spreads mainly through…", "dirty water", ["sunlight", "music", "cold air"]),
 mc("Public health focuses on the health of…", "whole communities", ["one person only", "pets only", "plants only"]),
 mc("Clean water and sewers greatly reduced…", "disease", ["rain", "population", "sleep"]),
 tf("John Snow is seen as a founder of epidemiology.", True),
 tf("Snow blamed cholera on bad smells.", False),
 voc("epidemic", "A disease spreading to many people in an area."),
 op("Name a public health measure in your town and how it helps.", "Clean water, vaccines, food inspection, etc., with how it prevents illness."),
]),
("The Immune System", "El sistema inmunitario", [
 mc("White blood cells help the body…", "fight infection", ["carry oxygen", "digest food", "build bone"]),
 mc("Antibodies attach to…", "germs", ["bones", "hair", "food"]),
 mc("The skin protects the body as a…", "barrier", ["pump", "filter of blood", "muscle"]),
 mc("A fever can be a sign the body is…", "fighting an infection", ["growing", "sleeping", "digesting"]),
 mc("Memory cells help the body respond faster…", "the next time", ["never", "only once", "to food"]),
 mc("An allergy is when the immune system reacts to something…", "usually harmless", ["always deadly", "invisible only", "made of metal"]),
 tf("Vaccines train the immune system.", True),
 tf("Red blood cells are the main germ fighters.", False),
 voc("antibody", "A protein that sticks to a germ so the body can remove it."),
 op("Explain how a vaccine and memory cells work together.", "The vaccine shows a safe version; memory cells remember and respond fast later."),
]),
("Growing Up Healthy", "Crecer saludable", [
 mc("Puberty is a time when the body…", "grows and changes", ["stops growing", "shrinks", "stays the same"]),
 mc("During puberty, growth spurts can make you need more…", "sleep and good food", ["soda", "screen time", "skipped meals"]),
 mc("Teens generally need about how much sleep?", "8 to 10 hours", ["3 to 4 hours", "15 to 18 hours", "1 hour"]),
 mc("Iron helps the blood carry…", "oxygen", ["sugar", "salt", "bones"]),
 mc("Questions about body changes are best asked to…", "a parent, doctor or school nurse", ["random websites", "no one", "rumors"]),
 mc("Everyone goes through puberty at…", "their own pace", ["the exact same day", "age 5", "age 30"]),
 tf("Puberty happens at different times for different people.", True),
 tf("Skipping breakfast helps a growing body.", False),
 voc("puberty", "The time when a child's body grows into an adult body."),
 op("What habits help your body as it grows?", "Sleep, balanced food, movement, and asking trusted adults questions."),
]),
]

BANDS['912'] = [
("The Scientific Method in Medicine", "El método científico en medicina", [
 mc("In a randomized controlled trial, participants are assigned to groups by…", "chance", ["their choice", "doctor's favorites", "age only"]),
 mc("A placebo is…", "an inactive treatment used for comparison", ["a stronger drug", "a vaccine", "a surgery"]),
 mc("In a double-blind trial, who doesn't know who gets the real treatment?", "both patients and researchers", ["only patients", "only researchers", "no one is blinded"]),
 mc("Peer review means a study is checked by…", "other experts", ["the authors' friends only", "advertisers", "the public vote"]),
 mc("Evidence-based medicine combines research evidence, clinical skill and…", "patient values", ["advertising", "rumor", "tradition alone"]),
 mc("The control group in a trial…", "does not get the new treatment", ["gets double doses", "chooses its treatment", "is the researchers"]),
 tf("The placebo effect can make people feel better even without an active drug.", True),
 tf("One small study is enough to prove a treatment works.", False),
 voc("randomized controlled trial", "A study that assigns people by chance to treatment or comparison groups."),
 op("Why is randomization important in a medical study?", "It balances groups so differences come from the treatment, not other factors."),
]),
("Traditional Medicine and Evidence", "Medicina tradicional y evidencia", [
 mc("Tu Youyou won the 2015 Nobel Prize for discovering…", "artemisinin", ["penicillin", "insulin", "aspirin"]),
 mc("Artemisinin treats…", "malaria", ["tuberculosis", "diabetes", "flu"]),
 mc("Tu Youyou found clues to artemisinin in…", "old Chinese herbal texts", ["Greek papyri", "Egyptian tombs", "Roman law"]),
 mc("Research on acupuncture suggests it may help some people with…", "certain kinds of chronic pain", ["curing cancer", "curing infections", "replacing vaccines"]),
 mc("Much of the measured benefit of acupuncture in trials resembles…", "sham acupuncture", ["surgery", "antibiotics", "chemotherapy"]),
 mc("Aspirin's history links to a compound from…", "willow bark", ["oak leaves", "rose petals", "pine sap"]),
 tf("Some modern medicines were first found in traditional plant remedies.", True),
 tf("Evidence shows herbal remedies cure cancer on their own.", False),
 voc("sham", "A fake version of a treatment used for comparison in a study."),
 op("How can a traditional remedy become a tested medicine?", "Identify the ingredient, test it in trials, check safety and dose, peer review."),
]),
("Herbs, Supplements and Safety", "Hierbas, suplementos y seguridad", [
 mc("St. John's wort can reduce the effect of some…", "prescription medicines", ["vitamins in food", "exercise", "water"]),
 mc("Some imported herbal products, including some Ayurvedic ones, have been found to contain…", "heavy metals like lead", ["extra vitamin C", "only water", "gold only"]),
 mc("In the U.S., dietary supplements are…", "not approved for effectiveness before sale like drugs", ["tested like prescription drugs", "illegal", "free"]),
 mc("\"Natural\" on a label means a product is…", "not automatically safe", ["always safe", "always effective", "FDA approved"]),
 mc("Ephedra, from the Chinese herb ma huang, was banned in U.S. supplements for…", "heart risks", ["tasting bad", "being too cheap", "no reason"]),
 mc("Before starting any herb or supplement, it's wise to…", "talk to a doctor or pharmacist", ["double the amount", "stop all medicine", "ask a stranger online"]),
 tf("Herbs can interact with prescription medicines.", True),
 tf("Anything labeled natural cannot cause harm.", False),
 voc("interaction", "When one substance changes how another works in the body."),
 op("Why should patients tell their doctor about every supplement they take?", "To avoid interactions and get safe, accurate care."),
]),
("Mind-Body Practices", "Prácticas mente-cuerpo", [
 mc("Research suggests yoga may help with…", "low back pain and stress", ["curing infections", "fixing broken bones", "replacing insulin"]),
 mc("Mindfulness meditation has evidence for helping…", "stress and anxiety for many people", ["cure all illness", "replace medicine", "heal cuts faster than bandages"]),
 mc("Tai chi has been studied for improving…", "balance and preventing falls in older adults", ["eyesight", "curing diabetes", "growing hair"]),
 mc("Integrative medicine combines conventional care with…", "evidence-informed complementary practices", ["rejecting doctors", "only herbs", "no treatment"]),
 mc("\"Complementary\" means used…", "together with conventional medicine", ["instead of all medicine", "only by doctors", "never"]),
 mc("\"Alternative\" means used…", "in place of conventional medicine", ["along with conventional medicine", "only in hospitals", "only in trials"]),
 tf("Meditation can be a helpful part of caring for mental health.", True),
 tf("Yoga has been shown to replace all medical treatment.", False),
 voc("integrative medicine", "Care that combines standard medicine with evidence-informed complementary practices."),
 op("When might a mind-body practice be a good addition to care?", "For stress, pain or balance, alongside and not instead of medical care."),
]),
("Epidemiology", "Epidemiología", [
 mc("Epidemiology studies…", "how disease spreads in populations", ["single cells only", "rocks", "weather"]),
 mc("Correlation between two things does not prove…", "causation", ["a link", "a pattern", "data"]),
 mc("Incidence measures…", "new cases over a time period", ["all existing cases", "deaths only", "cures"]),
 mc("Prevalence measures…", "all existing cases at a time", ["only new cases", "only deaths", "vaccines given"]),
 mc("A pandemic is an outbreak that…", "spreads across many countries", ["stays in one town", "affects animals only", "lasts one day"]),
 mc("Herd immunity happens when enough people are…", "immune", ["sick at once", "indoors", "tested"]),
 tf("Smoking was linked to lung cancer through epidemiology studies.", True),
 tf("Correlation always proves causation.", False),
 voc("epidemiology", "The study of how diseases spread and can be controlled in groups of people."),
 op("Give an example where correlation could mislead.", "A hidden third factor explains both things; notes need for controlled study."),
]),
("Global Health", "Salud global", [
 mc("WHO stands for…", "World Health Organization", ["World Hospital Office", "Wellness Help Organization", "World Healing Order"]),
 mc("Malaria is spread by…", "mosquitoes", ["handshakes", "water pipes", "cats"]),
 mc("A key tool to prevent malaria is…", "insecticide-treated bed nets", ["antibiotics for colds", "sunscreen", "ice packs"]),
 mc("Tuberculosis mainly affects the…", "lungs", ["skin", "eyes", "teeth"]),
 mc("TB is spread through…", "the air", ["mosquito bites", "food only", "touching doorknobs only"]),
 mc("Oral rehydration solution saves lives by treating…", "dehydration from diarrhea", ["broken bones", "malaria", "vision loss"]),
 tf("Tuberculosis is curable with a full course of the right medicines.", True),
 tf("Malaria spreads from person to person by handshakes.", False),
 voc("global health", "Health issues and care that reach across countries."),
 op("What makes a disease hard to control worldwide?", "Access to care, cost, drug resistance, weak health systems, travel."),
]),
("Health Systems Compared", "Sistemas de salud comparados", [
 mc("The UK's National Health Service is funded mainly through…", "taxes", ["private insurance only", "lottery", "donations"]),
 mc("Canada's system is often described as…", "single-payer public insurance", ["fully private", "no coverage", "military only"]),
 mc("In the U.S., many people get insurance through…", "employers", ["the United Nations", "their school only", "libraries"]),
 mc("Japan requires nearly everyone to have…", "health insurance", ["a private doctor", "a gym membership", "no insurance"]),
 mc("India's large public health insurance program is called…", "Ayushman Bharat", ["Medicare", "NHS", "Obamacare"]),
 mc("In China, many hospitals offer both Western medicine and…", "Traditional Chinese Medicine", ["Unani only", "no care", "Kampo only"]),
 tf("Countries pay for health care in different ways.", True),
 tf("Every country uses exactly the same health system.", False),
 voc("universal coverage", "When everyone in a country can get needed health care."),
 op("Compare two health systems. What does each do well?", "Names two systems with fair strengths and trade-offs."),
]),
("Medical Ethics", "Ética médica", [
 mc("Informed consent means a patient…", "agrees after understanding risks and benefits", ["signs without reading", "is not told anything", "lets family decide always"]),
 mc("The Tuskegee study (1932–1972) wrongly…", "withheld treatment from Black men with syphilis", ["gave free vaccines", "tested new surgery safely", "helped all patients"]),
 mc("After Tuskegee, the U.S. strengthened rules to…", "protect research participants", ["end all research", "hide studies", "pay doctors more"]),
 mc("\"First, do no harm\" is linked to the principle of…", "non-maleficence", ["profit", "speed", "secrecy"]),
 mc("Patient privacy in the U.S. is protected by a law called…", "HIPAA", ["NASA", "OSHA", "FDA"]),
 mc("Respecting a patient's own choices is called…", "autonomy", ["obedience", "tradition", "paternalism"]),
 tf("Ethics boards review research involving people.", True),
 tf("Doctors may experiment on patients without consent.", False),
 voc("informed consent", "Agreeing to care after understanding what it involves."),
 op("Why does trust matter between communities and medicine?", "Past harms like Tuskegee hurt trust; honesty and consent rebuild it."),
]),
("Mental Health", "Salud mental", [
 mc("Common, treatable mental health conditions include…", "depression and anxiety", ["broken arms", "sunburn", "cavities"]),
 mc("Therapy that works on thoughts and actions is…", "cognitive behavioral therapy", ["surgery", "physical therapy", "radiology"]),
 mc("In the U.S., the crisis line you can call or text is…", "988", ["411", "311", "611"]),
 mc("Stigma means…", "unfair negative attitudes", ["a medicine", "a symptom", "a diagnosis"]),
 mc("A helpful way to support a friend who is struggling is to…", "listen and help them reach a trusted adult", ["keep it secret from all adults", "tell them to get over it", "ignore it"]),
 mc("Mental health care is best provided by…", "trained professionals", ["social media", "rumors", "strangers"]),
 tf("Mental health conditions are treatable.", True),
 tf("Asking for mental health help is a sign of weakness.", False),
 voc("stigma", "Unfair shame or negative attitudes about something."),
 op("How can a school reduce stigma around mental health?", "Open talk, easy access to counselors, respectful language, education."),
]),
("Addiction Science", "Ciencia de la adicción", [
 mc("Addiction changes the brain's…", "reward system", ["hair growth", "bone density", "eye color"]),
 mc("A key chemical in the brain's reward system is…", "dopamine", ["calcium", "iron", "vitamin C"]),
 mc("Nicotine is the addictive chemical in…", "tobacco and vapes", ["fruit", "water", "milk"]),
 mc("The teen brain is still developing until about age…", "25", ["10", "15", "40"]),
 mc("Addiction is best understood as a…", "treatable health condition", ["moral failure", "choice only", "untreatable"]),
 mc("Naloxone is a medicine that can reverse an…", "opioid overdose", ["allergy", "infection", "broken bone"]),
 tf("Addiction can be treated, and people recover.", True),
 tf("Vapes contain no addictive substances.", False),
 voc("tolerance", "Needing more of a substance to feel the same effect."),
 op("Why might starting substance use early be riskier?", "The developing brain is more sensitive; habits form faster."),
]),
]

BANDS['adult'] = [
("Reading Labels", "Leer etiquetas", [
 mc("On a nutrition label, all numbers are based on the…", "serving size", ["whole package always", "price", "weight of the box"]),
 mc("The % Daily Value helps you see if a food is…", "high or low in a nutrient", ["organic", "cheap", "fresh"]),
 mc("Ingredients are listed from…", "most to least by weight", ["A to Z", "least to most", "newest to oldest"]),
 mc("On an over-the-counter medicine, the \"active ingredient\" is…", "what does the work", ["the flavor", "the color", "the box"]),
 mc("Two cold medicines may both contain…", "the same active ingredient", ["no ingredients", "only water", "sugar only"]),
 mc("An expiration date tells you…", "when a product may no longer work as well", ["when it was made", "the price", "the store"]),
 tf("Checking active ingredients can prevent taking too much of one medicine.", True),
 tf("The serving size is always the whole package.", False),
 voc("active ingredient", "The part of a medicine that treats the problem."),
 op("How would you compare two snack labels?", "Match serving sizes, then compare sugar, sodium, fiber and protein."),
]),
("Prescriptions", "Recetas médicas", [
 mc("A prescription label shows your name, the medicine, and…", "directions", ["a coupon", "a recipe", "the weather"]),
 mc("If directions are unclear, ask the…", "pharmacist", ["cashier", "neighbor", "internet forum"]),
 mc("\"Refills\" on a label means…", "how many more times it can be filled", ["how many pills are left", "the price", "the dose"]),
 mc("A generic drug has the same active ingredient as the…", "brand-name drug", ["placebo", "supplement", "vitamin"]),
 mc("Sharing prescription medicine with others is…", "not safe", ["a kind idea", "always fine", "required"]),
 mc("Before stopping a prescribed medicine, first…", "talk to your doctor", ["stop suddenly", "double up", "ask a friend"]),
 tf("Pharmacists can answer questions about your medicine.", True),
 tf("It's fine to take a friend's prescription.", False),
 voc("generic", "A lower-cost medicine with the same active ingredient as a brand name."),
 op("What questions would you ask the pharmacist about a new medicine?", "What it's for, how and when to take it, side effects, interactions."),
]),
("Talking With Your Doctor", "Hablar con su médico", [
 mc("Before a visit, it helps to…", "write down your questions", ["forget symptoms", "arrive late", "bring nothing"]),
 mc("Bring a list of all medicines, vitamins and…", "herbs or supplements", ["recipes", "receipts", "photos"]),
 mc("If you don't understand, you can ask the doctor to…", "explain it another way", ["stop talking", "skip it", "write in Latin"]),
 mc("\"Teach-back\" means you…", "repeat the plan in your own words", ["teach the doctor", "take notes silently", "leave early"]),
 mc("You have the right to ask for an…", "interpreter", ["extra bill", "discount always", "second appointment free"]),
 mc("Bringing a trusted person to a visit can help you…", "remember what was said", ["skip the visit", "avoid questions", "get more tests"]),
 tf("You should tell your doctor about any traditional remedies you use.", True),
 tf("Doctors don't want patients to ask questions.", False),
 voc("teach-back", "Saying the care plan back in your own words to check understanding."),
 op("Write three questions to bring to your next visit.", "Clear questions about symptoms, treatment, next steps or medicines."),
]),
("Insurance Basics", "Conceptos básicos de seguros", [
 mc("A premium is…", "what you pay each month for insurance", ["your copay", "the doctor's salary", "a refund"]),
 mc("A deductible is…", "what you pay before insurance starts sharing costs", ["a monthly fee", "a free visit", "a tax refund"]),
 mc("A copay is…", "a set amount paid for a visit or medicine", ["the yearly total", "an insurance card", "a penalty"]),
 mc("In-network doctors usually cost…", "less", ["more", "the same always", "nothing ever"]),
 mc("Medicaid mainly helps people with…", "lower incomes", ["only high incomes", "only pets", "only travel"]),
 mc("Medicare mainly covers people who are…", "65 or older", ["under 18", "students", "tourists"]),
 tf("Many preventive checkups are covered at no cost under many plans.", True),
 tf("The deductible and the premium are the same thing.", False),
 voc("deductible", "The amount you pay for care before your insurance starts to pay."),
 op("How would you choose between two insurance plans?", "Compare premium, deductible, copays, network and your usual needs."),
]),
("Diabetes", "Diabetes", [
 mc("Diabetes affects how the body uses…", "blood sugar", ["calcium", "oxygen", "salt only"]),
 mc("Insulin is a hormone made by the…", "pancreas", ["liver", "heart", "lungs"]),
 mc("Type 2 diabetes risk can be lowered by activity and…", "balanced eating", ["skipping all meals", "more soda", "less sleep"]),
 mc("An A1C test shows average blood sugar over about…", "3 months", ["1 day", "1 week", "5 years"]),
 mc("People with diabetes should check their…", "feet regularly", ["hair color", "shoe brand", "height"]),
 mc("Signs that may point to diabetes include…", "extreme thirst and frequent urination", ["sneezing", "itchy ears only", "curly hair"]),
 tf("Diabetes can be managed with a care team.", True),
 tf("Herbal teas can replace insulin.", False),
 voc("insulin", "A hormone that helps move sugar from blood into cells."),
 op("What daily habits help someone manage diabetes?", "Following the care plan, activity, balanced meals, checking sugar, visits."),
]),
("Blood Pressure and Heart Health", "Presión arterial y salud del corazón", [
 mc("The best way to know your blood pressure is to…", "have it measured", ["guess from how you feel", "wait for symptoms", "check your temperature"]),
 mc("Blood pressure is written as two numbers, like…", "120/80", ["98.6", "70 kg", "20/20"]),
 mc("Too much of which can raise blood pressure?", "sodium (salt)", ["water", "fiber", "vitamin C"]),
 mc("Heart attack warning signs can include…", "chest pain and shortness of breath", ["itchy toes", "hiccups", "sneezing"]),
 mc("If you think someone is having a heart attack, you should…", "call 911", ["drive them slowly later", "wait a day", "give them herbs"]),
 mc("A stroke warning sign is…", "face drooping on one side", ["a sore toe", "a runny nose", "dry skin"]),
 tf("High blood pressure often has no symptoms.", True),
 tf("Once blood pressure is normal, you can stop medicine without asking.", False),
 voc("hypertension", "Another word for high blood pressure."),
 op("How can a person lower their risk of heart disease?", "Less salt, activity, no smoking, checkups, taking prescribed medicine."),
]),
("Checking Health Claims Online", "Verificar información de salud en línea", [
 mc("Trustworthy health websites often end in…", ".gov or .edu", [".biz only", ".xyz", ".fun"]),
 mc("A red flag in a health ad is a claim that it…", "cures everything", ["has side effects", "was studied", "costs money"]),
 mc("MedlinePlus is run by the…", "National Library of Medicine", ["a soda company", "a movie studio", "a sports team"]),
 mc("Testimonials from happy customers are…", "not scientific evidence", ["proof it works", "peer review", "clinical trials"]),
 mc("A good question to ask about a claim is…", "who paid for this", ["how shiny is the website", "how many ads", "what font"]),
 mc("If a product is sold with a \"secret doctors don't want you to know,\" it is likely…", "misleading", ["reliable", "FDA approved", "tested"]),
 tf("Checking more than one reliable source is wise.", True),
 tf("A popular video is proof that a treatment works.", False),
 voc("misinformation", "False or misleading information."),
 op("Describe how you would check a health claim you saw online.", "Check source, evidence, date, who benefits, and ask a doctor."),
]),
("Herbs, Supplements and Traditions", "Hierbas, suplementos y tradiciones", [
 mc("Many families use traditional remedies. The key step is to…", "tell your doctor about them", ["hide them", "stop medicines", "double doses"]),
 mc("Ginkgo, garlic and ginseng may interact with…", "blood thinners", ["water", "fresh air", "sunlight"]),
 mc("Grapefruit juice can change how some…", "medicines work", ["shoes fit", "eyes see", "hair grows"]),
 mc("Supplements with a USP or NSF seal have been checked for…", "contents and quality", ["curing disease", "being natural", "low price"]),
 mc("Traditional remedies should not replace…", "treatment for serious illness", ["a healthy meal", "a walk", "a cup of tea"]),
 mc("A good way to bring up a traditional practice with a doctor is to…", "share it openly and ask about safety", ["keep it secret", "argue", "skip visits"]),
 tf("Respecting family traditions and being safe can go together.", True),
 tf("Supplements are checked for effectiveness before they are sold.", False),
 voc("supplement", "A product like a vitamin or herb taken in addition to food."),
 op("How could you talk with a doctor about a family remedy?", "Name it, how often it's used, and ask about safety and interactions."),
]),
("Preventive Care", "Cuidado preventivo", [
 mc("Screenings aim to find problems…", "early", ["late", "never", "only after symptoms"]),
 mc("A yearly flu shot is recommended for most people…", "6 months and older", ["only babies", "only over 90", "no one"]),
 mc("Quitting smoking lowers the risk of…", "heart and lung disease", ["broken bones", "freckles", "allergies to pets"]),
 mc("Adults are advised to get about how much moderate activity weekly?", "150 minutes", ["15 minutes", "15 hours", "none"]),
 mc("Sunscreen helps lower the risk of…", "skin cancer", ["colds", "diabetes", "flu"]),
 mc("A primary care provider is your…", "main doctor for regular care", ["surgeon only", "insurance agent", "pharmacist"]),
 tf("Regular checkups can find health problems early.", True),
 tf("Preventive care only matters for older adults.", False),
 voc("screening", "A test to look for a health problem before symptoms appear."),
 op("What preventive steps fit your life right now?", "Specific steps like checkups, vaccines, activity, sleep or screenings."),
]),
("Emergencies and Getting Care", "Emergencias y cómo recibir atención", [
 mc("For a life-threatening emergency, call…", "911", ["the pharmacy", "your boss", "a friend first"]),
 mc("Urgent care is for problems that are…", "not life-threatening but need quick care", ["heart attacks", "strokes", "routine checkups"]),
 mc("Poison Control in the U.S. can be reached at…", "1-800-222-1222", ["988", "411", "311"]),
 mc("A telehealth visit is care by…", "video or phone", ["mail only", "radio", "text from a stranger"]),
 mc("Community health centers often charge based on…", "income", ["height", "age only", "zip code alone"]),
 mc("Keeping a list of your medicines helps in an…", "emergency", ["argument", "election", "interview"]),
 tf("Community health centers can offer lower-cost care.", True),
 tf("Urgent care is the best place for a stroke.", False),
 voc("telehealth", "Getting health care by video or phone."),
 op("Make a plan: where would you go for a sprain, a fever, and chest pain?", "Urgent care or clinic for sprain/fever; 911 for chest pain."),
]),
]
