# Secret Societies — Daily Drafts banks. History from the record: clubs, codes, lodges and orders,
# legends named as legends, and how to test a claim. Every item comes from the course's own reviewed
# lessons (see hist_banks.py); this file only adds the Spanish strand names and a third wrong choice
# for each K–2 question. K–2 questions about a story character are left out (no EXTRA), because a
# drafts line has no story beside it.
from hist_banks import make

ES = {
 # K–2
 "What Makes a Club": "Qué es un club",
 "Kind Clubs": "Clubes amables",
 "Safe or Unsafe?": "¿Seguro o no seguro?",
 "What Is a Symbol?": "¿Qué es un símbolo?",
 "Showing Your Group": "Mostrar tu grupo",
 "Passwords and Signals": "Contraseñas y señales",
 "Builders Long Ago": "Constructores de hace mucho",
 "Learning the Trade": "Aprender el oficio",
 "Caring for Families": "Cuidar a las familias",
 "Chicago and Kind Clubs": "Chicago y los clubes amables",
 # 3–5
 "A Holy Place and Its Story": "Un lugar sagrado y su historia",
 "Why People Came, and the End": "Por qué venía la gente, y el final",
 "Guards on the Pilgrim Road": "Guardianes del camino de los peregrinos",
 "How People Saw Them": "Cómo los veía la gente",
 "The Parchment at Chinon": "El pergamino de Chinon",
 "Speaking Up for Freedom and School": "Hablar por la libertad y la escuela",
 "Odd Fellows and Eastern Star": "Odd Fellows y la Estrella de Oriente",
 "The Pigpen Cipher": "El cifrado pigpen",
 "The Green and Gold Book": "El libro verde y dorado",
 "The Art of Memory": "El arte de la memoria",
 # 6–8
 "Builders of Stone": "Constructores de piedra",
 "Rules, Rituals and a Ban": "Reglas, rituales y una prohibición",
 "The Eye on the Dollar": "El ojo del dólar",
 "Ekpe and Nsibidi": "Ekpe y nsibidi",
 "Signs, Poems and Secret Words": "Señales, poemas y palabras secretas",
 "Gone Without a Trace": "Desaparecido sin dejar rastro",
 "A Secret Order Against Newcomers": "Una orden secreta contra los recién llegados",
 "A Forged Oath": "Un juramento falsificado",
 "Prohibition Makes Gangs Rich": "La Prohibición enriquece a las pandillas",
 "The Tax Case": "El caso de los impuestos",
 # 9–12
 "A Professor Starts an Order": "Un profesor funda una orden",
 "Blaming the Revolution": "Culpar a la Revolución",
 "Witnesses Speak": "Hablan los testigos",
 "Where the Mafia Began": "Dónde empezó la Mafia",
 "The Maxi Trial in Palermo": "El Maxiproceso de Palermo",
 "How the Lie Spread": "Cómo se difundió la mentira",
 "How Historians Test a Document": "Cómo ponen a prueba un documento los historiadores",
 "What COINTELPRO Did": "Lo que hizo COINTELPRO",
 "Charges and a Final Night": "Cargos y una última noche",
 "Present and Disagree Respectfully": "Presentar y discrepar con respeto",
 # Adult
 "From Satire to Forgery": "De la sátira a la falsificación",
 "Why It Still Matters": "Por qué todavía importa",
 "Papers From Nowhere: MJ-12": "Papeles de la nada: MJ-12",
 "A Secret Program Begins": "Comienza un programa secreto",
 "Destroyed, Then Found": "Destruidos y luego encontrados",
 "Files From Media": "Los archivos de Media",
 "Northwoods and the Lesson": "Northwoods y la lección",
 "From Bulletin Boards to Shortwave": "De los tablones de anuncios a la onda corta",
 "Choose a Claim and Trace It": "Elige una afirmación y rastréala",
 "Sort and Argue": "Clasifica y argumenta",
}

EXTRA = {
 "What is a club?": "A kind of cloud",
 "Which one could be a club?": "A cup of milk",
 "What is a hobby?": "A kind of hat",
 "A soccer team is a kind of what?": "Password",
 "What is a member?": "A club snack",
 "Which is a kind way to welcome a new member?": "Walk away fast",
 "What does a kind club do?": "Keeps new kids out",
 "What can you say to a child who is alone?": "Not today",
 "What is a safe secret?": "A secret that makes you cry",
 "Why did builders in Scotland have a secret word?": "To name a cat",
 "What does an unsafe secret make you feel?": "Calm and cozy",
 "What can a fast heart or tears tell you?": "It is bedtime",
 "What is danger?": "A song you like",
 "Someone asks you to keep a secret about touching. What do you do?": "Hide it from everyone",
 "Are you in trouble for telling an unsafe secret?": "Yes, if it is late",
 "What is a symbol?": "A kind of snack",
 "What can a star stand for?": "A broken toy",
 "How many sides does a stop sign have?": "Six",
 "What does a yield sign tell a driver?": "Turn on the radio",
 "Why can drivers know a stop sign fast?": "It sings a song",
 "How many stars are on the flag of the United States?": "100",
 "What is a badge?": "A kind of soup",
 "What makes a good symbol?": "It changes every day",
 "What did a stone builder in old Scotland use a secret word for?": "To sing a song",
 "In 1599, what did a rule say new builders must be tested on?": "Their jumping",
 "What is a signal?": "A heavy stone",
 "What can a club's handshake show?": "That it is snowing",
 "What is a stonemason?": "A worker who fixes cars",
 "What is a very big, important church called?": "A barn",
 "Which of these did stonemasons build?": "Computers",
 "How did workers long ago cut stone?": "With robots",
 "Which church took more than 600 years to finish?": "Chicago City Hall",
 "Why could children finish a church their parents started?": "The stones built themselves",
 "What is an apprentice?": "A kind of cathedral",
 "About how long did learning often take?": "One hour",
 "What is a mason's mark?": "A kind of hammer",
 "Why do many experts think builders used marks?": "To make stones float",
 "What is a widow?": "A kind of door",
 "Which club built Mooseheart, a town for children?": "The Elks",
 "What is a funeral?": "A picnic in the park",
 "Why did some people start their own lodges?": "They wanted to sell cars",
 "Which club did Catholic men start in 1882?": "The Elks",
 "When did Chicago have a Prince Hall lodge?": "By 2000",
 "What year was Chicago's Masonic Temple built?": "1492",
 "What was at the top of the Masonic Temple?": "A swimming pool",
 "What happened to the Masonic Temple in 1939?": "It floated away",
 "What does a kind club do when you ask questions?": "Hides from you",
 "Someone says, \"Hide this from your family. It hurts.\" What do you do?": "Hide it well",
}

BANDS = make('sec', ES, EXTRA)
