# Sports History — Daily Drafts banks. History only: fields, rules, leagues and who got to play.
# Every item comes from the course's own reviewed lessons (see hist_banks.py); this file only adds
# the Spanish strand names and a third wrong choice for each K–2 question.
from hist_banks import make

ES = {
 # K–2
 "Very Old Play Places": "Lugares de juego muy antiguos",
 "Paths, Water and Ice": "Pistas, agua y hielo",
 "A Team Has a Number": "Un equipo tiene un número",
 "Parks for Everyone": "Parques para todos",
 "Lights After Dark": "Luces de noche",
 "Rules on Paper": "Reglas en papel",
 "Rules for Illinois Schools": "Reglas para las escuelas de Illinois",
 "Soccer Crosses the Sea": "El fútbol cruza el mar",
 "A Mat in Illinois": "Un tapete en Illinois",
 "A Hall in Tokyo": "Una sala en Tokio",
 # 3–5
 "Games Before Baseball": "Juegos antes del béisbol",
 "Strangers Share a Field": "Desconocidos comparten un campo",
 "New Tools, Same Diamond": "Nuevas herramientas, el mismo diamante",
 "The Room Shapes the Game": "El lugar da forma al juego",
 "Illinois School Gyms": "Gimnasios escolares de Illinois",
 "Campus Games Become a Code": "Los juegos universitarios se vuelven un código",
 "Kicking Before the Code": "Patear antes del código",
 "Illinois Pitches": "Canchas de Illinois",
 "Time on Paper": "El tiempo en papel",
 "Illinois Pools and Courts": "Piscinas y canchas de Illinois",
 # 6–8
 "Before the Line Was Drawn": "Antes de trazar la línea",
 "Crossing the Line": "Cruzar la línea",
 "Doors for Women and Girls": "Puertas para mujeres y niñas",
 "Commissions, Radio and Crowds": "Comisiones, radio y multitudes",
 "The City Builds Rooms": "La ciudad construye espacios",
 "Flags, Oaths and Flames": "Banderas, juramentos y llamas",
 "Before 1972": "Antes de 1972",
 "An Illinois Roster": "Una lista de Illinois",
 "Laws, Records, Not Posters": "Leyes y registros, no carteles",
 "The IHSA as a School Body": "La IHSA como organismo escolar",
 # 9–12
 "Students Ran the First Games": "Los estudiantes organizaron los primeros juegos",
 "Courts and the Clause": "Los tribunales y la cláusula",
 "The Clip": "El video corto",
 "Flags and Songs Before 1968": "Banderas y canciones antes de 1968",
 "A Tour of Their Own": "Un circuito propio",
 "Amateurism as a Belief": "El amateurismo como creencia",
 "Opening the Books": "Abrir las cuentas",
 "Taking Land for a Game": "Tomar tierra para un juego",
 "Who the Rosters Left Out": "A quién dejaron fuera las listas",
 "Keepers of the Record": "Guardianes del registro",
 # Adult
 "Clubs That Wrote the Laws": "Los clubes que escribieron las reglas",
 "What a League Controls": "Lo que controla una liga",
 "Rituals Before the Kickoff": "Rituales antes del saque inicial",
 "Opening a Category": "Abrir una categoría",
 "Classes in Paralympic Sport": "Clases en el deporte paralímpico",
 "Public Money, Chicago Walls": "Dinero público, muros de Chicago",
 "Schools That Train the Pros": "Escuelas que forman a los profesionales",
 "Rules, a Trophy and a League": "Reglas, un trofeo y una liga",
 "Legends Checked Against Records": "Leyendas comparadas con los registros",
 "Plans of Ballparks": "Planos de estadios de béisbol",
}

EXTRA = {
 "Where were the ancient Olympic Games held?": "Paris in France",
 "What was the old stadium at Olympia like?": "a wooden gym",
 "Where did people sit to watch?": "on a rink wall",
 "What was the old ball made of?": "paper",
 "What did players build for this game?": "an ice rink",
 "Where is the largest old ball court?": "Montreal in Canada",
 "How long is one outdoor lap in the inside lane?": "50 meters",
 "Why do tracks match in size?": "so they can hold water",
 "What is a lane?": "a peach basket rim",
 "How long are many U.S. school pools?": "100 meters",
 "How long is an Olympic pool?": "200 feet",
 "What do swimmers touch at each end?": "a peach basket",
 "Where did people play hockey before indoor rinks?": "in gyms",
 "Where was an indoor game played in 1875?": "Springfield",
 "How long is an NHL rink?": "400 meters",
 "How many players may one soccer team have on the pitch?": "twenty",
 "Who is one of the eleven?": "the coach in the stands",
 "When may a substitute come on?": "only after the game",
 "How many students were in Naismith's first class?": "one hundred",
 "How many basketball players per team are on the court today?": "two",
 "Why did rule makers change from nine?": "the gym had no lights",
 "Whose name did Chicago give the park in 1865?": "Queen Victoria",
 "What was part of the land before the park?": "an ice rink",
 "Who may use a public park?": "only the mayor",
 "Why did Chicago build small parks near homes?": "Nobody liked the big parks.",
 "What is a field house?": "a shed for tractors",
 "When did the Chicago Park District form?": "1988",
 "What city held the 1893 fair?": "Paris",
 "What did the lights let people do?": "sleep in the park",
 "Where did towns later put electric lights?": "only in barns",
 "When did Wrigley Field get lights?": "1900",
 "Which team plays at Wrigley Field?": "the Chicago White Sox",
 "Before 1988, Cubs home games were": "all on the road",
 "What marked the edges of the ground in 1863?": "painted walls",
 "How long could the 1863 ground be?": "up to 5 yards",
 "In the United States we call this game": "hockey",
 "How many rules did Naismith first write?": "fifty",
 "Where were the rules printed in January 1892?": "a hockey magazine",
 "Why did printing the rules matter?": "It made the ball bigger.",
 "What does IHSA stand for?": "Indoor Hockey Skating Association",
 "When was the IHSA formed?": "1937",
 "What do the by-laws tell schools?": "what color to paint the gym",
 "When were the first IHSA girls wrestling state finals?": "1988",
 "When did IHSA boys wrestling crown its first champions?": "1863",
 "Why did the IHSA add girls wrestling?": "The mats were new.",
 "Who helped carry soccer to new countries?": "only the players' pets",
 "What did people in new lands start?": "new stone courts",
 "When did soccer spread by ship?": "in the year 776 BCE",
 "In what city did FIFA begin?": "Tokyo",
 "What does FIFA do?": "writes school lunch menus",
 "Where was the first World Cup?": "Brazil",
 "When did the IHSA begin?": "1863",
 "When were the first IHSA boys wrestling champions?": "2022",
 "What is a mat?": "a round pool",
 "When were the first IHSA girls wrestling finals?": "1900",
 "Before that, where did some girls wrestle?": "on a tennis court",
 "What are finals?": "a kind of ball",
 "Who started the Kodokan?": "a club in London",
 "When did the Kodokan open?": "1900",
 "What does belt color show in judo?": "a birthday",
 "Where did judo first join the Olympics?": "Chicago",
 "When did women's judo become a full Olympic sport?": "1900",
 "What is an Olympic sport?": "a game only for one town",
}

BANDS = make('spt', ES, EXTRA)
