# Mathematics, K–12 — the course arc. Our own wording, following the Illinois
# Learning Standards for Mathematics (Common Core) progression band by band.
# Topics are guides for the writers; story = the chapter's opening narrative hook.
#
# Units number 1–27 straight through the course; chapters 1–62. `band` is the
# grade band; `strand` prints where a unit's years go. `level` sets the writing
# rules (SPEC.md).

BANDS = [
 dict(id="k-2",   title="Grades K–2",   level="k2"),
 dict(id="3-5",   title="Grades 3–5",   level="35"),
 dict(id="6-8",   title="Grades 6–8",   level="68"),
 dict(id="9-10",  title="Grades 9–10",  level="hs"),
 dict(id="11-12", title="Grades 11–12", level="hs2"),
]

UNITS = [
 # ══════════════════════════════ K–2 ══════════════════════════════
 dict(n=1, band="k-2", title="Counting and Numbers", strand="Number", chapters=[
  dict(n=1, title="Counting and Comparing", strand="Counting",
       topics="Counting to 100 by ones and tens; one number for each object (one-to-one); the last number tells how many; counting on from any number; comparing groups — more, fewer, the same; writing numbers 0–20; number words; zero means none; skip counting by 2s, 5s and 10s.",
       story="Counting the whole class for the field-trip bus"),
  dict(n=2, title="Tens and Ones", strand="Place Value",
       topics="A ten is a bundle of ten ones; teen numbers as ten and some more; two-digit numbers as tens and ones; base-ten blocks, ten frames; comparing two-digit numbers with >, < and =; 10 more and 10 less; the hundred chart and its patterns.",
       story="Bagging pennies in tens at the class store"),
 ]),
 dict(n=2, band="k-2", title="Adding and Subtracting", strand="Operations", chapters=[
  dict(n=3, title="Putting Together and Taking Apart", strand="Addition and Subtraction",
       topics="Addition as putting together and adding to; subtraction as taking apart, taking from and comparing; number bonds; word problems with pictures and objects; the equal sign means the same as; unknowns in any position (3 + ? = 7); making ten; doubles.",
       story="Nine ducks on the pond, four fly away"),
  dict(n=4, title="Facts Within 20 and Good Strategies", strand="Fluency",
       topics="Counting on and counting back; doubles and near doubles; making ten to add (8 + 5 = 8 + 2 + 3); think addition to subtract; fact families; fluency within 10 then 20; two-step story problems; checking an answer by a second way.",
       story="The fact-family house on the classroom wall"),
 ]),
 dict(n=3, band="k-2", title="Place Value to 1,000", strand="Number", chapters=[
  dict(n=5, title="Hundreds, Tens and Ones", strand="Place Value",
       topics="Three-digit numbers as hundreds, tens and ones; expanded form (300 + 40 + 7); reading and writing numbers to 1,000; comparing with >, < and =; counting by 5s, 10s and 100s; 100 more and 100 less; even and odd numbers.",
       story="A jar of 1,000 buttons and how to count it without losing your place"),
  dict(n=6, title="Adding and Subtracting Bigger Numbers", strand="Operations",
       topics="Adding and subtracting within 100 using place value (tens with tens, ones with ones); regrouping — trading ten ones for a ten; adding up to four two-digit numbers; adding and subtracting within 1,000 with models and drawings; mental math with 10s and 100s; explaining why a strategy works.",
       story="The lemonade stand: 48 cups on Saturday, 36 on Sunday"),
 ]),
 dict(n=4, band="k-2", title="Measuring, Time and Money", strand="Measurement", chapters=[
  dict(n=7, title="Length and Data", strand="Measurement and Data",
       topics="Comparing and ordering lengths; measuring with same-size units laid end to end; inches, feet, centimeters, meters and choosing the right tool; estimating length; measuring twice with two units; picture graphs and bar graphs; line plots of measurements; answering questions from a graph.",
       story="How long is the hallway? A class measures it in shoes, then in feet"),
  dict(n=8, title="Time and Money", strand="Measurement",
       topics="Telling time to the hour, half hour and five minutes on analog and digital clocks; a.m. and p.m.; the day's schedule; coins and their values; counting mixed coins; dollars and cents in word problems; making change with counting up.",
       story="The lunch-count clock and the bake-sale cash box"),
 ]),
 dict(n=5, band="k-2", title="Shapes and Equal Shares", strand="Geometry", chapters=[
  dict(n=9, title="Flat and Solid Shapes", strand="Geometry",
       topics="Naming shapes by their sides and corners, not their size or turn (triangles, squares, rectangles, hexagons, circles); solid shapes (cubes, cones, cylinders, spheres); composing bigger shapes from smaller ones; drawing shapes with given attributes; shapes in the world — signs, buildings, tiles.",
       story="Building a city out of blocks and finding the shapes in it"),
  dict(n=10, title="Halves, Thirds and Fourths", strand="Fractions Begin",
       topics="Partitioning circles and rectangles into two, three and four equal shares; halves, thirds, fourths, quarters; equal shares of the same whole can have different shapes; rows and columns of squares in a rectangle (arrays begin); sharing fairly in a story.",
       story="One sandwich, two hungry kids, and what 'fair' means"),
 ]),

 # ══════════════════════════════ 3–5 ══════════════════════════════
 dict(n=6, band="3-5", title="Multiplication and Division", strand="Operations", chapters=[
  dict(n=11, title="What Multiplying Means", strand="Multiplication",
       topics="Equal groups, arrays and area models; multiplication as repeated addition and as scaling; the commutative and distributive properties as pictures; facts through 10 × 10 with strategies (doubling, tens, nines); multiples and patterns in the multiplication table; word problems.",
       story="Egg cartons, muffin tins and the day the pattern showed up"),
  dict(n=12, title="Division and Fact Families", strand="Division",
       topics="Division as sharing and as grouping; unknown factors (? × 4 = 28); fact families; dividing with remainders and what to do with them; two-step word problems with all four operations; the order of operations begins; estimating to check.",
       story="Twenty-eight cookies, four friends, and a remainder"),
 ]),
 dict(n=7, band="3-5", title="Place Value and Multi-Digit Arithmetic", strand="Number", chapters=[
  dict(n=13, title="Place Value to the Millions", strand="Place Value",
       topics="Each place is ten times the one to its right; reading and writing large numbers; expanded and word form; comparing and ordering; rounding to any place and when to round; adding and subtracting multi-digit numbers with the standard algorithm and place-value reasoning.",
       story="How many seconds old are you?"),
  dict(n=14, title="Multi-Digit Multiplication and Division", strand="Operations",
       topics="Multiplying by tens and hundreds; area models and partial products for two- and three-digit numbers; the standard algorithm and why it works; dividing with partial quotients and long division; interpreting remainders; estimating products and quotients; multi-step problems.",
       story="The school's 27 classrooms and 34 desks each: a problem too big to count"),
 ]),
 dict(n=8, band="3-5", title="Fractions", strand="Number", chapters=[
  dict(n=15, title="What a Fraction Is", strand="Fractions",
       topics="A fraction as parts of a whole and as a number on the number line; unit fractions; equivalent fractions with models and by multiplying; comparing fractions with the same numerator or the same denominator and with benchmarks; whole numbers as fractions; fractions greater than one and mixed numbers.",
       story="The ruler, the pizza and the running track all agree on one thing"),
  dict(n=16, title="Adding, Subtracting and Multiplying Fractions", strand="Fractions",
       topics="Adding and subtracting with like denominators, then unlike; mixed numbers; multiplying a fraction by a whole number and by a fraction with area models; multiplication as scaling (bigger or smaller?); word problems with recipes and measurements.",
       story="Doubling a recipe that calls for 3/4 cup"),
  dict(n=17, title="Dividing With Fractions", strand="Fractions",
       topics="Dividing a whole number by a unit fraction and a unit fraction by a whole number with models; the story behind 'how many 1/4s in 3?'; fractions as division (3 ÷ 4 = 3/4); reasoning about answers; line plots with fractional data.",
       story="Cutting ribbon: three yards, quarter-yard bows"),
 ]),
 dict(n=9, band="3-5", title="Decimals", strand="Number", chapters=[
  dict(n=18, title="Tenths, Hundredths and Thousandths", strand="Decimals",
       topics="Decimals as fractions with denominators 10, 100, 1,000; place value to thousandths; reading, writing and comparing decimals; rounding decimals; decimals on the number line; money as decimals; metric units as decimals.",
       story="The 100-meter dash and the hundredths of a second between first and second"),
  dict(n=19, title="Operations With Decimals", strand="Decimals",
       topics="Adding and subtracting decimals with place-value alignment; multiplying decimals with models and reasoning about the decimal point; dividing decimals; multiplying and dividing by powers of ten; estimating; word problems with money and measurement.",
       story="The grocery receipt that did not add up"),
 ]),
 dict(n=10, band="3-5", title="Measurement and Data", strand="Measurement", chapters=[
  dict(n=20, title="Area, Perimeter and Volume", strand="Measurement",
       topics="Area as covering with unit squares; area of rectangles by multiplying; perimeter as distance around; same area, different perimeter; area of composite shapes; volume as packing with unit cubes; volume of rectangular prisms; formulas as shortcuts for counting.",
       story="Fencing and seeding the school garden"),
  dict(n=21, title="Units, Time and Data Displays", strand="Measurement and Data",
       topics="Converting within a system (inches to feet, grams to kilograms, minutes to hours); elapsed time; liquid volume and mass; line plots, bar graphs and picture graphs with scales; reading and making data displays; solving problems from data.",
       story="The class pet's weight, week by week, on a line plot"),
 ]),
 dict(n=11, band="3-5", title="Geometry and the Coordinate Plane", strand="Geometry", chapters=[
  dict(n=22, title="Angles, Lines and Shapes", strand="Geometry",
       topics="Points, lines, rays and angles; measuring angles in degrees with a protractor; right, acute and obtuse; parallel and perpendicular lines; classifying triangles and quadrilaterals by their properties; the hierarchy of shapes (every square is a rectangle); lines of symmetry.",
       story="The city planner's map and the angles of the streets"),
  dict(n=23, title="The Coordinate Plane and Patterns", strand="Geometry and Patterns",
       topics="The first quadrant: ordered pairs, plotting points, distances along grid lines; graphing a pattern; two number patterns and their relationship (add 3 vs add 6); generating and describing numerical patterns; real-world coordinate problems.",
       story="Treasure map: the X is at (7, 4)"),
 ]),

 # ══════════════════════════════ 6–8 ══════════════════════════════
 dict(n=12, band="6-8", title="Ratios, Rates and Proportions", strand="Ratios and Proportional Relationships", chapters=[
  dict(n=24, title="Ratios and Unit Rates", strand="Ratios",
       topics="Ratio language and notation; equivalent ratios with tables and double number lines; unit rates (miles per hour, dollars per pound); comparing rates; ratio problems with tape diagrams; converting units with rates; ratios in recipes, maps and speeds.",
       story="Which is the better deal? Two boxes of cereal and a calculator"),
  dict(n=25, title="Proportional Relationships and Percent", strand="Proportions",
       topics="Recognizing proportional relationships in tables, graphs and equations (y = kx); the constant of proportionality; percent as a rate per 100; percent of a number; percent increase and decrease; tax, tip, discount, simple interest and percent error; scale drawings.",
       story="The sale sign that said 30% off, then 20% more off"),
 ]),
 dict(n=13, band="6-8", title="The Number System", strand="Number", chapters=[
  dict(n=26, title="Integers and Rational Numbers", strand="Rational Numbers",
       topics="Negative numbers on the number line and in the world (temperature, elevation, debt); opposites and absolute value; ordering rational numbers; the coordinate plane with four quadrants; distances between points; fractions and decimals as rational numbers; repeating decimals.",
       story="Chicago in January: minus 20 and the wind chill"),
  dict(n=27, title="Operations With Rational Numbers", strand="Rational Numbers",
       topics="Adding and subtracting integers with chips and number lines; subtraction as adding the opposite; multiplying and dividing signed numbers and why a negative times a negative is positive; the properties of operations; operations with fractions and decimals of any sign; multi-step problems.",
       story="The checking account that went below zero"),
  dict(n=28, title="Exponents, Roots and Scientific Notation", strand="Number",
       topics="Integer exponents and their properties; zero and negative exponents; square roots and cube roots; perfect squares; rational vs irrational numbers and where √2 sits on the line; scientific notation for very large and very small numbers; operations in scientific notation.",
       story="The grains of rice on the chessboard"),
 ]),
 dict(n=14, band="6-8", title="Expressions, Equations and Inequalities", strand="Algebra Begins", chapters=[
  dict(n=29, title="Expressions and Properties", strand="Expressions",
       topics="Variables as unknowns and as quantities that vary; writing expressions from words; order of operations; evaluating expressions; equivalent expressions with the distributive property; combining like terms; factoring an expression; expressions for perimeter, cost and patterns.",
       story="The phone plan: $20 plus $5 a gigabyte"),
  dict(n=30, title="Equations and Inequalities", strand="Equations",
       topics="Solving one-step and two-step equations by keeping the balance; equations with the variable on both sides; equations with the distributive property; inequalities and their graphs on a number line; solving and interpreting inequalities in context; checking a solution.",
       story="The balance scale that explains every equation"),
 ]),
 dict(n=15, band="6-8", title="Functions and Linear Equations", strand="Algebra", chapters=[
  dict(n=31, title="Linear Equations and Slope", strand="Linear Equations",
       topics="Slope as rate of change and as rise over run; the same slope between any two points on a line (similar triangles); y = mx + b; graphing from slope and intercept; writing an equation from a graph, a table or two points; proportional vs linear; horizontal and vertical lines.",
       story="Two hills, two staircases, and the number that describes steepness"),
  dict(n=32, title="Functions", strand="Functions",
       topics="A function as a rule with exactly one output per input; tables, graphs, equations and words; linear vs nonlinear; comparing two functions given in different ways; sketching a graph from a story and telling a story from a graph; rate of change and initial value.",
       story="The graph of a bike ride: uphill, flat, a stop for water"),
  dict(n=33, title="Systems of Equations", strand="Systems",
       topics="Two lines, one point; solving systems by graphing, substitution and elimination; one solution, no solution, infinitely many; systems in context (two phone plans, mixing solutions); estimating a solution from a graph and checking it.",
       story="When does the tortoise catch the hare?"),
 ]),
 dict(n=16, band="6-8", title="Geometry", strand="Geometry", chapters=[
  dict(n=34, title="Area, Surface Area and Volume", strand="Measurement",
       topics="Area of triangles, parallelograms and trapezoids by decomposing; area of circles and the meaning of π; nets and surface area of prisms and pyramids; volume of prisms, cylinders, cones and spheres; problems with packaging, paint and pools.",
       story="Measuring a circle with a piece of string"),
  dict(n=35, title="Angles, Triangles and Scale", strand="Geometry",
       topics="Angle relationships — complementary, supplementary, vertical, adjacent; angles formed by parallel lines and a transversal; the angle sum of a triangle and why; the triangle inequality; constructing triangles from given conditions; scale drawings and scale factor; cross sections.",
       story="The surveyor who measured the Earth with shadows"),
  dict(n=36, title="Transformations and the Pythagorean Theorem", strand="Geometry",
       topics="Translations, reflections, rotations and dilations on the coordinate plane; congruence and similarity through transformations; the Pythagorean theorem with a proof by areas; its converse; distances on the coordinate plane; real applications (ladders, TV screens, diagonals).",
       story="A 3-4-5 rope and the builders of the pyramids"),
 ]),
 dict(n=17, band="6-8", title="Statistics and Probability", strand="Statistics and Probability", chapters=[
  dict(n=37, title="Describing Data", strand="Statistics",
       topics="Statistical questions; dot plots, histograms and box plots; measures of center (mean, median) and spread (range, interquartile range, mean absolute deviation); choosing the right measure; the shape of a distribution; comparing two groups.",
       story="How tall is a seventh grader? Twenty-eight answers and one class"),
  dict(n=38, title="Probability and Sampling", strand="Probability",
       topics="Probability as a number from 0 to 1; theoretical vs experimental probability; sample spaces, tree diagrams and lists for compound events; simulations; random samples and why they matter; drawing inferences about a population; comparing two populations.",
       story="Is the coin fair? A hundred flips"),
  dict(n=39, title="Two-Variable Data", strand="Statistics",
       topics="Scatter plots; patterns — clusters, outliers, positive and negative association, linear and nonlinear; fitting a line by eye; interpreting slope and intercept of a fitted line; two-way tables for categorical data; relative frequencies.",
       story="Does more sleep mean better scores? A class investigates"),
 ]),

 # ══════════════════════════════ 9–10 ══════════════════════════════
 dict(n=18, band="9-10", title="Algebra I: Linear Equations, Functions and Systems", strand="Algebra", chapters=[
  dict(n=40, title="Solving Linear Equations and Inequalities", strand="Algebra",
       topics="Equations as statements that can be true or false; solving multi-step equations with justification; literal equations and rearranging formulas; absolute value equations; compound inequalities; modeling with equations and inequalities; units and reasonableness.",
       story="The formula on the back of the fertilizer bag"),
  dict(n=41, title="Functions and Linear Models", strand="Functions",
       topics="Function notation and domain and range; interpreting f(x) in context; key features of graphs; linear functions and arithmetic sequences; slope as average rate of change; building linear models from data and situations; piecewise and step functions; transformations of linear graphs.",
       story="Taxi fare, cell data and the meaning of f(3)"),
  dict(n=42, title="Systems of Equations and Inequalities", strand="Systems",
       topics="Solving systems exactly and approximately; elimination as adding equations; systems with no or infinitely many solutions; systems of linear inequalities and feasible regions; linear programming lite — the best mix within limits; modeling business and mixture problems.",
       story="The bake sale budget: cookies, brownies and a table that only holds so much"),
 ]),
 dict(n=19, band="9-10", title="Algebra I: Exponents, Polynomials and Quadratics", strand="Algebra", chapters=[
  dict(n=43, title="Exponents and Exponential Functions", strand="Exponentials",
       topics="Properties of exponents including rational exponents; radicals; exponential growth and decay (doubling, half-life, interest); geometric sequences; comparing linear and exponential growth; building exponential models from tables and stories.",
       story="A penny doubled every day for a month"),
  dict(n=44, title="Polynomials and Factoring", strand="Polynomials",
       topics="Adding, subtracting and multiplying polynomials; the structure of expressions; factoring by GCF, trinomials, difference of squares and grouping; polynomial identities; the zero-product property; area models for multiplication and factoring.",
       story="The garden border problem: a rectangle inside a rectangle"),
  dict(n=45, title="Quadratic Functions and Equations", strand="Quadratics",
       topics="Graphs of quadratics — vertex, axis, intercepts; forms (standard, vertex, factored) and what each shows; solving by factoring, square roots, completing the square and the quadratic formula; the discriminant; projectile and area models; comparing linear, exponential and quadratic.",
       story="The basketball's arc and the equation that predicts it"),
 ]),
 dict(n=20, band="9-10", title="Geometry: Reasoning, Congruence and Triangles", strand="Geometry", chapters=[
  dict(n=46, title="Reasoning and Proof", strand="Geometry",
       topics="Definitions, postulates and theorems; inductive and deductive reasoning; conditional statements and converses; two-column, paragraph and flow proofs; angle and segment proofs; parallel lines and transversals proved; constructions with compass and straightedge.",
       story="Euclid's five rules and two thousand years of building on them"),
  dict(n=47, title="Congruence and Transformations", strand="Geometry",
       topics="Rigid motions and the definition of congruence; transformations in the coordinate plane with rules; symmetry; triangle congruence criteria (SSS, SAS, ASA, AAS) and why SSA fails; using congruent triangles to prove parts congruent (CPCTC); quadrilateral properties and proofs.",
       story="The bridge truss: why triangles hold and squares fold"),
  dict(n=48, title="Triangles and Their Centers", strand="Geometry",
       topics="The triangle angle sum and exterior angles; isosceles and equilateral theorems; perpendicular bisectors, angle bisectors, medians and altitudes; circumcenter, incenter, centroid; inequalities in triangles; the midsegment theorem; coordinate proofs.",
       story="Where to build the fire station: the point the same distance from three towns"),
 ]),
 dict(n=21, band="9-10", title="Geometry: Similarity, Trigonometry and Circles", strand="Geometry", chapters=[
  dict(n=49, title="Similarity and Right-Triangle Trigonometry", strand="Geometry",
       topics="Dilations and the definition of similarity; AA, SAS, SSS similarity; proportions in triangles; the Pythagorean theorem proved by similarity; special right triangles; sine, cosine and tangent as ratios; solving right triangles; angles of elevation and depression; indirect measurement.",
       story="Measuring the flagpole with a mirror on the ground"),
  dict(n=50, title="Circles, Area and Volume", strand="Geometry",
       topics="Central and inscribed angles; chords, tangents and secants; arc length and sector area; radians introduced; the equation of a circle; area and circumference derived; volume of cylinders, cones, spheres and pyramids with Cavalieri's principle; density and modeling with solids.",
       story="Why manhole covers are round"),
 ]),
 dict(n=22, band="9-10", title="Statistics in Algebra I", strand="Statistics", chapters=[
  dict(n=51, title="Describing and Comparing Data", strand="Statistics",
       topics="Dot plots, histograms, box plots; shape, center and spread; standard deviation introduced; outliers and their effect; comparing distributions; two-way frequency tables and conditional relative frequencies; reading data honestly.",
       story="Two pitchers, same average, very different seasons"),
  dict(n=52, title="Lines of Fit and Correlation", strand="Statistics",
       topics="Scatter plots and linear fits; residuals and residual plots; the correlation coefficient and what it does and does not mean; correlation is not causation; fitting exponential and quadratic models when a line fails; interpolation vs extrapolation.",
       story="Ice cream sales and drownings: the number that fooled a town"),
 ]),

 # ══════════════════════════════ 11–12 ══════════════════════════════
 dict(n=23, band="11-12", title="Algebra II: Polynomial, Rational and Radical Functions", strand="Algebra", chapters=[
  dict(n=53, title="Polynomial Functions", strand="Algebra",
       topics="Complex numbers and the fundamental theorem of algebra; polynomial division and the remainder and factor theorems; zeros, multiplicity and end behavior; graphing polynomials; building polynomial models (box volume); systems with a quadratic.",
       story="The open-top box: fold the corners and find the biggest volume"),
  dict(n=54, title="Rational and Radical Functions", strand="Algebra",
       topics="Rational expressions and their domains; operations with rational expressions; asymptotes and holes; solving rational equations and extraneous solutions; inverse variation; radical functions and equations; inverse functions; composition.",
       story="Average speed for the round trip is not the average of the speeds"),
 ]),
 dict(n=24, band="11-12", title="Algebra II: Exponential, Logarithmic and Trigonometric Functions", strand="Algebra", chapters=[
  dict(n=55, title="Exponentials and Logarithms", strand="Algebra",
       topics="The number e and continuous growth; logarithms as inverses; properties of logarithms; solving exponential and logarithmic equations; modeling with exponentials — population, compound interest, radioactive decay, the Richter and pH scales; logistic growth in plain terms.",
       story="The earthquake scale: why a 7 is thirty times a 6"),
  dict(n=56, title="Trigonometric Functions", strand="Trigonometry",
       topics="The unit circle and radians; sine and cosine as coordinates; graphs of sine, cosine and tangent; amplitude, period, phase shift; modeling periodic phenomena (tides, daylight, sound); the Pythagorean identity; solving simple trigonometric equations; the laws of sines and cosines.",
       story="The hours of daylight in Chicago across a year, as a wave"),
 ]),
 dict(n=25, band="11-12", title="Sequences, Series and Modeling", strand="Algebra and Modeling", chapters=[
  dict(n=57, title="Sequences and Series", strand="Sequences",
       topics="Arithmetic and geometric sequences, explicit and recursive; sigma notation; arithmetic and geometric series and their sums; infinite geometric series and convergence; the Fibonacci sequence and the golden ratio; recursion in the world — loans, populations, fractals.",
       story="Gauss adds 1 to 100 in a minute"),
  dict(n=58, title="Modeling With Functions", strand="Modeling",
       topics="The modeling cycle — question, assumptions, model, check, revise; choosing a function family from a situation; combining and transforming functions; fitting models to data with technology; piecewise models; error, limits of a model, and communicating a result.",
       story="How many people can Soldier Field empty in ten minutes?"),
 ]),
 dict(n=26, band="11-12", title="Statistics: From a Sample to a Claim", strand="Statistics and Probability", chapters=[
  dict(n=59, title="Distributions and the Normal Curve", strand="Statistics",
       topics="The normal distribution and the empirical rule; z-scores and percentiles; when the normal model fits and when it does not; probability rules — independence, conditional probability, two-way tables; expected value and decisions; the binomial setting in plain terms.",
       story="The height chart at the doctor's office: what the 90th percentile means"),
  dict(n=60, title="Sampling, Inference and Claims", strand="Statistics",
       topics="Surveys, experiments and observational studies; randomization and bias; sampling variability and simulation; margin of error and confidence intervals in plain terms; the logic of a hypothesis test; evaluating reports and headlines that use data; statistical vs practical significance.",
       story="The poll that called the election wrong, and what it forgot to ask"),
 ]),
 dict(n=27, band="11-12", title="Financial Math and Capstone", strand="Applied Mathematics", chapters=[
  dict(n=61, title="Financial Math", strand="Applied Mathematics",
       topics="Simple and compound interest; the effective annual rate; loans and amortization — car and student loans, mortgages; credit cards and minimum payments; saving and investing, the time value of money; budgets, taxes and take-home pay; inflation; deciding between options with math.",
       story="Two roommates, one car loan, and the difference a rate makes"),
  dict(n=62, title="Capstone: Model It", strand="Modeling",
       topics="Choosing a real question; gathering and cleaning data; building and comparing models; sensitivity and assumptions; visualizing results honestly; writing a mathematical argument; presenting and defending the model; a project plan with checkpoints.",
       story="The traffic light on Main Street: timing it with math"),
 ]),
]

# Rooms already on the site that belong to each unit — nothing gets deleted.
LINKS = {
 1: [("/m15", "Counting and how many — cards, quiz and lab"), ("/m17", "Tens and ones, then hundreds")],
 2: [("/m16", "Adding and subtracting within 20 — cards, quiz and lab")],
 3: [("/m17", "Tens and ones, then hundreds — cards, quiz and lab"), ("/m18", "Adding and subtracting within 1,000")],
 4: [("/m19", "Length, time and money — cards, quiz and lab")],
 5: [("/m20", "Shapes and equal shares — cards, quiz and lab")],
 6: [("/m21", "Multiplication and division: what they mean — cards, quiz and lab"), ("/concepts", "The operations that carry everything")],
 7: [("/m22", "Multi-digit multiplication — cards, quiz and lab")],
 8: [("/m23", "Fractions: add, subtract, multiply — cards, quiz and lab"), ("/concepts", "What a fraction is")],
 9: [("/m24", "Decimals — cards, quiz and lab")],
 10: [("/m25", "Measurement: area, perimeter, volume — cards, quiz and lab")],
 11: [("/m26", "Geometry and the coordinate plane — cards, quiz and lab")],
 12: [("/m27", "Ratios, rates and unit rates"), ("/m28", "Proportional relationships and percent")],
 13: [("/interior#mo-sep", "Integers — the 7th-grade year"), ("/interior#mo-oct", "Multiply, divide, properties"), ("/m33", "Exponents, roots and scientific notation"), ("/concepts", "Numbers that tell a story")],
 14: [("/interior#mo-nov", "Expressions — the 7th-grade year"), ("/interior#mo-dec", "Equations — the 7th-grade year"), ("/m29", "Inequalities")],
 15: [("/m34", "Linear equations and systems"), ("/m35", "Functions and slope")],
 16: [("/m30", "Area, surface area and volume"), ("/m31", "Angles, triangles and scale drawings"), ("/m36", "Transformations, congruence and similarity"), ("/m37", "The Pythagorean theorem")],
 17: [("/m32", "Probability and sampling"), ("/b12", "Review week · 6th-grade skills"), ("/b13", "Review week · practice")],
 18: [("/m38", "Algebra I: linear equations and inequalities"), ("/m39", "Algebra I: functions and linear models"), ("/m40", "Algebra I: systems")],
 19: [("/m41", "Algebra I: exponents, polynomials, factoring"), ("/m42", "Algebra I: quadratics")],
 20: [("/m43", "Geometry: proof, congruence and triangles")],
 21: [("/m44", "Geometry: similarity and right-triangle trigonometry"), ("/m45", "Geometry: circles, area and volume")],
 22: [("/m39", "Algebra I: functions and linear models"), ("/m50", "Statistics: from a sample to a claim")],
 23: [("/m46", "Algebra II: polynomial and rational functions")],
 24: [("/m47", "Algebra II: exponential and logarithmic functions"), ("/m48", "Trigonometric functions")],
 25: [("/m49", "Sequences and series"), ("/m52", "Capstone: model it")],
 26: [("/m50", "Statistics: from a sample to a claim")],
 27: [("/m51", "Financial math"), ("/m52", "Capstone: model it")],
}
