# Social Studies, K–12 — the course arc. Our own wording, following the Illinois
# Learning Standards for Social Science (civics, geography, economics, history,
# and the inquiry skills) band by band. Topics guide the writers; story = the
# chapter's opening narrative hook. Nothing here is copied from any textbook.
#
# Units number 1–24 straight through the course; chapters 1–55. `band` is the
# grade band; `strand` prints where a unit's years go; `level` sets the writing
# rules (SPEC.md). U.S. History for grades 6–8 is its own course (/us-history);
# this course's 6–8 band carries the world history, geography and Illinois civics
# that sit beside it, and links to it.

BANDS = [
 dict(id="k-2",   title="Grades K–2",   level="k2"),
 dict(id="3-5",   title="Grades 3–5",   level="35"),
 dict(id="6-8",   title="Grades 6–8",   level="68"),
 dict(id="9-10",  title="Grades 9–10",  level="hs"),
 dict(id="11-12", title="Grades 11–12", level="hs2"),
]

UNITS = [
 # ══════════════════════════════ K–2 ══════════════════════════════
 dict(n=1, band="k-2", title="Me, My Family, My School", strand="Civics and History", chapters=[
  dict(n=1, title="Who I Am and Who I Live With", strand="Identity and Family",
       topics="Every person has a name, a birthday, things they like and things they can do; families come in many shapes and sizes; family members help each other; family traditions and celebrations; a family story from long ago (a grandparent's childhood); how we are the same and different from classmates and why that is good.",
       story="Ana's family dinner: four generations at one table, and the story Grandpa tells every time"),
  dict(n=2, title="Rules at School and at Home", strand="Civics",
       topics="Why we have rules (safety, fairness, getting along); rules at home, in class, on the bus, at the pool; who makes the rules and how a class can make its own; what happens when a rule is broken and how to make it right; being a good classmate: taking turns, listening, telling the truth; a teacher, a principal and a crossing guard are leaders who help.",
       story="The first day of school: a class writes its own three rules"),
 ]),
 dict(n=2, band="k-2", title="Our Community", strand="Civics and Economics", chapters=[
  dict(n=3, title="Neighbors, Helpers and Jobs", strand="Community",
       topics="A community is the people who live and work near each other; neighborhoods in a city, a town and the country; community helpers (firefighter, nurse, mail carrier, bus driver, librarian, farmer) and what they do; every job matters; places in a community (school, library, park, clinic, store, place of worship); how people in a community solve a problem together (a playground cleanup).",
       story="The day the neighborhood fixed the broken swing"),
  dict(n=4, title="Needs, Wants and Money", strand="Economics",
       topics="Needs (food, water, shelter, clothes) and wants (a toy, a treat); people work to earn money; money buys goods and services; a goods is a thing, a service is work someone does for you; you cannot buy everything, so you choose; saving for something you want; trading and sharing; where food comes from (farm to store to table).",
       story="Leo's lemonade stand: earning, spending and the choice about the bike"),
 ]),
 dict(n=3, band="k-2", title="Maps and Places", strand="Geography", chapters=[
  dict(n=5, title="Where Things Are", strand="Maps",
       topics="A map is a drawing of a place from above; a map of the classroom, the school, the neighborhood; a map key and symbols; near and far, left and right, north, south, east and west; a globe is a model of Earth; land and water on a map; finding Illinois, the United States and Chicago; a route from home to school.",
       story="A treasure map of the classroom, drawn by the class"),
  dict(n=6, title="Land, Water and Weather Where We Live", strand="Places",
       topics="Landforms and water: hills, plains, rivers, lakes (Lake Michigan), the ocean; Illinois is mostly flat prairie and farmland; weather changes by season and shapes what people wear and do; people change places (build roads, plant crops, dig a pond) and places shape people (a fishing town, a farm town); taking care of a place: litter, water, trees.",
       story="A drive from Chicago to a farm downstate: what changes out the window"),
 ]),
 dict(n=4, band="k-2", title="Then and Now, and Our Country", strand="History and Civics", chapters=[
  dict(n=7, title="Long Ago and Today", strand="History",
       topics="Past, present and future; things that changed (how people travel, cook, talk to each other, go to school) and things that stayed the same (families, play, food); a timeline of a child's life and a family's life; old photos and objects as clues about the past; how a town changed over 100 years; asking a grown-up what school was like.",
       story="A shoebox of Grandma's things: a rotary phone, a ticket and a photo"),
  dict(n=8, title="Symbols, Holidays and Being a Citizen", strand="Civics",
       topics="The flag and what its stars and stripes stand for; the Pledge; the bald eagle, the Liberty Bell, the Statue of Liberty; holidays and who they remember (Martin Luther King Jr. Day, Presidents' Day, Independence Day, Veterans Day); people who made a difference (Abraham Lincoln from Illinois, Harriet Tubman, Cesar Chavez, Jane Addams of Chicago); being a good citizen: voting, helping, speaking up; a class vote.",
       story="The class votes on the name of the new class pet"),
 ]),

 # ══════════════════════════════ 3–5 ══════════════════════════════
 dict(n=5, band="3-5", title="Illinois: Land and People", strand="Geography and History", chapters=[
  dict(n=9, title="The Prairie State", strand="Illinois Geography",
       topics="Illinois on the map: neighbors, the Mississippi, Ohio, Illinois and Wabash rivers, Lake Michigan; the glaciers that flattened the land; the tallgrass prairie and the rich soil; regions of the state (Chicago and the north, the central farmland, the Shawnee hills in the south); climate and the seasons, tornadoes and floods; natural resources (soil, coal, water) and the main crops (corn, soybeans); how people use and change the land.",
       story="Standing in a restored prairie in June with grass taller than you"),
  dict(n=10, title="Illinois Then and Now", strand="Illinois History",
       topics="The Illinois people (Illiniwek) and the Cahokia mounds; French forts and fur traders; Illinois becomes a state in 1818; the Erie Canal, the Illinois and Michigan Canal and the railroads; Chicago grows from a fort to a great city; the Great Chicago Fire of 1871 and rebuilding; the Great Migration; Illinois today: cities, farms, universities; Illinois people who made a difference (Lincoln, Jane Addams, Ida B. Wells, Ronald Reagan, Barack Obama).",
       story="The fire of 1871, told from a rooftop on the night the wind changed"),
 ]),
 dict(n=6, band="3-5", title="The First Peoples of North America", strand="History and Geography", chapters=[
  dict(n=11, title="Nations Across the Continent", strand="Indigenous Peoples",
       topics="Peoples lived here for thousands of years; different lands, different ways of life: the Eastern Woodlands (longhouses, the three sisters), the Plains (bison, tipis), the Southwest (pueblos, irrigation), the Pacific Northwest (cedar, salmon, totem poles), the Arctic; Cahokia, the largest city north of Mexico; governments and councils (the Haudenosaunee Confederacy); stories, art and trade; Native nations today, including in Illinois and Chicago.",
       story="A market day at Cahokia around the year 1100"),
  dict(n=12, title="Encounter and Change", strand="Contact",
       topics="Why Europeans sailed west (trade, gold, land, religion); Columbus and what 1492 set in motion; the Columbian Exchange: horses, corn, potatoes, diseases; Spanish, French and English settlements and how each treated the peoples already there; trade, alliances and conflict; the loss of land and life; how Native peoples resisted and adapted; different points of view on the same events.",
       story="A French trader and an Illinois family exchange goods on the river, 1680"),
 ]),
 dict(n=7, band="3-5", title="Colonies to a New Nation", strand="U.S. History", chapters=[
  dict(n=13, title="Thirteen Colonies", strand="Colonial Life",
       topics="New England, Middle and Southern colonies and how geography shaped each; farms, towns, ships and shops; daily life for children; religion and schools; who had freedom and who did not: indentured servants and enslaved Africans; the Middle Passage in plain words; town meetings and colonial assemblies as early self-government; Britain far away and mostly hands-off.",
       story="A morning in 1740 on a Pennsylvania farm and a morning on a South Carolina rice plantation"),
  dict(n=14, title="Revolution and Constitution", strand="Founding",
       topics="Taxes without a vote (Stamp Act, tea), protests and the Boston Massacre; the Declaration of Independence and its big idea that people have rights; the war: Washington, Valley Forge, everyday soldiers, allies from France; the Articles of Confederation and why they failed; the Constitution: a plan with three branches, checks and balances, the Bill of Rights; who was left out at first and how the promise was stretched later.",
       story="Philadelphia, summer 1787: windows shut in the heat so no one could hear"),
  dict(n=15, title="The Young Nation Grows", strand="Expansion",
       topics="Washington the first president; the Louisiana Purchase and Lewis and Clark; the Northwest Territory and how Illinois came in; canals, steamboats and railroads; moving west and what that meant for Native nations (the Trail of Tears); inventions that changed work (the cotton gin, the reaper); the nation grows and the argument about slavery grows with it.",
       story="A flatboat down the Ohio in 1830 with everything a family owns"),
 ]),
 dict(n=8, band="3-5", title="Government: Local, State, National", strand="Civics", chapters=[
  dict(n=16, title="What Government Does and Who Decides", strand="Government",
       topics="Why we have government: laws, safety, roads, schools, parks; three levels — city or village, state, nation — and what each does; three branches at each level and who is in them (mayor and council, governor and General Assembly, president and Congress, judges); how a law is made; elections and voting; democracy means people decide; a class or school council as a small government.",
       story="A village board meeting about a new stop sign"),
  dict(n=17, title="Rights, Responsibilities and Illinois", strand="Citizenship",
       topics="Rights in the Bill of Rights in kid terms (speech, religion, fair trial); responsibilities: obeying laws, paying taxes, serving on juries, voting, speaking up; the Illinois Constitution and Springfield; how to make a change: petitions, letters, meetings, volunteering; symbols of Illinois; people who used their rights to make things fairer (Jane Addams, Ida B. Wells).",
       story="Fourth graders who got a crosswalk painted, step by step"),
 ]),
 dict(n=9, band="3-5", title="Money, Markets and Regions", strand="Economics and Geography", chapters=[
  dict(n=18, title="Producers, Consumers and Choices", strand="Economics",
       topics="Producers make and consumers buy; goods and services; scarcity: you cannot have everything, so every choice gives something up (opportunity cost); supply and demand in a school store; prices; earning, saving, spending and giving; banks; taxes pay for public goods; specialization and trade: why Illinois grows corn and Florida grows oranges; entrepreneurs.",
       story="The fifth-grade school store runs out of pencils and learns about price"),
  dict(n=19, title="Regions of the United States", strand="U.S. Geography",
       topics="Latitude and longitude, map scale, physical and political maps; five regions (Northeast, Southeast, Midwest, Southwest, West) and their landforms, climate, resources and big cities; the Midwest and Illinois in detail; rivers, mountains, deserts and coasts; how geography shapes jobs and food; moving people and goods across the country; natural hazards by region.",
       story="A truck of Illinois corn on its way to a port in New Orleans"),
 ]),

 # ══════════════════════════════ 6–8 ══════════════════════════════
 dict(n=10, band="6-8", title="The First Civilizations", strand="World History", chapters=[
  dict(n=20, title="From Hunting to Farming", strand="Prehistory",
       topics="How we know about people before writing: tools, bones, cave art, sites; hunter-gatherers and their skills; the last Ice Age and the peopling of the continents; the farming revolution around 10,000 years ago in several places; villages, surplus, specialization, social classes; Çatalhöyük; domestication of plants and animals; why farming changed everything, for better and worse.",
       story="A hunting band follows the herds, and one autumn some of them stay"),
  dict(n=21, title="Mesopotamia and Egypt", strand="River Valleys",
       topics="Rivers and civilization: the Tigris and Euphrates, the Nile; irrigation and floods; Sumer's city-states, cuneiform, the wheel, ziggurats; Hammurabi's Code; Egypt's Old, Middle and New Kingdoms, pharaohs, pyramids, hieroglyphs, the Rosetta Stone; daily life, women, workers, scribes; trade and war; what each civilization left us (writing, law, calendars).",
       story="A scribe's first day in a Sumerian tablet house"),
  dict(n=22, title="Indus, China and the Early Americas", strand="River Valleys",
       topics="The Indus cities (Harappa, Mohenjo-daro): planned streets, drains, an undeciphered script; early China: the Shang, oracle bones, the Zhou and the Mandate of Heaven; the Yellow River; the Olmec and early Mesoamerica; Norte Chico in Peru; what all early civilizations share and how they differ; how archaeologists work.",
       story="A cracked oracle bone and the question a Shang king asked it"),
 ]),
 dict(n=11, band="6-8", title="Classical Worlds", strand="World History", chapters=[
  dict(n=23, title="Ancient Greece", strand="Greece",
       topics="Mountains, islands and city-states; Athens and Sparta; the birth of democracy and who was excluded; the Persian Wars; the Golden Age: Parthenon, theater, philosophy (Socrates, Plato, Aristotle), history (Herodotus), medicine; Alexander the Great and the Hellenistic world; Greek ideas in our own government and language.",
       story="A citizen of Athens hurries to the Assembly on the Pnyx hill"),
  dict(n=24, title="Rome: Republic to Empire", strand="Rome",
       topics="Rome's founding stories and geography; the Republic: consuls, Senate, plebeians and patricians, the Twelve Tables; expansion and the Punic Wars; Julius Caesar and the end of the Republic; Augustus and the Pax Romana; roads, aqueducts, law, Latin; daily life, slavery, gladiators; Christianity in the empire; why the western empire fell and what survived.",
       story="A day in Pompeii in August of the year 79"),
  dict(n=25, title="India, China and the Silk Roads", strand="Asia",
       topics="The Maurya and Gupta empires; Ashoka's turn to peace; Hinduism and Buddhism in their historical setting; zero and Indian mathematics; the Qin and the first emperor, the terracotta army, the Great Wall; the Han dynasty, Confucian government, paper, the civil service; the Silk Roads: goods, ideas and diseases across Eurasia.",
       story="A camel caravan leaves Chang'an with silk and comes home with glass"),
 ]),
 dict(n=12, band="6-8", title="Faiths, Empires and Exchange", strand="World History", chapters=[
  dict(n=26, title="Islam, Byzantium and Africa", strand="500–1500",
       topics="The Byzantine Empire: Constantinople, Justinian's code, Hagia Sophia; the rise of Islam in its historical setting, the caliphates, the House of Wisdom, algebra and astronomy; trade across the Sahara; Ghana, Mali and Mansa Musa, Timbuktu; Great Zimbabwe and the Swahili coast; how gold, salt and ideas moved.",
       story="Mansa Musa's caravan arrives in Cairo, 1324, and the price of gold falls"),
  dict(n=27, title="Mongols, Medieval Europe and the Americas", strand="500–1500",
       topics="Feudal Europe: lords, knights, serfs, the Church, castles and cathedrals; the Crusades; the Black Death; the Magna Carta; Genghis Khan and the Mongol empire, the Pax Mongolica, Marco Polo; Japan under the shoguns; the Maya, Aztec and Inca: cities, calendars, roads, farming; the world in 1450 on the eve of contact.",
       story="A village in England in 1348 as the plague arrives by cart"),
 ]),
 dict(n=13, band="6-8", title="Geography of the World", strand="Geography", chapters=[
  dict(n=28, title="Reading the World", strand="Physical Geography",
       topics="Latitude, longitude, projections and why maps lie a little; the continents and oceans; plate tectonics, mountains, earthquakes and volcanoes; climate zones and what makes climate (latitude, altitude, oceans, winds); biomes from rainforest to tundra; rivers and watersheds; natural hazards and how people prepare; maps as arguments.",
       story="Three maps of the same world that make Africa three different sizes"),
  dict(n=29, title="People, Resources and Trade", strand="Human Geography",
       topics="Where people live and why (water, soil, coasts, cities); population growth and density; migration: push and pull; culture regions, languages and religions on the map; natural resources, renewable and not; farming, industry and services; trade routes then and now; globalization in a pair of shoes; cities and their problems; the environment and human choices.",
       story="Following one pair of sneakers from cotton field to your closet"),
 ]),
 dict(n=14, band="6-8", title="Citizens of Illinois", strand="Civics", chapters=[
  dict(n=30, title="The Constitution and Illinois Government", strand="Government",
       topics="Why the framers built three branches; the Preamble in plain words; Congress, the President, the Courts and how each checks the others; federalism: what the nation does and what Illinois does; the Illinois Constitution of 1970; the General Assembly, the governor, the Illinois Supreme Court; counties, townships, cities and school boards; the budget and taxes.",
       story="A bill about school start times travels from a student's idea to the governor's desk"),
  dict(n=31, title="Rights, Courts and Taking Part", strand="Citizenship",
       topics="The Bill of Rights, amendment by amendment; how rights have grown (13th, 14th, 15th, 19th, 26th); landmark cases students can grasp (Tinker, Brown, Miranda); how a court case works; voting: who can, how to register, why turnout matters; parties, media and finding the truth; ways to take part now: petitions, public comment, service, student government; civil discourse.",
       story="The armbands in Des Moines, 1965, and the case that reached the Supreme Court"),
 ]),

 # ══════════════════════════════ 9–10 ══════════════════════════════
 dict(n=15, band="9-10", title="World History: Empires and Exchange", strand="1200–1750", chapters=[
  dict(n=32, title="Networks of Afro-Eurasia", strand="1200–1450",
       topics="The Song dynasty's economic revolution; Islamic scholarship and Dar al-Islam; the Mongol empire's effects on trade and disease; Indian Ocean trade and the monsoon; trans-Saharan trade and Mali; the Black Death across continents; the Renaissance and the printing press; the Ottoman capture of Constantinople; the state of technology and knowledge in 1450 across regions.",
       story="Ibn Battuta sets out from Tangier in 1325 and does not stop for thirty years"),
  dict(n=33, title="The Atlantic World", strand="1450–1650",
       topics="Portuguese and Spanish voyages and the technology behind them; Columbus, the conquests of the Aztec and Inca and why they succeeded; the Columbian Exchange in full; the transatlantic slave trade: scale, systems, resistance; silver from Potosí and its global reach; the Reformation and religious wars; the Scientific Revolution; Europeans, Africans and Indigenous peoples in a single connected world.",
       story="Silver from Potosí pays for silk in Manila, 1580"),
  dict(n=34, title="Empires and the State", strand="1500–1750",
       topics="Gunpowder empires: Ottoman, Safavid, Mughal; the Ming and Qing; Tokugawa Japan's closed country; Russia under Peter; absolutism in France and constitutional government in England (the Glorious Revolution); the Enlightenment's ideas about rights and government; how states raised money and armies; comparing empires: tolerance, trade, art, decline.",
       story="Akbar's court in Fatehpur Sikri hosts a debate between faiths"),
 ]),
 dict(n=16, band="9-10", title="Revolutions and the Modern World", strand="1750–1914", chapters=[
  dict(n=35, title="Political Revolutions", strand="1750–1850",
       topics="The American Revolution as a world event; the French Revolution from the Estates-General to Napoleon; the Haitian Revolution; Latin American independence (Bolívar, Hidalgo); nationalism and the revolutions of 1848; abolition movements; what 'the rights of man' meant and who fought to be included (Olympe de Gouges, Toussaint Louverture).",
       story="The night of August 4, 1789, when the nobles gave up their privileges"),
  dict(n=36, title="The Industrial Revolution", strand="1760–1900",
       topics="Why Britain first: coal, capital, canals, cotton; steam engines, factories, railroads; the new working class, children in mills, the growth of cities; reformers, unions and Marx; industrialization spreads to Europe, the United States and Japan; new technologies (steel, electricity, telegraph) and new ideas; the environment and daily life transformed.",
       story="A ten-year-old's shift in a Manchester cotton mill, 1833"),
  dict(n=37, title="Nationalism and Imperialism", strand="1850–1914",
       topics="The unification of Italy and Germany; the Meiji Restoration; the scramble for Africa and the Berlin Conference; the British Raj and the 1857 rebellion; China's century of humiliation and the Boxer uprising; motives and justifications for empire, and resistance to it; the world of 1914: alliances, arms and a spark waiting.",
       story="Menelik II's army meets Italy at Adwa, 1896"),
 ]),
 dict(n=17, band="9-10", title="The Twentieth-Century World", strand="1914–Present", chapters=[
  dict(n=38, title="The World Wars", strand="1914–1945",
       topics="Causes of World War I, trench warfare, the home fronts, the Russian Revolution, the Treaty of Versailles; the Great Depression worldwide; fascism, Nazism and Stalinism; the road to World War II; the war in Europe and the Pacific; the Holocaust; the atomic bomb; the United Nations and a new balance of power.",
       story="Christmas 1914: soldiers climb out of the trenches to trade cigarettes"),
  dict(n=39, title="Cold War and Decolonization", strand="1945–1991",
       topics="Two superpowers and the iron curtain; the Marshall Plan, NATO and the Warsaw Pact; Korea, Cuba, Vietnam, Afghanistan; nuclear arms and détente; independence in India, Africa and Southeast Asia (Gandhi, Nkrumah, Ho Chi Minh); the Chinese Revolution; the Middle East after 1948; apartheid and its end; 1989 and the fall of the Soviet Union.",
       story="Berlin, November 9, 1989: a spokesman misreads a note and the wall opens"),
  dict(n=40, title="Globalization and Today", strand="1991–Present",
       topics="The internet and the global economy; the European Union; China's rise; terrorism and the wars after 2001; migration and refugees; climate change as a global question; human rights and international law; pandemics; inequality within and between nations; how to read the news of a connected world.",
       story="A container ship, a phone, and a T-shirt: three journeys around one world"),
 ]),
 dict(n=18, band="9-10", title="Human Geography", strand="Geography", chapters=[
  dict(n=41, title="Population and Culture", strand="Human Geography",
       topics="Population patterns, the demographic transition, aging and youth; migration theories and real cases; language families and diffusion; religion on the map; ethnicity, identity and conflict; culture and landscape; folk and popular culture; gender and development; reading census data and population pyramids.",
       story="Two population pyramids: Japan and Nigeria, side by side"),
  dict(n=42, title="Cities, Resources and the Environment", strand="Human Geography",
       topics="Urbanization and city models; agriculture from subsistence to agribusiness; industry and the global division of labor; development and its measures; energy, water and food security; environmental change, climate and sustainability; political geography: borders, states, nations, conflict; Chicago as a case study in every one of these.",
       story="Chicago from the top of the Willis Tower: where the rail lines and rivers go"),
 ]),
 dict(n=19, band="9-10", title="Civics: Rights, Power and Participation", strand="Civics", chapters=[
  dict(n=43, title="Foundations of American Democracy", strand="Government",
       topics="Enlightenment roots and colonial experience; the Declaration, the Articles, the Constitutional Convention and the compromises; the Federalist debates; the structure of the Constitution and the amendment process; federalism and its history; separation of powers and checks and balances in action; the Illinois Constitution compared.",
       story="Madison takes notes in the Convention, June 1787, and no one else does"),
  dict(n=44, title="Rights, Liberties and the Citizen's Tools", strand="Citizenship",
       topics="Civil liberties and civil rights: the difference; the First Amendment in cases; due process and equal protection; the incorporation of the Bill of Rights; landmark cases (Marbury, McCulloch, Brown, Gideon, Miranda, Tinker, Obergefell) in plain terms; elections, parties, interest groups and media; public opinion and polling; how to participate: registering, contacting officials, organizing, serving.",
       story="Clarence Earl Gideon writes to the Supreme Court in pencil from a Florida prison"),
 ]),

 # ══════════════════════════════ 11–12 ══════════════════════════════
 dict(n=20, band="11-12", title="U.S. History: Industry to the Progressive Era", strand="1865–1920", chapters=[
  dict(n=45, title="The Gilded Age", strand="1865–1900",
       topics="Reconstruction's end and Jim Crow; the transcontinental railroad, steel, oil and the corporation; Carnegie, Rockefeller and the trusts; immigration and the new city; Chicago's growth, the Haymarket affair and Pullman; labor unions and strikes; the Populists and farmers; the West, the Plains wars and the Dawes Act; the Chicago World's Fair of 1893.",
       story="The Pullman strike of 1894 and the town where the company owned everything"),
  dict(n=46, title="Progressives and Empire", strand="1890–1920",
       topics="Muckrakers and Progressive reforms: food safety, child labor, the settlement houses (Hull House), women's suffrage; Roosevelt, Taft and Wilson; conservation; the Spanish-American War, the Philippines, the Panama Canal; the Great Migration; World War I at home and abroad; the 1919 Chicago race riot; the Nineteenth Amendment.",
       story="Jane Addams opens Hull House on Halsted Street, 1889"),
 ]),
 dict(n=21, band="11-12", title="U.S. History: World Wars and the Cold War", strand="1920–1973", chapters=[
  dict(n=47, title="Boom, Bust and the New Deal", strand="1920–1941",
       topics="The 1920s: cars, radio, jazz, Prohibition, the Harlem Renaissance, nativism and the Klan's return; the Crash and the Great Depression; Hoover and Roosevelt; the New Deal programs and their critics; the Dust Bowl; labor's rise; the Supreme Court fight; the debate over government's role that has never ended.",
       story="A bank run in a small Illinois town, March 1933"),
  dict(n=48, title="World War II", strand="1939–1945",
       topics="Neutrality and Pearl Harbor; mobilizing the home front, women and war work; Japanese American incarceration; the war in Europe and the Pacific; D-Day; the Holocaust and America's response; the Manhattan Project (Chicago Pile-1) and Hiroshima; the war's end and the new world order; the GI Bill.",
       story="December 2, 1942: a squash court under Stagg Field and the first chain reaction"),
  dict(n=49, title="The Cold War at Home and Abroad", strand="1945–1973",
       topics="Containment, the Marshall Plan, NATO, Korea; McCarthyism; the suburbs, the baby boom, the interstate; the Cuban Missile Crisis; Kennedy, Johnson and the Great Society; Vietnam and the antiwar movement; the 1968 Democratic convention in Chicago; the space race; the counterculture.",
       story="Thirteen days in October 1962, hour by hour"),
 ]),
 dict(n=22, band="11-12", title="U.S. History: Civil Rights to Today", strand="1954–Present", chapters=[
  dict(n=50, title="The Movement", strand="1954–1968",
       topics="Brown v. Board, Emmett Till and Chicago, Montgomery, the sit-ins, the Freedom Rides, Birmingham, the March on Washington, Freedom Summer, Selma; the Civil Rights and Voting Rights Acts; King in Chicago, 1966; Malcolm X and Black Power; the movements that followed: women, Latino, Native, disability, LGBTQ rights; the strategies and the costs.",
       story="Mamie Till-Mobley insists on an open casket, Chicago, September 1955"),
  dict(n=51, title="From the 1970s to the Present", strand="1969–Present",
       topics="Watergate and trust in government; the energy crisis and stagflation; Reagan and the conservative turn; the end of the Cold War; the 1990s economy and the internet; September 11 and the wars that followed; the 2008 financial crisis; Obama, a president from Illinois; polarization, social media and the pandemic; how to read the recent past as history.",
       story="Election night 2008 in Grant Park"),
 ]),
 dict(n=23, band="11-12", title="Government and Economics", strand="Civics and Economics", chapters=[
  dict(n=52, title="The Three Branches in Practice", strand="Government",
       topics="How Congress actually works: committees, leadership, the filibuster, the budget; the presidency: powers, the executive branch, executive orders, war powers; the courts: judicial review, how cases reach the Supreme Court, interpretation debates; the bureaucracy; state and local government in Illinois; elections, campaign finance, gerrymandering, the Electoral College; civil discourse and how to evaluate a claim.",
       story="A federal budget deadline at midnight and what a shutdown actually stops"),
  dict(n=53, title="Markets, Money and Policy", strand="Economics",
       topics="Scarcity, incentives and opportunity cost; supply, demand and price; competition and market structure; market failures and the case for rules; GDP, inflation, unemployment and the business cycle; fiscal policy and the national debt; the Federal Reserve and monetary policy; trade and tariffs; personal finance: budgets, credit, saving, investing, insurance, the cost of college.",
       story="The price of eggs doubles, and every branch of economics has an explanation"),
 ]),
 dict(n=24, band="11-12", title="Capstone: Inquiry from the Sources", strand="Inquiry", chapters=[
  dict(n=54, title="How Historians Work", strand="Methods",
       topics="Asking a question worth asking; primary and secondary sources; sourcing, contextualizing, corroborating; bias, perspective and reliability; reading data and statistics as evidence; oral history; the ethics of research; a claim, evidence and reasoning; citation; how historians disagree and why interpretations change.",
       story="Two newspapers report the same Chicago strike and agree on almost nothing"),
  dict(n=55, title="An Inquiry of Your Own", strand="Project",
       topics="Choosing a local question (a street name, a school's history, a family migration, a law's effect); building a source set; interviews and archives; making the argument and answering the counterclaim; presenting to an audience; taking informed action: a letter, a proposal, a public comment; reflecting on what changed in your thinking.",
       story="A student asks why her street is named what it is, and finds a lawsuit"),
 ]),
]

# Every unit → the site's existing rooms that belong beside it (practice rooms).
LINKS = {
 1: [("/s7", "Me, my family, my class — cards, quiz and lab"), ("/s8", "Rules and fair choices — cards, quiz and lab")],
 2: [("/s11", "Needs, wants and work — cards, quiz and lab")],
 3: [("/s9", "Maps: where things are — cards, quiz and lab")],
 4: [("/s10", "Then and now — cards, quiz and lab"), ("/s12", "Symbols and stories of our country — cards, quiz and lab")],
 5: [("/s2", "Communities and Illinois — cards, quiz and lab")],
 6: [("/s3", "The first peoples — cards, quiz and lab")],
 7: [("/s4", "Explorers, colonies, a new nation — cards, quiz and lab")],
 8: [("/s1", "Government: local, state, national — cards, quiz and lab")],
 9: [("/s5", "Money, markets and choices — cards, quiz and lab"), ("/s6", "Maps and regions of the United States — cards, quiz and lab")],
 10: [("/s13", "The world before 1500 — cards, quiz and lab"), ("/us-history", "U.S. History, the whole course")],
 11: [("/s13", "The world before 1500 — cards, quiz and lab"), ("/religions", "World Religions")],
 12: [("/s13", "The world before 1500 — cards, quiz and lab"), ("/religions", "World Religions"), ("/us-history", "U.S. History, the whole course")],
 13: [("/s14", "The world's regions — cards, quiz and lab")],
 14: [("/b9", "The three branches"), ("/h9", "The Constitution"), ("/union", "A More Perfect Union, 1787–1865"), ("/h10", "The quiz room"), ("/us-history", "U.S. History, the whole course")],
 15: [("/s16", "Empires and exchange — cards, quiz and lab"), ("/religions#9-10", "World Religions: the traditions in their own words")],
 16: [("/s17", "Revolutions and the modern world — cards, quiz and lab")],
 17: [("/s17", "Revolutions and the modern world — cards, quiz and lab"), ("/s21", "The world wars and the Cold War — cards, quiz and lab")],
 18: [("/s18", "Human geography — cards, quiz and lab")],
 19: [("/s19", "Civics: rights, power, participation — cards, quiz and lab"), ("/h9", "The Constitution")],
 20: [("/s20", "Industry to the Progressive Era — cards, quiz and lab")],
 21: [("/s21", "The world wars and the Cold War — cards, quiz and lab")],
 22: [("/s22", "Civil rights to today — cards, quiz and lab")],
 23: [("/s23", "Government — cards, quiz and lab"), ("/s24", "Economics — cards, quiz and lab"), ("/economics", "Economics, every unit")],
 24: [("/s25", "Capstone: an inquiry from the sources — cards, quiz and lab"), ("/religions#11-12", "World Religions: comparison and inquiry")],
}
