# Reina-Valera 1909. Romans from Project Gutenberg's 1909 New Testament; the rest as the 1909 reads.
T={
"ps23_1":"Jehová es mi pastor; nada me faltará.",
"ps23_4":"Aunque ande en valle de sombra de muerte, No temeré mal alguno; porque tú estarás conmigo: Tu vara y tu cayado me infundirán aliento.",
"ps23_6":"Ciertamente el bien y la misericordia me seguirán todos los días de mi vida: Y en la casa de Jehová moraré por largos días.",
"ps46_1":"Dios es nuestro amparo y fortaleza, Nuestro pronto auxilio en las tribulaciones.",
"ps46_10":"Estad quietos, y conoced que yo soy Dios: Ensalzado he de ser entre las gentes, ensalzado seré en la tierra.",
"ps100_1":"Cantad alegres á Dios, habitantes de toda la tierra.",
"ps100_4":"Entrad por sus puertas con reconocimiento, Por sus atrios con alabanza: Alabadle, bendecid su nombre.",
"ps150_6":"Todo lo que respira alabe á JAH. Aleluya.",
"co13_1":"Si yo hablase lenguas humanas y angélicas, y no tengo caridad, vengo á ser como metal que resuena, ó címbalo que retiñe.",
"co13_4":"La caridad es sufrida, es benigna; la caridad no tiene envidia, la caridad no hace sinrazón, no se ensancha;",
"co13_5":"No es injuriosa, no busca lo suyo, no se irrita, no piensa el mal;",
"co13_6":"No se huelga de la injusticia, mas se huelga de la verdad;",
"co13_7":"Todo lo sufre, todo lo cree, todo lo espera, todo lo soporta.",
"co13_8":"La caridad nunca deja de ser: mas las profecías se han de acabar, y cesarán las lenguas, y la ciencia ha de ser quitada;",
"co13_12":"Ahora vemos por espejo, en obscuridad; mas entonces veremos cara á cara: ahora conozco en parte; mas entonces conoceré como soy conocido.",
"co13_13":"Y ahora permanecen la fe, la esperanza, y la caridad, estas tres: empero la mayor de ellas es la caridad.",
"jos1_9":"Mira que te mando que te esfuerces y seas valiente: no temas ni desmayes, porque Jehová tu Dios será contigo en donde quiera que fueres.",
"pr3_5":"Fíate de Jehová de todo tu corazón, Y no estribes en tu prudencia.",
"pr3_6":"Reconócelo en todos tus caminos, Y él enderezará tus veredas.",
"isa40_31":"Mas los que esperan á Jehová tendrán nuevas fuerzas; levantarán las alas como águilas, correrán, y no se cansarán, caminarán, y no se fatigarán.",
"jer29_11":"Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis.",
"rom8_28":"Y sabemos que á los que á Dios aman, todas las cosas les ayudan á bien, es á saber, á los que conforme al propósito son llamados.",
"rom8_38":"Por lo cual estoy cierto que ni la muerte, ni la vida, ni ángeles, ni principados, ni potestades, ni lo presente, ni lo por venir, Ni lo alto, ni lo bajo, ni ninguna criatura nos podrá apartar del amor de Dios, que es en Cristo Jesús Señor nuestro.",
"php4_13":"Todo lo puedo en Cristo que me fortalece.",
"heb11_1":"Es pues la fe la sustancia de las cosas que se esperan, la demostración de las cosas que no se ven.",
"heb11_6":"Empero sin fe es imposible agradar á Dios; porque es menester que el que á Dios se allega, crea que le hay, y que es galardonador de los que le buscan.",
"eph6_10":"Por lo demás, hermanos míos, confortaos en el Señor, y en la potencia de su fortaleza.",
"eph6_11":"Vestíos de toda la armadura de Dios, para que podáis estar firmes contra las asechanzas del diablo.",
"eph6_14":"Estad pues firmes, ceñidos vuestros lomos de verdad, y vestidos de la cota de justicia.",
"eph6_15":"Y calzados los pies con el apresto del evangelio de paz;",
"eph6_16":"Sobre todo, tomando el escudo de la fe, con que podáis apagar todos los dardos de fuego del maligno.",
"eph6_17":"Y tomad el yelmo de salud, y la espada del Espíritu; que es la palabra de Dios;",
"lk11_2":"Padre nuestro que estás en los cielos: sea tu nombre santificado. Venga tu reino. Sea hecha tu voluntad, como en el cielo, así también en la tierra. El pan nuestro de cada día, dánoslo hoy. Y perdónanos nuestros pecados, porque también nosotros perdonamos á todos los que nos deben. Y no nos metas en tentación, mas líbranos del mal.",
}
