# Science, K–12 — the course arc. Our own wording, following the Illinois
# Learning Standards for Science (NGSS) storyline band by band. Topics are
# guides for the writers; story = the chapter's opening narrative hook.
#
# Units number 1–27 straight through the course; chapters 1–60. `band` is the
# grade band the unit belongs to; `strand` is what the U.S. History course
# prints where a unit's years go. `level` sets the writing rules (SPEC.md).

BANDS = [
 dict(id="k-2",   title="Grades K–2",   level="k2"),
 dict(id="3-5",   title="Grades 3–5",   level="35"),
 dict(id="6-8",   title="Grades 6–8",   level="68"),
 dict(id="9-10",  title="Grades 9–10",  level="hs"),
 dict(id="11-12", title="Grades 11–12", level="hs2"),
]

UNITS = [
 # ══════════════════════════════ K–2 ══════════════════════════════
 dict(n=1, band="k-2", title="Pushes, Pulls and Stuff", strand="Physical Science", chapters=[
  dict(n=1, title="Pushes and Pulls", strand="Forces and Motion",
       topics="A push or a pull makes things start, stop, speed up, slow down, or change direction; bigger pushes make bigger changes; things that touch can push and pull; a ball rolling into another ball; ramps; stopping a moving thing; using a push to solve a problem (moving a heavy box).",
       story="The playground: who is pushing and who is pulling"),
  dict(n=2, title="What Things Are Made Of", strand="Matter",
       topics="Describing materials by color, hardness, texture, bendiness, and whether they soak up water; sorting objects by their properties; choosing the right material for a job (a raincoat, a window); solids keep their shape and liquids take the shape of their container; a big thing can be built from small pieces and taken apart; heating and cooling can change things — some changes go back (ice, butter) and some do not (a cooked egg, burnt toast).",
       story="Building a fort out of couch cushions, blocks and blankets"),
 ]),
 dict(n=2, band="k-2", title="Light, Sound and Waves", strand="Physical Science", chapters=[
  dict(n=3, title="Sound Is a Wiggle", strand="Waves",
       topics="Vibrating things make sound (a drum skin, a rubber band, your throat); sound can make things vibrate (rice on a drum); loud and soft, high and low; sound travels through air, water and solids; a string telephone; using sound to send a message (a bell, a whistle).",
       story="The drum bench: put your hand on the drum and feel it"),
  dict(n=4, title="Light and Seeing", strand="Waves",
       topics="You need light to see things; a dark room; light comes from the sun, fire, bulbs; some materials let light through, some let a little through, some block it and make shadows; mirrors bounce light; light can carry a signal (a flashlight blink, a lighthouse); the telescope collects light.",
       story="A shadow puppet show behind a bedsheet"),
 ]),
 dict(n=3, band="k-2", title="Living Things and Where They Live", strand="Life Science", chapters=[
  dict(n=5, title="What Plants and Animals Need", strand="Living Things",
       topics="Living and nonliving; plants need water, light and air to grow; animals need food, water, air and shelter; animals eat plants or other animals; plants and animals change their surroundings (a squirrel buries nuts, roots crack a sidewalk); people can change the land too and can take care of it.",
       story="A bean seed in a cup on the windowsill, day by day"),
  dict(n=6, title="Parents, Young and Habitats", strand="Living Things",
       topics="Young plants and animals look like their parents but not exactly; animals care for their young; body parts that help living things survive (beaks, claws, thorns, fur); many different kinds of living things live in different places (pond, prairie, forest, desert); a habitat gives what a living thing needs; pollinators and seeds that travel.",
       story="A trip to the Illinois prairie in June: who lives here?"),
 ]),
 dict(n=4, band="k-2", title="Earth, Sky and Weather", strand="Earth and Space Science", chapters=[
  dict(n=7, title="Weather and Seasons", strand="Weather",
       topics="Weather is what the air is like today: sunny, cloudy, rainy, snowy, windy, hot, cold; measuring and charting weather; the four seasons in Illinois and how daylight changes; some weather is dangerous and forecasts help people get ready (tornado drill, snow day); dressing for the weather.",
       story="The classroom weather chart, one month of stickers"),
  dict(n=8, title="Sun, Moon and Stars", strand="Space",
       topics="The sun rises and sets in a pattern; the sun warms the ground, water and air; shade keeps things cooler; the moon can be seen in the day or the night and its shape seems to change in a pattern; stars come out at night; the telescope shows the moon's craters.",
       story="One week of looking for the moon from the back porch"),
  dict(n=9, title="Land, Water and Change", strand="Earth's Surface",
       topics="Earth has land and water — hills, rivers, lakes, oceans; maps show where they are; most water is in the ocean and is salty; water can be liquid or ice; wind and water change the shape of the land, fast (a flood) or slow (a river bend); people build walls and plant grass to slow it down.",
       story="Rain on the playground: where does the water go?"),
 ]),

 # ══════════════════════════════ 3–5 ══════════════════════════════
 dict(n=5, band="3-5", title="Forces, Motion and Energy", strand="Physical Science", chapters=[
  dict(n=10, title="Forces and Motion", strand="Forces",
       topics="Forces have strength and direction; balanced forces and no change in motion, unbalanced forces and change; gravity pulls down; friction slows things; predicting motion from a pattern (a pendulum, a ball on a ramp); magnets push and pull without touching; static electricity; using forces to solve a problem (a magnetic latch).",
       story="Two tug-of-war teams and a rope that does not move"),
  dict(n=11, title="Energy on the Move", strand="Energy",
       topics="Faster means more energy; energy can be moved from place to place by sound, light, heat and electricity; collisions move energy from one object to another; energy stored in food, fuel and batteries; a circuit turns stored energy into light and motion; designing a device that changes energy from one form to another.",
       story="The marble run that took a whole Saturday"),
 ]),
 dict(n=6, band="3-5", title="Matter and Waves", strand="Physical Science", chapters=[
  dict(n=12, title="Particles Too Small to See", strand="Matter",
       topics="Matter is made of particles too small to see; a gas is still matter (a balloon has weight); weight stays the same when matter changes shape, melts, dissolves or is mixed — measuring to prove it; identifying materials by properties (color, hardness, conductivity, solubility, magnetism); mixing can make new substances (baking soda and vinegar) or not (salt and water).",
       story="The sugar that disappeared but did not go away"),
  dict(n=13, title="Waves, Light and Information", strand="Waves",
       topics="Waves have amplitude and wavelength; waves in water and a jump rope; waves make objects move; light reflects off objects into our eyes and that is how we see; light bends when it passes through water and lenses; patterns like Morse code, binary and drum signals carry information; the wave bench.",
       story="Sending a message across the gym with only a flashlight"),
 ]),
 dict(n=7, band="3-5", title="Life: Cycles, Traits and Survival", strand="Life Science", chapters=[
  dict(n=14, title="Life Cycles and Traits", strand="Living Things",
       topics="Life cycles are different but all have birth, growth, reproduction and death (frog, butterfly, bean, oak); traits are inherited from parents and can also be changed by the environment (a plant in shade, a well-fed dog); variation among siblings; some traits give an advantage in finding mates or food.",
       story="The monarchs that hatched in Room 12"),
  dict(n=15, title="Structures, Senses and Survival", strand="Living Things",
       topics="Plants and animals have internal and external structures for survival, growth and reproduction (roots, stems, thorns, heart, lungs, skin); the eye and how light lets animals see; senses send information to the brain and the brain responds; living in groups helps some animals survive; when the environment changes, some survive, some move, some die; fossils tell what lived long ago.",
       story="The fossil in the Mazon Creek rock"),
 ]),
 dict(n=8, band="3-5", title="Ecosystems and the Flow of Energy", strand="Life Science", chapters=[
  dict(n=16, title="Where Plants Get Their Food", strand="Energy in Living Things",
       topics="Plants get the materials for growth mostly from air and water, not from the soil (van Helmont's tree); the sun's energy is stored in plants; animals get energy from the food they eat; food moves through the body to give energy, growth and repair; a healthy plate.",
       story="A tree that grew 160 pounds in a pot of soil that lost two ounces"),
  dict(n=17, title="Food Webs and the Cycle of Matter", strand="Ecosystems",
       topics="Producers, consumers and decomposers; food chains and food webs in a pond, a prairie and a forest; matter cycles among plants, animals, decomposers, air, water and soil; what happens when one link is removed; a healthy ecosystem and one that is out of balance; people protecting a habitat.",
       story="What the owl pellet was hiding"),
 ]),
 dict(n=9, band="3-5", title="Earth, Weather and Space", strand="Earth and Space Science", chapters=[
  dict(n=18, title="Weather and Climate", strand="Weather",
       topics="Weather is measured (temperature, precipitation, wind) and patterns are seen across seasons; climate is the usual weather over many years and differs around the world; weather hazards (tornadoes, floods, blizzards) and how design reduces harm; forecasting.",
       story="The night the tornado sirens went off"),
  dict(n=19, title="Earth's Changing Surface", strand="Earth's Surface",
       topics="Rock layers and fossils show change over time; weathering breaks rock, erosion moves it, deposition drops it (water, ice, wind, plants); rates of change — fast and slow; maps of mountains, earthquakes and volcanoes show patterns; Illinois glaciers shaped the flat land; protecting people from earthquakes and floods.",
       story="Why Illinois is so flat: the ice that was a mile thick"),
  dict(n=20, title="Earth in Space", strand="Space",
       topics="The sun is a star that looks big because it is close; stars differ in brightness because of distance; Earth's rotation makes day and night and the sun's daily path; Earth's orbit and tilt make the seasons and change the stars we see; the moon's phases; shadows through a day; gravity pulls everything toward Earth's center.",
       story="The shadow stick on the blacktop, marked every hour"),
  dict(n=21, title="Earth's Systems and People", strand="Earth's Systems",
       topics="Earth's four systems — geosphere, hydrosphere, atmosphere, biosphere — and how they interact; where Earth's water is (oceans, ice, groundwater, lakes) in a graph; how people use resources and change the environment; conservation, recycling and protecting Earth's resources; Chicago's river that runs backward.",
       story="The river Chicago turned around"),
 ]),

 # ══════════════════════════════ 6–8 ══════════════════════════════
 dict(n=10, band="6-8", title="Matter and Its Interactions", strand="Physical Science", chapters=[
  dict(n=22, title="Atoms, Molecules and States of Matter", strand="Matter",
       topics="Substances are made of atoms; molecules and extended structures; models of pure substances; states of matter as particle motion; temperature and thermal energy; changes of state add or remove energy; density; the periodic table introduced; the microscope's limits and the atom's size.",
       story="Robert Brown's dancing pollen grains under the microscope"),
  dict(n=23, title="Chemical Reactions and Energy", strand="Chemistry",
       topics="Physical vs chemical change; evidence of a reaction; atoms rearrange and mass is conserved; synthesis, decomposition, combustion in everyday life; reactions that release or absorb thermal energy; designing a hand warmer or cold pack; safety in the lab.",
       story="The Chicago fire of 1871 and what fire actually is"),
 ]),
 dict(n=11, band="6-8", title="Forces, Motion and Energy", strand="Physical Science", chapters=[
  dict(n=24, title="Forces and Newton's Laws", strand="Forces",
       topics="Newton's three laws in plain language; net force, mass and acceleration; collisions and designing to reduce harm (helmets, crumple zones); gravity depends on mass and distance; electric and magnetic forces act at a distance and fields; planning a fair test of a force.",
       story="The egg drop and the physics of a soft landing"),
  dict(n=25, title="Energy: Kinetic, Potential and Heat", strand="Energy",
       topics="Kinetic energy grows with mass and with speed squared; potential energy in height, springs and fields; energy transfer and conservation in a roller coaster; thermal energy, temperature and heat; conduction, convection, radiation; designing a device to keep a drink cold or hot; energy in food and fuel.",
       story="The roller coaster at Six Flags Great America and the first hill"),
 ]),
 dict(n=12, band="6-8", title="Waves and Information", strand="Physical Science", chapters=[
  dict(n=26, title="Waves, Sound and Light", strand="Waves",
       topics="Amplitude, wavelength, frequency and energy; mechanical waves need a medium, light does not; sound speed in air, water and steel; the ear; reflection, refraction, absorption and transmission of light; the eye and lenses; the wave bench and the drum bench as instruments.",
       story="The turntable: a groove is a wave you can see"),
  dict(n=27, title="Light, Lenses and Signals", strand="Waves and Technology",
       topics="How a microscope and a telescope use lenses and mirrors; the electromagnetic spectrum; why digital signals resist noise better than analog; how a phone sends a picture; fiber optics; sonar and radar; the history of the telescope from Galileo to Webb.",
       story="Galileo points a spyglass at Jupiter, January 1610"),
 ]),
 dict(n=13, band="6-8", title="Cells, Bodies and Reproduction", strand="Life Science", chapters=[
  dict(n=28, title="Cells and Body Systems", strand="Living Things",
       topics="All living things are made of cells; unicellular and multicellular life; cell parts and their jobs (nucleus, membrane, mitochondria, chloroplast, cell wall); cells to tissues to organs to systems; how body systems work together (digestive, circulatory, respiratory, nervous, muscular, skeletal); the microscope and Hooke's cork.",
       story="Hooke's cork, Leeuwenhoek's 'animalcules' and the first look inside life"),
  dict(n=29, title="Growth, Reproduction and Behavior", strand="Living Things",
       topics="Photosynthesis and cellular respiration as the flow of matter and energy; sensory receptors, nerves and the brain; memories and behavior; animal behaviors and plant structures that help reproduction (courtship, seed dispersal, flowers and pollinators); environmental and genetic factors in growth.",
       story="The bee, the flower and a deal millions of years old"),
 ]),
 dict(n=14, band="6-8", title="Ecosystems and Heredity", strand="Life Science", chapters=[
  dict(n=30, title="Ecosystems and Populations", strand="Ecosystems",
       topics="Resource availability limits populations; competition, predation and mutualism; energy flow and matter cycling through food webs; photosynthesis and decomposers; biodiversity and ecosystem services; disruptions (invasive carp in Illinois rivers, drought, wildfire) and resilience; designing a solution to protect an ecosystem.",
       story="The carp that jumped into the boat: an invader in the Illinois River"),
  dict(n=31, title="Heredity and Genes", strand="Heredity",
       topics="Chromosomes, genes and proteins; sexual and asexual reproduction and variation; Punnett squares and probability; mutations — harmful, helpful, neutral; selective breeding and genetic engineering; the Human Genome Project; Gregor Mendel's peas.",
       story="Mendel's garden: 28,000 pea plants and a pattern"),
 ]),
 dict(n=15, band="6-8", title="Earth and Space Systems", strand="Earth and Space Science", chapters=[
  dict(n=33, title="Earth's Systems: Rock, Water and Weather", strand="Earth's Systems",
       topics="The rock cycle; plate tectonics and the map of earthquakes and volcanoes; the water cycle driven by the sun and gravity; weather from air masses, fronts and the ocean; regional climate; forecasting hazards; Illinois's New Madrid fault zone.",
       story="The winter the Mississippi ran backward: New Madrid, 1811"),
  dict(n=34, title="Space Systems and Earth's History", strand="Space",
       topics="The Earth–sun–moon system: seasons, phases, eclipses; gravity and orbits in the solar system; scale of the solar system and the galaxy; the geologic time scale and how rock layers and fossils date Earth's history; the telescope as a time machine.",
       story="The 2024 eclipse over Carbondale, Illinois"),
  dict(n=35, title="Earth and Human Activity", strand="Earth and People",
       topics="Uneven distribution of resources (minerals, fresh water, energy); natural hazards and forecasting; human impact on land, water and air; population growth and consumption; the greenhouse effect and the evidence for a warming climate; designing to reduce impact; monitoring.",
       story="Lake Michigan: the water that six million people drink"),
 ]),

 # ══════════════════════════════ 9–10 ══════════════════════════════
 dict(n=16, band="9-10", title="Biology: Cells and Energy", strand="Life Science", chapters=[
  dict(n=36, title="The Chemistry of Life and the Cell", strand="Cells",
       topics="Water, carbon and the macromolecules (carbohydrates, lipids, proteins, nucleic acids); enzymes; cell theory; prokaryotes and eukaryotes; organelles and specialization; the membrane, diffusion, osmosis and active transport; homeostasis and feedback; the microscope's stains and magnifications.",
       story="Why a cell is small: surface, volume and a limit on size"),
  dict(n=37, title="Photosynthesis, Respiration and Growth", strand="Energy in Life",
       topics="Photosynthesis inputs and outputs; cellular respiration and ATP; fermentation; the carbon cycle at the cell scale; cell division — mitosis and the cell cycle; cancer as division gone wrong; stem cells and differentiation; body systems as interacting parts.",
       story="Priestley's mouse, the sprig of mint and the air that came back"),
 ]),
 dict(n=17, band="9-10", title="Biology: Genetics and Inheritance", strand="Life Science", chapters=[
  dict(n=38, title="DNA, Genes and Inheritance", strand="Genetics",
       topics="DNA structure and replication; transcription, translation and proteins; mutations; meiosis and genetic variation; Mendelian and non-Mendelian inheritance (incomplete dominance, codominance, sex-linked traits); pedigrees; biotechnology, genome sequencing and CRISPR with their ethics; Rosalind Franklin's Photo 51.",
       story="Photo 51: the picture that showed the shape of DNA"),
 ]),
 dict(n=18, band="9-10", title="Biology: Ecosystems and Human Impact", strand="Life Science", chapters=[
  dict(n=40, title="Ecosystems, Energy and Cycles", strand="Ecology",
       topics="Carrying capacity and limiting factors; population growth curves; energy pyramids and the ten percent rule; carbon, nitrogen and water cycles; interactions — competition, predation, symbiosis; succession after a disturbance; keystone species; the prairie and the fire that keeps it.",
       story="Yellowstone's wolves and the rivers that changed"),
  dict(n=41, title="Biodiversity and Human Impact", strand="Ecology and People",
       topics="Biodiversity and why it matters; habitat loss, invasive species, pollution, overharvesting, climate change; group behavior and survival; conservation biology and restoration; designing and evaluating solutions; the Illinois prairie restoration at Nachusa Grasslands.",
       story="The bison that came back to Nachusa"),
 ]),
 dict(n=19, band="9-10", title="Physical Science: Matter and Reactions", strand="Physical Science", chapters=[
  dict(n=42, title="Atoms, the Periodic Table and Bonding", strand="Chemistry",
       topics="Atomic structure — protons, neutrons, electrons; isotopes; electron arrangement and valence; the periodic table's patterns (reactivity, atomic radius, ionization energy); ionic, covalent and metallic bonds; naming compounds; properties from structure (why salt dissolves, why diamond is hard).",
       story="Mendeleev's gaps: the elements he predicted before anyone found them"),
  dict(n=43, title="Reactions, Energy and the Nucleus", strand="Chemistry",
       topics="Balancing equations and conservation of mass; reaction types; reaction rates and collisions; energy in bonds — exothermic and endothermic; equilibrium in plain terms; nuclear processes — fission, fusion, radioactive decay and half-life; carbon dating; nuclear power's benefits and risks.",
       story="Chicago Pile-1: the first chain reaction, under a football stadium"),
 ]),
 dict(n=20, band="9-10", title="Physical Science: Forces, Energy and Waves", strand="Physical Science", chapters=[
  dict(n=44, title="Motion, Forces and Momentum", strand="Physics",
       topics="Describing motion with graphs; Newton's second law with numbers; momentum and its conservation in collisions; designing for safety; gravitational and electrostatic force laws; fields; orbits and satellites.",
       story="The crash test: what a dummy teaches"),
  dict(n=45, title="Energy, Fields and Waves", strand="Physics",
       topics="Kinetic, potential and thermal energy with numbers; conservation of energy and the idea of a system; heat flow and the second law in plain terms; energy resources; wave properties and the wave equation; electromagnetic radiation, photons and the spectrum; how waves carry information; the wave bench.",
       story="Faraday's magnet and coil: electricity from motion"),
 ]),
 dict(n=21, band="9-10", title="Earth and Space", strand="Earth and Space Science", chapters=[
  dict(n=46, title="The Universe and Earth's Place in It", strand="Space",
       topics="The sun's fusion and its life cycle; the Big Bang evidence (redshift, cosmic background); spectra and what starlight tells us; the solar system's formation; Kepler's laws in plain terms; dating Earth with radioactive decay; the telescope's history.",
       story="Edwin Hubble and the galaxy that was not a nebula"),
  dict(n=47, title="Earth's Systems and Climate", strand="Earth's Systems",
       topics="Plate tectonics and the evidence; Earth's interior and convection; the rock and water cycles at scale; feedbacks among systems; the carbon cycle and the greenhouse effect; climate history in ice cores; models and projections; the Great Lakes' formation.",
       story="Alfred Wegener's fit of the continents that no one believed"),
  dict(n=48, title="Human Sustainability", strand="Earth and People",
       topics="Natural resources and their limits; natural hazards and risk; human impacts on Earth's systems; evaluating solutions with cost, benefit and constraint; climate change mitigation and adaptation; agriculture, water and energy in Illinois.",
       story="The Dust Bowl and the soil that blew to Washington"),
 ]),

 # ══════════════════════════════ 11–12 ══════════════════════════════
 dict(n=22, band="11-12", title="Chemistry: Atoms, Bonding and Reactions", strand="Chemistry", chapters=[
  dict(n=49, title="Atomic Structure, Periodicity and Bonding", strand="Chemistry",
       topics="Quantum model of the atom in plain terms — orbitals, electron configurations; periodic trends explained; ionic, covalent, metallic and intermolecular forces; Lewis structures, VSEPR and molecular shape; polarity and properties; spectroscopy as evidence.",
       story="The flame test: colors that gave away the elements"),
  dict(n=50, title="Reactions, Kinetics and Equilibrium", strand="Chemistry",
       topics="Reaction types and redox; rates, collision theory, catalysts and activation energy; reaction mechanisms; dynamic equilibrium and Le Châtelier's principle; the Haber process and why it feeds the world; electrochemistry — batteries and corrosion.",
       story="Fritz Haber, ammonia and the bread from the air"),
 ]),
 dict(n=23, band="11-12", title="Chemistry: Stoichiometry, Solutions and Energy", strand="Chemistry", chapters=[
  dict(n=51, title="Moles, Stoichiometry and Gases", strand="Chemistry",
       topics="The mole and Avogadro's number; molar mass; balancing and using ratios; limiting reactants and percent yield; the gas laws and the ideal gas law; kinetic-molecular theory; real gases; airbags and the chemistry of a fast reaction.",
       story="An airbag inflates in 30 milliseconds: the stoichiometry of a crash"),
  dict(n=52, title="Solutions, Acids, Bases and Thermochemistry", strand="Chemistry",
       topics="Solubility and concentration (molarity); colligative properties; acids and bases, pH and buffers; titration; enthalpy, calorimetry and Hess's law; entropy and free energy in plain terms; ocean acidification as applied chemistry.",
       story="The lake that turned acid: Lake Michigan's neighbors and acid rain"),
 ]),
 dict(n=24, band="11-12", title="Physics: Motion and Forces", strand="Physics", chapters=[
  dict(n=53, title="Kinematics and Dynamics", strand="Physics",
       topics="Vectors; position, velocity and acceleration graphs; equations of motion; projectiles; Newton's laws with free-body diagrams; friction and inclines; circular motion; the physics of a car crash and a seat belt.",
       story="Galileo's inclined plane: slowing gravity down to measure it"),
  dict(n=54, title="Momentum, Gravitation and Rotation", strand="Physics",
       topics="Impulse and momentum; elastic and inelastic collisions in two dimensions; center of mass; torque and rotational equilibrium; angular momentum; universal gravitation and orbital mechanics; Kepler's laws; satellites and the ISS.",
       story="Apollo 13: the physics that brought a broken ship home"),
 ]),
 dict(n=25, band="11-12", title="Physics: Energy, Waves and Electricity", strand="Physics", chapters=[
  dict(n=55, title="Energy and Thermodynamics", strand="Physics",
       topics="Work, energy and power; conservation and energy diagrams; springs and oscillation; heat, temperature and specific heat; the laws of thermodynamics; engines and efficiency; entropy and the arrow of time; power plants and the grid.",
       story="Joule's paddle wheel: heat measured by a falling weight"),
  dict(n=56, title="Waves, Light, Electricity and Magnetism", strand="Physics",
       topics="Wave interference, standing waves and resonance; the Doppler effect; reflection, refraction, lenses and mirrors with ray diagrams; diffraction and the wave–particle debate; electric charge, fields and potential; circuits — Ohm's law, series and parallel; magnetism and induction; the turntable's cartridge as a generator.",
       story="Young's double slit: light that adds up to darkness"),
 ]),
 dict(n=26, band="11-12", title="Environmental Science", strand="Earth and Environmental Science", chapters=[
  dict(n=57, title="Earth's Systems, Ecosystems and Resources", strand="Environmental Science",
       topics="Systems thinking and feedback; biomes and biodiversity; energy and matter cycles; soil, water and mineral resources; agriculture and food systems; fossil fuels and renewable energy compared; water use and the Ogallala aquifer; Illinois farmland and the Mississippi's dead zone.",
       story="The dead zone at the mouth of the Mississippi"),
  dict(n=58, title="Pollution, Climate and Sustainability", strand="Environmental Science",
       topics="Air and water pollution and their regulation (Clean Air and Clean Water Acts); the ozone story as a solved problem; climate science — evidence, models, impacts; mitigation, adaptation and carbon accounting; environmental justice; policy tools, cost–benefit and trade-offs; designing a sustainable community.",
       story="The hole in the sky that the world agreed to fix"),
 ]),
 dict(n=27, band="11-12", title="Capstone: Argue From Evidence", strand="Science Practices", chapters=[
  dict(n=59, title="Reading and Judging Evidence", strand="Science Practices",
       topics="Claims, evidence and reasoning; correlation vs causation; sample size, bias and control groups; reading graphs honestly; error, uncertainty and significant figures; peer review and replication; evaluating a news story about science; case studies — vaccines and autism, the ozone layer, smoking and cancer.",
       story="John Snow's map and the pump handle"),
  dict(n=60, title="Designing and Making the Case", strand="Science Practices",
       topics="Asking a testable question; designing an investigation with variables and controls; collecting and analyzing data; models and their limits; engineering design cycle with criteria and constraints; writing a scientific explanation; presenting and defending a claim; a capstone project plan.",
       story="Barbara McClintock and the jumping genes nobody believed"),
 ]),
 # ═════════════ 6–8, added 2026-09-27: the music benches' own unit ═════════════
 # Numbered 28 because 1–27 were taken; it sits in the 6–8 band beside Unit 12
 # (Waves and Information), where sound and waves already live.
 dict(n=28, band="6-8", title="Sound, Rhythm and Recorded Music", strand="Physical Science", chapters=[
  dict(n=61, title="What Sound Is", strand="Sound Waves",
       topics="Vibration; sound as a chain of pushes through a medium; no sound in a vacuum; frequency and pitch; amplitude and loudness; wavelength and the speed of sound; the ear; the range of hearing; decibels and hearing safety; seeing sound on the oscilloscope.",
       story="A block party where the bass shakes a soda can"),
  dict(n=62, title="Rhythm and Time", strand="Patterns in Time",
       topics="A beat as a repeating event; tempo in beats per minute; measuring tempo; bars and counting; a bar cut into 16 steps; kick, snare and hi-hat patterns; swing; why a steady pulse helps us move and focus; rhythms in nature; when a fast rhythm becomes a pitch.",
       story="Chicago house music and a steady kick drum"),
  dict(n=63, title="Recording and Playing Back", strand="Storing Sound",
       topics="The phonautograph and the phonograph; a record groove as a wave; turntable speed and pitch; scratching; pitch control and blending records; sampling rate; bit depth; the 1987 12-bit 26.04 kHz sampler; analog and digital.",
       story="Edison shouts a nursery rhyme into a tinfoil cylinder, 1877"),
  dict(n=64, title="Making It Your Own", strand="Design and Test",
       topics="Designing a beat for a purpose; building in layers; changing one variable at a time; reading a waveform; kick and hi-hat on the oscilloscope; timing a beat with numbers; protecting hearing; giving credit for samples; explaining a design with claim, evidence and reasoning.",
       story="A first beat, built and then measured"),
 ]),
]

# Rooms already on the site that belong to each unit — nothing gets deleted.
LINKS = {
 1: [("/b26", "Pushes and pulls — cards, quiz and lab"), ("/b31", "Materials and how they change — cards, quiz and lab")],
 2: [("/b30", "Light and sound — cards, quiz and lab"), ("/drum-machine", "The drum bench"), ("/waves", "The wave bench"), ("/telescope", "The telescope")],
 3: [("/b28", "What living things need — cards, quiz and lab"), ("/microscope", "The microscope")],
 4: [("/b29", "Weather and seasons — cards, quiz and lab"), ("/b27", "Sun, moon and sky — cards, quiz and lab"), ("/telescope", "The telescope")],
 5: [("/b18", "Forces and motion — cards, quiz and lab"), ("/b21", "Energy — cards, quiz and lab")],
 6: [("/b23", "Matter — cards, quiz and lab"), ("/waves", "The wave bench"), ("/decks", "The turntables")],
 7: [("/b19", "Life cycles and traits — cards, quiz and lab"), ("/microscope", "The microscope")],
 8: [("/b24", "Ecosystems and food webs — cards, quiz and lab")],
 9: [("/b20", "Weather and climate — cards, quiz and lab"), ("/b22", "Earth's changing surface — cards, quiz and lab"), ("/b25", "Earth in space — cards, quiz and lab"), ("/telescope", "The telescope")],
 10: [("/b14", "Matter and its interactions — cards, quiz and lab"), ("/microscope", "The microscope")],
 11: [("/b15", "Forces, energy and waves — cards, quiz and lab")],
 12: [("/b15", "Forces, energy and waves — cards, quiz and lab"), ("/waves", "The wave bench"), ("/drum-machine", "The drum bench"), ("/decks", "The turntables"), ("/telescope", "The telescope")],
 13: [("/b2", "The cell system — cards, quiz and lab"), ("/b3", "Body systems — cards, quiz and lab"), ("/b4", "Reproduction — cards, quiz and lab"), ("/microscope", "The microscope")],
 14: [("/b1", "Living things in the biosphere"), ("/b5", "Ecosystems"), ("/b6", "Populations"), ("/b7", "Heredity"), ("/vocab", "Science words, five ways")],
 15: [("/b16", "Earth's systems — cards, quiz and lab"), ("/b17", "Space systems — cards, quiz and lab"), ("/telescope", "The telescope")],
 16: [("/b32", "Biology: cells and energy — cards, quiz and lab"), ("/microscope", "The microscope")],
 17: [("/vocab", "Science words, five ways")],
 18: [("/b34", "Biology: ecosystems and human impact — cards, quiz and lab")],
 19: [("/b35", "Physical science: matter and reactions — cards, quiz and lab")],
 20: [("/b36", "Physical science: forces, energy, waves — cards, quiz and lab"), ("/waves", "The wave bench"), ("/decks", "The turntables")],
 21: [("/b37", "Earth and space — cards, quiz and lab"), ("/telescope", "The telescope")],
 22: [("/b38", "Chemistry: atoms, bonding, reactions — cards, quiz and lab")],
 23: [("/b39", "Chemistry: stoichiometry and solutions — cards, quiz and lab")],
 24: [("/b40", "Physics: motion and forces — cards, quiz and lab")],
 25: [("/b41", "Physics: energy, waves, electricity — cards, quiz and lab"), ("/waves", "The wave bench"), ("/decks", "The turntables"), ("/drum-machine", "The drum bench")],
 26: [("/b42", "Environmental science — cards, quiz and lab")],
 28: [("/drum-machine", "The Drum Machine"), ("/decks", "The turntables"), ("/waves", "The oscilloscope"), ("/b15", "Forces, energy and waves — cards, quiz and lab")],
 27: [("/b43", "Capstone: argue from evidence — cards, quiz and lab"), ("/microscope", "The microscope"), ("/telescope", "The telescope")],
}
