# Buddhist Texts — Daily Drafts banks. Studied, never preached: "Buddhists teach…", "The Dhammapada says…".
# Exact quotations only from U.S.-public-domain translations (Müller's Dhammapada 1881, Rhys Davids); otherwise paraphrase.
def mc(q, a, w): return ["mc", q, a, w]
def tf(q, v): return ["tf", q, v]
def voc(w, d): return ["voc", w, d]
def op(q, m): return ["open", q, m]

BANDS = {}

BANDS['k2'] = [
("Prince Siddhartha", "El príncipe Siddhartha", [
 mc("Before he was called the Buddha, his name was…", "Siddhartha", ["Rama", "Confucius", "Arjuna"]),
 mc("Siddhartha grew up as a…", "prince in a palace", ["farmer in a field", "fisher at sea", "king of monkeys"]),
 mc("Siddhartha’s father wanted to keep him…", "inside the palace, away from sad things", ["on a boat", "in the forest", "in a school far away"]),
 mc("Siddhartha was born long ago in what is now…", "Nepal", ["Brazil", "Egypt", "Japan"]),
 mc("Siddhartha’s mother was Queen…", "Maya", ["Sita", "Mary", "Draupadi"]),
 mc("One day Siddhartha left the palace to…", "find out why people suffer", ["buy a horse", "go fishing", "build a castle"]),
 tf("Siddhartha was born a prince.", True),
 tf("Siddhartha stayed in the palace his whole life.", False),
 voc("palace", "A very large, fancy home for a king or queen."),
 op("Siddhartha wanted to understand why people feel sad. What helps you when you feel sad?", "Any honest answer, such as talking to someone, a hug, or quiet time."),
]),
("Under the Bodhi Tree", "Bajo el árbol Bodhi", [
 mc("Siddhartha sat under a tree to…", "think very deeply (meditate)", ["take a nap", "eat fruit", "hide"]),
 mc("The tree is called the…", "Bodhi tree", ["apple tree", "palm tree", "pine tree"]),
 mc("Buddhists say that under the tree Siddhartha became the…", "Buddha", ["king", "giant", "monkey"]),
 mc("“Buddha” means…", "“the awakened one”", ["“the sleepy one”", "“the rich one”", "“the tall one”"]),
 mc("Sitting quietly and paying close attention is called…", "meditation", ["shouting", "running", "painting"]),
 mc("The Bodhi tree is a kind of…", "fig tree", ["oak tree", "cactus", "banana plant"]),
 tf("Buddhists say the Buddha woke up to the truth under a tree.", True),
 tf("“Buddha” means “the sleepy one.”", False),
 voc("meditate", "To sit still and quietly pay attention."),
 op("Sit still and take three slow breaths. How did your body feel?", "Any honest noticing, such as calm, wiggly or relaxed."),
]),
("The Buddha as Teacher", "El Buda como maestro", [
 mc("After he woke up, the Buddha spent his life…", "teaching others", ["ruling a kingdom", "sailing", "sleeping"]),
 mc("The Buddha’s first students were…", "five friends", ["his horses", "kings", "birds"]),
 mc("The Buddha taught by walking from town to town and…", "talking with people", ["writing letters", "sending pictures", "singing on TV"]),
 mc("The Buddha’s teaching is called the…", "Dharma", ["Veda", "Torah", "Dao"]),
 mc("The Buddha taught that everyone can learn to be…", "kind and wise", ["rich", "famous", "strong"]),
 mc("The Buddha taught for about…", "45 years", ["1 day", "3 weeks", "500 years"]),
 tf("The Buddha taught many people.", True),
 tf("The Buddha only taught kings.", False),
 voc("teacher", "A person who helps others learn."),
 op("Who is a teacher who helps you? What did they teach you?", "Any person and any lesson."),
]),
("The Monkey King", "El rey mono", [
 mc("The Jataka tales are stories of the Buddha’s…", "past lives", ["favorite foods", "trips to the moon", "school days"]),
 mc("In one Jataka tale, the Buddha is a monkey king who…", "makes a bridge with his own body", ["steals mangoes", "fights a lion", "runs away"]),
 mc("The monkey king helps his monkeys…", "escape across a river", ["find candy", "build a boat", "hide in a cave"]),
 mc("The human king who saw this learned that a good leader…", "cares for others first", ["takes everything", "is always loud", "never helps"]),
 mc("The monkeys lived in a big…", "mango tree", ["castle", "boat", "desert"]),
 mc("The monkey king was…", "brave and caring", ["lazy", "selfish", "mean"]),
 tf("In the Jataka tales, animals can teach lessons.", True),
 tf("The monkey king leaves his monkeys behind.", False),
 voc("leader", "A person who guides a group."),
 op("How can you be a good leader for your class or team?", "Help others, listen, share, go first on hard jobs, or any caring answer."),
]),
("The Hare in the Moon", "El conejo en la luna", [
 mc("In a Jataka tale, a hare has nothing to give a hungry traveler, so it offers…", "itself", ["a carrot", "a coin", "a flower"]),
 mc("The hungry traveler was really…", "a god testing the hare", ["a hunter", "a monkey", "a king"]),
 mc("To honor the hare, its picture was placed on the…", "moon", ["sun", "sea", "mountain"]),
 mc("The hare shows the good quality of…", "giving", ["taking", "hiding", "sleeping"]),
 mc("The hare’s friends were a monkey, a jackal and an…", "otter", ["elephant", "eagle", "owl"]),
 mc("Many people in Asia look at the moon and see a…", "rabbit", ["dog", "car", "boat"]),
 tf("The hare wanted to help someone hungry.", True),
 tf("The hare was selfish.", False),
 voc("generous", "Happy to give and share."),
 op("What is something you could give to help someone else?", "Time, help, a snack, a kind word, or any giving answer."),
]),
("Kind to All Living Things", "Bondad con todo ser vivo", [
 mc("Buddhists try not to…", "harm living things", ["read", "sing", "play"]),
 mc("A wish that all beings be happy is called…", "loving-kindness", ["bad luck", "a riddle", "a race"]),
 mc("Which is a kind thing to do for a bug?", "carry it outside gently", ["step on it", "trap it in a jar forever", "shout at it"]),
 mc("A Buddhist wish is: “May all beings be…”", "happy and safe", ["sad", "lost", "angry"]),
 mc("Kindness can be for…", "everyone, even people we do not know", ["only best friends", "only family", "no one"]),
 mc("When someone is sad, kindness means…", "caring and helping", ["laughing at them", "ignoring them", "taking their things"]),
 tf("Buddhists teach kindness to animals.", True),
 tf("Buddhists say kindness is only for friends.", False),
 voc("kindness", "Being friendly, caring and helpful."),
 op("Finish the wish: “May all beings be…” Then say one thing you wish for everyone.", "Happy, safe, healthy, peaceful; any kind wish."),
]),
("Calm Breathing", "Respiración tranquila", [
 mc("Buddhist monks and nuns often practice by paying attention to their…", "breath", ["shoes", "phone", "lunch"]),
 mc("Breathing slowly can help you feel…", "calm", ["angry", "cold", "hungry"]),
 mc("Paying attention to what is happening right now is called…", "mindfulness", ["forgetting", "shouting", "guessing"]),
 mc("When you meditate, you often sit…", "still and quiet", ["upside down", "running", "on a swing"]),
 mc("If your mind wanders while meditating, you can…", "gently bring it back", ["give up forever", "yell", "run away"]),
 mc("Buddhists also practice walking…", "slowly and carefully, noticing each step", ["as fast as they can", "backward only", "with eyes closed on a road"]),
 tf("Calm breathing is part of Buddhist practice.", True),
 tf("You must be perfect to meditate.", False),
 voc("mindful", "Paying close attention to right now."),
 op("Name a time when calm breathing could help you.", "Before a test, when upset, before bed, or any honest answer."),
]),
("Telling the Truth", "Decir la verdad", [
 mc("The Buddha taught that we should speak words that are…", "true and kind", ["mean", "false", "loud"]),
 mc("One Buddhist promise is not to…", "tell lies", ["read books", "smile", "sing"]),
 mc("In a story, the Buddha’s son Rahula learned about lying from a…", "cup of water", ["tree", "horse", "drum"]),
 mc("The Buddha’s son was named…", "Rahula", ["Rama", "Hanuman", "Arjuna"]),
 mc("If you break something by accident, the honest thing is to…", "tell the truth", ["hide it", "blame a friend", "run away"]),
 mc("Kind words make others feel…", "good", ["scared", "sad", "left out"]),
 tf("Buddhists teach that honest words matter.", True),
 tf("The Buddha said lying is fine.", False),
 voc("honest", "Telling the truth."),
 op("Why is it important to tell the truth?", "People can trust you; it keeps friendships strong; any sound reason."),
]),
("Sharing", "Compartir", [
 mc("Buddhist monks and nuns receive food from…", "people who share with them", ["a store", "a robot", "a farm they own"]),
 mc("Giving is called “dana.” Dana means…", "generosity", ["anger", "sleep", "winning"]),
 mc("Buddhist monks and nuns carry a…", "bowl for food", ["phone", "sword", "suitcase"]),
 mc("People who give food to monks often feel…", "happy to share", ["angry", "cheated", "bored"]),
 mc("Which is sharing?", "splitting your snack with a friend", ["keeping all the toys", "taking a turn twice", "hiding the crayons"]),
 mc("Buddhist monks and nuns often wear robes that are…", "orange, red or brown", ["polka-dotted", "made of gold", "rainbow striped"]),
 tf("Sharing is an important Buddhist value.", True),
 tf("Buddhist monks buy all their food at stores.", False),
 voc("share", "To let others have or use some of what you have."),
 op("Tell about a time someone shared with you. How did it feel?", "Any honest answer about being shared with."),
]),
("Special Days", "Días especiales", [
 mc("Many Buddhists celebrate the Buddha’s birthday on a holiday called…", "Vesak", ["Diwali", "Holi", "Hanukkah"]),
 mc("At Vesak, many Buddhists light…", "lanterns", ["fireworks only", "bonfires on the beach", "nothing"]),
 mc("On some Buddhist holidays, people pour water on a statue of the…", "baby Buddha", ["king", "monkey", "moon"]),
 mc("A Buddhist place of worship is often called a…", "temple", ["stadium", "mall", "garage"]),
 mc("A bell at a temple is rung to…", "help people pay attention", ["call dogs", "start a race", "scare birds"]),
 mc("At the temple, people often bow to show…", "respect", ["anger", "hunger", "sleepiness"]),
 tf("Vesak remembers the Buddha’s birth.", True),
 tf("Vesak is a winter snow festival.", False),
 voc("lantern", "A light with a cover around it."),
 op("What would you put on a lantern to celebrate something good?", "Any picture or word of something good."),
]),
]

BANDS['35'] = [
("Who the Buddha Was", "Quién fue el Buda", [
 mc("The Buddha lived about…", "2,500 years ago", ["200 years ago", "10,000 years ago", "50 years ago"]),
 mc("The Buddha was born in Lumbini, in present-day…", "Nepal", ["China", "Japan", "Thailand"]),
 mc("His family name was…", "Gautama", ["Kong", "Singh", "Li"]),
 mc("Siddhartha left home at about age…", "29", ["5", "60", "90"]),
 mc("Before his awakening, Siddhartha tried living with almost no food. He learned that…", "hurting the body did not bring wisdom", ["fasting is the only way", "food is bad", "sleep is best"]),
 mc("The Buddha taught a “Middle Way” between…", "too much comfort and too much hardship", ["north and south", "day and night", "cats and dogs"]),
 tf("The Buddha is also called Shakyamuni, “sage of the Shakya clan.”", True),
 tf("Buddhists teach that the Buddha is the creator god.", False),
 voc("Middle Way", "A path between too much and too little."),
 op("Give an example of a “middle way” in your life, between too much and too little.", "Balancing screen time and play, sleep and study, or any balance example."),
]),
("The Four Sights", "Las cuatro visiones", [
 mc("Outside the palace, Siddhartha first saw an…", "old man", ["elephant", "army", "angel"]),
 mc("The second sight was a…", "sick person", ["king", "baby", "horse"]),
 mc("The third sight was a…", "dead body", ["bird", "dancer", "boat"]),
 mc("The fourth sight was a…", "calm holy man who had left home", ["merchant", "soldier", "child"]),
 mc("The first three sights showed Siddhartha that all people face…", "old age, sickness and death", ["riches", "fame", "only happiness"]),
 mc("The fourth sight gave Siddhartha…", "hope that there was a way to peace", ["a new horse", "a crown", "a map"]),
 tf("The Four Sights led Siddhartha to leave the palace.", True),
 tf("The fourth sight was a king.", False),
 voc("suffering", "Pain, sadness or feeling that something is not right."),
 op("Why do you think seeing these sights changed Siddhartha so much?", "He had been kept from pain; seeing it for the first time made him want to find an answer for everyone."),
]),
("Awakening", "El despertar", [
 mc("Siddhartha sat under the Bodhi tree at…", "Bodh Gaya", ["Lumbini", "Beijing", "Rome"]),
 mc("Buddhist stories say a being named Mara tried to…", "distract and frighten him", ["feed him", "teach him", "crown him"]),
 mc("Siddhartha touched the earth to show…", "the earth was his witness", ["he was tired", "he wanted to dig", "he lost something"]),
 mc("Awakening or enlightenment means…", "seeing the truth clearly", ["waking from a nap", "turning on a lamp", "becoming rich"]),
 mc("The Buddha’s first sermon was given at…", "Deer Park near Sarnath", ["a palace", "the sea", "a school in China"]),
 mc("The first sermon is called “Setting in Motion the Wheel of…”", "the Dharma", ["the chariot", "the year", "the moon"]),
 tf("The wheel is a common Buddhist symbol for the teaching.", True),
 tf("Mara helped Siddhartha meditate.", False),
 voc("enlightenment", "Full understanding; for Buddhists, waking up to the truth."),
 op("Mara stands for distractions. What distracts you when you try to focus, and what helps?", "Phones, noise, worries; helps: a quiet place, a plan, breathing."),
]),
("The Jataka Tales", "Los cuentos Jataka", [
 mc("There are more than…", "500 Jataka tales", ["5", "20", "2 million"]),
 mc("In the Jataka tales, the future Buddha is called the…", "Bodhisattva", ["Mara", "Brahma", "king of Lanka"]),
 mc("In “The Monkey King,” the Bodhisattva stretches himself to form a…", "bridge", ["boat", "wall", "rope swing"]),
 mc("In “The Golden Deer,” a deer saves a drowning man who later…", "betrays the deer to a king", ["becomes a deer", "builds a temple", "flies away"]),
 mc("In the tale of the hare, the hare jumps into a fire to…", "feed a hungry traveler", ["stay warm", "escape a fox", "find carrots"]),
 mc("Each Jataka tale usually teaches a…", "virtue, like generosity or patience", ["math skill", "map", "recipe"]),
 tf("Some Jataka tales are like Aesop’s fables.", True),
 tf("Jataka tales are about the Buddha’s trips to other planets.", False),
 voc("virtue", "A good quality, like honesty or kindness."),
 op("Pick a Jataka tale and name the virtue it teaches.", "Monkey King: self-giving leadership; Hare: generosity; Golden Deer: compassion and honesty."),
]),
("The Four Noble Truths", "Las Cuatro Nobles Verdades", [
 mc("The first Noble Truth says that life includes…", "suffering (dukkha)", ["only joy", "no change", "no problems"]),
 mc("The second Noble Truth says suffering comes from…", "craving and clinging", ["rain", "bad luck only", "animals"]),
 mc("The third Noble Truth says that suffering…", "can end", ["can never end", "is good", "is not real"]),
 mc("The fourth Noble Truth says the way to end suffering is the…", "Eightfold Path", ["Silk Road", "Great Wall", "Four Sights"]),
 mc("The Four Noble Truths are often compared to a doctor who…", "names the illness, its cause, the cure and the medicine", ["sells medicine", "has no patients", "only writes books"]),
 mc("“Craving” means…", "wanting something so much you cannot let go", ["being full", "sleeping well", "being sick"]),
 tf("The Four Noble Truths were part of the Buddha’s first sermon.", True),
 tf("The third Noble Truth says suffering can never end.", False),
 voc("craving", "A strong wanting that will not let go."),
 op("Think of a time you really wanted something and felt upset. How could letting go have helped?", "Any honest example; letting go could bring calm and ease the upset."),
]),
("The Eightfold Path", "El Noble Óctuple Sendero", [
 mc("The Eightfold Path is often shown as a…", "wheel with eight spokes", ["ladder", "star", "tree"]),
 mc("“Right Speech” means…", "speaking truthfully and kindly", ["speaking loudly", "never talking", "talking fast"]),
 mc("“Right Action” means…", "not harming, not stealing", ["winning every game", "working all night", "only praying"]),
 mc("“Right Livelihood” means…", "earning a living in a way that does not harm", ["getting rich", "not working", "working at night"]),
 mc("“Right Mindfulness” means…", "paying careful attention", ["forgetting", "daydreaming", "shouting"]),
 mc("The Eightfold Path is grouped into wisdom, ethics and…", "meditation", ["money", "sports", "music"]),
 tf("“Right Effort” means working to grow good thoughts.", True),
 tf("The Eightfold Path has twelve parts.", False),
 voc("path", "A way to go; a way to live."),
 op("Choose one step of the Eightfold Path and give an example of it at school.", "Right Speech: telling the truth kindly; Right Action: not taking others’ things; any fit example."),
]),
("The Three Jewels", "Las Tres Joyas", [
 mc("The Three Jewels are the Buddha, the Dharma and the…", "Sangha", ["Veda", "Temple", "Moon"]),
 mc("The Dharma is…", "the Buddha’s teaching", ["a temple", "a monk’s robe", "a festival"]),
 mc("The Sangha is…", "the community of Buddhists", ["a mountain", "a book", "a food"]),
 mc("Buddhists “take refuge” in the Three Jewels. Refuge means…", "a safe place", ["a prize", "a punishment", "a game"]),
 mc("Buddhist monks are called bhikkhus; Buddhist nuns are called…", "bhikkhunis", ["gurus", "rabbis", "sages"]),
 mc("Buddhists often recite the Three Refuges…", "in daily practice", ["only once in life", "never", "only in winter"]),
 tf("The Three Jewels are also called the Triple Gem.", True),
 tf("The Sangha is the name of a river.", False),
 voc("refuge", "A safe place to go."),
 op("What is a “safe place” in your life, a person, a place or an idea?", "Any honest answer."),
]),
("The Dhammapada", "El Dhammapada", [
 mc("The Dhammapada is a collection of…", "short sayings of the Buddha", ["long war stories", "recipes", "laws of kings"]),
 mc("The Dhammapada has 423 verses in…", "26 chapters", ["2 chapters", "100 chapters", "1 chapter"]),
 mc("The best-known Dhammapada comes down to us in the language called…", "Pali", ["Latin", "Chinese", "Sanskrit only"]),
 mc("In Max Müller’s 1881 translation, verse 5 says: “hatred ceases by…”", "love", ["hatred", "anger", "war"]),
 mc("The Dhammapada begins by saying our lives are shaped by our…", "thoughts", ["shoes", "houses", "birthdays"]),
 mc("Many Dhammapada verses compare the mind to things like…", "a fish, a thatched house and a clear lake", ["cars", "computers", "phones"]),
 tf("The Dhammapada is one of the most widely read Buddhist texts.", True),
 tf("The Dhammapada says hatred ends by more hatred.", False),
 voc("verse", "A short piece of writing, often one line or a few lines."),
 op("Müller’s Dhammapada says, “All that we are is the result of what we have thought.” Tell what this means in your own words.", "What we think shapes who we become; good thoughts lead to good actions."),
]),
("Monks, Nuns and Temples", "Monjes, monjas y templos", [
 mc("Buddhist monks and nuns usually…", "shave their heads", ["wear crowns", "grow long hair", "wear armor"]),
 mc("A Buddhist monastery is a place where…", "monks or nuns live and practice", ["kings rule", "soldiers train", "food is sold"]),
 mc("A stupa is a dome-shaped building that often holds…", "relics", ["water", "cars", "horses"]),
 mc("Many Buddhist temples have statues of the Buddha sitting in…", "meditation", ["a chair", "a car", "a boat"]),
 mc("Monks walk each morning to receive food. This is called an…", "alms round", ["arms race", "all-nighter", "almanac"]),
 mc("Buddhist monks and nuns follow many rules called the…", "Vinaya", ["Veda", "Analects", "Torah"]),
 tf("In some countries, many boys spend a short time as monks.", True),
 tf("Buddhist monks usually wear armor.", False),
 voc("monastery", "A place where monks or nuns live, pray and study."),
 op("Monks live simply with few things. What is one thing you could live without, and one you could not?", "Any honest answer."),
]),
("Buddhism Spreads", "El budismo se extiende", [
 mc("Emperor Ashoka helped spread Buddhism across…", "India and beyond", ["Europe", "the Americas", "Antarctica"]),
 mc("Ashoka turned to Buddhism after a terrible…", "war", ["flood", "storm", "earthquake"]),
 mc("Buddhism traveled to China along the…", "Silk Road", ["Nile River", "Amazon", "Route 66"]),
 mc("Buddhism became important in countries such as…", "Thailand, Japan and Tibet", ["Iceland, Chile and Peru", "Canada, Mexico and Cuba", "Egypt, Ghana and Kenya"]),
 mc("Ashoka carved his messages on…", "stone pillars", ["paper", "tree bark only", "glass"]),
 mc("Buddhism began in…", "India", ["Japan", "China", "Tibet"]),
 tf("Buddhism is practiced all over the world today.", True),
 tf("Ashoka spread Buddhism by winning more wars.", False),
 voc("emperor", "A ruler of many lands."),
 op("Ashoka changed after seeing the harm of war. What can people learn from his change?", "People can grow; seeing harm can lead to kindness and peace."),
]),
]

BANDS['68'] = [
("Life of the Buddha", "La vida del Buda", [
 mc("Siddhartha Gautama was born around…", "the 5th or 6th century BCE", ["100 CE", "1000 CE", "3000 BCE"]),
 mc("Siddhartha married Yashodhara and had a son named…", "Rahula", ["Ananda", "Ashoka", "Mara"]),
 mc("His years as a wandering seeker included…", "extreme fasting that nearly killed him", ["ruling a kingdom", "sailing abroad", "fighting wars"]),
 mc("A young woman named Sujata ended his fast by offering…", "rice milk", ["bread", "fish", "wine"]),
 mc("The Buddha died at about age 80 at…", "Kushinagar", ["Lumbini", "Rome", "Mecca"]),
 mc("The Buddha’s death is called his…", "parinirvana", ["baptism", "coronation", "Diwali"]),
 tf("Buddhists do not see the Buddha as a god but as a teacher who found the way.", True),
 tf("The Buddha wrote his teachings down himself.", False),
 voc("ascetic", "A person who gives up comforts for a spiritual goal."),
 op("Why did the Buddha reject both palace comfort and extreme fasting?", "Neither brought wisdom; the Middle Way lets the mind be clear and healthy."),
]),
("The Four Noble Truths", "Las Cuatro Nobles Verdades", [
 mc("Dukkha is often translated…", "suffering or unsatisfactoriness", ["joy", "wealth", "prayer"]),
 mc("Tanha, the cause of suffering, means…", "craving or thirst", ["generosity", "sleep", "wisdom"]),
 mc("The end of suffering is called…", "nirvana", ["samsara", "karma", "Sangha"]),
 mc("“Nirvana” literally means…", "“blowing out,” like a flame", ["“heaven”", "“mountain”", "“victory”"]),
 mc("The Four Noble Truths are presented like a…", "doctor’s diagnosis and cure", ["legal ruling", "battle plan", "poem about love"]),
 mc("Which truth names the path to the end of suffering?", "the fourth", ["the first", "the second", "the third"]),
 tf("Buddhists say the Four Noble Truths are meant to be tested in one’s own life.", True),
 tf("Nirvana is a place on a map.", False),
 voc("diagnosis", "Figuring out what is wrong and why."),
 op("Explain the doctor comparison: what are the illness, the cause, the cure and the medicine?", "Illness: suffering; cause: craving; cure: nirvana; medicine: the Eightfold Path."),
]),
("The Noble Eightfold Path", "El Noble Óctuple Sendero", [
 mc("Right View and Right Intention make up the part called…", "wisdom", ["ethics", "meditation", "ritual"]),
 mc("Right Speech, Right Action and Right Livelihood make up…", "ethical conduct", ["wisdom", "meditation", "worship"]),
 mc("Right Effort, Right Mindfulness and Right Concentration make up…", "mental discipline", ["ethics", "wisdom", "charity"]),
 mc("A butcher or arms dealer would conflict with…", "Right Livelihood", ["Right View", "Right Concentration", "Right Intention"]),
 mc("Right Concentration refers to…", "deep, focused meditation", ["studying for tests", "eating well", "sports"]),
 mc("The path steps are practiced…", "together, not one after another", ["in strict order only", "once a year", "only by monks"]),
 tf("Gossip goes against Right Speech.", True),
 tf("Right Livelihood means earning as much money as possible.", False),
 voc("livelihood", "The way a person earns a living."),
 op("Pick two steps of the Path and show how they support each other.", "Right Mindfulness helps Right Speech: noticing anger lets you choose kind words."),
]),
("Karma, Rebirth and Nirvana", "Karma, renacimiento y nirvana", [
 mc("In Buddhism, karma means…", "intentional action and its effects", ["fate set by gods", "luck", "a prayer"]),
 mc("The cycle of rebirth is called…", "samsara", ["nirvana", "dharma", "sangha"]),
 mc("The Wheel of Life shows beings trapped by greed, hatred and…", "delusion", ["joy", "wealth", "rain"]),
 mc("In the Wheel of Life, greed, hatred and delusion are shown as a rooster, a snake and a…", "pig", ["tiger", "fish", "eagle"]),
 mc("Nirvana is the end of…", "craving and rebirth", ["the world", "all life on earth", "study"]),
 mc("For Buddhists, what matters most in karma is the…", "intention behind an action", ["size of the action", "day it happens", "weather"]),
 tf("Buddhists and Hindus both speak of karma and rebirth, but explain them differently.", True),
 tf("In Buddhism, karma is punishment handed out by a god.", False),
 voc("intention", "What you mean to do and why."),
 op("Two people give money to charity, one to help and one to show off. How would Buddhist teaching on intention see them?", "The act is the same, but the helper’s kind intention makes good karma; showing off is rooted in craving."),
]),
("The Three Marks of Existence", "Las Tres Marcas de la existencia", [
 mc("The Three Marks are impermanence, suffering and…", "not-self", ["heaven", "wealth", "fate"]),
 mc("Anicca, impermanence, means…", "everything changes", ["nothing changes", "only people change", "stars never change"]),
 mc("Anatta, not-self, means…", "there is no permanent, unchanging self", ["people do not exist", "animals have no feelings", "you should hate yourself"]),
 mc("A river is a good image for impermanence because…", "its water is always moving and changing", ["it is blue", "it is cold", "it is long"]),
 mc("The Buddha said clinging to what changes leads to…", "suffering", ["joy that lasts", "wealth", "peace"]),
 mc("In the Questions of King Milinda, the monk Nagasena compares a person to a…", "chariot made of parts", ["mountain", "river of salt", "tree of gold"]),
 tf("Nagasena’s chariot shows “chariot” is a name for parts put together.", True),
 tf("Anicca means everything stays the same forever.", False),
 voc("impermanent", "Not lasting forever; always changing."),
 op("Name something in your life that has changed. How did you feel about the change?", "Any honest example and feeling."),
]),
("The Tipitaka", "El Tipitaka", [
 mc("“Tipitaka” means…", "“three baskets”", ["“three rivers”", "“three kings”", "“three wheels”"]),
 mc("The Vinaya Pitaka contains…", "rules for monks and nuns", ["the Buddha’s past lives", "philosophy only", "songs"]),
 mc("The Sutta Pitaka contains…", "the Buddha’s talks and dialogues", ["monastery rules", "a history of China", "legal cases"]),
 mc("The Abhidhamma Pitaka contains…", "detailed analysis of the mind and teaching", ["stories of kings", "recipes", "poems for children"]),
 mc("The Tipitaka was first written down in Sri Lanka around…", "the 1st century BCE", ["the 10th century CE", "the Buddha’s childhood", "1900 CE"]),
 mc("Before it was written, the teaching was…", "memorized and recited by monks", ["painted on walls", "lost", "kept by kings"]),
 tf("The Tipitaka is also called the Pali Canon.", True),
 tf("The Buddha wrote the Tipitaka with his own hand.", False),
 voc("canon", "An official collection of sacred texts."),
 op("Why were the teachings sorted into three “baskets”?", "To keep different kinds of teaching organized: rules, talks and deep analysis."),
]),
("The Dhammapada", "El Dhammapada", [
 mc("The Dhammapada is found in which basket?", "the Sutta Pitaka", ["the Vinaya", "the Abhidhamma", "none of them"]),
 mc("Müller’s translation of verse 1 says our lives are “founded on our…”", "thoughts", ["houses", "parents", "kings"]),
 mc("Verse 5 in Müller’s translation calls “hatred ceases by love” an…", "old rule", ["new law", "idea of kings", "impossible thing"]),
 mc("The Dhammapada chapter “The Twin Verses” pairs…", "a harmful mind and a pure mind", ["two kings", "two rivers", "two animals"]),
 mc("The Dhammapada says one who conquers himself is greater than one who…", "conquers a thousand men in battle a thousand times", ["wins a race", "gets rich", "builds a temple"]),
 mc("The Dhammapada compares a wise person to a…", "deep, clear, calm lake", ["storm", "wild horse", "fire"]),
 tf("Many Dhammapada verses use images from nature.", True),
 tf("The Dhammapada praises conquering others in war as the greatest victory.", False),
 voc("conquer", "To defeat or gain control over."),
 op("Why might conquering yourself be harder than conquering an army?", "Your own anger and habits are always with you and hard to see; changing them takes long practice."),
]),
("Theravada and Mahayana", "Theravada y Mahayana", [
 mc("Theravada means…", "“the way of the elders”", ["“the great vehicle”", "“the diamond way”", "“the middle kingdom”"]),
 mc("Theravada is most common in…", "Sri Lanka, Thailand and Myanmar", ["Japan and Korea", "Tibet and Mongolia", "India only"]),
 mc("Mahayana means…", "“great vehicle”", ["“small boat”", "“old way”", "“thunder path”"]),
 mc("Mahayana is most common in…", "China, Korea, Japan and Vietnam", ["Sri Lanka", "Laos", "Cambodia"]),
 mc("In Mahayana, a bodhisattva is one who…", "delays nirvana to help all beings", ["rules a kingdom", "never meditates", "only studies"]),
 mc("Vajrayana, a third branch, is most linked with…", "Tibet", ["Brazil", "Sri Lanka", "Greece"]),
 tf("Theravada texts are mainly in Pali; many Mahayana texts survive in Sanskrit and Chinese.", True),
 tf("All Buddhists use exactly the same texts.", False),
 voc("bodhisattva", "One who seeks awakening in order to help all beings."),
 op("Why might the idea of a bodhisattva appeal to many people?", "It joins wisdom with compassion; it offers helpers and a goal of saving everyone, not just oneself."),
]),
("Practice in the Sangha", "La práctica en la Sangha", [
 mc("The Five Precepts for lay Buddhists include not killing, not stealing and not…", "lying", ["reading", "working", "traveling"]),
 mc("Another Precept is to avoid…", "intoxicants that cloud the mind", ["vegetables", "exercise", "music lessons"]),
 mc("Metta meditation sends…", "loving-kindness to all beings", ["money to the temple", "letters to kings", "prayers for rain only"]),
 mc("A mala is a string of beads used for…", "counting recitations", ["paying at markets", "decoration only", "games"]),
 mc("Lay Buddhists support monks and nuns with…", "food and needed items", ["weapons", "taxes", "votes"]),
 mc("Uposatha days, tied to the moon, are days for…", "extra practice and keeping more precepts", ["feasting", "war", "trade"]),
 tf("Most Buddhists are lay people, not monks or nuns.", True),
 tf("The Five Precepts are only for monks.", False),
 voc("precept", "A rule to guide how you act."),
 op("Choose one Precept and tell how it could help a community.", "Not stealing builds trust; not lying lets people rely on each other; any reasoned answer."),
]),
("Buddhism Across Asia", "El budismo en Asia", [
 mc("Ashoka sent his son Mahinda to bring Buddhism to…", "Sri Lanka", ["Japan", "Greece", "Persia"]),
 mc("The Chinese monk Xuanzang traveled to India to collect…", "Buddhist texts", ["spices", "silk", "horses"]),
 mc("Borobudur, a huge Buddhist monument, is in…", "Indonesia", ["India", "Tibet", "Korea"]),
 mc("Buddhism reached Japan by way of…", "Korea and China", ["Russia", "the Pacific islands", "Europe"]),
 mc("The Dalai Lama is a leading teacher of…", "Tibetan Buddhism", ["Theravada", "Zen", "Pure Land"]),
 mc("The Diamond Sutra printed in 868 CE is the oldest dated…", "printed book", ["painting", "map", "bell"]),
 tf("Buddhism changed as it met new cultures.", True),
 tf("Buddhism never left India.", False),
 voc("pilgrim", "A person who travels to a holy place."),
 op("How might Buddhism look different in Thailand and Japan, and why?", "Different branches, languages, arts and customs grew as it blended with each local culture."),
]),
]

BANDS['912'] = [
("The Pali Canon", "El Canon Pali", [
 mc("The Sutta Pitaka is divided into five collections called…", "Nikayas", ["Mandalas", "Kandas", "Suras"]),
 mc("The Digha Nikaya is the collection of…", "long discourses", ["short sayings", "rules for nuns", "past lives"]),
 mc("The First Council after the Buddha’s death is said to have been held at…", "Rajagaha", ["Rome", "Nalanda in 1200 CE", "Kyoto"]),
 mc("At the First Council, the Buddha’s attendant Ananda recited…", "the discourses (suttas)", ["the monastic rules", "the Vedas", "the Lotus Sutra"]),
 mc("T. W. Rhys Davids founded the Pali Text Society in…", "1881", ["1650", "1990", "1492"]),
 mc("Many suttas begin with the formula…", "“Thus have I heard”", ["“In the beginning”", "“Once upon a time”", "“The Master said”"]),
 tf("Scholars debate how much of the Pali Canon goes back to the Buddha himself.", True),
 tf("The Pali Canon was compiled in the 20th century.", False),
 voc("discourse", "A formal talk or teaching."),
 op("Why might a text open with “Thus have I heard”? What does that tell readers about how it was passed on?", "It marks oral transmission: a disciple reports what he heard, stressing faithful memory rather than authorship."),
]),
("Close Reading the Dhammapada", "Lectura atenta del Dhammapada", [
 mc("Müller’s Dhammapada verse 1: if a man speaks or acts “with an evil thought,” pain follows him as…", "the wheel follows the foot of the ox", ["night follows day", "rain follows cloud", "a shadow follows a tree"]),
 mc("Verse 2 pairs this with a pure thought, after which happiness follows like…", "a shadow that never leaves", ["a river", "a wheel", "a king"]),
 mc("The image of the ox and cart stresses that consequences are…", "inevitable and close behind", ["random", "far away", "reversible by luck"]),
 mc("The Dhammapada chapter on “The Mind” compares an unsteady mind to…", "a fish taken from the water", ["a mountain", "a lamp", "a wheel"]),
 mc("The Dhammapada says a single word that brings peace is better than…", "a thousand empty words", ["a thousand coins", "one song", "silence"]),
 mc("In the Dhammapada, “Brahmana” in the last chapter is redefined as…", "one who is truly pure in conduct, not by birth", ["a priest by birth only", "a king", "a merchant"]),
 tf("The Dhammapada’s final chapter challenges status by birth.", True),
 tf("The ox image says consequences can be escaped easily.", False),
 voc("parallelism", "Repeating a sentence pattern with a change to compare ideas."),
 op("Analyze how verses 1 and 2 use parallel structure to make their point.", "Same frame, opposite causes: evil thought brings pain like a wheel; pure thought brings happiness like a shadow. The mirror form shows mind shapes outcome."),
]),
("Dependent Origination", "Originación dependiente", [
 mc("Dependent origination (pratītyasamutpāda) teaches that things…", "arise from causes and conditions", ["come from nowhere", "are created by one god", "never change"]),
 mc("A classic summary: “When this is, that is; from the arising of this…”", "that arises", ["nothing arises", "all ends", "time stops"]),
 mc("The chain of dependent origination has how many links?", "twelve", ["three", "eight", "one hundred"]),
 mc("The first link of the chain is…", "ignorance", ["birth", "craving", "death"]),
 mc("Dependent origination supports the idea of not-self because…", "nothing exists on its own apart from conditions", ["people are illusions", "the self is Brahman", "only God is real"]),
 mc("Breaking the chain at craving leads to…", "the end of suffering", ["rebirth as a god", "wealth", "fame"]),
 tf("Dependent origination is often pictured around the rim of the Wheel of Life.", True),
 tf("Dependent origination says things arise without causes.", False),
 voc("condition", "Something that must be there for another thing to happen."),
 op("Use a plant to explain dependent origination.", "A plant arises from seed, soil, water, sun and time; take away a condition and it does not arise. So do all things."),
]),
("Not-Self", "El no-yo", [
 mc("The Anattalakkhana Sutta, the Buddha’s second discourse, teaches about…", "not-self", ["the Four Sights", "monastic rules", "the Jatakas"]),
 mc("In it, the Buddha asks whether body, feeling, perception, formations and consciousness are…", "permanent or impermanent", ["good or evil", "hot or cold", "old or new"]),
 mc("These five are called the…", "five aggregates (skandhas)", ["five precepts", "five pillars", "five classics"]),
 mc("The argument: if something is impermanent and leads to suffering, it cannot be…", "“mine,” “I” or “my self”", ["seen", "named", "studied"]),
 mc("Nagasena’s chariot argument concludes that “Nagasena” is…", "a convenient name for changing parts", ["a soul in heaven", "a god", "an illusion with no use"]),
 mc("Anatta differs from the Upanishads, which teach…", "an eternal atman", ["no self", "many gods only", "no ethics"]),
 tf("Buddhists argue that seeing not-self reduces selfish clinging.", True),
 tf("Anatta teaches that people should not care about themselves at all.", False),
 voc("aggregate", "A whole made from gathered parts."),
 op("Summarize the not-self argument in three steps, then give one objection someone might raise.", "Each aggregate is impermanent; what is impermanent brings suffering; so it is not a lasting self. Objection: memory and responsibility seem to need a continuing self."),
]),
("Key Suttas", "Suttas clave", [
 mc("The Dhammacakkappavattana Sutta is the Buddha’s…", "first sermon", ["last words", "birth story", "monastic code"]),
 mc("In the Fire Sermon, the Buddha says the senses are…", "burning with greed, hatred and delusion", ["cool and calm", "made of light", "gifts of kings"]),
 mc("The Kalama Sutta advises people not to accept teachings just because of…", "tradition or authority, but to test them", ["reason", "experience", "kindness"]),
 mc("The Metta Sutta asks one to love all beings as a mother…", "protects her only child", ["rules her house", "teaches school", "cooks dinner"]),
 mc("The Mahaparinibbana Sutta describes…", "the Buddha’s last days", ["his birth", "his marriage", "his fasting"]),
 mc("Among the Buddha’s last words, in Rhys Davids’s translation, he urges his followers to…", "work out their salvation with diligence", ["build temples", "worship him", "return home"]),
 tf("The Kalama Sutta is often cited as encouraging critical thinking.", True),
 tf("In the Fire Sermon, the fire stands for joy.", False),
 voc("diligence", "Careful, steady effort."),
 op("The Kalama Sutta says to test teachings by whether they lead to harm or benefit. Is that a good test? Explain.", "Any reasoned view: it grounds belief in experience; but some truths may be hard to test directly."),
]),
("Mahayana Sutras", "Sutras Mahayana", [
 mc("The Heart Sutra is famous for the line…", "“form is emptiness, emptiness is form”", ["“thus have I heard”", "“the Tao that can be named”", "“know thyself”"]),
 mc("“Emptiness” (shunyata) means things are…", "empty of fixed, independent existence", ["worthless", "invisible", "made of air"]),
 mc("The Lotus Sutra teaches that…", "all beings can become Buddhas", ["only monks can wake up", "the Buddha was only a man", "there is no path"]),
 mc("The Lotus Sutra uses the parable of…", "a burning house", ["a lost coin", "a golden deer", "a monkey bridge"]),
 mc("Nagarjuna, a key Mahayana thinker, founded the…", "Madhyamaka (Middle Way) school", ["Pure Land school", "Theravada", "Confucian school"]),
 mc("The Diamond Sutra is so named because its wisdom…", "cuts through illusion like a diamond", ["is expensive", "sparkles", "was found in a mine"]),
 tf("Mahayana sutras were written down centuries after the Buddha.", True),
 tf("The Lotus Sutra says only a few can become Buddhas.", False),
 voc("parable", "A short story that teaches a lesson by comparison."),
 op("Explain the burning house parable: what do the house, the children and the carts stand for?", "House: the world of suffering; children: beings unaware of danger; carts: teachings used skillfully to lead them out."),
]),
("Zen and Pure Land", "Zen y Tierra Pura", [
 mc("Zen (Chan in Chinese) stresses…", "meditation and direct insight", ["long rituals only", "memorizing all texts", "wealth"]),
 mc("A koan is…", "a puzzling question used to go beyond logic", ["a type of temple", "a rice dish", "a robe"]),
 mc("A famous koan asks: “What is the sound of…”", "one hand clapping", ["the ocean", "a bell at dawn", "rain"]),
 mc("Pure Land Buddhism centers on devotion to…", "Amitabha Buddha", ["Mara", "Confucius", "Indra"]),
 mc("Pure Land followers recite Amitabha’s name hoping to be reborn in…", "the Pure Land", ["Lumbini", "heaven of Indra", "the Silk Road"]),
 mc("Bodhidharma is traditionally credited with bringing Zen to…", "China", ["Sri Lanka", "India", "Greece"]),
 tf("Zen and Pure Land are both Mahayana schools.", True),
 tf("A koan is meant to be solved with simple logic.", False),
 voc("koan", "A puzzle question used in Zen to wake up the mind."),
 op("Zen relies on one’s own effort; Pure Land relies on Amitabha’s help. Compare the two approaches.", "Zen: self-power through meditation; Pure Land: other-power through faith and recitation; both aim at awakening."),
]),
("Tibetan Buddhism", "El budismo tibetano", [
 mc("Tibetan Buddhism is part of the branch called…", "Vajrayana", ["Theravada", "Confucianism", "Jainism"]),
 mc("The Tibetan Book of the Dead (Bardo Thödol) guides a person through…", "the state between death and rebirth", ["a wedding", "a harvest", "a coronation"]),
 mc("A mandala is a…", "sacred circular design", ["drum", "prayer bead", "robe"]),
 mc("Sand mandalas are swept away when finished to show…", "impermanence", ["anger", "mistakes", "wealth"]),
 mc("“Om mani padme hum” is a mantra linked to…", "Avalokiteshvara, bodhisattva of compassion", ["Mara", "Ashoka", "Laozi"]),
 mc("The Dalai Lama left Tibet for exile in India in…", "1959", ["1776", "1914", "2001"]),
 tf("Prayer wheels hold written mantras and are turned by hand.", True),
 tf("Sand mandalas are kept forever in museums as the tradition requires.", False),
 voc("mandala", "A circle design that stands for the universe."),
 op("Why might a monk spend days on a sand mandala and then sweep it away?", "The act teaches impermanence and non-attachment; the value is in the practice, not keeping the thing."),
]),
("Buddhist Ethics", "La ética budista", [
 mc("The four “immeasurables” are loving-kindness, compassion, sympathetic joy and…", "equanimity", ["wealth", "pride", "fame"]),
 mc("Karuna means…", "compassion", ["anger", "wisdom", "patience"]),
 mc("Mudita means…", "joy in others’ happiness", ["sadness", "fear", "envy"]),
 mc("Upekkha, equanimity, means…", "a balanced, steady mind", ["not caring at all", "anger", "fear"]),
 mc("“Engaged Buddhism,” a term used by Thich Nhat Hanh, applies teaching to…", "social and political problems", ["only private meditation", "ancient history", "sports"]),
 mc("Thich Nhat Hanh worked for peace during the…", "Vietnam War", ["Crusades", "Napoleonic Wars", "Cold War space race"]),
 tf("Martin Luther King Jr. nominated Thich Nhat Hanh for the Nobel Peace Prize.", True),
 tf("Equanimity means not caring about anyone.", False),
 voc("compassion", "Feeling others’ pain and wanting to help."),
 op("How does equanimity differ from not caring? Give an example.", "Equanimity stays steady while still caring, e.g., a nurse calm in a crisis who still helps with warmth."),
]),
("Comparing Traditions", "Comparar tradiciones", [
 mc("Buddhism and Hinduism both use the words karma, dharma and…", "samsara", ["Sabbath", "Torah", "Qur’an"]),
 mc("A key difference: the Upanishads teach an eternal self, while the Buddha taught…", "anatta, not-self", ["many souls", "a self in heaven", "the self is God"]),
 mc("In China, Buddhism mixed with…", "Daoism and Confucianism", ["Islam only", "Greek religion", "Norse myth"]),
 mc("Both the Dhammapada and the Analects stress…", "training character through daily conduct", ["conquest", "wealth", "magic"]),
 mc("The Buddha’s “Middle Way” resembles Aristotle’s idea of…", "virtue as a mean between extremes", ["the atom", "the republic", "the syllogism"]),
 mc("Unlike the Abrahamic faiths, early Buddhism does not center on…", "a creator God", ["ethics", "community", "texts"]),
 tf("Describing traditions fairly means using their own terms.", True),
 tf("Buddhism and Daoism never influenced each other.", False),
 voc("syncretism", "The blending of different beliefs or practices."),
 op("Compare how the Dhammapada and Hillel’s rule each summarize ethics in a few words.", "Dhammapada: avoid evil, do good, purify the mind; Hillel: do not do to others what is hateful to you. Both are short guides to action."),
]),
]

BANDS['adult'] = [
("The Buddha’s life", "La vida del Buda", [
 mc("The Buddha’s given name was…", "Siddhartha Gautama", ["Kong Qiu", "Arjuna", "Ashoka"]),
 mc("He grew up as a…", "prince", ["slave", "sailor", "merchant"]),
 mc("The Four Sights were an old man, a sick man, a dead man and…", "a wandering holy man", ["a king", "a child", "a warrior"]),
 mc("He reached awakening under the…", "Bodhi tree", ["olive tree", "oak", "cherry tree"]),
 mc("“Buddha” means…", "awakened one", ["king", "teacher of kings", "son of heaven"]),
 mc("He taught for about…", "45 years", ["5 years", "100 years", "one day"]),
 tf("Buddhists see the Buddha as a human teacher, not a creator god.", True),
 tf("The Buddha stayed a prince all his life.", False),
 voc("awakening", "Seeing clearly what is true."),
 op("What might push someone to leave a comfortable life to seek answers?", "Seeing suffering, asking big questions, feeling that comfort is not enough."),
]),
("The Four Noble Truths", "Las Cuatro Nobles Verdades", [
 mc("The first Truth: life involves…", "suffering", ["only pleasure", "no change", "perfect peace"]),
 mc("The second Truth: suffering is caused by…", "craving", ["gods", "stars", "animals"]),
 mc("The third Truth: suffering…", "can end", ["cannot end", "is good", "is fake"]),
 mc("The fourth Truth: the way out is the…", "Eightfold Path", ["Four Sights", "Five Classics", "Ten Commandments"]),
 mc("The end of suffering is…", "nirvana", ["samsara", "karma", "dukkha"]),
 mc("The Truths are often compared to a…", "doctor’s diagnosis and treatment", ["court trial", "battle plan", "contract"]),
 tf("The Four Noble Truths were in the Buddha’s first sermon.", True),
 tf("Buddhism says suffering has no cause.", False),
 voc("dukkha", "Suffering, stress or dissatisfaction."),
 op("Think of a recent stress. What craving or clinging was underneath it?", "Any honest reflection, such as wanting control, approval or a certain result."),
]),
("The Eightfold Path", "El Óctuple Sendero", [
 mc("The Path has eight parts grouped as wisdom, ethics and…", "meditation", ["money", "ritual", "study only"]),
 mc("Right Speech means…", "truthful, kind and helpful words", ["speaking often", "saying nothing", "winning arguments"]),
 mc("Right Livelihood means…", "work that does not cause harm", ["the best-paying job", "no job", "only farming"]),
 mc("Right Mindfulness means…", "clear awareness of the present", ["planning the future", "remembering the past", "daydreaming"]),
 mc("Right Effort means…", "growing good states of mind and letting go of harmful ones", ["working overtime", "exercising", "never resting"]),
 mc("The Path is pictured as a…", "wheel with eight spokes", ["ladder", "tree", "mountain"]),
 tf("The Path steps are practiced together.", True),
 tf("Right Livelihood means earning the most money.", False),
 voc("mindfulness", "Paying full attention to the present moment."),
 op("Which step of the Path would help you most at work or home this week? Why?", "Any step with a practical reason."),
]),
("Key teachings", "Enseñanzas clave", [
 mc("Anicca means…", "impermanence", ["not-self", "suffering", "kindness"]),
 mc("Anatta means…", "not-self", ["impermanence", "joy", "rebirth"]),
 mc("Karma in Buddhism is…", "intentional action and its effects", ["fate", "luck", "punishment from a god"]),
 mc("Samsara is…", "the cycle of rebirth", ["enlightenment", "a temple", "a monk"]),
 mc("The Middle Way avoids…", "extremes of indulgence and self-denial", ["all food", "all work", "all people"]),
 mc("Dependent origination says…", "all things arise from causes and conditions", ["all things are random", "one god makes all", "nothing changes"]),
 tf("The Three Marks are impermanence, suffering and not-self.", True),
 tf("Buddhism teaches that nothing ever changes.", False),
 voc("impermanence", "The truth that all things change."),
 op("How could remembering impermanence help in a hard time?", "Hard times also pass; it eases panic and helps patience."),
]),
("The scriptures", "Las escrituras", [
 mc("The Pali Canon is also called the…", "Tipitaka, “three baskets”", ["Vedas", "Analects", "Mishnah"]),
 mc("The Dhammapada is a collection of…", "sayings of the Buddha", ["laws", "maps", "hymns to Agni"]),
 mc("The Jataka tales tell…", "the Buddha’s past lives", ["the history of China", "the life of Krishna", "rules for nuns"]),
 mc("The Heart Sutra is a short…", "Mahayana text on emptiness", ["Theravada law code", "Zen koan collection", "Jataka tale"]),
 mc("The Lotus Sutra teaches that…", "all can become Buddhas", ["only monks are saved", "the world is evil", "there is no path"]),
 mc("The world’s oldest dated printed book is a copy of the…", "Diamond Sutra", ["Bible", "Analects", "Qur’an"]),
 tf("Buddhist texts exist in Pali, Sanskrit, Chinese and Tibetan.", True),
 tf("Buddhism has only one short book.", False),
 voc("sutra", "A Buddhist scripture, often a talk of the Buddha (Pali: sutta)."),
 op("Why might a religion keep its texts in several languages?", "It spread to many lands, and each culture translated and kept the texts in its own language."),
]),
("Schools of Buddhism", "Escuelas del budismo", [
 mc("Theravada is found mostly in…", "Sri Lanka and Southeast Asia", ["Japan", "Tibet", "Korea"]),
 mc("Mahayana is found mostly in…", "East Asia", ["Sri Lanka", "Thailand", "Myanmar"]),
 mc("Vajrayana is linked especially with…", "Tibet", ["Laos", "Cambodia", "Sri Lanka"]),
 mc("Zen stresses…", "meditation and direct insight", ["devotion to Amitabha", "long rituals", "memorizing all texts"]),
 mc("Pure Land stresses…", "faith in Amitabha Buddha", ["koans", "fasting", "silence only"]),
 mc("A bodhisattva is one who…", "works to free all beings", ["rules a country", "only studies", "never meditates"]),
 tf("Different schools share the core teachings of the Buddha.", True),
 tf("Zen is a form of Theravada.", False),
 voc("school", "Here, a branch of a religion with its own way of teaching."),
 op("Which school’s approach sounds most interesting to you, and why?", "Any school with a reason."),
]),
("Meditation", "Meditación", [
 mc("Samatha meditation develops…", "calm and focus", ["wealth", "strength", "speed"]),
 mc("Vipassana meditation develops…", "insight into how things are", ["memory for dates", "sleep", "appetite"]),
 mc("A common first object of meditation is the…", "breath", ["clock", "phone", "radio"]),
 mc("Metta meditation cultivates…", "loving-kindness", ["anger", "competition", "fear"]),
 mc("When the mind wanders, meditators are taught to…", "gently return to the object", ["quit", "scold themselves", "sleep"]),
 mc("Walking meditation means…", "walking slowly and noticing each step", ["running a race", "hiking fast", "walking with music"]),
 tf("Mindfulness programs used in hospitals grew partly from Buddhist practice.", True),
 tf("Meditation requires an empty mind from the first try.", False),
 voc("insight", "Clear understanding from looking closely."),
 op("Try two minutes of breath meditation. What did you notice?", "Any honest noticing."),
]),
("Ethics and precepts", "Ética y preceptos", [
 mc("The Five Precepts include not killing, not stealing and…", "not lying", ["not singing", "not working", "not traveling"]),
 mc("Another Precept is avoiding…", "sexual misconduct", ["all friendship", "sports", "reading"]),
 mc("The fifth Precept is to avoid…", "intoxicants that cloud the mind", ["vegetables", "sleep", "cold water"]),
 mc("Karuna is…", "compassion", ["greed", "pride", "fear"]),
 mc("Dana is…", "generosity", ["debt", "danger", "dance"]),
 mc("Buddhist ethics stresses the role of…", "intention", ["luck", "birth", "wealth"]),
 tf("Many Buddhists practice vegetarianism out of compassion.", True),
 tf("The Precepts are only for monks.", False),
 voc("precept", "A rule for right action."),
 op("Which Precept would be hardest for most people today? Why?", "Any Precept with a reason, e.g., right speech online."),
]),
("Buddhism today", "El budismo hoy", [
 mc("About how many Buddhists are there worldwide?", "about 500 million", ["about 5 million", "about 3 billion", "about 50,000"]),
 mc("The country with the most Buddhists is…", "China", ["Brazil", "India", "Spain"]),
 mc("Thich Nhat Hanh taught “engaged Buddhism,” linking practice to…", "social action and peace", ["business only", "sports", "nothing outside temples"]),
 mc("The 14th Dalai Lama won the Nobel Peace Prize in…", "1989", ["1901", "1945", "2020"]),
 mc("Mindfulness-based stress reduction was developed by…", "Jon Kabat-Zinn", ["Ashoka", "Laozi", "Gandhi"]),
 mc("Buddhist temples in the U.S. serve…", "Asian American communities and converts", ["no one", "only tourists", "only monks"]),
 tf("Buddhist ideas appear in modern psychology.", True),
 tf("Buddhism has no followers outside Asia.", False),
 voc("engaged", "Taking part actively."),
 op("Where have you seen Buddhist ideas in daily life, media or health?", "Mindfulness apps, yoga classes, films, therapy; any honest example."),
]),
("Reading the Dhammapada", "Leer el Dhammapada", [
 mc("Müller’s Dhammapada verse 1 begins: “All that we are is the result of…”", "what we have thought", ["what we have eaten", "what kings decide", "where we were born"]),
 mc("Verse 5 says hatred ceases by…", "love", ["hatred", "revenge", "silence"]),
 mc("The Dhammapada says the greatest victory is over…", "oneself", ["a thousand men", "a king", "a city"]),
 mc("The Dhammapada compares a mind well trained to a house with…", "a good roof that rain cannot get through", ["no doors", "gold walls", "many rooms"]),
 mc("The best-known version of the Dhammapada has come down to us in…", "Pali, the language of the Theravada canon", ["Latin", "Greek", "Arabic"]),
 mc("One line teaches to avoid evil, do good and…", "purify the mind", ["get rich", "win fame", "rule others"]),
 tf("The Dhammapada is short enough to read in an afternoon.", True),
 tf("The Dhammapada praises revenge.", False),
 voc("sayings", "Short memorable teachings."),
 op("Choose a Dhammapada idea and say how it applies to a conflict you have seen.", "“Hatred ceases by love”: answering anger with calm can end a feud; any fit example."),
]),
]
