# Chinese Classics (the Analects and the Daodejing) — Daily Drafts banks. Studied, never preached:
# "Confucius taught…", "The Daodejing says…". Exact quotations only from Legge's translations
# (Analects 1861/1893, Tao Teh King 1891), U.S. public domain; otherwise paraphrase.
def mc(q, a, w): return ["mc", q, a, w]
def tf(q, v): return ["tf", q, v]
def voc(w, d): return ["voc", w, d]
def op(q, m): return ["open", q, m]

BANDS = {}

BANDS['k2'] = [
("Confucius the Teacher", "Confucio el maestro", [
 mc("Confucius lived long ago in…", "China", ["Mexico", "France", "Egypt"]),
 mc("Confucius’s job was being a…", "teacher", ["pirate", "farmer only", "king"]),
 mc("Confucius loved to…", "learn and teach", ["sleep all day", "fight", "hide"]),
 mc("Confucius’s students wrote down his words in a book called the…", "Analects", ["Vedas", "Jatakas", "Dhammapada"]),
 mc("Confucius lived about…", "2,500 years ago", ["25 years ago", "250 years ago", "25,000 years ago"]),
 mc("Confucius taught that good people are…", "kind and fair", ["loud and bossy", "greedy", "lazy"]),
 tf("Confucius was a famous teacher.", True),
 tf("Confucius lived in Spain.", False),
 voc("teacher", "A person who helps others learn."),
 op("What do you like to learn about?", "Any honest answer."),
]),
("Laozi and the Ox", "Laozi y el buey", [
 mc("Laozi is known as a wise man from old…", "China", ["India", "Greece", "Peru"]),
 mc("A story says Laozi left on the back of a…", "water buffalo", ["horse", "camel", "dragon"]),
 mc("At the gate, a guard asked Laozi to…", "write down his wisdom", ["pay money", "turn back", "sing a song"]),
 mc("The book Laozi is said to have written is the…", "Daodejing", ["Analects", "Ramayana", "Dhammapada"]),
 mc("“Dao” means…", "“the Way”", ["“the wall”", "“the war”", "“the wind”"]),
 mc("Laozi liked things that are…", "quiet and simple", ["loud and busy", "fancy", "fast"]),
 tf("Laozi is linked with the Daodejing.", True),
 tf("In the story, Laozi rides away on a dragon.", False),
 voc("wise", "Knowing what is good and true, and using it well."),
 op("Laozi liked simple things. What simple thing makes you happy?", "Any simple thing, such as a walk, a hug or a song."),
]),
("Respect for Family", "Respeto a la familia", [
 mc("Confucius taught children to respect their…", "parents and grandparents", ["toys", "phones", "pets only"]),
 mc("Caring for your parents is called…", "filial piety", ["homework", "recess", "a festival"]),
 mc("Which shows respect to a grandparent?", "listening when they talk", ["walking away", "yelling", "ignoring them"]),
 mc("Confucius taught that a family is like a…", "team that cares for each other", ["race to win", "zoo", "store"]),
 mc("Many Chinese families honor their…", "ancestors", ["neighbors’ cars", "shoes", "clouds"]),
 mc("Ancestors are…", "family members who lived long ago", ["new babies", "friends at school", "teachers"]),
 tf("Confucius taught respect for family.", True),
 tf("Confucius said parents do not matter.", False),
 voc("ancestor", "A family member who lived long ago."),
 op("Name one way you help your family.", "Any helping job, such as setting the table or helping a sibling."),
]),
("Learning Every Day", "Aprender cada día", [
 mc("Confucius said learning is a…", "joy", ["punishment", "waste", "secret"]),
 mc("Confucius said you can learn something from…", "every person you meet", ["no one", "only kings", "only books"]),
 mc("If you do not know something, Confucius said to…", "say you do not know", ["pretend", "hide", "guess and lie"]),
 mc("Confucius said a good student…", "reviews old lessons and learns new ones", ["never practices", "forgets fast", "stops asking"]),
 mc("When you make a mistake, Confucius taught you should…", "fix it", ["hide it", "blame others", "cry forever"]),
 mc("Confucius started learning seriously at age…", "15", ["2", "50", "90"]),
 tf("Confucius loved asking questions.", True),
 tf("Confucius said only rich children can learn.", False),
 voc("practice", "Doing something again and again to get better."),
 op("What is something you got better at by practicing?", "Any skill, such as reading, riding a bike, or drawing."),
]),
("Water Is Soft and Strong", "El agua es suave y fuerte", [
 mc("The Daodejing says the softest thing in the world is…", "water", ["rock", "iron", "fire"]),
 mc("Water can wear away…", "hard rock", ["the sky", "the sun", "nothing"]),
 mc("Water always flows…", "to the low places", ["up the mountain", "into the sky", "nowhere"]),
 mc("The Daodejing says being gentle like water can be…", "strong", ["weak only", "silly", "bad"]),
 mc("Water helps plants, animals and people. It gives without…", "fighting", ["sharing", "moving", "flowing"]),
 mc("A river going around a rock shows being…", "flexible", ["stuck", "angry", "lost"]),
 tf("The Daodejing uses water to teach a lesson.", True),
 tf("The Daodejing says water is the hardest thing.", False),
 voc("gentle", "Soft and kind; not rough."),
 op("How can you be gentle like water with a friend?", "Speak softly, take turns, go around a problem instead of fighting."),
]),
("The Golden Rule of Confucius", "La regla de oro de Confucio", [
 mc("Confucius said: “What you do not want done to yourself, do not do to…”", "others", ["dogs", "trees", "the sky"]),
 mc("If you do not like being pushed, you should…", "not push others", ["push harder", "push first", "push back"]),
 mc("Confucius called this idea…", "reciprocity", ["recess", "a riddle", "a race"]),
 mc("Treating others as you want to be treated makes people feel…", "cared for", ["scared", "left out", "tricked"]),
 mc("Which follows Confucius’s rule?", "sharing because you like when others share", ["taking the biggest cookie", "cutting in line", "grabbing toys"]),
 mc("Many other teachers, like Hillel and Jesus, taught…", "a similar rule", ["the opposite rule", "no rules", "only math"]),
 tf("Confucius taught a golden rule.", True),
 tf("Confucius’s rule says do mean things first.", False),
 voc("fair", "Treating people the right way, the same way."),
 op("Say Confucius’s rule in your own words.", "Do not do to others what you would not want done to you."),
]),
("Good Friends", "Buenos amigos", [
 mc("The Analects begins by saying it is a joy when…", "a friend comes from far away", ["it rains", "a test ends", "you win a game"]),
 mc("Confucius said good friends are…", "honest", ["always agreeing", "rich", "loud"]),
 mc("A good friend tells you the…", "truth, kindly", ["lies you want", "nothing", "gossip"]),
 mc("A good friend helps you become…", "better", ["meaner", "lazier", "sadder"]),
 mc("Confucius said to be a good friend, you must…", "keep your word", ["forget promises", "brag", "take things"]),
 mc("When a friend is sad, a good friend…", "listens", ["laughs", "walks away", "teases"]),
 tf("Confucius said friendship brings joy.", True),
 tf("Confucius said friends should lie to each other.", False),
 voc("trust", "Believing someone will be honest and do what they say."),
 op("What makes someone a good friend?", "Honesty, kindness, listening, keeping promises, or any fair answer."),
]),
("Being Honest", "Ser honesto", [
 mc("Confucius taught that a good person’s words and actions…", "match", ["never match", "are secret", "change every day"]),
 mc("Keeping a promise shows you are…", "trustworthy", ["sneaky", "lazy", "sleepy"]),
 mc("Confucius said he watches not only what people say but…", "what they do", ["what they eat", "what they wear", "what they buy"]),
 mc("If you broke a cup, the honest thing to say is…", "“I broke it. I am sorry.”", ["“The cat did it.”", "“It was already broken.”", "nothing"]),
 mc("Being honest helps people…", "trust you", ["fear you", "forget you", "avoid you"]),
 mc("Confucius said a good person is slow to speak and…", "quick to act", ["quick to brag", "slow to help", "never acts"]),
 tf("Confucius thought honesty was important.", True),
 tf("Confucius said it is fine to break promises.", False),
 voc("promise", "Saying you will surely do something."),
 op("Tell about a promise you kept.", "Any honest example."),
]),
("Yin and Yang", "Yin y yang", [
 mc("The yin-yang symbol is a circle with…", "black and white parts", ["only red", "stars", "squares"]),
 mc("Yin and yang show that opposites…", "go together", ["never meet", "fight forever", "are the same"]),
 mc("Which pair is like yin and yang?", "day and night", ["cat and cat", "red and red", "one and one"]),
 mc("In the symbol, each half has a small dot of the…", "other color", ["same color", "color green", "color gold"]),
 mc("Yin is often linked with…", "quiet, dark and cool", ["loud and hot", "fast and bright", "sharp and hard"]),
 mc("Yang is often linked with…", "active, bright and warm", ["cold and dark", "still and wet", "sleepy"]),
 tf("Yin and yang need each other.", True),
 tf("Yin and yang mean only good and bad.", False),
 voc("opposite", "As different as can be, like up and down."),
 op("Name two opposites that go together in your day.", "Work and play, day and night, awake and asleep; any pair."),
]),
("The Butterfly Dream", "El sueño de la mariposa", [
 mc("Zhuangzi was a wise man who told…", "funny, puzzling stories", ["only laws", "recipes", "war plans"]),
 mc("Zhuangzi dreamed he was a…", "butterfly", ["dragon", "tiger", "fish"]),
 mc("When he woke up, he wondered if he was a butterfly…", "dreaming he was a man", ["eating a flower", "flying home", "lost"]),
 mc("In another story, Zhuangzi watches fish and says they are…", "happy", ["angry", "sleepy", "cold"]),
 mc("Zhuangzi’s stories make us…", "wonder and think", ["fall asleep", "feel scared", "stop thinking"]),
 mc("Zhuangzi followed the ideas of…", "Laozi", ["Hanuman", "the Buddha", "Rama"]),
 tf("Zhuangzi’s butterfly story is a puzzle to think about.", True),
 tf("Zhuangzi dreamed he was a lion.", False),
 voc("dream", "Pictures and stories in your mind while you sleep."),
 op("If you dreamed you were an animal, what would you be? Why?", "Any animal and reason."),
]),
]

BANDS['35'] = [
("Who Was Confucius?", "¿Quién fue Confucio?", [
 mc("Confucius was born in the state of Lu in…", "551 BCE", ["551 CE", "1551 CE", "51 BCE"]),
 mc("Confucius’s Chinese name, Kongzi, means…", "Master Kong", ["Great King", "Old Dragon", "River Man"]),
 mc("Confucius grew up…", "poor, and his father died when he was young", ["as a prince", "in a palace", "on a ship"]),
 mc("Confucius worked for a time as a…", "government official", ["pirate", "soldier only", "painter"]),
 mc("Confucius traveled from state to state hoping rulers would…", "govern with goodness", ["give him gold", "start wars", "build walls"]),
 mc("Confucius had many students; tradition says about…", "3,000", ["3", "30", "3 million"]),
 tf("Confucius believed anyone willing to learn could be taught.", True),
 tf("Confucius was an emperor.", False),
 voc("official", "A person who works in a government job."),
 op("Confucius taught anyone who wanted to learn, rich or poor. Why does that matter?", "Learning should be open to all; talent is everywhere."),
]),
("The Analects", "Las Analectas", [
 mc("The Analects was put together by…", "Confucius’s students and their students", ["Confucius alone", "an emperor", "Laozi"]),
 mc("Most passages in the Analects are…", "short sayings and conversations", ["long stories", "songs", "maps"]),
 mc("Many passages begin: “The Master said…” The Master is…", "Confucius", ["Laozi", "a king", "a student"]),
 mc("The Analects has how many books (chapters)?", "20", ["2", "200", "7"]),
 mc("In Legge’s translation, the first line asks: “Is it not pleasant to learn with a constant…”", "perseverance and application?", ["friend at your side?", "bowl of rice?", "rest after?"]),
 mc("The Analects has been studied in China for over…", "2,000 years", ["20 years", "200 years", "20,000 years"]),
 tf("The Analects is a collection, not a story.", True),
 tf("Confucius wrote every word of the Analects himself.", False),
 voc("saying", "A short, wise sentence people remember."),
 op("Why might students write down their teacher’s words?", "To remember them, share them and keep the teaching after the teacher is gone."),
]),
("Family and Respect", "Familia y respeto", [
 mc("Xiao, or filial piety, means…", "respect and care for parents", ["respect for rulers only", "love of animals", "a harvest festival"]),
 mc("Confucius said serving parents is not only feeding them but also…", "treating them with respect", ["buying them gifts", "leaving home", "ignoring them"]),
 mc("Confucius taught five key relationships. One is…", "parent and child", ["cat and mouse", "teacher and toy", "sun and moon"]),
 mc("Another of the five relationships is…", "friend and friend", ["rock and rock", "tree and river", "car and road"]),
 mc("In the five relationships, older and younger should…", "each do their part", ["never talk", "switch roles daily", "compete"]),
 mc("During Qingming, many Chinese families…", "clean and visit ancestors’ graves", ["fly to the moon", "fast for a month", "build boats"]),
 tf("Confucius thought a good family helps make a good country.", True),
 tf("Filial piety means obeying only your friends.", False),
 voc("relationship", "How two people are connected."),
 op("Name one way you show respect to an older family member.", "Any honest example."),
]),
("Ren: Kindness", "Ren: bondad", [
 mc("Ren is the Confucian virtue of…", "humaneness or goodness to others", ["speed", "wealth", "anger"]),
 mc("When asked what ren is, Confucius said it is to…", "love others", ["rule others", "fear others", "beat others"]),
 mc("A person with ren is…", "caring and fair", ["greedy", "cruel", "lazy"]),
 mc("Confucius said ren is…", "close at hand, if you want it", ["impossible", "only for kings", "only for old people"]),
 mc("Which act shows ren?", "helping a new student find their class", ["laughing at a mistake", "cutting in line", "taking the last seat unfairly"]),
 mc("Confucius’s golden rule goes with ren: do not do to others…", "what you do not want done to you", ["anything at all", "only nice words", "what they did to you"]),
 tf("Ren is about how we treat other people.", True),
 tf("Ren means winning at any cost.", False),
 voc("humane", "Kind and caring toward people."),
 op("Give an example of ren you saw this week.", "Any real act of kindness."),
]),
("Li: Good Manners and Ritual", "Li: buenos modales y ritual", [
 mc("Li means proper…", "manners and ritual", ["food", "weather", "money"]),
 mc("Confucius said: look at nothing, listen to nothing, say nothing and do nothing that is…", "against li (what is proper)", ["kind", "true", "quiet"]),
 mc("Bowing to a teacher is an example of…", "li", ["yin", "dao", "wu wei"]),
 mc("Confucius thought good manners help people…", "live together in peace", ["get rich", "win fights", "stay alone"]),
 mc("Confucius said ritual without a kind heart is…", "empty", ["perfect", "enough", "fun"]),
 mc("Which is an example of li at a meal?", "waiting for elders to begin eating", ["grabbing food first", "leaving early", "shouting"]),
 tf("Li includes both ceremonies and everyday manners.", True),
 tf("Confucius said manners do not matter.", False),
 voc("ritual", "A set way of doing something with special meaning."),
 op("What is one good-manners ritual in your family or school?", "Saying please and thank you, shaking hands, a greeting; any example."),
]),
("Who Was Laozi?", "¿Quién fue Laozi?", [
 mc("“Laozi” means…", "“Old Master”", ["“Young King”", "“Great River”", "“Strong Arm”"]),
 mc("Tradition says Laozi kept records at the court of the…", "Zhou kings", ["Roman emperors", "Indian rajas", "Egyptian pharaohs"]),
 mc("A story says Confucius once visited Laozi and compared him to a…", "dragon", ["mouse", "rock", "tree"]),
 mc("Laozi is said to have left China through a mountain…", "pass, where a guard asked him to write", ["tunnel", "sea port", "cave city"]),
 mc("Many historians say we know…", "very little for sure about Laozi’s life", ["everything about Laozi", "Laozi’s birthday exactly", "Laozi wrote the Analects"]),
 mc("Laozi is seen as the founder of…", "Daoism", ["Confucianism", "Buddhism", "Hinduism"]),
 tf("Laozi’s life is surrounded by legends.", True),
 tf("Laozi and Confucius are the same person.", False),
 voc("legend", "An old story that may be partly true."),
 op("Why might a teacher’s life become full of legends?", "People admired him, retold stories, and filled in gaps over time."),
]),
("The Daodejing", "El Daodejing", [
 mc("The Daodejing has how many short chapters?", "81", ["8", "18", "810"]),
 mc("“Daodejing” means about…", "“The Classic of the Way and Its Power”", ["“The Book of War”", "“The Song of the River”", "“The Rules of Kings”"]),
 mc("James Legge’s 1891 translation calls it the…", "Tao Teh King", ["Song Celestial", "Light of Asia", "Great Learning"]),
 mc("The Daodejing is written in…", "short poems", ["long stories", "letters", "lists of kings"]),
 mc("In Legge’s translation, Chapter 64 says: “The journey of a thousand li commences with…”", "a single step", ["a map", "a horse", "a friend"]),
 mc("A “li” is a Chinese unit of…", "distance", ["money", "weight", "time"]),
 tf("The Daodejing is one of the most translated books in the world.", True),
 tf("The Daodejing is a long novel.", False),
 voc("classic", "An old book people still read and honor."),
 op("“The journey of a thousand li commences with a single step.” What big task could you start with one small step?", "Any task broken into a first step, like reading one page."),
]),
("Yin and Yang", "Yin y yang", [
 mc("The yin-yang symbol is called the…", "taijitu", ["mandala", "stupa", "diya"]),
 mc("Yin and yang are…", "opposite forces that complete each other", ["two gods at war", "two kings", "two rivers"]),
 mc("Which is yin?", "the moon and shade", ["the sun and fire", "summer noon", "a shout"]),
 mc("Which is yang?", "the sun and heat", ["the moon", "winter night", "stillness"]),
 mc("The small dots in the symbol show that…", "each side holds a bit of the other", ["there are four sides", "it is broken", "it is a target"]),
 mc("The seasons show yin and yang because…", "summer turns into winter and back again", ["seasons never change", "it is always summer", "winter lasts forever"]),
 tf("In Daoist thought, balance between yin and yang is healthy.", True),
 tf("Yin is good and yang is evil.", False),
 voc("balance", "When different parts are even and steady."),
 op("How can you keep balance between work and rest?", "Take breaks, sleep well, plan play and study times; any honest answer."),
]),
("Zhuangzi’s Stories", "Los cuentos de Zhuangzi", [
 mc("Zhuangzi lived about 200 years after…", "Laozi was said to live", ["the Buddha’s grandsons", "Rome fell", "the pyramids"]),
 mc("In “The Butterfly Dream,” Zhuangzi could not tell if he was a man or a butterfly. This asks…", "what is real", ["what to eat", "who is king", "where to sleep"]),
 mc("In “Cook Ding,” a cook carves an ox so skillfully that…", "his knife stays sharp for 19 years", ["he loses the ox", "he cuts himself", "it takes a year"]),
 mc("Cook Ding succeeds by…", "following the natural lines of the ox", ["chopping hard", "buying many knives", "working fast"]),
 mc("In “The Useless Tree,” a crooked tree lives long because…", "no one wants to cut it down", ["it is the tallest", "it has gold", "a king guards it"]),
 mc("Zhuangzi’s stories are often…", "funny and surprising", ["dull and plain", "angry", "only about war"]),
 tf("Zhuangzi uses stories to teach about the Dao.", True),
 tf("In Cook Ding’s story, the cook hacks wildly at the ox.", False),
 voc("skill", "The ability to do something well."),
 op("The “useless” tree lived long. Can something that looks useless be valuable? Give an example.", "Yes, like a quiet park, a rest day, or play; any reasoned example."),
]),
("Books of Ancient China", "Libros de la antigua China", [
 mc("Early Chinese books were written on…", "strips of bamboo tied together", ["paper from stores", "glass", "metal plates only"]),
 mc("Paper was invented in China around…", "105 CE", ["1500 CE", "3000 BCE", "1900 CE"]),
 mc("Chinese writing uses…", "characters", ["an alphabet of 26 letters", "only pictures of animals", "numbers only"]),
 mc("Chinese writing is often done with a…", "brush and ink", ["crayon", "pen and pencil only", "spray can"]),
 mc("The Qin emperor ordered many books…", "burned", ["printed", "translated", "hidden in caves"]),
 mc("Chinese is read, in old books, from…", "top to bottom, right to left", ["bottom to top", "left to right only", "in circles"]),
 tf("Calligraphy, beautiful writing, is an art in China.", True),
 tf("The first Chinese books were printed on computers.", False),
 voc("calligraphy", "The art of beautiful writing."),
 op("Why might bamboo books be hard to carry and keep?", "They were heavy and bulky; cords broke and strips fell out of order."),
]),
]

BANDS['68'] = [
("China in Confucius’s Time", "China en tiempos de Confucio", [
 mc("Confucius lived during the…", "Spring and Autumn period", ["Tang dynasty", "Ming dynasty", "Qing dynasty"]),
 mc("By Confucius’s time, the power of the Zhou kings had…", "weakened, and local states competed", ["grown stronger", "spread to India", "ended in peace"]),
 mc("The Zhou kings claimed to rule by the…", "Mandate of Heaven", ["Silk Road", "Great Wall", "Five Pillars"]),
 mc("The Mandate of Heaven meant a ruler could lose power if he…", "ruled badly", ["grew old", "had no son", "lost a game"]),
 mc("After Confucius came the violent Warring States period, which ended when China was unified by the…", "Qin", ["Han", "Song", "Tang"]),
 mc("Confucius wanted to return to the ways of the early…", "Zhou", ["Qin", "Mongols", "Romans"]),
 tf("Confucius taught during a time of disorder.", True),
 tf("Confucius lived during the Ming dynasty.", False),
 voc("dynasty", "A line of rulers from one family."),
 op("Why might a teacher in a time of chaos focus on family, manners and good government?", "Order starts close to home; good habits and honest leaders could bring back peace."),
]),
("The Analects", "Las Analectas", [
 mc("Confucius’s best-loved student, who died young, was…", "Yan Hui", ["Mencius", "Laozi", "Zhuangzi"]),
 mc("The bold, brave student often scolded in the Analects is…", "Zilu", ["Yan Hui", "Xunzi", "Han Feizi"]),
 mc("In Analects 2.4, Confucius traces his life: at fifteen he set his heart on…", "learning", ["war", "wealth", "travel"]),
 mc("At seventy, he says, he could follow his heart’s desire…", "without going against what is right", ["and become rich", "and become king", "and leave China"]),
 mc("Legge’s Analects 15.23 names one word to guide a whole life:", "reciprocity", ["obedience", "victory", "silence"]),
 mc("Confucius said: “Learning without thought is labour lost; thought without learning is…”", "perilous", ["easy", "fun", "useless"]),
 tf("The Analects shows Confucius as a real teacher with favorite students and frustrations.", True),
 tf("The Analects is arranged as one long story in time order.", False),
 voc("disciple", "A student who follows a teacher."),
 op("Explain “Learning without thought is labour lost; thought without learning is perilous.”", "Facts need reflection to mean anything; ideas without knowledge can lead you wrong. You need both."),
]),
("Ren, Li, Xiao and the Junzi", "Ren, li, xiao y el junzi", [
 mc("The junzi is…", "the noble or exemplary person", ["a court musician", "a type of rice", "a war general"]),
 mc("The opposite of the junzi in the Analects is the…", "petty person (xiaoren)", ["emperor", "farmer", "monk"]),
 mc("Confucius said the junzi seeks what is right; the petty person seeks…", "profit", ["wisdom", "friends", "rest"]),
 mc("Ren is best translated…", "humaneness", ["ritual", "obedience", "courage"]),
 mc("Li is best translated…", "ritual propriety", ["goodness", "wisdom", "loyalty"]),
 mc("Xiao, the root of ren according to the Analects, is…", "filial piety", ["courage", "music", "trade"]),
 tf("For Confucius, being a junzi depends on character, not birth.", True),
 tf("Junzi means a person of noble birth only, in Confucius’s teaching.", False),
 voc("virtue", "A strong good quality of character."),
 op("Describe a junzi in modern life. What would they do in a group project?", "Do their share, be honest, help others, put the goal above credit."),
]),
("Governing by Virtue", "Gobernar con virtud", [
 mc("Confucius said a ruler who governs by virtue is like the…", "North Star, which stays in place while all stars turn around it", ["sun that burns", "storm that scares", "river that floods"]),
 mc("Confucius said leading people with laws and punishments makes them…", "avoid punishment but feel no shame", ["good forever", "happy", "wise"]),
 mc("Leading with virtue and ritual, Confucius said, gives people…", "a sense of shame and a desire to be good", ["fear only", "nothing", "wealth"]),
 mc("“Rectifying names” means…", "making words match reality, so a ruler truly acts as a ruler", ["changing everyone’s name", "writing new books", "spelling well"]),
 mc("Confucius compared a ruler’s virtue to the wind and the people to…", "grass that bends", ["stone that stays", "fire that burns", "water that freezes"]),
 mc("Confucius said a ruler needs food, weapons and the people’s trust. The most important is…", "trust", ["weapons", "food", "gold"]),
 tf("Confucius believed leaders teach most by example.", True),
 tf("Confucius taught that harsh punishment is the best way to rule.", False),
 voc("example", "A model for others to copy."),
 op("Confucius said trust matters more than food or weapons. Do you agree? Why?", "Any reasoned view; without trust, a state cannot hold together."),
]),
("Mencius and Xunzi", "Mencio y Xunzi", [
 mc("Mencius taught that human nature is…", "good", ["evil", "empty", "random"]),
 mc("Mencius’s example: anyone who sees a child about to fall into a well feels…", "alarm and compassion", ["nothing", "anger", "joy"]),
 mc("Xunzi taught that human nature is…", "bad, and goodness comes from training", ["good", "divine", "fixed"]),
 mc("Xunzi compared shaping people to…", "straightening wood or sharpening metal", ["planting flowers", "letting rivers run", "watching stars"]),
 mc("Mencius’s mother is famous for…", "moving house three times to find a good place to raise him", ["being an empress", "writing the Analects", "teaching Laozi"]),
 mc("Mencius said people have the right to…", "overthrow a cruel ruler", ["never question rulers", "skip school", "take land"]),
 tf("Mencius and Xunzi both followed Confucius but disagreed about human nature.", True),
 tf("Xunzi believed people are born perfectly good.", False),
 voc("human nature", "What people are like at birth, before training."),
 op("Is human nature good, like Mencius said, or does it need shaping, like Xunzi said? Give a reason.", "Any reasoned position with an example."),
]),
("The Daodejing", "El Daodejing", [
 mc("Legge’s Chapter 1 begins: “The Tao that can be trodden is not the enduring and unchanging…”", "Tao", ["name", "king", "river"]),
 mc("The first line suggests the Dao is…", "beyond words", ["easy to define", "a road in China", "a king’s law"]),
 mc("The Daodejing is often said to be addressed especially to…", "rulers", ["farmers only", "children only", "soldiers only"]),
 mc("The Daodejing praises water because it…", "benefits all things and does not compete", ["is hard", "is loud", "flows uphill"]),
 mc("The Daodejing says the best rulers are those the people…", "barely know exist", ["fear", "praise loudly", "never obey"]),
 mc("The Daodejing values being like an uncarved block, meaning…", "simple and natural", ["heavy", "useless", "rich"]),
 tf("The Daodejing uses paradox, saying things that seem opposite.", True),
 tf("The Daodejing praises rulers who control every detail.", False),
 voc("paradox", "A statement that seems to contradict itself but may be true."),
 op("Why might a book say the true Dao cannot be put into words and then use 5,000 words about it?", "Words can point toward what they cannot hold; it is a playful, humble way to teach."),
]),
("Dao, De and Wu Wei", "Dao, de y wu wei", [
 mc("De means…", "virtue or inner power", ["war", "ritual", "family"]),
 mc("Wu wei is often translated…", "effortless action or non-forcing", ["hard work", "loud action", "fast action"]),
 mc("Wu wei does not mean doing nothing. It means…", "acting in harmony without forcing", ["sleeping all day", "giving up", "quitting school"]),
 mc("An example of wu wei is…", "a swimmer moving with the current", ["pushing a boulder uphill", "shouting at a tree", "fighting the wind"]),
 mc("Ziran, a Daoist ideal, means…", "naturalness, being so of itself", ["wealth", "courage", "ritual"]),
 mc("The Daodejing says that when people stop grasping…", "things settle into order", ["everything collapses", "wars begin", "rivers dry"]),
 tf("Daoists admire the natural world as a model.", True),
 tf("Wu wei means being lazy.", False),
 voc("harmony", "Things fitting and working well together."),
 op("Describe a time when trying too hard made something worse, and easing off helped.", "Any honest example, like falling asleep or learning a skill."),
]),
("Zhuangzi", "Zhuangzi", [
 mc("The book Zhuangzi is known for its…", "humor, fables and wordplay", ["laws", "battle plans", "tax records"]),
 mc("In the Butterfly Dream, the point is that…", "the line between dream and waking is uncertain", ["butterflies dream", "sleep is bad", "Zhuangzi was ill"]),
 mc("In “The Joy of Fish,” a friend asks Zhuangzi how he can know fish are happy, since he is…", "not a fish", ["asleep", "a king", "hungry"]),
 mc("Cook Ding teaches a king about…", "nourishing life by moving with the natural way", ["cooking fancy food", "war", "taxes"]),
 mc("When his wife died, Zhuangzi was found…", "drumming and singing, seeing death as part of nature", ["weeping forever", "building a tomb of gold", "fleeing"]),
 mc("Zhuangzi turned down a job as a high official, saying he would rather be…", "a turtle dragging its tail in the mud", ["a sacred turtle in a box", "a king", "a general"]),
 tf("Zhuangzi uses humor to question fixed ideas.", True),
 tf("Zhuangzi took the high official job at once.", False),
 voc("perspective", "A point of view; how things look from one place."),
 op("How does the fish story show that people see things from different perspectives?", "Each speaker judges from his own place; it asks how anyone knows another’s mind."),
]),
("The Four Books and Five Classics", "Los Cuatro Libros y los Cinco Clásicos", [
 mc("The Four Books are the Analects, the Mencius, the Great Learning and the…", "Doctrine of the Mean", ["Daodejing", "Book of Rites", "Zhuangzi"]),
 mc("The Five Classics include the Book of Songs, the Book of Documents, the Book of Rites, the Spring and Autumn Annals and the…", "Book of Changes (Yijing)", ["Analects", "Daodejing", "Art of War"]),
 mc("The Yijing (I Ching) uses 64 figures called…", "hexagrams", ["mandalas", "suras", "koans"]),
 mc("A hexagram is made of six…", "solid or broken lines", ["circles", "stars", "colors"]),
 mc("The Book of Songs contains about 300…", "poems", ["laws", "maps", "letters"]),
 mc("The Great Learning links a peaceful world to…", "cultivating oneself, then family, then state", ["building walls", "winning wars", "trading silk"]),
 tf("The Daodejing is not one of the Confucian Four Books.", True),
 tf("The Four Books include the Daodejing.", False),
 voc("classics", "Old books a culture honors and keeps studying."),
 op("The Great Learning says order spreads from self to family to country. Is that a good plan? Why?", "Any reasoned view; good leaders start with their own character."),
]),
("The Classics in Chinese History", "Los clásicos en la historia china", [
 mc("Confucianism became the official state teaching under the…", "Han dynasty", ["Qin dynasty", "Mongol Yuan only", "People’s Republic"]),
 mc("China’s civil service exams tested knowledge of…", "the Confucian classics", ["math only", "Buddhist sutras", "horse riding"]),
 mc("The civil service exams were ended in…", "1905", ["1066", "1492", "2005"]),
 mc("Qin Shi Huang, the first emperor, followed Legalism, which stressed…", "strict laws and harsh punishment", ["kindness and ritual", "wu wei", "meditation"]),
 mc("Daoism also became an organized religion with…", "temples, priests and rituals", ["no followers", "one book only", "no practices"]),
 mc("Confucian ideas spread to…", "Korea, Japan and Vietnam", ["Brazil", "Norway", "Kenya"]),
 tf("For centuries, a person could rise in Chinese government by passing exams.", True),
 tf("The first emperor made Confucianism the state teaching.", False),
 voc("civil service", "Government jobs filled by people chosen for skill."),
 op("Choosing officials by exam instead of birth: what are the strengths and weaknesses?", "Strength: talent over family; weakness: tests memorization, favors those who can afford study."),
]),
]

BANDS['912'] = [
("Text and Transmission", "Texto y transmisión", [
 mc("Scholars think the Analects was compiled…", "over several generations after Confucius’s death", ["by Confucius in one year", "in 1900 CE", "by Laozi"]),
 mc("The oldest known Daodejing manuscripts were found at…", "Guodian and Mawangdui", ["Pompeii", "Qumran", "Nalanda"]),
 mc("The Mawangdui silk texts place the…", "De section before the Dao section", ["Analects before the Daodejing", "Zhuangzi first", "Dao section only"]),
 mc("The Qin “burning of the books” in 213 BCE targeted…", "texts that challenged the state, including many Confucian works", ["only Buddhist sutras", "only maps", "nothing"]),
 mc("Zhu Xi (12th century) made the Four Books the core of…", "the exam curriculum", ["Buddhist schools", "the army", "Daoist temples"]),
 mc("James Legge translated the Chinese Classics while working as a…", "missionary and later an Oxford professor", ["soldier", "merchant", "emperor’s cook"]),
 tf("Different manuscripts of the Daodejing show variations in wording and order.", True),
 tf("Scholars agree Laozi wrote the Daodejing in one sitting.", False),
 voc("manuscript", "A text written by hand."),
 op("Why does finding older manuscripts matter for reading a classic?", "They show how the text changed, test later versions and help separate original wording from additions."),
]),
("Close Reading the Analects", "Lectura atenta de las Analectas", [
 mc("Analects 1.1 moves from learning, to friends from afar, to…", "not being upset when others do not recognize you", ["winning office", "getting rich", "ruling a state"]),
 mc("The structure of 1.1 suggests a junzi’s joy comes from…", "inner growth, not outside praise", ["fame", "wealth", "power"]),
 mc("In Analects 2.17, Confucius tells Zilu that real knowledge is…", "knowing what you know and knowing what you do not know", ["knowing everything", "never asking", "memorizing"]),
 mc("In Analects 7.8, Confucius says he does not teach one who is not…", "eager", ["rich", "noble", "old"]),
 mc("When asked about serving spirits, Confucius replied that one should first learn to…", "serve people", ["pray more", "build temples", "fast"]),
 mc("Analects 12.1 defines ren as…", "overcoming the self and returning to ritual propriety", ["ruling by force", "loving wealth", "leaving society"]),
 tf("The Analects often shows Confucius adjusting his answer to the student asking.", True),
 tf("Confucius focuses mainly on the afterlife in the Analects.", False),
 voc("propriety", "Behaving in the fitting, right way."),
 op("Why might Confucius give different answers to the same question from different students?", "He teaches the person, not only the idea; a bold student needs caution, a timid one needs courage."),
]),
("Self-Cultivation", "El cultivo de sí mismo", [
 mc("Zengzi says he examines himself daily on three points, including whether he has been…", "faithful to friends", ["rich", "famous", "strong"]),
 mc("Confucius said when you see a worthy person, you should…", "think of becoming equal to them", ["envy them", "avoid them", "mock them"]),
 mc("When you see an unworthy person, Confucius said, you should…", "look inward and examine yourself", ["laugh", "punish them", "ignore it"]),
 mc("The Doctrine of the Mean teaches…", "balance and harmony in feeling and action", ["extremes", "wealth", "war"]),
 mc("The Great Learning says the root of order in the world is…", "cultivating the self", ["a strong army", "trade", "luck"]),
 mc("Confucius said the junzi is not a “vessel,” meaning…", "not limited to one narrow use", ["not useful", "not wealthy", "not strong"]),
 tf("Confucian self-cultivation is a lifelong process.", True),
 tf("Confucius taught that character is fixed at birth.", False),
 voc("cultivate", "To grow and develop with care over time."),
 op("Zengzi reviews his day with three questions. Write three questions you could use.", "Any three reflective questions, e.g., Was I honest? Did I help? Did I learn?"),
]),
("Rectifying Names and Rule", "Rectificar los nombres y gobernar", [
 mc("In Analects 13.3, Confucius says if names are not correct…", "language will not match reality, and affairs will fail", ["poems will rhyme", "nothing happens", "rulers grow wiser"]),
 mc("“Let the ruler be a ruler, the minister a minister, the father a father, the son a son” means…", "each person should fulfill the duties of their role", ["everyone swaps roles", "only rulers matter", "names should change"]),
 mc("A modern example of an “incorrect name” would be…", "calling a harmful policy “protection”", ["spelling a word wrong", "a nickname", "a new song"]),
 mc("Mencius argued a cruel king who loses the Mandate…", "is no longer truly a king but a mere “fellow”", ["must be obeyed", "becomes a god", "rules forever"]),
 mc("Confucian government by virtue contrasts with Legalism’s reliance on…", "laws and punishments", ["ritual", "music", "poetry"]),
 mc("Han Feizi, the Legalist, thought rulers should rely on…", "clear laws, rewards and punishments", ["virtue alone", "wu wei alone", "Buddhist monks"]),
 tf("Rectifying names links honest language to good government.", True),
 tf("Mencius said subjects must obey even a cruel king.", False),
 voc("legitimacy", "The right to rule, accepted by the people."),
 op("Give a modern example where a name hides the truth, and explain why Confucius would object.", "Any example of euphemism or spin; when words stop matching facts, trust and right action fail."),
]),
("Human Nature Debate", "El debate sobre la naturaleza humana", [
 mc("Mencius named four “sprouts” of goodness: compassion, shame, deference and…", "the sense of right and wrong", ["greed", "fear", "anger"]),
 mc("The sprouts, Mencius said, must be…", "nourished, like plants", ["cut off", "ignored", "hidden"]),
 mc("Mencius told of a farmer from Song who helped his crops by…", "pulling on them, and killed them", ["watering them", "singing to them", "fencing them"]),
 mc("The farmer’s story warns against…", "forcing growth", ["farming", "patience", "study"]),
 mc("Xunzi said goodness comes from…", "deliberate effort, teachers and ritual", ["nature alone", "luck", "heaven’s gift"]),
 mc("Xunzi’s famous essay argues that human nature is…", "bad", ["good", "neutral", "divine"]),
 tf("Both Mencius and Xunzi believed education matters.", True),
 tf("Mencius said goodness grows best if you pull on it hard.", False),
 voc("innate", "Present from birth."),
 op("Use the farmer of Song to explain Mencius’s view of moral growth. Then give Xunzi’s reply.", "Goodness grows naturally if nourished, not forced; Xunzi replies that without teachers and ritual people follow selfish desire."),
]),
("Close Reading the Daodejing", "Lectura atenta del Daodejing", [
 mc("Legge’s Chapter 1 continues: “The name that can be named is not the enduring and unchanging…”", "name", ["Tao", "king", "path"]),
 mc("Chapter 11 says the usefulness of a cup or wheel comes from its…", "empty space", ["solid sides", "color", "maker"]),
 mc("Chapter 8 says the highest excellence is like…", "water", ["iron", "fire", "a mountain"]),
 mc("Chapter 2 argues that when everyone knows beauty as beauty…", "ugliness appears, since opposites define each other", ["all is beautiful", "art ends", "rulers win"]),
 mc("Chapter 80 imagines an ideal…", "small, simple village content with its life", ["great empire", "busy port", "army camp"]),
 mc("Chapter 76 says the stiff and hard belong to death, while the soft and weak belong to…", "life", ["kings", "stone", "war"]),
 tf("The Daodejing often reverses common values: softness over hardness, emptiness over fullness.", True),
 tf("Chapter 11 says usefulness comes only from what is solid.", False),
 voc("reversal", "Turning a usual idea upside down."),
 op("Explain Chapter 11’s claim that emptiness is useful. Give one example of your own.", "A cup holds because it is hollow; a room serves because of open space; e.g., free time makes room for ideas."),
]),
("Paradox and Wu Wei", "Paradoja y wu wei", [
 mc("The Daodejing says the sage…", "acts without striving, and so nothing is left undone", ["strives and wins", "does nothing at all", "rules by force"]),
 mc("“Governing a large state is like cooking a small fish” means…", "handle it gently and do not over-stir", ["use high heat", "eat it quickly", "cut it into pieces"]),
 mc("The Daodejing says the more laws and orders are made…", "the more thieves and robbers there will be", ["the fewer crimes", "the richer the land", "the happier people are"]),
 mc("The Daodejing warns against weapons, calling them…", "instruments of evil omen", ["tools of glory", "gifts of heaven", "signs of virtue"]),
 mc("The sage puts himself last and so…", "finds himself first", ["is forgotten", "loses all", "is punished"]),
 mc("A modern leader using wu wei might…", "set clear aims and trust the team rather than micromanage", ["control every task", "give no aims at all", "punish every mistake"]),
 tf("Wu wei is compatible with effective action.", True),
 tf("The Daodejing praises many strict laws.", False),
 voc("micromanage", "To control every small detail of others’ work."),
 op("Compare the Daodejing’s view of government with Confucius’s. Where do they agree and differ?", "Both prefer virtue to force; Confucius stresses ritual and roles, the Daodejing less interference and naturalness."),
]),
("Zhuangzi and Perspective", "Zhuangzi y la perspectiva", [
 mc("Zhuangzi’s opening story tells of a giant bird, Peng, mocked by…", "a small quail and a cicada", ["a dragon", "a king", "a fox"]),
 mc("The small creatures mocking Peng show that…", "small views cannot grasp large ones", ["small is always wiser", "birds cannot fly", "the story is false"]),
 mc("In “Three in the Morning,” monkeys are angry at three nuts in the morning and four at night but happy with four and three. This shows…", "people react to labels, not substance", ["monkeys can count", "nuts are rare", "the keeper was cruel"]),
 mc("Zhuangzi’s view is often called…", "perspectivism or relativism", ["legalism", "materialism", "militarism"]),
 mc("The Zhuangzi’s “Inner Chapters” are the first…", "seven chapters, often held closest to Zhuangzi himself", ["seventy chapters", "two chapters", "Analects"]),
 mc("Zhuangzi pokes fun at Confucians for…", "rigid rules and rituals", ["being too kind", "loving nature", "avoiding office"]),
 tf("Zhuangzi uses humor as a way to do philosophy.", True),
 tf("In “Three in the Morning,” the monkeys get more food in total.", False),
 voc("relativism", "The view that truth or value depends on the point of view."),
 op("Explain “Three in the Morning” and apply it to something in school or news.", "Same total, different framing; e.g., a “sale” that is the same price, or two schedules with equal work."),
]),
("Neo-Confucianism and the Exams", "Neoconfucianismo y los exámenes", [
 mc("Neo-Confucianism, led by Zhu Xi, blended Confucian ethics with ideas like…", "principle (li) and vital energy (qi)", ["wu wei only", "Legalism", "Greek logic"]),
 mc("Neo-Confucianism responded partly to the influence of…", "Buddhism and Daoism", ["Christianity", "Islam", "Norse myth"]),
 mc("Wang Yangming taught the unity of…", "knowledge and action", ["king and god", "sea and land", "yin and war"]),
 mc("The civil exams under the Ming required the “eight-legged essay,” a…", "strict formal essay on the classics", ["poem about nature", "math test", "sports event"]),
 mc("Critics of the exam system said it…", "rewarded memorization over fresh thought", ["was too easy", "had no rules", "tested only women"]),
 mc("Confucianism was criticized during China’s May Fourth Movement (1919) as…", "holding back modern change", ["too modern", "too Buddhist", "too scientific"]),
 tf("Confucian thought has been both honored and attacked in modern China.", True),
 tf("The exam system tested mainly Buddhist texts.", False),
 voc("synthesis", "A new whole made by combining ideas."),
 op("Wang Yangming said to know and not to act is not yet to know. Explain with an example.", "Knowing you should be kind but not acting shows you have not truly understood; e.g., knowing to study but not studying."),
]),
("Comparing Traditions", "Comparar tradiciones", [
 mc("Analects 15.23 and Hillel’s rule are both phrased…", "in the negative: do not do what you would not want", ["as commands to worship", "as laws of war", "as poems about nature"]),
 mc("The Daodejing’s water image and the Gita’s detached action both counsel…", "acting without grasping", ["seeking fame", "forceful control", "revenge"]),
 mc("Unlike the Bible or Qur’an, the Analects says little about…", "a creator God", ["family", "ethics", "learning"]),
 mc("Confucius’s junzi and Aristotle’s virtuous person both…", "build character by habit", ["reject study", "seek wealth", "avoid friends"]),
 mc("Chinese Buddhism, Confucianism and Daoism are often called…", "the Three Teachings", ["the Three Jewels", "the Three Baskets", "the Trinity"]),
 mc("Confucian ritual and Daoist naturalness disagree most about…", "whether social forms help or hinder the good", ["whether water exists", "the value of kindness", "family names"]),
 tf("Many Chinese people have drawn on more than one of the Three Teachings.", True),
 tf("Confucianism and Daoism agree on everything.", False),
 voc("ethic", "A set of ideas about right action."),
 op("Choose a Confucian and a Daoist idea and compare them fairly, naming one agreement and one difference.", "Li vs. ziran: both seek harmony; Confucius builds it through ritual, the Daodejing by returning to natural simplicity."),
]),
]

BANDS['adult'] = [
("Confucius’s life", "La vida de Confucio", [
 mc("Confucius lived from about…", "551 to 479 BCE", ["100 to 50 BCE", "1200 to 1300 CE", "3000 to 2900 BCE"]),
 mc("He came from the state of…", "Lu", ["Qin", "Rome", "Han"]),
 mc("His main work was…", "teaching", ["farming", "sailing", "war"]),
 mc("He hoped rulers would govern by…", "virtue", ["fear", "luck", "trickery"]),
 mc("His teachings survive mainly in the…", "Analects", ["Daodejing", "Tipitaka", "Upanishads"]),
 mc("His Chinese name is…", "Kongzi", ["Laozi", "Mengzi", "Zhuangzi"]),
 tf("Confucius taught students from many backgrounds.", True),
 tf("Confucius wrote the Analects alone.", False),
 voc("sage", "A very wise person."),
 op("What makes a teacher’s words last 2,500 years?", "They speak to lasting human questions: family, character, leadership, learning."),
]),
("The Analects", "Las Analectas", [
 mc("The Analects is a collection of…", "sayings and conversations", ["poems about war", "laws", "myths"]),
 mc("Legge’s first line: “Is it not pleasant to learn with a constant perseverance and…”", "application?", ["friendship?", "wealth?", "rest?"]),
 mc("Legge’s 15.23: “What you do not want done to yourself, do not do to…”", "others", ["kings", "animals", "enemies only"]),
 mc("Confucius said learning without thinking is…", "labour lost", ["enough", "joy", "wisdom"]),
 mc("The Analects has…", "20 books", ["81 chapters", "3 baskets", "18 chapters"]),
 mc("“The Master said” refers to…", "Confucius", ["Laozi", "Mencius", "the emperor"]),
 tf("The Analects was compiled by followers after Confucius died.", True),
 tf("The Analects is one continuous story.", False),
 voc("analects", "Selected sayings gathered together."),
 op("Which Analects saying would help you most at work? Why?", "Any saying with a practical reason."),
]),
("Confucian virtues", "Virtudes confucianas", [
 mc("Ren means…", "humaneness", ["ritual", "loyalty", "wisdom"]),
 mc("Li means…", "ritual and proper conduct", ["kindness", "money", "power"]),
 mc("Xiao means…", "filial piety", ["courage", "music", "trade"]),
 mc("Yi means…", "rightness", ["greed", "silence", "speed"]),
 mc("Zhi means…", "wisdom", ["wealth", "anger", "strength"]),
 mc("The junzi is the…", "exemplary person", ["emperor", "servant", "monk"]),
 tf("Confucius saw virtue as learned through practice.", True),
 tf("Ren means ruling by force.", False),
 voc("rightness", "Doing what is morally right."),
 op("Which Confucian virtue do you see most in people you admire?", "Any virtue with an example."),
]),
("Family and society", "Familia y sociedad", [
 mc("The Five Relationships include ruler and subject, parent and child, husband and wife, older and younger sibling, and…", "friend and friend", ["teacher and pet", "buyer and seller", "king and god"]),
 mc("In each relationship, Confucius stressed…", "mutual duties", ["one side only", "no duties", "money"]),
 mc("Ancestor veneration means…", "honoring family members who have died", ["worshipping kings", "fearing ghosts", "ignoring the past"]),
 mc("Confucius said a good ruler is like the wind, and the people are like…", "grass that bends", ["stone", "fire", "rain"]),
 mc("The Great Learning links world peace to…", "self-cultivation and orderly families", ["armies", "trade", "walls"]),
 mc("Confucian ideas shaped family customs in…", "East Asia", ["South America", "Scandinavia", "West Africa"]),
 tf("Confucian family ideals have been debated, including views of women’s roles.", True),
 tf("Confucius said family does not matter to society.", False),
 voc("veneration", "Deep respect and honor."),
 op("How do family expectations in your life compare to the Five Relationships?", "Any honest comparison."),
]),
("Laozi and the Daodejing", "Laozi y el Daodejing", [
 mc("Laozi means…", "Old Master", ["Great King", "Wise Child", "Mountain Man"]),
 mc("The Daodejing has…", "81 short chapters", ["20 books", "3 parts", "400 chapters"]),
 mc("Legge’s Chapter 1 begins: “The Tao that can be trodden is not the enduring and unchanging…”", "Tao", ["king", "name", "river"]),
 mc("Legge’s Chapter 64: “The journey of a thousand li commences with…”", "a single step", ["a plan", "a horse", "a map"]),
 mc("Legge called the book the…", "Tao Teh King", ["Song Celestial", "Doctrine of the Mean", "Book of Changes"]),
 mc("Historians say Laozi’s life is…", "largely legend", ["well documented", "the same as Confucius’s", "recorded day by day"]),
 tf("The Daodejing is one of the most translated books in the world.", True),
 tf("The Daodejing is a Confucian text.", False),
 voc("Dao", "The Way: the source and flow of all things."),
 op("“The journey of a thousand li commences with a single step.” What first step could you take on a goal?", "Any concrete first step."),
]),
("Dao and wu wei", "Dao y wu wei", [
 mc("Dao means…", "the Way", ["the wall", "the war", "the word"]),
 mc("De means…", "virtue or power", ["death", "debt", "desire"]),
 mc("Wu wei means…", "effortless, non-forcing action", ["laziness", "hard labor", "fighting"]),
 mc("The Daodejing’s model of strength is…", "water", ["iron", "fire", "a mountain"]),
 mc("The Daodejing says the best rulers…", "are barely noticed", ["are feared", "control everything", "make many laws"]),
 mc("Yin and yang are…", "complementary opposites", ["enemies", "gods", "two books"]),
 tf("Wu wei does not mean doing nothing.", True),
 tf("The Daodejing prizes hardness over softness.", False),
 voc("wu wei", "Acting without forcing; going with the grain."),
 op("Where in your life would less forcing bring better results?", "Any honest example, like conversations, sleep or learning."),
]),
("Zhuangzi", "Zhuangzi", [
 mc("Zhuangzi was a Daoist thinker known for…", "stories and humor", ["law codes", "war", "trade"]),
 mc("In the Butterfly Dream he wonders…", "whether he is a man dreaming of a butterfly or a butterfly dreaming of a man", ["how butterflies fly", "what to eat", "who is king"]),
 mc("Cook Ding carves an ox by…", "following its natural structure", ["hacking hard", "using many knives", "rushing"]),
 mc("“Three in the Morning” shows people react to…", "framing more than substance", ["hunger", "weather", "music"]),
 mc("The useless tree survives because…", "no one wants its wood", ["it is guarded", "it is gold", "it is small"]),
 mc("Zhuangzi turned down office, preferring to be…", "a turtle dragging its tail in the mud", ["a sacred bone in a temple", "a king", "a general"]),
 tf("Zhuangzi questions fixed ideas of right and wrong.", True),
 tf("Zhuangzi wrote the Analects.", False),
 voc("framing", "How something is presented, which shapes how we see it."),
 op("Give a modern example of “Three in the Morning.”", "Same deal, different packaging, like prices or schedules; any fit example."),
]),
("Mencius and Xunzi", "Mencio y Xunzi", [
 mc("Mencius said human nature is…", "good", ["bad", "empty", "fixed"]),
 mc("Xunzi said human nature is…", "bad, and made good by effort", ["good", "divine", "random"]),
 mc("Mencius’s child-at-the-well example shows…", "natural compassion", ["fear of water", "greed", "indifference"]),
 mc("Mencius said people may remove…", "a cruel ruler", ["their parents", "teachers", "all laws"]),
 mc("Xunzi stressed the role of…", "teachers and ritual", ["luck", "nature alone", "wealth"]),
 mc("Both Mencius and Xunzi were followers of…", "Confucius", ["Laozi", "the Buddha", "Han Feizi"]),
 tf("They agreed education matters but disagreed about human nature.", True),
 tf("Mencius said people are born bad.", False),
 voc("nature", "What something is like on its own, from the start."),
 op("Are people naturally good or shaped by training? Give an example from life.", "Any reasoned view with an example."),
]),
("The classics in history", "Los clásicos en la historia", [
 mc("Confucianism became state teaching under the…", "Han dynasty", ["Qin", "Tang only", "Qing only"]),
 mc("Civil service exams tested…", "the Confucian classics", ["science", "sports", "Buddhist sutras"]),
 mc("The exams ended in…", "1905", ["1500", "1776", "1999"]),
 mc("Neo-Confucianism was led by…", "Zhu Xi", ["Laozi", "Ashoka", "Shankara"]),
 mc("Confucian influence spread to…", "Korea, Japan and Vietnam", ["Peru", "Egypt", "Sweden"]),
 mc("The Qin emperor burned books in…", "213 BCE", ["1905", "551 BCE", "618 CE"]),
 tf("Confucian ideas shaped Chinese government for about 2,000 years.", True),
 tf("The exams were open only to Daoist priests.", False),
 voc("bureaucracy", "A system of government offices and officials."),
 op("What is one strength and one weakness of choosing officials by exam?", "Strength: merit over birth; weakness: favors memorization and those who can afford study."),
]),
("The classics today", "Los clásicos hoy", [
 mc("Confucius Temples in many cities honor him on…", "his traditional birthday, Teachers’ Day in Taiwan", ["New Year only", "no day", "Halloween"]),
 mc("Many business leaders read the Daodejing for ideas on…", "leadership", ["cooking", "sports scores", "weather"]),
 mc("Tai chi, a slow movement practice, is linked with…", "Daoist ideas", ["Legalism", "Buddhist law", "Roman sport"]),
 mc("Confucian values such as respect for education remain strong in…", "many East Asian families", ["no families", "only ancient China", "only monasteries"]),
 mc("Words from Chinese thought in English include…", "yin, yang, Tao", ["karma, guru", "sushi, emoji", "ballet, café"]),
 mc("The Daodejing has been translated into English…", "hundreds of times", ["once", "never", "only in 2020"]),
 tf("Ancient Chinese classics are still widely read around the world.", True),
 tf("No one reads the Analects today.", False),
 voc("legacy", "What is handed down from the past."),
 op("Which idea from the Analects or Daodejing do you want to remember? Why?", "Any idea with a personal reason."),
]),
]
