# Hindu Texts — Daily Drafts banks. Studied, never preached: "Hindus tell…", "The Gita says…".
# Exact quotations only from U.S.-public-domain translations (Müller, Griffith, Arnold); otherwise paraphrase.
def mc(q, a, w): return ["mc", q, a, w]
def tf(q, v): return ["tf", q, v]
def voc(w, d): return ["voc", w, d]
def op(q, m): return ["open", q, m]

BANDS = {}

BANDS['k2'] = [
("Rama and Sita", "Rama y Sita", [
 mc("In the Ramayana, Rama is a…", "prince", ["farmer", "sailor", "baker"]),
 mc("Who is Rama’s wife?", "Sita", ["Draupadi", "Radha", "Parvati"]),
 mc("Rama, Sita and Lakshmana went to live in the…", "forest", ["desert", "sea", "city"]),
 mc("Who took Sita away to his island?", "Ravana", ["Hanuman", "Lakshmana", "Bharata"]),
 mc("Lakshmana is Rama’s…", "brother", ["father", "teacher", "king"]),
 mc("At the end of the story, Rama and Sita go home to…", "Ayodhya", ["Lanka", "the moon", "the ocean"]),
 tf("The Ramayana is a very old story from India.", True),
 tf("In the story, Rama gives up and never looks for Sita.", False),
 voc("prince", "The son of a king and queen."),
 op("Rama keeps a promise even when it is hard. Tell about a time you kept a promise.", "Any honest answer about keeping a promise."),
]),
("Hanuman the Helper", "Hanumán el ayudante", [
 mc("In the Ramayana, Hanuman is a…", "monkey hero", ["lion king", "fish", "giant bird"]),
 mc("Hanuman helps…", "Rama find Sita", ["Ravana keep Sita", "build a city", "sail a ship"]),
 mc("How does Hanuman get across the sea to Lanka?", "he leaps across", ["he swims slowly", "he takes a boat", "he digs a tunnel"]),
 mc("Hanuman is known for being…", "loyal and brave", ["lazy", "mean", "sleepy"]),
 mc("Who helps build a bridge to Lanka?", "an army of monkeys and bears", ["only Ravana", "fish", "kings from far away"]),
 mc("Hanuman gives Sita a sign that Rama sent him. What is it?", "Rama’s ring", ["a flower", "a crown", "a book"]),
 tf("Hanuman is a good friend to Rama.", True),
 tf("Hanuman is afraid to help.", False),
 voc("loyal", "Staying true to a friend."),
 op("Hanuman is a helper. How can you help a friend?", "Any kind way to help, such as sharing or listening."),
]),
("Krishna as a Child", "Krishna de niño", [
 mc("Hindus tell stories of Krishna as a little boy who loved…", "butter", ["candy", "pizza", "rice cakes"]),
 mc("Young Krishna grew up among…", "cow herders", ["kings in a palace", "sailors", "miners"]),
 mc("Krishna is often shown playing a…", "flute", ["drum", "violin", "trumpet"]),
 mc("In one story, Krishna lifts a whole…", "hill to keep people safe from rain", ["house to move it", "tree to eat fruit", "boat to the sea"]),
 mc("Krishna’s skin is often painted…", "blue", ["green", "orange", "white"]),
 mc("Hindus see Krishna as a form of the god…", "Vishnu", ["Ganesha", "Hanuman", "Ravana"]),
 tf("Stories of young Krishna are often playful and fun.", True),
 tf("Krishna is shown playing a guitar.", False),
 voc("flute", "A thin musical pipe you blow into."),
 op("Krishna shares and plays with friends. What game do you like to play with friends?", "Any game named."),
]),
("Ganesha", "Ganesha", [
 mc("Ganesha has the head of an…", "elephant", ["eagle", "ox", "owl"]),
 mc("Hindus pray to Ganesha at the start of new things because he is called the…", "remover of obstacles", ["god of rain", "king of Lanka", "keeper of the sea"]),
 mc("Ganesha rides a…", "mouse", ["horse", "tiger", "swan"]),
 mc("Ganesha’s parents are…", "Shiva and Parvati", ["Rama and Sita", "Krishna and Radha", "Brahma and Sarasvati"]),
 mc("Ganesha is often shown with a bowl of…", "sweets", ["rocks", "shoes", "books only"]),
 mc("An obstacle is something that…", "gets in your way", ["helps you fly", "makes you taller", "tastes sweet"]),
 tf("Many Hindus say a prayer to Ganesha before starting something new.", True),
 tf("Ganesha has the head of a lion.", False),
 voc("obstacle", "Something that blocks your way."),
 op("What is something new you are starting this year?", "Any new thing, such as a sport, a class or a book."),
]),
("Diwali", "Diwali", [
 mc("Diwali is called the festival of…", "lights", ["snow", "kites", "harvest only"]),
 mc("At Diwali, families light small clay lamps called…", "diyas", ["drums", "flags", "masks"]),
 mc("Many Hindus remember Rama coming home at Diwali. People lit lamps to…", "welcome him", ["scare him", "hide from him", "cook food"]),
 mc("At Diwali, many families make colorful floor designs called…", "rangoli", ["origami", "quilts", "mosaics"]),
 mc("Diwali comes in the…", "fall", ["summer only", "spring only", "same day every year in January"]),
 mc("Diwali shows light winning over…", "darkness", ["water", "wind", "sand"]),
 tf("Families share sweets at Diwali.", True),
 tf("Diwali is a festival of snow.", False),
 voc("festival", "A special time when people celebrate together."),
 op("Draw or tell about a light that makes you feel happy.", "Any light named, such as a candle, a lamp or the sun."),
]),
("Holi", "Holi", [
 mc("Holi is known as the festival of…", "colors", ["books", "boats", "bells"]),
 mc("At Holi, people throw bright colored…", "powder and water", ["rocks", "shoes", "leaves"]),
 mc("Holi comes in the…", "spring", ["winter", "middle of the night", "fall only"]),
 mc("Holi is a time to be friends and…", "forgive", ["argue", "stay inside", "be alone"]),
 mc("A story told at Holi is about a boy named Prahlad who was…", "saved from a fire", ["lost at sea", "a king of monkeys", "a giant"]),
 mc("On Holi, people often…", "play, sing and share food", ["sleep all day", "stay quiet", "work alone"]),
 tf("Holi welcomes spring.", True),
 tf("At Holi, everyone wears only white and stays clean.", False),
 voc("forgive", "To stop being angry at someone."),
 op("What colors would you use to make a happy picture?", "Any colors named."),
]),
("Namaste and Respect", "Namasté y respeto", [
 mc("Many Hindus greet people by pressing their hands together and saying…", "namaste", ["aloha", "shalom", "ciao"]),
 mc("Namaste is a way to show…", "respect", ["anger", "hunger", "sleep"]),
 mc("Many Hindu children touch the feet of elders to show…", "respect", ["they are tired", "they are cold", "they want to run"]),
 mc("In Hindu stories, a teacher is called a…", "guru", ["king", "giant", "chef"]),
 mc("Rama obeys his father even when it is hard. This shows…", "respect for parents", ["being lazy", "being rude", "being scared"]),
 mc("Before eating, many Hindus give thanks for…", "the food", ["the rain only", "the car", "a toy"]),
 tf("Namaste is a greeting.", True),
 tf("Namaste means “go away.”", False),
 voc("respect", "Treating someone as important and worth caring about."),
 op("How do you show respect to a grown-up or a friend?", "Listening, using kind words, saying thank you, or any honest answer."),
]),
("Kindness to Every Living Thing", "Bondad con todo ser vivo", [
 mc("Many Hindus try not to hurt any living thing. This idea is called…", "ahimsa", ["karma", "diya", "puja"]),
 mc("Many Hindus treat which animal with special care?", "the cow", ["the shark", "the spider", "the rat"]),
 mc("Many Hindus do not eat meat because they want to…", "not hurt animals", ["grow taller", "run faster", "stay awake"]),
 mc("Which is a kind thing to do for an animal?", "give it water", ["pull its tail", "chase it", "yell at it"]),
 mc("Hindus often see the whole world as…", "full of life to care for", ["empty", "only for people", "a toy"]),
 mc("Many Hindus honor trees and rivers. A river Hindus call holy is the…", "Ganges", ["Nile", "Thames", "Amazon"]),
 tf("Ahimsa means not hurting living things.", True),
 tf("Ahimsa means hurting animals is fine.", False),
 voc("gentle", "Soft and careful; not rough."),
 op("Name one way you can be gentle with an animal or a plant.", "Give it water, pet it softly, do not step on it, or any kind answer."),
]),
("Stories That Teach", "Cuentos que enseñan", [
 mc("The Panchatantra is a book of…", "animal stories that teach lessons", ["recipes", "maps", "songs about the sea"]),
 mc("The Panchatantra stories were told to teach…", "young princes to be wise", ["dogs to sit", "farmers to plant", "sailors to swim"]),
 mc("In one tale, a monkey tricks a crocodile. The monkey is…", "clever", ["sleepy", "mean", "slow"]),
 mc("In the monkey and crocodile story, the crocodile wants the monkey’s…", "heart", ["banana", "tail", "tree"]),
 mc("The monkey says he left his heart…", "up in the tree", ["at home", "in the river", "on the moon"]),
 mc("A story’s lesson is also called its…", "moral", ["title", "cover", "page"]),
 tf("Many Panchatantra stories have talking animals.", True),
 tf("The Panchatantra is a cookbook.", False),
 voc("moral", "The lesson a story teaches."),
 op("Tell a lesson you learned from a story.", "Any lesson, such as be kind, tell the truth, or think before you act."),
]),
("Prayer and Worship", "Oración y culto", [
 mc("Hindu worship with flowers, light and food is called…", "puja", ["yoga", "rangoli", "diya"]),
 mc("Many Hindu homes have a small…", "shrine for prayer", ["garage", "boat", "castle"]),
 mc("A Hindu place of worship is called a…", "temple", ["stadium", "barn", "mall"]),
 mc("During puja, people often ring a…", "bell", ["phone", "drum set", "whistle"]),
 mc("A sound Hindus often chant at the start of prayer is…", "Om", ["Hi", "Boo", "Yay"]),
 mc("Many Hindus take off their shoes before entering a…", "temple", ["store", "bus", "park"]),
 tf("Puja can happen at home or in a temple.", True),
 tf("Hindus only pray on one day each year.", False),
 voc("temple", "A building where people worship."),
 op("Hindus offer flowers during puja. What is a special way your family says thank you?", "Any family tradition, such as a meal, a card, a hug, or saying grace."),
]),
]

BANDS['35'] = [
("What Hindu Texts Are", "Qué son los textos hindúes", [
 mc("The oldest Hindu texts are the…", "Vedas", ["Puranas", "Analects", "Sutras"]),
 mc("Most old Hindu texts were first written in…", "Sanskrit", ["Latin", "Greek", "Arabic"]),
 mc("Before they were written down, the Vedas were…", "memorized and chanted", ["painted on walls", "kept secret by kings only", "sung by birds"]),
 mc("Hindus call the texts they see as heard from the gods “shruti,” which means…", "what is heard", ["what is sold", "what is forgotten", "what is drawn"]),
 mc("Texts like the Ramayana and Mahabharata are called “smriti,” which means…", "what is remembered", ["what is hidden", "what is eaten", "what is counted"]),
 mc("Which is a long Hindu story poem, or epic?", "the Mahabharata", ["the Dhammapada", "the Torah", "the Daodejing"]),
 tf("Hinduism has many sacred books, not just one.", True),
 tf("The Vedas were first written in English.", False),
 voc("epic", "A very long story poem about heroes."),
 op("Why might people memorize a text instead of writing it down?", "Writing was rare or costly; chanting kept the exact sounds; teachers passed it on face to face."),
]),
("The Ramayana", "El Ramayana", [
 mc("The Ramayana is traditionally said to be written by the poet…", "Valmiki", ["Vyasa", "Homer", "Kabir"]),
 mc("Why did Rama leave Ayodhya for fourteen years?", "his father kept a promise to his stepmother Kaikeyi", ["he wanted to travel", "he lost a battle", "he was chasing Hanuman"]),
 mc("Rama’s brother Bharata ruled while Rama was gone by…", "placing Rama’s sandals on the throne", ["crowning himself forever", "burning the palace", "moving to Lanka"]),
 mc("Ravana, the king of Lanka, has…", "ten heads", ["wings", "one eye", "a fish tail"]),
 mc("Who flew to Lanka and found Sita?", "Hanuman", ["Lakshmana", "Bharata", "Dasharatha"]),
 mc("Many Hindus remember Rama’s return home during…", "Diwali", ["Holi", "Vesak", "Ramadan"]),
 tf("Rama is seen as an example of doing one’s duty.", True),
 tf("Sita is Ravana’s sister.", False),
 voc("exile", "Being sent away from home for a long time."),
 op("Bharata puts Rama’s sandals on the throne. What does that show about him?", "He is loyal to his brother; he holds the kingdom for Rama and does not grab power."),
]),
("The Mahabharata", "El Mahabharata", [
 mc("The Mahabharata is traditionally said to be told by the sage…", "Vyasa", ["Valmiki", "Laozi", "Hanuman"]),
 mc("The Mahabharata is about a war between two groups of…", "cousins", ["animals", "gods and giants", "sailors"]),
 mc("The five brothers who are the heroes are the…", "Pandavas", ["Kauravas", "Vedas", "Rishis"]),
 mc("The hundred cousins who oppose them are the…", "Kauravas", ["Pandavas", "Brahmins", "Buddhas"]),
 mc("Which Pandava brother is a great archer?", "Arjuna", ["Ravana", "Rama", "Ganesha"]),
 mc("The Mahabharata is famous for being…", "one of the longest poems in the world", ["a short song", "a book of maps", "a list of kings only"]),
 tf("The Bhagavad Gita is a part of the Mahabharata.", True),
 tf("The Mahabharata is about a war between Rama and Ravana.", False),
 voc("archer", "A person who shoots with a bow and arrows."),
 op("The brothers lose a dice game and lose their kingdom. What can people learn from that part of the story?", "Games of chance and pride can cost a lot; think before you risk what matters."),
]),
("The Bhagavad Gita", "El Bhagavad Gita", [
 mc("“Bhagavad Gita” means…", "Song of the Lord", ["Book of Kings", "Story of the River", "Law of the Land"]),
 mc("In the Gita, the prince Arjuna talks with…", "Krishna, who drives his chariot", ["Rama, his brother", "Ravana, his enemy", "a monkey"]),
 mc("At the start, Arjuna does not want to fight because…", "his relatives and teachers are on the other side", ["he is sleepy", "he lost his bow", "it is raining"]),
 mc("Krishna teaches Arjuna to do his duty without…", "worrying about the reward", ["thinking", "any rules", "friends"]),
 mc("Where does the Gita take place?", "on a battlefield", ["in a temple", "on a ship", "in a school"]),
 mc("The Gita has how many chapters?", "18", ["3", "100", "7"]),
 tf("The Gita is a conversation.", True),
 tf("In the Gita, Arjuna is a farmer.", False),
 voc("duty", "What you are supposed to do; your job or role."),
 op("Krishna says do your work well and do not worry only about the prize. How could that help at school?", "You focus on learning and effort, not only on the grade, and feel less stress."),
]),
("One God in Many Forms", "Un Dios en muchas formas", [
 mc("Many Hindus believe one ultimate reality is behind everything. It is called…", "Brahman", ["Brahma", "Atman", "Ravana"]),
 mc("Three well-known Hindu gods are Brahma, Vishnu and…", "Shiva", ["Hanuman", "Arjuna", "Valmiki"]),
 mc("In Hindu stories, Brahma is known as the…", "creator", ["destroyer", "trickster", "monkey king"]),
 mc("Vishnu is known as the…", "preserver who protects the world", ["river goddess", "god of mice", "king of Lanka"]),
 mc("Shiva is known as the destroyer who also…", "makes new beginnings possible", ["rules the sea only", "writes books", "guards the moon"]),
 mc("Lakshmi is the goddess of…", "wealth and good fortune", ["war", "snow", "music only"]),
 tf("Many Hindus see the many gods as forms of one divine reality.", True),
 tf("Rama and Krishna are described as forms of Shiva.", False),
 voc("avatar", "A form a god takes when coming to earth, like Rama or Krishna for Vishnu."),
 op("A person can be a student, a sister and a friend all at once. How is that like the Hindu idea of one God in many forms?", "One person plays many roles; many Hindus see one divine reality shown in many forms."),
]),
("Dharma and Karma", "Dharma y karma", [
 mc("In Hindu teaching, dharma means…", "right duty and the right way to live", ["a kind of food", "a song", "a river"]),
 mc("Karma is the idea that…", "actions have results", ["nothing matters", "luck decides all", "only kings count"]),
 mc("Good actions, Hindus teach, lead to…", "good results", ["bad results", "no results", "a flood"]),
 mc("Hindus believe the soul is born again after death. This is called…", "reincarnation", ["karma", "dharma", "puja"]),
 mc("A student’s dharma would include…", "studying and respecting teachers", ["ruling a kingdom", "leading an army", "selling cows"]),
 mc("Which story hero is often seen as a model of dharma?", "Rama", ["Ravana", "the crocodile", "Kaikeyi"]),
 tf("Karma teaches that what you do matters.", True),
 tf("Dharma means doing whatever you want.", False),
 voc("karma", "The idea that every action brings a result."),
 op("Give an example of a good action and the good result it might bring.", "Helping a classmate leads to a new friend; any cause-and-result pair."),
]),
("Festivals", "Festividades", [
 mc("Diwali celebrates the victory of…", "light over darkness", ["winter over summer", "sea over land", "night over day"]),
 mc("Navaratri means “nine nights” and honors the goddess…", "Durga", ["Sita", "Radha", "Kaikeyi"]),
 mc("On Raksha Bandhan, a sister ties a thread on her brother’s…", "wrist", ["ankle", "hair", "shoe"]),
 mc("Janmashtami celebrates the birthday of…", "Krishna", ["Rama", "Ganesha", "Hanuman"]),
 mc("On Ganesh Chaturthi, people make and honor statues of…", "Ganesha", ["Arjuna", "Lakshmi", "Vyasa"]),
 mc("On Holi, many Hindus remember the story of…", "Prahlad being saved from fire", ["the Pandavas’ war", "the monkey and crocodile", "Ravana’s ten heads"]),
 tf("Hindu festivals often follow the moon’s calendar, so the dates move.", True),
 tf("Diwali is on the same date every year on the Western calendar.", False),
 voc("calendar", "A way of counting days, months and years."),
 op("Pick one Hindu festival and say what it celebrates.", "Diwali: light over darkness and Rama’s return; Holi: spring and good over evil; any accurate match."),
]),
("Worship at Home and Temple", "Culto en casa y en el templo", [
 mc("Puja is Hindu…", "worship with offerings", ["dance class", "farm work", "a board game"]),
 mc("A statue or image of a god used in worship is called a…", "murti", ["mantra", "guru", "sutra"]),
 mc("A sacred word or phrase repeated in prayer is a…", "mantra", ["murti", "diya", "rangoli"]),
 mc("Darshan means…", "seeing and being seen by the divine at a temple", ["a meal", "a greeting to friends", "a map"]),
 mc("Offered food, later shared with people, is called…", "prasad", ["karma", "moksha", "Veda"]),
 mc("Aarti is a ritual in which people wave…", "a lamp in front of the deity", ["flags", "fans", "books"]),
 tf("Many Hindus worship at home every day.", True),
 tf("Hindus must go to a temple to pray at all.", False),
 voc("offering", "A gift given in worship, such as flowers or fruit."),
 op("Why might sharing prasad afterward be important to a Hindu family?", "It turns worship into sharing; everyone takes part in the blessing."),
]),
("Old Tales: Panchatantra and Hitopadesha", "Cuentos antiguos: Panchatantra e Hitopadesha", [
 mc("The Panchatantra was made to teach young princes about…", "wise choices and good sense", ["farming only", "cooking", "sailing"]),
 mc("In “The Tortoise and the Geese,” the tortoise falls because he…", "opens his mouth to talk", ["is too heavy", "falls asleep", "lets go on purpose"]),
 mc("The lesson of “The Tortoise and the Geese” is…", "know when to stay quiet", ["always talk", "never fly", "eat more"]),
 mc("In “The Lion and the Hare,” the small hare wins by…", "tricking the lion with its reflection in a well", ["fighting harder", "running away", "calling an army"]),
 mc("The Hitopadesha is another book of…", "animal fables with lessons", ["war plans", "songs to Shiva", "star maps"]),
 mc("In the Panchatantra, stories are often told…", "inside other stories", ["only as pictures", "backward", "without animals"]),
 tf("Some Panchatantra stories travelled to Persia, Arabia and Europe.", True),
 tf("In the lion-and-hare tale, the lion wins by being clever.", False),
 voc("fable", "A short story, often with animals, that teaches a lesson."),
 op("The small hare beats the big lion by thinking. What does that fable say about size and strength?", "Brains can beat size; a small or weak one can win by being wise."),
]),
("Sanskrit and Sacred Sound", "Sánscrito y sonido sagrado", [
 mc("Sanskrit is an old language of…", "India", ["Egypt", "China", "Mexico"]),
 mc("The sound “Om” is, for many Hindus, a…", "sacred sound of the whole universe", ["greeting for friends", "number", "name of a river"]),
 mc("Sanskrit is written in a script called…", "Devanagari", ["Latin", "Cyrillic", "Hanzi"]),
 mc("Which English word comes from Sanskrit?", "yoga", ["pizza", "robot", "tortilla"]),
 mc("“Namaste” comes from Sanskrit and means about…", "“I bow to you”", ["“good night”", "“I am hungry”", "“come here”"]),
 mc("Teachers passed down Vedic chants with great care so that…", "every sound stayed exact", ["they could change them", "they rhymed in English", "they got shorter"]),
 tf("Sanskrit is related to many European languages, like English and Spanish.", True),
 tf("Sanskrit is only a made-up language for movies.", False),
 voc("chant", "To say or sing words over and over in a steady rhythm."),
 op("Why would it matter to keep every sound of a chant exact?", "Hindus hold the sound itself as sacred; a change would change the text."),
]),
]

BANDS['68'] = [
("The Vedas", "Los Vedas", [
 mc("How many Vedas are there?", "four", ["two", "seven", "twelve"]),
 mc("The four Vedas are the Rig, Sama, Yajur and…", "Atharva", ["Gita", "Purana", "Upanishad"]),
 mc("The Rig Veda is mostly made of…", "hymns to gods such as Agni and Indra", ["laws for kings", "animal fables", "war stories"]),
 mc("Agni, praised in the Rig Veda, is the god of…", "fire", ["the sea", "love", "music"]),
 mc("The Sama Veda is known for…", "melodies for chanting hymns", ["recipes", "medicine only", "maps"]),
 mc("Scholars date the Rig Veda to roughly…", "1500–1200 BCE", ["500 CE", "1800 CE", "50 BCE"]),
 tf("The Rig Veda is one of the oldest religious texts still in use.", True),
 tf("The Vedas were first written down on paper when they were composed.", False),
 voc("hymn", "A song of praise, often to a god."),
 op("The Rig Veda says, in Griffith’s translation, “To what is One, sages give many a title.” What does this line suggest?", "One reality can be called by many names; different gods may be names for one truth."),
]),
("The Upanishads", "Los Upanishads", [
 mc("The Upanishads are philosophical texts that come at the…", "end of the Vedas", ["start of the Ramayana", "middle of the Gita", "end of the Puranas"]),
 mc("“Upanishad” is often explained as “sitting down near,” meaning…", "students sitting near a teacher", ["kings near a throne", "cows near a river", "soldiers near a wall"]),
 mc("The Upanishads ask questions like…", "What is the self? What is ultimate reality?", ["How do you build a boat?", "Who won the war?", "How much does rice cost?"]),
 mc("In the Chandogya Upanishad, a father teaches his son Shvetaketu with…", "salt dissolved in water", ["a sword", "a dice game", "a bow"]),
 mc("The salt lesson shows that Brahman is…", "present everywhere though unseen", ["only in temples", "only in the sky", "made of salt"]),
 mc("The phrase “Tat tvam asi” is usually translated…", "“You are that”", ["“Go and learn”", "“Light the lamp”", "“Fight the war”"]),
 tf("The Upanishads are usually taught through dialogues between teachers and students.", True),
 tf("The Upanishads are mostly lists of kings.", False),
 voc("self", "A person’s inner being; in the Upanishads, atman."),
 op("Why would a teacher use salt in water to explain something you cannot see?", "It makes an invisible idea concrete: you cannot see the salt, but you can taste it everywhere."),
]),
("The Ramayana", "El Ramayana", [
 mc("The Ramayana is divided into seven books called…", "kandas", ["suras", "sutras", "psalms"]),
 mc("Rama’s father, King Dasharatha, had promised Kaikeyi…", "two wishes", ["a horse", "a crown for Rama", "a trip to Lanka"]),
 mc("Kaikeyi used her wishes to…", "send Rama away and make her son Bharata king", ["give Rama gold", "free Sita", "build a temple"]),
 mc("Sita is taken after Ravana disguises himself as…", "a wandering holy man", ["a deer", "a monkey", "a king of Ayodhya"]),
 mc("A golden deer draws Rama away. It is really…", "a demon in disguise", ["Hanuman", "a gift from Bharata", "Lakshmi"]),
 mc("The Ramayana has been retold in many lands, including…", "Thailand and Indonesia", ["Norway and Chile", "Peru and Iceland", "Canada only"]),
 tf("Rama is honored by many Hindus as an avatar of Vishnu.", True),
 tf("The Ramayana is only told in India.", False),
 voc("disguise", "Clothes or a shape used to hide who you really are."),
 op("Rama leaves home rather than make his father break a promise. Is keeping that promise right? Give a reason.", "Any reasoned view: honoring duty and one’s word; or questioning whether an unfair promise should bind."),
]),
("The Mahabharata and the Gita", "El Mahabharata y el Gita", [
 mc("The Mahabharata has about how many verses?", "100,000", ["500", "5,000", "10 million"]),
 mc("The war in the Mahabharata is fought at…", "Kurukshetra", ["Lanka", "Ayodhya", "Mecca"]),
 mc("The Pandavas’ shared wife is…", "Draupadi", ["Sita", "Radha", "Kaikeyi"]),
 mc("The Pandavas lost their kingdom in…", "a rigged dice game", ["a flood", "a fire", "a race"]),
 mc("In the Gita, Krishna says the self is eternal: it is…", "never born and never dies", ["born each morning", "made of fire", "only in the body"]),
 mc("In the Gita, “karma yoga” is the path of…", "selfless action", ["silent study only", "fasting", "sleeping"]),
 tf("Arjuna’s doubt at the start of the Gita is about fighting his own family.", True),
 tf("In the Gita, Krishna fights Arjuna.", False),
 voc("dilemma", "A hard choice between two options."),
 op("What is Arjuna’s dilemma, and why is it hard?", "Fight and harm family and teachers, or refuse and fail his warrior duty; both choices cost him."),
]),
("Brahman and Atman", "Brahman y Atman", [
 mc("In Hindu thought, Brahman is…", "the one ultimate reality", ["a caste", "a festival", "a river"]),
 mc("Atman is…", "the true inner self or soul", ["a god of war", "a book", "a food offering"]),
 mc("Many Upanishads teach that atman and Brahman are…", "one", ["enemies", "unrelated", "brothers"]),
 mc("Brahma (the creator god) and Brahman (ultimate reality) are…", "different ideas", ["the same word", "two rivers", "two epics"]),
 mc("The Katha Upanishad tells of a boy, Nachiketa, who questions…", "Yama, the god of death", ["Rama", "a monkey", "a king of Lanka"]),
 mc("Nachiketa asks Yama what happens…", "after death", ["at the market", "in a war", "at a wedding"]),
 tf("Many Hindus believe the atman is not destroyed when the body dies.", True),
 tf("Brahman is the name of a Hindu festival.", False),
 voc("ultimate", "The highest, deepest or final."),
 op("Nachiketa turns down wealth to learn the truth about death. What does that choice tell you about him?", "He values wisdom and truth over riches; he is brave and curious."),
]),
("Karma, Samsara and Moksha", "Karma, samsara y moksha", [
 mc("Samsara is…", "the cycle of birth, death and rebirth", ["a type of temple", "a hymn", "a kind of food"]),
 mc("Moksha is…", "release from the cycle of rebirth", ["a festival", "a god", "a war"]),
 mc("Hindus teach that karma shapes…", "future lives and experiences", ["only the weather", "nothing", "only animals"]),
 mc("The four goals of life in Hindu tradition are dharma, artha, kama and…", "moksha", ["samsara", "Veda", "puja"]),
 mc("Artha is the goal of…", "earning a living and success", ["prayer only", "pleasure only", "rebirth"]),
 mc("Kama, as a life goal, means…", "enjoyment and love", ["duty", "wealth", "freedom"]),
 tf("In Hindu teaching, moksha is the highest goal.", True),
 tf("Samsara means a single life with no rebirth.", False),
 voc("cycle", "Something that goes around and repeats."),
 op("Draw or describe samsara as a picture. Where does moksha fit?", "A wheel of birth, death and rebirth; moksha is stepping off the wheel."),
]),
("Paths of Yoga", "Los caminos del yoga", [
 mc("In Hindu tradition, “yoga” means…", "a path or discipline that joins a person with the divine", ["only stretching", "a food", "a game"]),
 mc("Bhakti yoga is the path of…", "loving devotion", ["knowledge", "action", "breathing only"]),
 mc("Jnana yoga is the path of…", "knowledge and insight", ["devotion", "work", "fasting"]),
 mc("Karma yoga is the path of…", "selfless action", ["singing", "study only", "sleep"]),
 mc("Raja yoga focuses on…", "meditation and control of the mind", ["cooking", "war", "trade"]),
 mc("The Yoga Sutras are traditionally credited to…", "Patanjali", ["Valmiki", "Vyasa", "Confucius"]),
 tf("The Gita describes more than one path to God.", True),
 tf("In Hindu texts, yoga only means exercise.", False),
 voc("devotion", "Deep love and loyalty, often to God."),
 op("Which path, knowledge, devotion or action, fits a doctor who helps people without wanting praise? Why?", "Karma yoga: selfless action done as duty, not for reward."),
]),
("The Puranas and Devotion", "Los Puranas y la devoción", [
 mc("The Puranas are texts full of…", "stories of gods, creation and heroes", ["tax laws", "maps", "math tables"]),
 mc("The Bhagavata Purana tells many stories of…", "Krishna", ["Ravana", "Buddha only", "Laozi"]),
 mc("Vishnu’s ten avatars include Rama, Krishna and…", "Narasimha, the man-lion", ["Ganesha", "Hanuman", "Arjuna"]),
 mc("The churning of the ocean story tells gods and demons pulling…", "a great serpent to churn the sea for nectar", ["ropes on a ship", "a chariot", "a tree"]),
 mc("Stories of Shiva often show him as…", "a meditating yogi and cosmic dancer", ["a merchant", "a farmer", "a monkey"]),
 mc("The goddess Durga is shown defeating…", "the buffalo demon Mahisha", ["Rama", "Krishna", "Ganesha"]),
 tf("Devotion to one chosen god is common among Hindus.", True),
 tf("The Puranas are older than the Rig Veda.", False),
 voc("demon", "In these stories, a powerful being who fights the gods."),
 op("Why might stories of gods be easier for many people than philosophy like the Upanishads?", "Stories are vivid, easy to remember and to share; they teach ideas through characters."),
]),
("Hindu Life and Practice", "Vida y práctica hindú", [
 mc("Hindu life rituals that mark stages of life are called…", "samskaras", ["suras", "kandas", "sutras"]),
 mc("The four traditional stages of life begin with…", "student", ["retiree", "king", "priest"]),
 mc("The last traditional stage is…", "renunciant, giving up worldly life", ["student", "householder", "soldier"]),
 mc("A pilgrimage is…", "a journey to a holy place", ["a meal", "a festival game", "a type of prayer bead"]),
 mc("Varanasi is a holy city on the river…", "Ganges", ["Indus", "Nile", "Yangtze"]),
 mc("The Kumbh Mela is…", "one of the largest religious gatherings on earth", ["a small family meal", "a war", "a school"]),
 tf("Many Hindus bathe in the Ganges as an act of purification.", True),
 tf("All Hindus follow exactly the same practices.", False),
 voc("pilgrimage", "A journey to a holy place."),
 op("The four stages of life are student, householder, forest dweller and renunciant. Which stage are you in, and what is its duty?", "Student: learning, respecting teachers, building character."),
]),
("Hindu Texts in History", "Los textos hindúes en la historia", [
 mc("The Indus Valley civilization flourished around…", "2500 BCE", ["500 CE", "1500 CE", "1900 CE"]),
 mc("The Gupta period, a golden age of Hindu art and learning, was around…", "300–550 CE", ["2000 BCE", "1700 CE", "1950 CE"]),
 mc("Many old temples, like those at Angkor Wat, show Hindu influence in…", "Cambodia", ["Brazil", "Ireland", "Kenya"]),
 mc("The 19th-century teacher who spoke on Hinduism in Chicago in 1893 was…", "Swami Vivekananda", ["Gandhi", "Tagore", "Ashoka"]),
 mc("Mahatma Gandhi said the Gita was…", "a guide he turned to often", ["a book he never read", "a war manual", "only a poem"]),
 mc("The Mahabharata was retold as a TV series in India in…", "the 1980s", ["the 1800s", "the 1500s", "never"]),
 tf("Hinduism is often called one of the world’s oldest living religions.", True),
 tf("Hindu texts had no influence outside India.", False),
 voc("civilization", "A large, organized society with cities and culture."),
 op("Why might an ancient story like the Ramayana still be retold on TV today?", "Its themes, duty, loyalty, good and evil, still speak to people; it is part of shared culture."),
]),
]

BANDS['912'] = [
("Shruti and Smriti", "Shruti y smriti", [
 mc("Shruti texts are held to be…", "revealed, “heard” by ancient sages", ["written by kings", "folk tales", "modern law"]),
 mc("Which is shruti?", "the Upanishads", ["the Ramayana", "the Laws of Manu", "the Puranas"]),
 mc("Which is smriti?", "the Mahabharata", ["the Rig Veda", "the Sama Veda", "the Isha Upanishad"]),
 mc("Each Veda has layers: Samhitas (hymns), Brahmanas (ritual), Aranyakas and…", "Upanishads", ["Puranas", "Sutras of Patanjali", "Jatakas"]),
 mc("Though smriti, the Gita is treated by many Hindus as…", "nearly as authoritative as shruti", ["unimportant", "a comic tale", "a foreign text"]),
 mc("The Dharmashastras, such as the Manusmriti, deal mainly with…", "law, duty and social order", ["astronomy only", "love poetry", "medicine"]),
 tf("Oral transmission of the Vedas used memory techniques that recited verses in several patterns to prevent errors.", True),
 tf("Shruti means “remembered.”", False),
 voc("canon", "A set of texts accepted as authoritative."),
 op("Hinduism has no single founder and no single book. How does the shruti/smriti division help organize its texts?", "It ranks texts by authority: revealed shruti first, remembered smriti as guidance and story; it lets many texts coexist."),
]),
("The Rig Veda", "El Rig Veda", [
 mc("The Rig Veda contains about how many hymns?", "1,028", ["18", "114", "10,000"]),
 mc("The Rig Veda is organized into ten books called…", "mandalas", ["kandas", "suras", "chapters of Manu"]),
 mc("The Nasadiya hymn (10.129) is known for…", "questioning whether anyone knows how creation began", ["listing kings", "describing a battle", "giving laws"]),
 mc("The Purusha Sukta (10.90) describes the world made from…", "a cosmic being", ["an egg of stone", "a river", "a tortoise"]),
 mc("Indra, praised often in the Rig Veda, is a god of…", "storms and war", ["wealth", "learning", "the dead"]),
 mc("Soma in the Rig Veda is…", "a ritual drink and a god", ["a king", "a city", "a river goddess"]),
 tf("The Purusha Sukta has been used in debates about the origin of caste.", True),
 tf("The Nasadiya hymn claims complete certainty about creation.", False),
 voc("cosmology", "An account of how the universe began and is ordered."),
 op("The Nasadiya hymn ends by asking whether even the highest god knows how creation began. Why might a sacred text include doubt?", "It honors mystery; it invites inquiry; it shows humility before what cannot be known."),
]),
("Reading the Upanishads", "Leer los Upanishads", [
 mc("In the Katha Upanishad, Yama offers Nachiketa…", "wealth and long life instead of the answer", ["a kingdom in Lanka", "a bow", "nothing"]),
 mc("The Katha Upanishad compares the body to…", "a chariot, with the self as its rider", ["a house of salt", "a river", "a tree of fire"]),
 mc("In the chariot image, the senses are the…", "horses", ["wheels", "road", "reins"]),
 mc("The Brihadaranyaka Upanishad describes the self as “neti, neti,” meaning…", "“not this, not this”", ["“here it is”", "“go and learn”", "“you are that”"]),
 mc("The Mandukya Upanishad explains the syllable…", "Om", ["Namaste", "Rama", "Agni"]),
 mc("The Isha Upanishad teaches enjoying the world…", "by letting go of greed", ["by owning more", "only through war", "by avoiding work"]),
 tf("“Neti, neti” describes ultimate reality by saying what it is not.", True),
 tf("The chariot image says the senses should drive without control.", False),
 voc("metaphor", "Describing one thing as another to show a likeness."),
 op("Explain the chariot metaphor: who is the rider, driver, reins and horses, and what does it teach?", "Self is rider, intellect the driver, mind the reins, senses the horses; a trained mind guides the senses toward the goal."),
]),
("Close Reading the Gita", "Lectura atenta del Gita", [
 mc("In Arnold’s 1885 translation, the Gita is titled…", "The Song Celestial", ["The Light of Asia", "The Sacred Books", "The Lord’s Law"]),
 mc("In Chapter 2, Krishna argues Arjuna should not grieve because…", "the self is eternal and cannot be slain", ["the war is fake", "the enemy will flee", "fate is random"]),
 mc("Krishna’s teaching on action is that one has a right to the work but…", "not to its fruits", ["not to rest", "not to prayer", "only to victory"]),
 mc("In Chapter 11, Krishna shows Arjuna his…", "universal form", ["palace", "chariot’s wheel", "childhood"]),
 mc("Robert Oppenheimer famously quoted Chapter 11 after…", "the first atomic bomb test", ["the moon landing", "World War I", "the fall of Rome"]),
 mc("The Gita joins together ideas of duty, knowledge and…", "devotion", ["trade", "revenge", "magic"]),
 tf("Gandhi read the Gita as teaching nonviolence, even though its setting is a war.", True),
 tf("The Gita ends with Arjuna refusing to fight.", False),
 voc("detachment", "Acting without clinging to the results."),
 op("The Gita is set on a battlefield, yet Gandhi read it as a call to nonviolence. How can readers find such different meanings?", "Some read the war literally; others read it as an inner struggle, so the teaching on duty without attachment can support nonviolence."),
]),
("The Epics as Literature", "Las epopeyas como literatura", [
 mc("Both Indian epics use a frame structure, meaning…", "stories are told inside other stories", ["they have no plot", "they are only songs", "they are written backward"]),
 mc("Draupadi’s humiliation in the dice hall is a turning point because…", "it makes the war almost certain", ["it ends the story", "it is a joke", "it happens after the war"]),
 mc("Karna is a tragic figure because he is…", "a Pandava by birth who fights for the Kauravas out of loyalty", ["a villain with no depth", "a god", "a monkey"]),
 mc("Tulsidas retold the Ramayana in Hindi as the…", "Ramcharitmanas", ["Gita Govinda", "Rig Veda", "Panchatantra"]),
 mc("Sita’s trial by fire has led modern readers to discuss…", "gender and justice in the epic", ["farming methods", "astronomy", "sea travel"]),
 mc("The Mahabharata says of itself that what is found in it is found elsewhere, and what is not in it is…", "found nowhere", ["false", "in the Vedas", "lost"]),
 tf("Both epics are still performed in dance, drama and puppet theater across South and Southeast Asia.", True),
 tf("Karna knowingly fights for his own brothers’ side.", False),
 voc("tragic", "About a person whose good qualities lead to their downfall."),
 op("Compare Rama and Arjuna as heroes. How is each tested, and how does each respond?", "Rama is tested by exile and loss and keeps dharma; Arjuna by doubt about killing kin, resolved through Krishna’s teaching."),
]),
("Schools of Hindu Thought", "Escuelas del pensamiento hindú", [
 mc("Vedanta means…", "the end of the Vedas, the Upanishads’ teaching", ["a kind of temple", "a festival", "a caste"]),
 mc("Shankara’s Advaita Vedanta teaches that…", "atman and Brahman are not two", ["the world is all there is", "God and souls are wholly separate", "there is no self"]),
 mc("Ramanuja’s Vishishtadvaita teaches…", "souls are real parts of God, one yet distinct", ["souls are illusions", "there is no God", "only matter exists"]),
 mc("Madhva’s Dvaita teaches that God and souls are…", "eternally distinct", ["identical", "illusions", "the same as matter"]),
 mc("The six classical schools (darshanas) include Nyaya, which focuses on…", "logic", ["dance", "cooking", "poetry"]),
 mc("In Advaita, the world as we usually see it is called…", "maya, an appearance", ["karma", "dharma", "prasad"]),
 tf("Hindu philosophy contains serious disagreements, not one single view.", True),
 tf("Dvaita teaches that God and the soul are identical.", False),
 voc("nondual", "Not two; the view that reality is one."),
 op("Choose Advaita or Dvaita. State its view of God and the self in one sentence, and one reason a thinker might hold it.", "Advaita: self and Brahman are one; reason: the Upanishads say “you are that.” Dvaita: God and souls are distinct; reason: devotion needs a God to love."),
]),
("Bhakti Poets", "Poetas bhakti", [
 mc("The bhakti movement stressed…", "personal love for God open to all", ["priestly ritual only", "war", "Sanskrit only"]),
 mc("Mirabai was a princess-poet devoted to…", "Krishna", ["Shiva", "Ravana", "Indra"]),
 mc("Kabir, a weaver-poet, criticized…", "empty ritual in both Hindu and Muslim practice", ["all poetry", "the Ganges", "farmers"]),
 mc("Many bhakti poets wrote in…", "local languages, not only Sanskrit", ["Latin", "English", "Chinese"]),
 mc("The Alvars and Nayanars were early bhakti poets of…", "South India (Tamil)", ["Nepal", "Persia", "Tibet"]),
 mc("Jayadeva’s Gita Govinda celebrates the love of…", "Krishna and Radha", ["Rama and Sita", "Shiva and Parvati", "Nala and Damayanti"]),
 tf("Bhakti poets included women and people of low caste.", True),
 tf("Bhakti poets insisted only priests could approach God.", False),
 voc("vernacular", "The everyday language people speak."),
 op("Why would writing in everyday language be a big change for religious life?", "Ordinary people could understand and sing the texts directly, without priests or Sanskrit."),
]),
("Dharma and Society", "Dharma y sociedad", [
 mc("The four varnas in classical texts are Brahmins, Kshatriyas, Vaishyas and…", "Shudras", ["Pandavas", "Rishis", "Gurus"]),
 mc("Jati refers to…", "birth groups tied to occupation and community", ["a type of hymn", "a yoga pose", "a temple"]),
 mc("B. R. Ambedkar, who led the drafting of India’s constitution, burned the Manusmriti in 1927 to protest…", "caste discrimination", ["British taxes", "a war", "temple prices"]),
 mc("India’s constitution (1950)…", "outlawed untouchability", ["made caste required", "banned religion", "made Sanskrit the only language"]),
 mc("Svadharma in the Gita means…", "one’s own duty", ["another’s duty", "no duty", "a festival"]),
 mc("Many Hindu reformers argued that caste by birth…", "is not required by the deepest teachings", ["is the heart of the Upanishads", "was invented in 1950", "only exists abroad"]),
 tf("Hindus themselves have long debated whether caste is essential to the tradition.", True),
 tf("Ambedkar supported the caste rules of the Manusmriti.", False),
 voc("reform", "A change meant to make something better or fairer."),
 op("How can a tradition’s texts be used both to defend and to challenge social hierarchy? Use one example.", "The Purusha Sukta was cited for caste; reformers and bhakti poets cited equality of all souls before God to challenge it."),
]),
("Modern Readers", "Lectores modernos", [
 mc("Henry David Thoreau wrote that he bathed his mind in…", "the Bhagavad Gita", ["the Rig Veda only", "the Analects", "the Dhammapada"]),
 mc("Gandhi’s word for “holding to truth” in nonviolent resistance is…", "satyagraha", ["samsara", "moksha", "ahimsa"]),
 mc("Rabindranath Tagore, who won the Nobel Prize in 1913, wrote…", "Gitanjali", ["The Song Celestial", "Walden", "Ramcharitmanas"]),
 mc("Vivekananda’s 1893 Chicago speech is remembered for greeting the audience as…", "“Sisters and Brothers of America”", ["“Friends and enemies”", "“Citizens of Rome”", "“Children of the Ganges”"]),
 mc("Martin Luther King Jr. learned nonviolent methods partly from…", "Gandhi", ["Ravana", "Shankara", "Kabir"]),
 mc("Max Müller edited a famous 19th-century series called…", "The Sacred Books of the East", ["The Song Celestial", "The Great Books", "The Harvard Classics"]),
 tf("Gandhi’s ahimsa drew on Hindu, Jain and Christian ideas.", True),
 tf("Hindu texts were unknown in the West until the year 2000.", False),
 voc("nonviolence", "Refusing to harm others, even in a struggle."),
 op("Trace one idea from a Hindu text to a modern movement.", "Ahimsa and the Gita’s detached action shaped Gandhi’s satyagraha, which influenced King and the civil rights movement."),
]),
("Comparing Traditions", "Comparar tradiciones", [
 mc("Hinduism and Buddhism both use the ideas of…", "karma and rebirth", ["the Trinity", "the Five Pillars", "the Sabbath"]),
 mc("Unlike the Upanishads’ atman, the Buddha taught…", "anatta, no permanent self", ["an eternal self", "many selves in heaven", "the self is Brahman"]),
 mc("Jainism, like Hinduism, stresses…", "ahimsa, nonviolence", ["holy war", "no ethics", "one prophet"]),
 mc("Sikhism, founded by Guru Nanak, arose in…", "the Punjab", ["Tibet", "Japan", "Arabia"]),
 mc("Both the Gita and the Daodejing value…", "acting without grasping for results", ["conquest", "wealth above all", "silence only"]),
 mc("A key difference: Hindu texts often describe a personal God (like Krishna), while the Daodejing’s Dao is…", "impersonal", ["a king", "a warrior", "a monkey"]),
 tf("Comparing religions means describing each fairly, not ranking them.", True),
 tf("Hinduism and Buddhism share no ideas.", False),
 voc("comparative", "Looking at two or more things side by side."),
 op("Compare how the Upanishads and the Buddha answer the question “What is the self?”", "Upanishads: an eternal atman one with Brahman; Buddha: no permanent self, only changing parts; both seek release from rebirth."),
]),
]

BANDS['adult'] = [
("The sacred texts", "Los textos sagrados", [
 mc("Hindu sacred texts are grouped as shruti (heard) and…", "smriti (remembered)", ["sutta (thread)", "sura (chapter)", "tanakh"]),
 mc("The Vedas are…", "the oldest Hindu scriptures", ["modern novels", "Buddhist rules", "Chinese classics"]),
 mc("The two great Hindu epics are the Ramayana and the…", "Mahabharata", ["Upanishads", "Puranas", "Dhammapada"]),
 mc("The Bhagavad Gita is found in the…", "Mahabharata", ["Ramayana", "Rig Veda", "Manusmriti"]),
 mc("The classical language of the texts is…", "Sanskrit", ["Pali", "Hindi only", "Persian"]),
 mc("Many Hindus today know the epics best through…", "family retellings, TV and festivals", ["court records", "tax forms", "only scholars"]),
 tf("Hinduism has no single founder.", True),
 tf("Hindus have one book that all must follow in the same way.", False),
 voc("scripture", "Writing a religion holds sacred."),
 op("Why might a tradition with many texts suit people with different needs?", "People can meet the sacred through story, song, philosophy or ritual, whatever speaks to them."),
]),
("Vedas and Upanishads", "Vedas y Upanishads", [
 mc("The Rig Veda is mainly…", "hymns", ["laws", "fables", "history"]),
 mc("The Upanishads mainly explore…", "the self and ultimate reality", ["farming", "trade", "war tactics"]),
 mc("Brahman is…", "the ultimate reality", ["a caste only", "a priest’s robe", "a city"]),
 mc("Atman is…", "the inner self", ["the body", "a hymn", "a god of fire"]),
 mc("“Tat tvam asi” means about…", "“You are that”", ["“Go in peace”", "“Know your duty”", "“Light the lamp”"]),
 mc("The Upanishads often teach through…", "questions and answers between teacher and student", ["legal cases", "maps", "prices"]),
 tf("The Vedas were passed on by memory for centuries before being written down.", True),
 tf("The Upanishads come before the Rig Veda.", False),
 voc("philosophy", "The study of big questions about life and truth."),
 op("What question from the Upanishads would you most want to ask a teacher?", "Any genuine question, such as “Who am I?” or “What lasts after death?”"),
]),
("The epics", "Las epopeyas", [
 mc("In the Ramayana, Rama rescues Sita from…", "Ravana", ["Arjuna", "Krishna", "Duryodhana"]),
 mc("Hanuman is…", "Rama’s devoted monkey ally", ["Ravana’s brother", "a river", "a sage"]),
 mc("The Mahabharata centers on a war between…", "the Pandavas and the Kauravas", ["Rama and Ravana", "gods and fish", "India and Rome"]),
 mc("Draupadi is…", "the wife of the Pandavas", ["Rama’s mother", "a goddess of rain", "Ravana’s queen"]),
 mc("The epics are often used to teach…", "duty, loyalty and right action", ["banking", "chemistry", "sports rules"]),
 mc("Diwali is linked in many regions to…", "Rama’s return to Ayodhya", ["the Gita’s war", "the Vedas’ writing", "the monsoon"]),
 tf("The epics show heroes facing hard moral choices.", True),
 tf("The Ramayana is a short poem of ten lines.", False),
 voc("loyalty", "Standing by someone through hard times."),
 op("Which epic character would you want as a friend, and why?", "Any character with a reason, e.g., Hanuman for loyalty."),
]),
("The Bhagavad Gita", "El Bhagavad Gita", [
 mc("The Gita is a dialogue between Arjuna and…", "Krishna", ["Rama", "Vyasa", "Shiva"]),
 mc("Arjuna hesitates because…", "he must fight his own relatives", ["he is ill", "he lost his army", "he hates Krishna"]),
 mc("Krishna teaches acting without attachment to…", "the results", ["friends", "food", "rules"]),
 mc("The Gita names paths of action, knowledge and…", "devotion", ["money", "war", "travel"]),
 mc("An 1885 English verse translation by Edwin Arnold is called…", "The Song Celestial", ["Gitanjali", "Walden", "The Light of Asia"]),
 mc("Gandhi called the Gita his…", "spiritual guide", ["enemy", "war plan", "cookbook"]),
 tf("Many people outside Hinduism read the Gita for guidance.", True),
 tf("The Gita tells readers to act only for reward.", False),
 voc("attachment", "Holding on tightly to an outcome."),
 op("Think of a task you do for its own sake. How is that like the Gita’s teaching?", "Doing good work without fixating on praise or payment is action without attachment."),
]),
("Key ideas", "Ideas clave", [
 mc("Dharma is…", "duty and right living", ["a festival", "a food", "a god"]),
 mc("Karma is…", "action and its results", ["luck", "a temple", "a greeting"]),
 mc("Samsara is…", "the cycle of rebirth", ["a holy river", "a prayer", "a caste"]),
 mc("Moksha is…", "liberation from rebirth", ["a punishment", "a war", "a song"]),
 mc("Ahimsa is…", "nonviolence", ["wealth", "pleasure", "silence"]),
 mc("The four aims of life are dharma, artha, kama and…", "moksha", ["samsara", "puja", "Veda"]),
 tf("Many Hindus see karma as working across lifetimes.", True),
 tf("Karma means everything is random.", False),
 voc("liberation", "Being set free."),
 op("Which Hindu idea do you find most useful for daily life? Explain.", "Any idea with a reason, e.g., ahimsa for patience, dharma for responsibility."),
]),
("Deities and devotion", "Deidades y devoción", [
 mc("Brahma, Vishnu and Shiva are linked with…", "creation, preservation and destruction", ["sun, moon and stars", "past, present and future only", "earth, water and air"]),
 mc("Rama and Krishna are avatars of…", "Vishnu", ["Shiva", "Brahma", "Indra"]),
 mc("Ganesha is honored as…", "remover of obstacles", ["god of war", "goddess of rivers", "lord of death"]),
 mc("Lakshmi is goddess of…", "prosperity", ["war", "rain", "knowledge"]),
 mc("Sarasvati is goddess of…", "learning and music", ["wealth", "storms", "fire"]),
 mc("Many Hindus say the many deities are…", "faces of one divine reality", ["rivals", "only statues", "all the same person"]),
 tf("A family may keep a special devotion to one deity.", True),
 tf("Hindu worship is always done only by priests.", False),
 voc("deity", "A god or goddess."),
 op("Why might a student pray to Sarasvati before exams?", "She is goddess of learning; the prayer asks for clear thinking and focus."),
]),
("Yoga and meditation", "Yoga y meditación", [
 mc("In Hindu texts, yoga first means…", "discipline that unites the self with the divine", ["gym exercise", "a diet", "a dance"]),
 mc("Patanjali’s Yoga Sutras define yoga as…", "stilling the movements of the mind", ["bending the body", "fasting", "chanting only"]),
 mc("The Yoga Sutras have how many “limbs”?", "eight", ["three", "ten", "twelve"]),
 mc("Pranayama is…", "breath control", ["a festival", "a hymn", "a caste"]),
 mc("Dhyana is…", "meditation", ["diet", "debt", "duty"]),
 mc("The postures (asanas) are…", "only one part of yoga", ["all of yoga", "not in yoga", "a kind of prayer bead"]),
 tf("Modern exercise yoga grew from older Hindu spiritual practice.", True),
 tf("The Yoga Sutras are mostly about stretching.", False),
 voc("meditation", "Training attention by resting the mind on one thing."),
 op("Try one minute of slow breathing. What did you notice?", "Any honest noticing, such as a calmer body or a busy mind."),
]),
("Festivals and life rites", "Fiestas y ritos de la vida", [
 mc("Diwali is the festival of…", "lights", ["colors", "kites", "boats"]),
 mc("Holi is the festival of…", "colors", ["lights", "books", "masks"]),
 mc("Navaratri honors the goddess…", "Durga", ["Sita", "Radha", "Kaikeyi"]),
 mc("A Hindu wedding often includes walking around…", "a sacred fire", ["a tree", "a river", "a temple bell"]),
 mc("At death, many Hindus practice…", "cremation", ["burial at sea", "mummification", "sky burial"]),
 mc("The thread ceremony (upanayana) traditionally marks…", "the start of formal study", ["a wedding", "retirement", "a birthday"]),
 tf("Many Hindu rites mark stages of life from birth to death.", True),
 tf("Hindu festivals happen on the same Western date each year.", False),
 voc("rite", "A set ceremony with special meaning."),
 op("What life event does your family mark with a ceremony?", "Any event, such as a birthday, graduation or wedding."),
]),
("Hinduism around the world", "El hinduismo en el mundo", [
 mc("About how many people practice Hinduism worldwide?", "about 1.2 billion", ["about 1 million", "about 50 million", "about 5 billion"]),
 mc("The country with the most Hindus is…", "India", ["Brazil", "China", "Egypt"]),
 mc("A majority-Hindu country besides India is…", "Nepal", ["Japan", "Spain", "Chile"]),
 mc("The island of Bali, in Indonesia, is mostly…", "Hindu", ["Buddhist", "Christian", "Jewish"]),
 mc("The Hindu population of the United States is about…", "2–3 million", ["50,000", "50 million", "zero"]),
 mc("ISKCON (the Hare Krishna movement) spreads devotion to…", "Krishna", ["Shiva", "Indra", "Buddha"]),
 tf("Hindu temples exist in many U.S. cities.", True),
 tf("Hinduism is practiced only in India.", False),
 voc("diaspora", "People living far from their ancestors’ homeland."),
 op("How might a Hindu family abroad keep its traditions?", "Home shrines, temples, festivals, language and food, and retelling the epics."),
]),
("Hindu texts today", "Los textos hindúes hoy", [
 mc("Gandhi drew on the Gita and ahimsa for…", "nonviolent resistance", ["a new army", "a trade deal", "a school test"]),
 mc("Yoga and meditation are now used worldwide for…", "health and calm", ["only religion", "sports betting", "farming"]),
 mc("Some Hindu teachers apply ahimsa today to…", "vegetarian diet and care for the environment", ["cars", "phones", "banking"]),
 mc("Hindu texts appear in popular culture, for example…", "films and TV series of the epics", ["tax codes", "road maps", "weather reports"]),
 mc("Words from Sanskrit in everyday English include…", "karma, guru, avatar", ["pizza, robot, taco", "sushi, emoji, tofu", "ballet, café, menu"]),
 mc("Hindu reformers used the texts to argue for…", "ending caste discrimination", ["more caste rules", "banning study", "ending festivals"]),
 tf("Ancient texts can be read in new ways by each generation.", True),
 tf("Hindu texts no longer matter to anyone today.", False),
 voc("interpretation", "One way of explaining what a text means."),
 op("Name one idea from Hindu texts you have heard used in daily life. Where did you hear it?", "Karma, yoga, guru, avatar, or ahimsa, with any honest source."),
]),
]
